### ISSUE TITLE
Get-History not working properly when using up or down keys

### ISSUE THREAD

**Issue by cielakm** [PowerShell/vscode-powershell#688] opened 2017-04-19 15:06 UTC
### Issue Description

When using up and down arrows it will enumerate the empty history. If you look at the get-History it contains empty values. This is not the case when using Powershell shell.

![codeissue2](https://cloud.githubusercontent.com/assets/22874273/25186487/34f5f10e-2518-11e7-983d-0cf054429651.gif)

This is also causing an issue when running a selected part of the script with F8. When more then one line is selected to run this is kept in the history therefore obstructing the view for the next line.

![codeissue1](https://cloud.githubusercontent.com/assets/22874273/25186791/184d7134-2519-11e7-96f1-4e5b10050b8f.gif)

I want also to ask if there is a possibility to specify 
"terminal.integrated.shell.windows": "c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", to be set to "PowerShell Integrated" shell rather then Powershell so I could open multiple integrated shells and to use only one $profile file to run.

### System Details

PS C:\> code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331
PS C:\> $pseditor.EditorServicesVersion
PS C:\> code --list-extensions --show-versions
gerane.Theme-Blackboard@0.0.2
gerane.Theme-tonic@0.0.2
GrapeCity.gc-excelviewer@1.1.13
IBM.output-colorizer@0.1.0
ms-vscode.PowerShell@0.12.2
Poorchop.theme-darktooth@0.0.2
robertohuertasm.vscode-icons@7.5.1
ryu1kn.partial-diff@0.2.0
spywhere.guides@0.7.0
woodywoodsta.vscode-material-syntax-dark@0.1.1
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by daviwil** [comment] 2017-04-25 16:49
Thanks Marek!  Closing this as a duplicate of #618, I'll be fixing this soon.

**Closed by daviwil** 2017-04-25 16:49 UTC
