### ISSUE TITLE
Extension loads but doesn't work when Code is loaded from a command line.

### ISSUE THREAD

**Issue by JMCorp** [PowerShell/vscode-powershell#42] opened 2015-12-03 18:29 UTC
I open powershell command console and type Code then hit enter (also tried with Code . ) and the extension doesn't work. if I use the Code shortcut from my task bar it works fine. Though doing ">ext show" says the extension is loaded, it's not working. I type "get-pro" and ctrl+space and I get completion items in the taskbar launched code, but not in the powershell command line launched code.

**Comment by daviwil** [comment] 2015-12-03 18:30
Hmmm, interesting, I haven't seen this issue before.  Will investigate, thanks!

**Comment by JMCorp** [comment] 2015-12-03 18:46
May be related: Running task bar link to code "as administrator" does the same thing.

**Comment by daviwil** [comment] 2015-12-03 18:47
When you run 'code' from the command line, are you running it from an Administrator console?  I wonder if admin elevation is causing a problem somehow.

**Comment by JMCorp** [comment] 2015-12-03 18:49
no, running code from command line I was running it as my regular user account. I did try running powershell.exe "as administrator" as a test, and it does the same thing.

**Comment by daviwil** [comment] 2015-12-11 23:48
Hey @JMCorp, I wasn't able to reproduce this issue.   The next time you see it can you send me the log file at this location:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell\bin\EditorServices.log`

You can e-mail it to me at my username @microsoft.com.  Thanks!

**Comment by tylerl0706** [comment] 2018-01-27 00:35
Since this has been quiet and we can't get a repro, I'm going to close it. Feel free to open a new issue if you still see this!

**Closed by tylerl0706** 2018-01-27 00:35 UTC
Labels: Issue-Bug, Needs-Repro-Info
