### ISSUE TITLE
Getting error -  Unable to instantiate; language client undefined. when i select the commands in powershell and press pf8. Powershell version - 2020.3.0

### ISSUE THREAD

**Issue by Chaebi** [PowerShell/vscode-powershell#2592] opened 2020-03-30 12:30 UTC
* Slack Community Chat: https://powershell.slack.com (you can sign-up at http://slack.poshcode.org/ for an invite)
* Gitter Chat: https://gitter.im/PowerShell/vscode-powershell

**Comment by TylerLeonhardt** [comment] 2020-03-30 15:52
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by Chaebi** [comment] 2020-03-31 11:47
Here are the logs 
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4408793/vscode-powershell.log)

**Comment by SydneyhSmith** [comment] 2020-03-31 21:11
@Chaebi thanks for the information, could you please also provide the diagnostic logs-instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment), thanks for your help!

**Comment by Chaebi** [comment] 2020-04-01 11:31
When i am changing the log level to Diagnostic ( powershell.developer.editorServicesLogLevel": "Diagnostic" ). it asks me to run a new Powershell session but then it gives me the message as "the terminal process terminated with exit code: 1". No error message other than this shows on the screen. 
Can this error message not creating the diagnostic logs as expected by you ?. Because, i followed the same steps to create the log file last time @TylerLeonhardt  asked me to provide logs

**Comment by SydneyhSmith** [comment] 2020-04-02 21:17
@Chaebi sorry the confusion thanks for giving that a try...what version of PowerShell are you using?

**Comment by Chaebi** [comment] 2020-04-02 21:22
Powershell 2020.3.0

**Comment by TylerLeonhardt** [comment] 2020-04-02 21:28
@Chaebi what version of PowerShell are you trying to use with the PowerShell extension? Do you have PowerShell 7 installed on your machine or PowerShell Core 6? Or do you only have Windows PowerShell?

**Comment by TylerLeonhardt** [comment] 2020-04-02 21:29
If you only have Windows PowerShell, this could be a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2526

**Comment by TylerLeonhardt** [comment] 2020-04-02 21:30
Ah just checked your logs... You are using Windows PowerShell. Ok, this is a duplicate.

**Comment by TylerLeonhardt** [comment] 2020-04-02 21:31
I need more info on this issue and posted a comment in that other issue on how to get more info for me: https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-607990799

**Closed** 2020-04-03 22:00 UTC
Labels: Resolution-Duplicate
