### ISSUE TITLE
Debug Watch list not available

### ISSUE THREAD

**Issue by ebmarquez** [PowerShell/vscode-powershell#2639] opened 2020-04-17 14:35 UTC
Issue Type: <b>Bug</b>

When running the debugger, the Variables: Auto section show the correct variables but the Watch list show  "not available"

Extension version: 2020.4.2
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (36.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4493541/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4493542/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4493543/EditorServices.log)

**Comment by JustinGrote** [comment] 2020-04-17 14:42
Dupe of https://github.com/PowerShell/vscode-powershell/issues/2396?

**Comment by ebmarquez** [comment] 2020-04-17 14:42
![Annotation 2020-04-17 073842](https://user-images.githubusercontent.com/15785107/79581263-0caba980-807f-11ea-93ea-c8a2298f4740.png)

**Comment by ebmarquez** [comment] 2020-04-17 14:44
It might be a dup.  I also noticed I can't add new Watch variables when in a debug session. :-(

**Comment by JustinGrote** [comment] 2020-04-17 14:52
Yeah I didn't specifically mention this part of it but it is also a problem for #2390 

As a workaround, the `Powershell: Restart Current Session` will fix it without having to reload all of vscode. It also generally only occurs for me if I use the "Stop" button on the debugger rather than running it to completion, suggesting a cleanup issue in PSES and/or omnisharp

**Comment by SydneyhSmith** [comment] 2020-04-21 21:09
Thanks everyone, going to mark this as a duplicate.

**Closed** 2020-04-22 22:00 UTC
Labels: Resolution-Duplicate
