### ISSUE TITLE
$psEditor.Workspace.Path starting with '/c%3A/' on Windows

### ISSUE THREAD

**Issue by brianary** [PowerShell/vscode-powershell#2322] opened 2019-11-22 17:15 UTC
### System Details

System Details Output
```
### VSCode version: 1.41.0-insider bf7d03bf88732af0b46e473c663c49e18e839f9c x64

### VSCode extensions:
adamvoss.yaml@0.0.9
brunnerh.insert-unicode@0.7.0
darkriszty.markdown-table-prettify@2.4.0
DavidAnson.vscode-markdownlint@0.32.0
donjayamanne.githistory@0.4.6
DotJoshJohnson.xml@2.5.0
dracula-theme.theme-dracula@2.18.1
eamodio.gitlens@10.2.0
EditorConfig.EditorConfig@0.14.2
emmanuelbeziat.vscode-great-icons@2.1.47
eriklynd.json-tools@1.0.2
geeklearningio.graphviz-markdown-preview@0.0.8
golf1052.code-sync@2.6.1
GrapeCity.gc-excelviewer@2.1.32
HookyQR.GitHubIssues@0.1.2
Ionide.Ionide-FAKE@1.2.3
Ionide.Ionide-fsharp@4.3.1
Ionide.Ionide-Paket@1.12.0
just4developments.testing-regex@0.0.2
lextudio.restructuredtext@116.0.0
ms-mssql.mssql@1.7.1
ms-vscode.csharp@1.21.7
ms-vscode.powershell@2019.11.0
ms-vscode.powershell-preview@2019.11.0
Perkovec.emoji@0.0.3
ryu1kn.partial-diff@1.4.0
searKing.preview-vscode@2.0.3
SimonSiefke.svg-preview@2.7.5
wayou.vscode-todo-highlight@1.0.4
yzhang.markdown-all-in-one@2.5.1


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.18362.145                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.18362.145                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

```

### Issue Description

I am experiencing a problem using the `$psEditor.Workspace.Path` property.

#### Expected Behaviour

-- Description of what *should* be happening --

This property _used to_ return a valid, native Windows path, typically starting with `C:\`, which could then be used with `Set-Location` or `Push-Location`.

#### Actual Behaviour

-- Description of what actually happens --

The property now returns a linuxy path, typically starting with `/c%3A/`. When given to `Push-Location`, for example, returns:

```samp
Push-Location : Cannot find path 'C:\c%3A\Users\brian\GitHub\SelectXmlExtensions' because it does not exist.
At line:1 char:1
+ Push-Location $psEditor.Workspace.Path
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\c%3A\Users\b...ctXmlExtensions:String) [Push-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.PushLocationCommand
```

**Comment by rjmholt** [comment] 2019-11-26 22:04
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2306

**Closed** 2019-11-27 23:00 UTC
Labels: Resolution-Duplicate
