### ISSUE TITLE
Setting "powershell.codeFormatting.useCorrectCasing" is removing ".\" paths 

### ISSUE THREAD

**Issue by dprice** [PowerShell/vscode-powershell#2725] opened 2020-05-20 19:39 UTC
Steps to reproduce
------------------
In either VSCode v1.45.1 or VSCode Insiders v1.46.0-insider, when `powershell.codeFormatting.useCorrectCasing` is set to `true`, any scripts that call another PowerShell script file like this:

```PowerShell
& .\Test-Junk.ps1
```

will get automatically formatted like this:

```PowerShell
& Test-Junk.ps1
```

which breaks the script. See attached gif showing the issue. It may be difficult to see, but I also have the format on save.

![PowerShell_Format_Path_Issue](https://user-images.githubusercontent.com/84499/82489724-1e360600-9ab0-11ea-85ba-f071bbfe47c5.gif)

Environment data
----------------

```PowerShell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core 
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> (Get-Module -ListAvailable PSScriptAnalyzer).Version | ForEach-Object { $_.ToString() }
1.18.0
1.18.3
```

**Comment by SydneyhSmith** [comment] 2020-05-26 21:07
@dprice thanks for opening this issue...upon investigation it looks like this bug is fixed in the latest version of PSSA but VSCode is not pulling in this version thus you see the bug, therefore this looks like a duplicate of #2697

**Closed** 2020-05-27 22:00 UTC
Labels: Resolution-Duplicate
