### ISSUE TITLE
PowerShell debugger to break on error

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#538] opened 2017-03-14 21:16 UTC
Hi,

Is it possible to have PowerShell debugger in VSCode to break in case there's an unhandled exception/error record being sent to the console (kind of like ErrorActionPreference set to Inquire for cmdlets, but for regular exceptions as well)? That could really make debugging experience much better. Currently, every time I see an unhandled error on the console, I have to figure out where did it come from, set one or more breakpoints and restart debugging and if VSCode could break automatically, it would save me from the manual effort.

Thanks,
Glober777

**Comment by daviwil** [comment] 2017-03-14 21:20
Yep, we definitely want to add this.  It will depend on PowerShell gaining the ability to break on exceptions, see this issue for more details:

https://github.com/PowerShell/PowerShell/issues/2830

**Comment by JustinGrote** [comment] 2019-07-21 18:55
This should be marked as a dupe of #298

**Comment by SydneyhSmith** [comment] 2019-07-23 16:03
Thanks @JustinGrote closing as a duplicate of #298

**Closed by SydneyhSmith** 2019-07-23 16:03 UTC
Labels: Issue-Enhancement, Triage
