### ISSUE TITLE
Constantly Freezes on Run

### ISSUE THREAD

**Issue by eliptus** [PowerShell/vscode-powershell#3213] opened 2021-02-27 12:28 UTC
Issue Type: <b>Bug</b>

Open a ps1 script. Press F5 to run. Freezes about 50% of the time.

Extension version: 2021.2.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.63GB free)|
|Process Argv|C:\\Users\\elipt\\Documents\\Skyrim Mods\\SkyFem Voice Patching --crash-reporter-id c197158e-cf38-48f4-814d-14face8924f4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by rjmholt** [comment] 2021-03-01 17:33
Possible duplicate of https://github.com/PowerShell/vscode-powershell/issues/3216. That issue is newer but contains more information, meaning more likelihood of solving the issue

**Closed** 2021-03-02 19:00 UTC
Labels: Issue-Bug, Needs: Triage :mag:, Resolution-Duplicate
