### ISSUE TITLE
Here-string is incorrectly completed

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#181] opened 2016-05-14 15:46 UTC
# Issue

When you type `@'`, a single quote is tacked on at the end, but doesn't include the closing `@`, so you're left with `@''`, which isn't a useful PowerShell construct.
# Expected Result

In my opinion, one of two things should happen, when you type `@'`:
1. Nothing
2. ``n`n'@`is appended (two new lines, followed by`'@`), and then the caret should be moved to the middle line (see screenshot)

![image](https://cloud.githubusercontent.com/assets/466713/15269338/ea6b0c7a-19b8-11e6-81f0-182300aaa0c2.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment] 2016-05-14 17:17
This is probably caused by how VS Code does its quote completions, they might not account for weird syntax like ours.  I'll see if there's anything I can do on our side.

**Comment by DouglasPlumley** [comment] 2017-05-31 13:14
Seeing the same issue, #1 would be better than the current behavior.

Thanks!

**Comment by tylerl0706** [comment] 2018-09-07 14:29
I'm duping this to a newer one #1517. I think we might be able to modify the auto closing pairs here:
https://github.com/Microsoft/vscode/blob/master/extensions/powershell/language-configuration.json#L11

But I've not tried it

**Closed** 2018-09-07 14:29 UTC
Labels: Area-Code Formatting, Issue-Bug
