### ISSUE TITLE
Terminal doesn't remove additional lines run from the editor when viewing history.

### ISSUE THREAD

**Issue by BoardWithLife** [PowerShell/vscode-powershell#1027] opened 2017-09-07 22:31 UTC
### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.2
- Output from `$PSVersionTable`: See Below

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PS C:\PSWork> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS C:\PSWork> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1358
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1358
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with running multiple lines in the editor creating issues when browsing history from the terminal.

1 .Create Multiple lines of code in the editor. (Just declare 3 variables on separate lines).
2. Select the three lines and run with F8
3. When focused on the Integrated terminal and using the up arrow to review history, the two additional lines do not disappear from the terminal window.
Here is a video of the behavior:
[VSCode.zip](https://github.com/PowerShell/vscode-powershell/files/1286273/VSCode.zip)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by AspenForester** [comment] 2017-10-04 15:20
This is related to issue #998

**Comment by SydneyhSmith** [comment] 2019-03-26 22:46
Closing this as a dupe of #998

**Closed by SydneyhSmith** 2019-03-26 22:46 UTC
