### ISSUE TITLE
Login-AzureRmAccount opens dialog in background

### ISSUE THREAD

**Issue by ronx** [PowerShell/vscode-powershell#541] opened 2017-03-15 01:25 UTC
### System Details

- Operating system name and version: Windows 10.0.14393.0
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`: 
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Login-AzureRmAccount opens the login dialog in the background with no tray window. I can alt-tab to the window, no big deal, so there's an easy workaround. Just wanted to throw it on the radar.

### Attached Logs

May already be a known limitation, and not causing error/exception, so probably easy to reproduce. Let me know if logs would help.

**Comment by daviwil** [comment] 2017-03-15 02:30
Hey Rob, thanks for the report.  This may be an issue with how they show their login UI, might need an extra step to force it to come to the front.  Does it work correctly for you if you launch it from powershell.exe in the VS Code integrated terminal, separately from the new integrated console?

**Comment by ronx** [comment] 2017-03-15 03:16
Seems to do the same thing from powershell.exe as well as powershell integrated console.

**Comment by carlocardella** [comment] 2017-04-29 16:32
powershell console and ISE work fine on a number of different machines for me, I have this problem only with Code (and Insiders) on those same machines

**Comment by rjmholt** [comment] 2018-09-20 22:50
This is the relevant VSCode issue btw: https://github.com/Microsoft/vscode/issues/42356

**Comment by JustinGrote** [comment] 2020-04-17 16:21
This should be closed as a dupe of the more general issue #621

**Closed** 2020-04-21 21:27 UTC
Labels: Issue-Bug, Needs: Attention :wave:
