### ISSUE TITLE
PowerShell extention doesn't handle multi-line commands

### ISSUE THREAD

**Issue by GaryNease** [PowerShell/vscode-powershell#2244] opened 2019-10-17 21:45 UTC
Issue Type: <b>Bug</b>

The following works in ISE etc but not in this product:
foreach ($assembly in $smoarray) { 
	$assembly = [Reflection.Assembly]::LoadWithPartialName($assembly)
}
... returns "Missing closing '}' in statement block or type definition."

Adding backticks to escape the linefeed also doesn't work, returns:
"Incomplete string token."

Extension version: 2019.9.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment] 2019-10-18 21:37
Thanks for opening an issue @GaryNease.

This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1278, and is addressed by https://github.com/PowerShell/vscode-powershell/issues/535.

That issue is closed because this works in the `powershell-preview` extension, and is planned to come to the stable extension in the coming months.

**Closed** 2019-10-19 22:00 UTC
Labels: Resolution-Duplicate
