### ISSUE TITLE
Make PowerShell Command Explorer usable

### ISSUE THREAD

**Issue by iricigor** [PowerShell/vscode-powershell#1635] opened 2018-12-06 10:13 UTC
Nice idea with `PowerShell Command Explorer` in v.1.10, but like it is done at the moment it is not usable. There must be some search/filter field or grouping/folding per module.

## Steps to reproduce
```PowerShell
PS C:\> (Get-Command).Count
2319
```

## Expected result

Control(s) exists to filter which commands are displayed

<details><summary>screnshot</summary>

![image](https://user-images.githubusercontent.com/15923171/49577066-ea603280-f946-11e8-9c1f-384082a4183c.png)

</details>

## Actual result

An endless list of `Add-AzureRM...` commands is displayed (well almost endless, to be technically correct).
<details><summary>screnshot</summary>

![image](https://user-images.githubusercontent.com/15923171/49576761-39599800-f946-11e8-942a-e7a09b084555.png)

</details>

**Comment by rjmholt** [comment] 2018-12-06 14:33
Closing this as a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1405.

The PowerShell Command Explorer is a community contributed feature. Please feel free to submit a PR with the improvements you are seeking.

**Closed by rjmholt** 2018-12-06 14:33 UTC
