### ISSUE TITLE
createTemporaryIntegratedConsole setting clears out integrated console after debugging session ends

### ISSUE THREAD

**Issue by grzegorz-silarski** [PowerShell/vscode-powershell#938] opened 2017-07-04 07:53 UTC
### System Details

- Operating system name and version: Win10 Pro
- VS Code version: 1.13.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`: 

PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with createTemporaryIntegratedConsole setting.
If that feature is turned on integrated console clears out each time after debugging session ends.
This is important to preserve console output because it can contain errors collected during a debugging process.

**Comment by rkeithhill** [comment] 2017-07-04 20:09
Duplicate of #907

**Closed by rkeithhill** 2017-07-04 20:09 UTC
Labels: Resolution-Duplicate
