### ISSUE TITLE
Oddity with cursor movement after hitting enter

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#1188] opened 2018-02-04 07:36 UTC
### System Details
```
PS C:\GitHub\StackDb> code -v
1.19.3
7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
x64
PS C:\GitHub\StackDb> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0


PS C:\GitHub\StackDb> code --list-extensions --show-versions
AlanWalk.markdown-toc@1.5.6
daylerees.rainglow@1.5.2
eamodio.gitlens@7.5.10
ms-mssql.mssql@1.3.0
ms-vscode.PowerShell@1.5.1
ms-vscode.wordcount@0.1.0
ryu1kn.partial-diff@0.5.1
sensourceinc.vscode-sql-beautify@0.0.4
Shan.code-settings-sync@2.8.7
streetsidesoftware.code-spell-checker@1.6.3
waderyan.gitblame@2.2.0
PS C:\GitHub\StackDb> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
[Twitter conversation with Tyler...](https://twitter.com/wsmelton/status/959640064258138112)

Seeing odd behavior that just seems to pop-up on me that hitting enter for a new line and the cursor will just jump ack to the previous line.

### Attached Logs

[VSCode_PSExtension_CursorIssue.zip](https://github.com/PowerShell/vscode-powershell/files/1692566/VSCode_PSExtension_CursorIssue.zip)

**Comment by tylerl0706** [comment] 2018-02-06 06:11
Thanks for the report, @wsmelton! We'll take a look!

**Comment by Omniusz** [comment] 2018-02-15 15:16
I experience the same thing, but only with very scripts, it seems to be when the 'references' labels occur

**Comment by rjmholt** [comment] 2018-10-16 21:34
Going to close this as a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1154.

**Closed by rjmholt** 2018-10-16 21:34 UTC
