### ISSUE TITLE
Visual Studio Code 64-bit With A 32-bit Integrated Console

### ISSUE THREAD

**Issue by blackneuron** [PowerShell/vscode-powershell#1007] opened 2017-08-24 20:00 UTC
### System Details

- Operating system name and version: Windows 7 64-bit 6.1.7601
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

code --list-extensions --show-versions
CoenraadS.bracket-pair-colorizer@0.10.8
DotJoshJohnson.xml@1.9.2
eliean.vscode-svn@0.1.0
fantasytyx.tortoise-svn@0.1.1
formulahendry.auto-close-tag@0.4.3
ms-mssql.mssql@1.1.0
ms-vscode.cpptools@0.12.3
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.4.1
PKief.material-icon-theme@2.2.0
wmaurer.change-case@1.0.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

When I installed the Visual Studio Code 64-bit version and tried to open a 32-bit PowerShell Integrated Console my only option was 64-bit.  On the 32-bit version of Visual Studio Code I can open either one.  Is this a bug or can a 32-bit Integrated Console not be opened in 64-bit VS Code?  Just wondering as I need to switch between them based on drivers.

### Attached Logs

N/A

**Comment by daviwil** [comment] 2017-08-24 22:55
It's a bug, will get this fixed shortly.

**Comment by daviwil** [comment] 2017-09-05 23:30
Resolving as duplicate of #1008.

**Closed by daviwil** 2017-09-05 23:30 UTC
Labels: Area-Language Server, Issue-Bug, Resolution-Duplicate
