### ISSUE TITLE
$ErrorActionPreference = 'stop' not showing the ERROR 

### ISSUE THREAD

**Issue by ohenrikh** [PowerShell/vscode-powershell#2576] opened 2020-03-23 11:26 UTC
Hi
$ErrorActionPreference = 'stop' 
in vscode causes the script to stop without throwing the ERROR code to Display when running with F5.

eg: 
**Script:**
$ErrorActionPreference = 'stop'
write-WrongCommandLine "foo"
Write-Host 'Hello World'

**Output vscode**: 
nothing, but the script stops as wanted
**Output ISE and wanted**
write-WrongCommandLine : The term 'write-WrongCommandLine' is not recognized as the name of a cmdle….
and the script stops

**Comment by corbob** [comment] 2020-03-23 12:53
Sounds like what I ran into in #2565. Are you running the stable extension?

**Comment by ohenrikh** [comment] 2020-03-23 13:03
Yes stable ver 5.1

**Comment by TylerLeonhardt** [comment] 2020-03-23 14:45
Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? This should be fixed in that.

You can still use whatever version of PowerShell you'd like. This is the Preview build of the _vs code extension_.

**Comment by ohenrikh** [comment] 2020-03-23 15:00
the preview Works as I liked 👍

**Comment by TylerLeonhardt** [comment] 2020-03-23 15:13
Great! I'll close this now since it's just pending a new release of the stable extension

**Comment by ohenrikh** [comment] 2020-03-23 15:14
than you

**Closed by TylerLeonhardt** 2020-03-23 15:13 UTC
Labels: Resolution-Fixed

**Comment by deadlydog** [comment] 2020-04-06 20:07
I just ran into this today and noticed that it was only affecting PowerShell 7; PowerShell 5.1 still displayed the error fine. Switching from the `PowerShell` VS Code extension to the `PowerShell Preview` extension has fixed the issue 👍

**Comment by rjmholt** [comment] 2020-04-07 16:26
> I'll also point out here that the Azure DevOps PowerShell extension has a similar bug in it when using Pwsh currently, and I've reported that issues here.

Given the nature of the fix here (which was to solve a race condition in the way errors were printed), it's likely that the two are unrelated.

**Comment by JoseRa-KnowIT** [comment] 2022-06-19 07:59
This issue is still happening on both stable (v2022.5.1) and preview (v2022.6.1) :

```
PS> $ErrorActionPreference = 'Stop' 
PS> Invalid-Command  

An error occurred while running the REPL loop:
System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter 
is set to Stop: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)  
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)        
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear(PowerShell pwsh, PSInvocationSettings invocationSettings) 
in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 88
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand(PowerShell pwsh, PSCommand psCommand, PSInvocationSettings 
invocationSettings) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 105
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 166
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 70
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 92
--- End of stack trace from previous location ---
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.get_Result() in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 58
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteAndGetResult(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 108
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokePSCommand[TResult](PSCommand psCommand, PowerShellExecutionOptions executionOptions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 432
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokePSCommand(PSCommand psCommand, PowerShellExecutionOptions executionOptions, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 435
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.InvokeInput(String input, CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 917
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.DoOneRepl(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Host\PsesInternalHost.cs:line 829

```

**Comment by JustinGrote** [comment] 2022-06-20 04:35
@JoseRa-KnowIT 
I'm unable to reproduce on preview:
![image](https://user-images.githubusercontent.com/15258962/174526031-e44d1fd3-e961-4f23-82fe-0764b3e27501.png)

**Comment by JoseRa-KnowIT** [comment] 2022-06-20 20:08
@JustinGrote thank you for your reply, I really appreciate your time.

It turned out to be caused by a module loaded in my profile (HistoryPx).
I disabled that modules and it seems to be working ok on both stable and preview extensions.
