### ISSUE TITLE
"Unrecognized token in source text" message the very first time Enter is pressed at [DBG] prompt

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#2278] opened 2019-11-04 20:56 UTC
Issue Description
=====

The very first time I press Enter at the [DBG] prompt (which is missing, see #1850), I get:

![image](https://user-images.githubusercontent.com/12860484/68156760-b1608180-ff4c-11e9-8856-65fd8855329d.png)

Attached Logs
=====

See 
[1572900663-0a6384c3-9784-4218-b9b3-4cfd2709d74f1572900632277.zip](https://github.com/PowerShell/vscode-powershell/files/3806058/1572900663-0a6384c3-9784-4218-b9b3-4cfd2709d74f1572900632277.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.39.2|
| PowerShell Extension Version | 2019.11.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0-preview.5|
|PSEdition|Core|
|GitCommitId|7.0.0-preview.5|
|OS|Microsoft Windows 10.0.18362|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0-preview.5|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|8.0.10|
|angular-console|nrwl|8.1.2|
|angular2-inline|natewallace|0.0.17|
|angular2-switcher|infinity1207|0.2.0|
|autoit|Damien|1.0.1|
|azure-account|ms-vscode|0.8.7|
|azure-pipelines|ms-azure-devops|1.157.4|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|10.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|cmake|twxs|0.0.17|
|cpptools|ms-vscode|0.26.1|
|csharp|ms-vscode|1.21.5|
|debugger-for-chrome|msjsdiag|4.12.1|
|gc-excelviewer|GrapeCity|2.1.32|
|github-pr|jasonnutter|1.0.0|
|html-css-class-completion|Zignd|1.19.0|
|indent-rainbow|oderwat|7.4.0|
|java|redhat|0.52.0|
|live-html-previewer|hdg|0.3.0|
|lorem-ipsum|Tyriar|1.2.0|
|markdown-all-in-one|yzhang|2.5.1|
|markdown-pdf|yzane|1.4.1|
|mssql|ms-mssql|1.7.0|
|ng-template|Angular|0.802.3|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|platformio|formulahendry|0.3.0|
|powershell-preview|ms-vscode|2019.11.0|
|prettier-vscode|esbenp|2.3.0|
|printcode|nobuhito|3.0.0|
|python|ms-python|2019.10.44104|
|quicktype|quicktype|12.0.46|
|rainbow-csv|mechatroner|1.3.1|
|reg|ionutvmi|1.0.1|
|remote-wsl|ms-vscode-remote|0.39.9|
|rest-client|humao|0.22.2|
|todo-tree|Gruntfuggly|0.0.162|
|vscode-color|anseki|0.4.5|
|vscode-html-css|ecmel|0.2.3|
|vscode-java-debug|vscjava|0.23.0|
|vscode-java-dependency|vscjava|0.6.0|
|vscode-java-pack|vscjava|0.8.0|
|vscode-java-test|vscjava|0.21.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-m3u|af4jm|1.0.0|
|vscode-markdownlint|DavidAnson|0.31.2|
|vscode-maven|vscjava|0.19.1|
|vscode-npm-script|eg2|0.3.9|
|vscode-standardjs|chenxsan|1.2.3|
|vscode-svg-previewer|vitaliymaz|0.5.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|

**Comment by rjmholt** [comment] 2019-11-04 21:01
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2274

**Comment by sba923** [comment] 2019-11-05 10:13
I can't repro the @ / error message outside of the debugging context. Running a script with no breakpoints or invoking a cmdlet behaves normally.

**Comment by rjmholt** [comment] 2019-11-05 17:15
Yes I think the `@` is inserted when the prompt is cancelled, which only happens when you run things from the editor rather than the console. Discussion continues in #2274.

**Closed** 2019-11-06 18:00 UTC
Labels: Resolution-Duplicate
