### ISSUE TITLE
Signature help for calling .NET methods

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/vscode-powershell#1532] opened 2018-09-14 17:28 UTC
**Summary of the new feature**

When calling .NET methods in PowerShell scripts, I would like to see signature help. I can see the signature in the completion info, but not once I typed the `(`.

**Comment by tylerl0706** [comment] 2018-09-18 21:14
This is actually a dupe of https://github.com/PowerShell/PowerShellEditorServices/issues/13. It's been around for a while and is something that everyone would enjoy.

We'll get to this as soon as we can... however we're spread quite thin at the moment

**Comment by rjmholt** [comment] 2018-10-10 06:11
Going to close this as a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1356.

**Closed by rjmholt** 2018-10-10 06:11 UTC
Labels: Area-IntelliSense, Issue-Enhancement
