### ISSUE TITLE
[Insiders] Cannot change Terminal Name from "Powershell Integrated Console"

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2766] opened 2020-06-13 00:04 UTC
Issue Type: <b>Bug</b>

You can use `$host.ui.RawUI.WindowTitle` to set the title on a normal terminal in latest vscode insiders. The powershell extension overrides this for the integrated terminal, there should be an option to support setting from the UI terminal. This will need to be careful to ignore the initial Powershell window setting, but allow everything from basically the profile onwards.

![image](https://user-images.githubusercontent.com/15258962/84554856-c9f8fd00-acce-11ea-8f0d-3c4e4d53f393.png)

Extension version: 2020.6.1
VS Code version: Code - Insiders 1.47.0-insider (7e4cc2c435927e5a2845897961a2af10ee7f784d, 2020-06-12T06:03:53.183Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment] 2020-06-13 00:30
I have a feeling that I might need guidance from @Tyriar for this one. How can I support this?

**Comment by JustinGrote** [comment] 2020-06-13 00:33
@TylerLeonhardt not entirely sure it "overrides" per se, maybe it just never makes the roundtrip back from PSES back to the xterm title API?

**Comment by Tyriar** [comment] 2020-06-13 15:43
This is by design; once an extension sets a title it cannot be unset. The terminal title is determined by the following priority:

1. An extension has set it
2. A process has set it with `terminal.integrated.experimentalUseTitleEvent` set to true
3. The shell title is pulled from the process name (which process it gets it from is a little complicated)

Currently you can't do anything here but I'm open to suggestions to change how it works 🤔

**Comment by TylerLeonhardt** [comment] 2020-06-13 18:02
I don't know... I mean. @JustinGrote is there a scenario here you have in mind? I don't want people to forget which one is the Integrated Console 😅

**Comment by JustinGrote** [comment] 2020-06-13 22:39
I would say this is an extremely low priority item, the use cases I can think of can pretty well just be communicated at the console, and you make a good point that the integrated can stay that and other terms can retitle themselves (e.g. Remoting to another system)

**Comment by andschwa** [comment] 2021-05-25 17:38
> This is by design; once an extension sets a title it cannot be unset. The terminal title is determined by the following priority:
> 
> 1. An extension has set it
> 2. A process has set it with `terminal.integrated.experimentalUseTitleEvent` set to true
> 3. The shell title is pulled from the process name (which process it gets it from is a little complicated)
> 
> Currently you can't do anything here but I'm open to suggestions to change how it works 🤔

This being the case, I'm going to close this issue. Thanks for the information 😁

**Closed** 2021-05-26 23:00 UTC
Labels: Area-Integrated Console, Issue-Discussion, Resolution-Answered
