### ISSUE TITLE
Unfortunate color choices with semantic highlighting

### ISSUE THREAD

**Issue by mattpwhite** [PowerShell/vscode-powershell#2856] opened 2020-08-03 19:22 UTC
(this is in reference to the PowerShell Preview extension 2020.7.0)

I understand that there are some limitations around the mapping PS token types to the (smaller) set of types the VS Code API allows and that this requires some compromises.  That said, I'm particularly bothered by the way things are colored with the default VS Code theme.  I don't mean which colors are chosen (that's obviously personal taste), I mean places where token types that are frequently adjacent to each other are given the *same* color.  The point of giving things colors is to provide contrast, that's not happening in a number of common cases.

1. Parameter names and variables are the same color.

![image](https://user-images.githubusercontent.com/3004040/89218433-01cc4480-d59c-11ea-96dd-45eabd0ba6f8.png)

1. Attributes and types are the same color.  This makes complex parameter declarations a bit harder to read.  It also makes attributes that have a type as an argument a bit worse.

![image](https://user-images.githubusercontent.com/3004040/89218709-84ed9a80-d59c-11ea-8c0c-289acc975ce3.png)

![image](https://user-images.githubusercontent.com/3004040/89218623-65567200-d59c-11ea-840f-dcd2ec179811.png)

**Comment by TylerLeonhardt** [comment] 2020-08-03 19:29
> Attributes and types are the same color.

This was raised in #2852 and I don't think there's anything we can do about it at a PowerShell token level.

**Comment by Jaykul** [comment] 2020-08-04 16:53
3. Command names as parameter values should be highlighted as strings, not as commands:
![image](https://user-images.githubusercontent.com/192942/89321884-7b723a00-d651-11ea-87c3-36156c00a43c.png)

**Comment by SydneyhSmith** [comment] 2020-08-04 21:01
Thanks @mattpwhite interestingly it looks like we are semantically labeling attributes and types separately and correctly, so it looks like the issue is with the default theme not showing these differently---I wonder if this repros in other themes?

**Comment by TylerLeonhardt** [comment] 2020-08-04 21:09
This is also a problem in TypeScript coloring:
![image](https://user-images.githubusercontent.com/2644648/89345224-ef194480-d65b-11ea-8695-0176013c9751.png)

In this example, foo is a "variable" and bar is a "parameter"...

So I think this should be fixed in the theme if you can please open an issue in https://github.com/Microsoft/vscode

**Closed** 2020-08-04 22:00 UTC
Labels: Area-Semantic Highlighting, Resolution-Duplicate, Resolution-External, vscode-feature

**Comment by mattpwhite** [comment] 2020-08-05 03:07
The TypeScript analogy isn't right.  Those are both variables, I wasn't saying that arguments should be colored differently than non-argument variables.  I was saying that the parameter _name_ being the same color as a variable is unfortunate.  TypeScript (AFAIK) doesn't have named arguments. The analogy would be a named argument in C# or Python.  Unfortunately those also get the same color, so I guess this is on VS Code.

![image](https://user-images.githubusercontent.com/3004040/89367173-61167b80-d6a6-11ea-9ab2-baa8f2c2c9af.png)

In the above, I'd want the `whatever` in `Foo` and the `something` in `Bar` to all be the same.  The argument _name_ `whatever` in `Bar` is what I would hope would be colored differently. Anyway, one for the VS Code repo, not PS...

**Comment by TylerLeonhardt** [comment] 2020-08-05 14:54
@mattpwhite if you look at the TypeScript tokens, you'll see what I mean:

![image](https://user-images.githubusercontent.com/2644648/89428041-cbeca480-d6f0-11ea-9658-5d3c37614f63.png)

![image](https://user-images.githubusercontent.com/2644648/89428076-d73fd000-d6f0-11ea-8d65-c694011849e0.png)

Look at "semantic token type".

**Comment by TylerLeonhardt** [comment] 2020-08-05 15:07
Same deal with PowerShell:

![image](https://user-images.githubusercontent.com/2644648/89429609-9f398c80-d6f2-11ea-9b75-570c95db674b.png)
![image](https://user-images.githubusercontent.com/2644648/89429636-a95b8b00-d6f2-11ea-9369-30d2178c369e.png)

We are providing the right names for tokens but the problem is that for the default theme they are colored the same.

**Comment by TylerLeonhardt** [comment] 2020-08-05 15:08
If you want to see this view, simply do (ctrl+Shift+p) and type:
![image](https://user-images.githubusercontent.com/2644648/89429754-cd1ed100-d6f2-11ea-9896-4ec0158f5d42.png)
