### ISSUE TITLE
Block for comment based help does not fold

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/vscode-powershell#1335] opened 2018-05-27 01:49 UTC
code -v
1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64

$pseditor.EditorServicesVersion
PS C:\src\t> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      7      0      0

code --list-extensions --show-versions
C:>code --list-extensions --show-versions
ms-python.python@2018.4.0
ms-vscode.PowerShell@1.7.0

$PSVersionTable

PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I am experiencing a problem with folding the block of comment based help.

A block of comment-based help cannot fold the entire block. Each item (.SYNOPSIS, .DESCRIPTION, etc.) can be folded, but not the entire block of <# #>.

**Comment by tylerl0706** [comment] 2018-05-29 21:13
This is a dupe of https://github.com/PowerShell/vscode-powershell/issues/1276 😄

**Closed by tylerl0706** 2018-05-29 21:13 UTC
