### ISSUE TITLE
Better visual indicator that things are wrong

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1592] opened 2018-10-27 16:25 UTC
**Summary of the new feature**

Right now when there is an error of sort VSCode the only visual indicator is the red file with a problem

![image](https://user-images.githubusercontent.com/15063294/47585631-1eb2fd00-d95e-11e8-8af4-b22a70cb8e84.png)

Or none at all until you run it and it's too late. 

**Proposed technical implementation details (optional)**

It would be great to show line where the first (I guess only 1st problem is visible, not all of them but if more then one, it would be great to see all) problem is more or less occurring. I sometimes see red file and then I search for a missing comma on 1000 line script. It's often easier to press F5, and see where it terminates.

**Comment by rkeithhill** [comment] 2018-10-27 16:30
Have you checked out at the `Problems` view?  Press <kbd>ctrl+shift+m</kbd> and it will show all detected problems in the script file, along with other files you have open.   One thing the extension is not good about is removing entries from the Problems views after they have been fixed.  Closing and re-opening the file will fix it but certainly is not ideal.

**Comment by PrzemyslawKlys** [comment] 2018-10-27 16:42
I saw this problems tab but it's often hidden (as Terminal is my main one). Not sure if you can divide that screen into 3 separate screens. 

![image](https://user-images.githubusercontent.com/15063294/47606679-ed4a3800-da16-11e8-8be7-3f8640166056.png)

Also notice that I sometimes (often) use the screen like that:

![image](https://user-images.githubusercontent.com/15063294/47606695-0bb03380-da17-11e8-934e-00e40213cdfe.png)

And notice how it only started to see problem after I added another function Test { } with an error. All errors above were ignored and not visible until I've run it.

![image](https://user-images.githubusercontent.com/15063294/47606727-677abc80-da17-11e8-87b3-7b68562604c0.png)


It also doesn't see problems with chars, or wrong lines but that is related to: https://github.com/PowerShell/PSScriptAnalyzer/issues/1089 and 

https://github.com/PowerShell/PSScriptAnalyzer/issues/981 still I would expect PSSA to pick this up? Or I have wrong expectancy on this?

**Comment by TylerLeonhardt** [comment] 2018-11-08 22:22
So I think this is a combination of issues.

1) that you're not getting results beck from PSScriptAnalyzer fast enough - dupe of https://github.com/PowerShell/vscode-powershell/issues/1232

2) that you'd like a feature from VSCode to split the bottom pane where you could have Problems next to, say, the Terminal.

@PrzemyslawKlys would you mind opening an issue on VSCode for that feature request?

Is it reasonable to close this as a dupe?

**Closed as completed** 2018-11-08 22:27 UTC
Labels: Issue-Enhancement

**Comment by PrzemyslawKlys** [comment] 2018-11-08 22:32
Like... 

![image](https://user-images.githubusercontent.com/15063294/48231440-69953180-e3ae-11e8-9d90-70c7fbfd9f8c.png)

So many problems, and complains... that are not there anymore. I can press F5 and it will tell me there are no errors, yet VS Code claims there are 6 problems :-) including critical ones...
