### ISSUE TITLE
Holding Ctrl+Shift+Left/Right Arrow doesn't work in the variable selection

### ISSUE THREAD

**Issue by Ali64B** [PowerShell/vscode-powershell#1358] opened 2018-06-10 19:16 UTC
### System Details

- Operating system name and version: Win 10
- VS Code version: 1.23.1
- PowerShell extension version: 1.7.0.0

### Issue Description

I can't select a variable with CTRL+SHIFT+LEFT/RIGHT ARROW, it doesn't continue highlighting a $ character. 

kind regard :-)

**Comment by rjmholt** [comment] 2018-06-11 17:45
Hi @Ali64B, would you be able to provide a small reproducible scenario? Like a code snippet we could try to reproduce this with? And if the behaviour is more visual, you should be able to upload a GIF here that demonstrates it.

**Comment by Ali64B** [comment] 2018-06-12 16:48
Variable in PowerShell must start with “$” and since “$” has been introduced as white space character there is no way to select the whole variable name with one time using CTRL+SHIFT+LEFT/RIGHT ARROW.

**Comment by tylerl0706** [comment] 2018-06-14 21:53
Hey @Ali64B, can you elaborate on what you mean by 

> since "$" has been introduced as a white space character

**Comment by rjmholt** [comment] 2018-06-14 22:21
It looks like `$` should be included in our "word" definition already:
https://github.com/PowerShell/vscode-powershell/blob/9bf58a7ab21275653ee1f9ff7571060fc094e0c7/src/main.ts#L56

**Comment by Ali64B** [comment] 2018-06-17 19:36
Hi @rjmholt.
That is exactly what I told.

**Comment by rjmholt** [comment] 2018-06-17 19:43
@Ali64B No I mean, that regex defines "words" in PowerShell, and already includes `$variable`, so that should already work (but evidently doesn't).

Is there another place where you're saying we're defining whitespace characters?

Otherwise, it may be a change we need to make in [the VSCode code](https://github.com/Microsoft/vscode/tree/master/extensions/powershell), although I'm not sure where.

So to be clear, I'm not sure what is causing this bug, but I think the line I linked above is already correct.

**Comment by Ali64B** [comment] 2018-06-17 19:44
Hi @tylerl0706, I think the solution found by  @rjmholt.

**Comment by Ali64B** [comment] 2018-06-17 20:09
This issue is not fixed yet [Allow language extensions to override editor.wordSeparators](https://github.com/Microsoft/vscode/issues/33701)

**Comment by rjmholt** [comment] 2018-06-17 20:14
Good find! That looks like it might be the part in question. That means users can override that setting then yes??

**Comment by Ali64B** [comment] 2018-06-17 20:33
Yes , you're right.

**Comment by rjmholt** [comment] 2018-06-17 20:35
So I'm thinking we should come up with a good regex for PowerShell and post it here (so that anyone can use it). And then work out if there's a way for us to set that setting when the extension is running.

I've also followed up on that issue you linked.

**Comment by tylerl0706** [comment] 2018-06-18 02:28
```
, "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
```

**Comment by tylerl0706** [comment] 2018-06-18 16:48
Since we don't have this at the language level yet, I'm gonna go ahead and close this in favor of the VSCode issue.

Let me know if you think otherwise!

**Closed by tylerl0706** 2018-06-18 16:48 UTC

**Comment by rkeithhill** [comment] 2018-06-19 23:31
So I tried that `"editor.wordSeparators"` for a while and decided I didn't like it.  When you double-click to select a variable `$foo` it will not highlight any instances of the form `${foo}` which is common inside double-quoted strings.  So I'm going back to the default value for this setting.

**Comment by rjmholt** [comment] 2018-06-20 01:56
Does this work better?

```json
"word.separators": "`~!@#%^&*()-=+[}\\|;:'\",.<>/?"
```

**Comment by rkeithhill** [comment] 2018-06-20 21:15
Still leaves the `${var}` form unselected:

![image](https://user-images.githubusercontent.com/5177512/41685056-9363c520-749c-11e8-8d61-655164213250.png)

And you still have the issue of the whole variable not being selected when you specify the scope e.g,: `$global:foo = 1`.

**Comment by rjmholt** [comment] 2018-06-21 02:32
Oh whoops, I left one of the braces in. Also we could try taking the colon out too:

```json
"editor.wordSeparators": "`~!#%^&*()-=+[]\\|;'\",.<>/?"
```

(Also took the `@` out for splatting)

**Comment by rkeithhill** [comment] 2018-06-23 21:07
That handles the `$script:foo = 1` case but it still won't highlight `"${script:foo}"` when I have selected `$script:foo` in the assignment statement.
