### ISSUE TITLE
Integrated terminal crashes with PS Extension V2 when stopping interactive debug session

### ISSUE THREAD

**Issue by muzzar78** [PowerShell/vscode-powershell#1531] opened 2018-09-14 14:10 UTC
## Issue Description ##

I am experiencing a problem with PowerShell integrated terminal crashing when I stop an interactive debugging session. I'm able to replicate the problem each time I stop the interactive debugging session.

## Attached Logs ##
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/2383616/vscode-powershell.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.27.2|
| PowerShell Extension Version | 2.0.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.1.0|
|PSEdition|Core|
|GitCommitId|6.1.0|
|OS|Microsoft Windows 10.0.17134 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.1.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.4.3|
|azurerm-vscode-tools|msazurermtools|0.4.2|
|csharp|ms-vscode|1.16.1|
|gitlens|eamodio|8.5.6|
|kubernetes-snippets|ipedrazas|0.1.9|
|markdown-pdf|yzane|1.2.0|
|PowerShell|ms-vscode|2.0.0|
|vscode-azurestorage|ms-azuretools|0.4.1|
|vscode-docker|PeterJausovec|0.2.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|0.1.13|
|vscode-yaml|redhat|0.0.16|;

</details>

**Comment by muzzar78** [comment] 2018-10-05 15:33
I did some more testing. This issue occurs when in the interactive session I launch a script with a breakpoint. Then if I stop the debugger while inside the script the error occurs. If I step through the script to completion then stop the debugger the issues doesn't occur.

**Comment by tylerl0706** [comment] 2018-10-05 16:16
Thanks for the update @muzzar78 can you repro this crash in 1.9.0? I'd like to determine that the issue is in v2.

**Comment by rjmholt** [comment] 2018-10-05 16:19
I think this is also in 1.9.0 -- see https://github.com/PowerShell/vscode-powershell/issues/1494. I think this is probably a duplicate of that issue -- although the more data we have the better.

**Comment by rjmholt** [comment] 2018-10-08 22:19
Duping this to https://github.com/PowerShell/vscode-powershell/issues/1494 so we can keep all the discussion there.

**Closed by rjmholt** 2018-10-08 22:19 UTC
Labels: Area-Debugging, Issue-Bug
