### ISSUE TITLE
README.md has incorrect encoding, causing garbled display of the Details page

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#1875] opened 2019-04-13 06:08 UTC
The README.md file for preview 3 (a.k.a. 2.0.2) has incorrect encoding (UTF-16 with two BOMs?):

![image](https://user-images.githubusercontent.com/12860484/56075441-1d1daa00-5dc3-11e9-9b6b-730b6d1e2254.png)

As a result, the "Details" page in VScode is garbled:

![image](https://user-images.githubusercontent.com/12860484/56075447-36265b00-5dc3-11e9-96f6-866187fc9c7b.png)

**Comment by TylerLeonhardt** [comment] 2019-04-13 18:41
This is probably caused by [this line](https://github.com/PowerShell/vscode-powershell/blob/master/vscode-powershell.build.ps1#L122) in the build script. This should be `Out-File -Encoding utf8`

We'll get this fixed.

**Comment by bergmeister** [comment] 2019-04-13 19:01
@TylerLeonhardt The `Out-File` cmdlet might not be the best choice here. AFAIK the `Set-Content` cmdlet's purpose is to be a special case of `Out-File` for string based content and my past experience is that once I switched from `Out-File` to `Set-Content` then encoding problems went away (this was experience from the days of Windows PowerShell, since PowerShell Core has been refactored to have a much better and consistent encoding behaviour, I have not had any encoding problems in PS6 any more)

**Comment by chuanjiao10** [comment] 2019-04-15 06:21
It is recommended to keep the bom header.

**Comment by codykonior** [comment] 2019-04-15 08:17
It is not recommended to keep the BOM header. Not only does it break this, it breaks git comparisons, and it's unfriendly to Linux.

Furthermore, VSCode's default encoding is UTF-8 without BOM. PowerShell 6's default encoding is UTF-8 without BOM on all platforms.

**Comment by chuanjiao10** [comment] 2019-04-15 10:50
Readme.md is a text file. It has bom, no bom, and VS Code defaults to UTF-8 without BOM.
PowerShell defaults to UTF-8 without BOM. It doesn't matter.
does it matter?
If it has a bom header, can't vscode open it?
If it has a bom header, can powershell not open it?

Why the bom of this project is set to follow your powershell project?

edge on windows open marketplace web page no garbled .

**Comment by rjmholt** [comment] 2019-04-15 16:16
This problem is specific to the preview version, since we add a snippet to the README for that using a PowerShell command.

Since VSCode is the primary place the README is displayed, I imagine BOM-less UTF-8 is the way to go. We probably have the odd emoji in the README, so anything trying to read that as CP-1252 or CP-437 is going to have garbage bits, but if you're using the preview extension, I'd expect you to be using UTF-8.

**Comment by SydneyhSmith** [comment] 2019-05-28 19:33
This issue is fixed in the latest release.

**Closed by SydneyhSmith** 2019-05-28 19:33 UTC
Labels: Area-Documentation, Issue-Bug
