### ISSUE TITLE
Code folding is messed up in the 2020.5.0 preview

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#2708] opened 2020-05-17 18:51 UTC
Issue Description
=====

The code folding indicators are appearing on lines they shouldn't and don't always appear on lines where they should.

![image](https://user-images.githubusercontent.com/5177512/82156976-e030ac00-983b-11ea-81d9-8aec2c84e6ba.png)

Attached Logs
=====
This is it. 
```
2020-05-15 09:52:24.103 -06:00 [INF] PowerShell runtime version: 7.1.0, edition: Core
2020-05-15 09:52:24.555 -06:00 [INF] highlight handler loaded
2020-05-15 09:52:27.528 -06:00 [INF] Configuring PSScriptAnalyzer with rules at 'c:\Users\Keith\GitHub\dahlbyk\posh-git\PSScriptAnalyzerSettings.psd1'
2020-05-16 15:47:13.165 -06:00 [ERR] Execution of the following command(s) completed with errors:

    Microsoft.PowerShell.Core\Get-Command GitTabExpansionInternal -ErrorAction Ignore


2020-05-17 12:34:20.597 -06:00 [ERR] Execution of the following command(s) completed with errors:

    Microsoft.PowerShell.Core\Get-Command For -ErrorAction Ignore
```
I had log verbosity set to normal.  When I changed it to diagnostic, the session restarted and this issue went away.  :-(   As a result, this is probably not actionable so no biggie if you close it as not reproducible.  So far, I haven't been able to repro this.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0-preview.2|
|PSEdition|Core|
|GitCommitId|7.1.0-preview.2|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0-preview.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|codetour|vsls-contrib|0.0.25|
|cpptools|ms-vscode|0.28.0|
|csharp|ms-dotnettools|1.21.18|
|debugger-for-chrome|msjsdiag|4.12.6|
|EditorConfig|EditorConfig|0.14.5|
|gistfs|vsls-contrib|0.0.67|
|gitdoc|vsls-contrib|0.0.6|
|githistory|donjayamanne|0.6.5|
|github-markdown-preview|bierner|0.0.2|
|gitlens|eamodio|10.2.1|
|html-snippets|abusaidm|0.2.1|
|lsp-inspector-webview|octref|0.0.2|
|markdown-all-in-one|yzhang|2.8.0|
|markdown-checkbox|bierner|0.1.3|
|markdown-emoji|bierner|0.0.9|
|markdown-preview-github-styles|bierner|0.1.6|
|markdown-yaml-preamble|bierner|0.0.4|
|powershell-preview|ms-vscode|2020.5.0|
|python|ms-python|2020.5.78807|
|remote-wsl|ms-vscode-remote|0.44.2|
|sass-indented|robinbentley|1.5.1|
|theme-cobalt2|wesbos|2.1.6|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-markdownlint|DavidAnson|0.35.1|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|

**Comment by scriptingstudio** [comment] 2020-05-17 20:01
Can confirm

**Comment by TylerLeonhardt** [comment] 2020-05-17 20:06
My guess is that this is a dupe of https://github.com/PowerShell/vscode-powershell/issues/2627

**Comment by SydneyhSmith** [comment] 2020-05-19 21:01
Thanks @TylerLeonhardt I'll mark this as a dupe.

**Closed** 2020-05-20 22:00 UTC
Labels: Resolution-Duplicate
