### ISSUE TITLE
Walkthrough's for PowerShell

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3647] opened 2021-10-28 15:55 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

VS Code has a contribution point of Walkthroughs that appear in the Getting Started/Welcome view when the user opens vscode:
![image](https://user-images.githubusercontent.com/2644648/139290742-1ffb5a26-b968-4630-8256-62b7726498ba.png)

When you click on one, you get this:
![image](https://user-images.githubusercontent.com/2644648/139290922-a071d6aa-e070-4794-86b8-ae4525b03ff6.png)

I remember wanting to build this myself before this feature existed.

This would be a fantastic place to configure those polarizing options like:
* Choosing the version of PowerShell
* ISE Mode
* showing the terminal (`powershell.integratedConsole.showOnStartup`) _I'd love this one!_
* showing the command explorer

### Proposed Design

Here are the docs on this:
https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs

Shouldn't be _too_ much work to add the contribution and some small code that actually changes these things (just commands).

Here's a sample extension:
https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample

cc @jacksonkearl

**Comment by TylerLeonhardt** [comment] 2022-02-24 23:54
Links to the documentation either on the vscode website or PowerShell Docs would also be great.

**Comment by fflaten** [comment] 2022-06-19 14:36
@andschwa This is taken now, right? Should the survey URL mentioned in Community Call be available here or was is it closed already? 🙂

**Comment by S-Hakim** [comment] 2022-06-21 16:49
@fflaten You can fill out the [survey](https://forms.office.com/r/23tVpPJGyx) here. This is currently being worked on (:

**Comment by andschwa** [comment] 2022-08-03 18:34
Going to resolve this as a duplicate of #4080! Thanks for the idea Tyler.

**Closed by andschwa** 2022-08-03 18:34 UTC
Labels: Issue-Enhancement, Area-Documentation
