### ISSUE TITLE
PowerShell Intellisense and most right-click features stop working

### ISSUE THREAD

**Issue by MikeStephens-MS** [PowerShell/vscode-powershell#2596] opened 2020-03-31 21:44 UTC
Issue Description
=====
When I author PowerShell scripts, I notice that after a non-deterministic amount of time, Intellisense for the cmdlets stops working. When this happens, the "PowerShell" progress message spins indefinitely. What else happens is that most of the right-click functions such as Go to references or Go to definition do not work. A blue progress-like indicator starts scrolling from the left to right across the top of the screen. The only way to fix this is to close VSC completely (reloading the extension of VSC does not resolve the issue). I first noticed this behavior two releases ago.
Filed with VSCode, who pointed the finger at the extension [PowerShell Intellisense and most right-click feature stop working #93607 Closed](https://github.com/microsoft/vscode/issues/93607)
Attached Logs
https://github.com/microsoft/vscode/issues/93607  [Closed]
[StartEditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/4411704/StartEditorServices.zip)
[StartEditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/4411706/StartEditorServices.zip)
[StartEditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/4411707/StartEditorServices.zip)

=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.43.2|
| PowerShell Extension Version | 2020.3.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.628|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.628|
|BuildVersion|10.0.18362.628|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.8.0|
|docs-article-templates|docsmsft|0.2.7|
|docs-images|docsmsft|0.0.6|
|docs-linting|docsmsft|0.0.2|
|docs-metadata|docsmsft|1.0.4|
|docs-preview|docsmsft|0.3.44|
|docs-yaml|docsmsft|0.2.4|
|LinkCheckMD|blackmist|0.3.1|
|powershell|ms-vscode|2020.3.0|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-sidebar|Acrolinx|1.1.2|
|vscode-yaml|redhat|0.7.2|

**Comment by TylerLeonhardt** [comment] 2020-04-02 21:10
Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? It has a few performance fixes in it and it might be fixed in that already.

**Comment by MikeStephens-MS** [comment] 2020-04-03 19:51
@TylerLeonhardt Thank you for the direction. I disabled the current and installed the preview. Encountered the same problem using the preview.  Additional info-- it does not seem to matter how big the script is.  One script is 800 lines while the other is 200. the same side effects occur the PowerShell extension progress message just spins endlessly. Also, when in this state, code folding does not work either. It is visible, but if you click the chevron, it does not respond.

**Comment by PrzemyslawKlys** [comment] 2020-04-04 16:22
I've been seeing the same thing. I'm using the newest preview. First, few autocomplete features work fine and then it suddenly stops. Terminal continues to work (PSReadLine).

**Comment by TylerLeonhardt** [comment] 2020-04-05 03:45
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by PrzemyslawKlys** [comment] 2020-04-05 21:11
[1586085787-b4f071c6-ec13-4ba6-8d6d-7552d19a59661586085785900.zip](https://github.com/PowerShell/vscode-powershell/files/4434908/1586085787-b4f071c6-ec13-4ba6-8d6d-7552d19a59661586085785900.zip)

When I stumble on the issue IntelliSense doesn't work. But if you wait enough time it comes back from time to time.

**Comment by SydneyhSmith** [comment] 2020-04-07 21:19
We are working on the fix for this issue right now, but I am going to mark as duplicate of #2522

**Closed** 2020-04-08 22:00 UTC
Labels: Area-IntelliSense, Issue-Performance, Needs-Repro-Info, Resolution-Duplicate
