### ISSUE TITLE
Formatter does not obey some whitespace settings

### ISSUE THREAD

**Issue by anttiah** [PowerShell/vscode-powershell#2375] opened 2019-12-18 14:17 UTC
# Issue Description
The `powershell.codeFormatting.WhitespaceInsideBrace` setting has no effect and formatter adds whitespaces regardless of its value.

This has been around since 2019.9.0. I was hoping it would get fixed in this release but it didn't.

AFAIK, this one has nothing to do with the pipeline indentation issues reported earlier and should not be treated as a duplicate of any of those.

# Steps to reproduce
Set
`"powershell.codeFormatting.WhitespaceInsideBrace": false`

Type into the editor
`& {0}`

Format document (`Alt` + `Shift` + `F`)

# Expected behaviour
`& {0}`
No whitespace gets added inside braces.

# Actual, incorrect behavior
`& { 0 }`
Note the added whitespace after the `{` and before the `}`.
 
# Environment data
vscode-powershell v2019.12.0

VS Code
```
Version: 1.41.0 (system setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

# Notes
This is basically a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2245 but it got closed with erroneous information before I found it and managed to comment.

**Comment by SydneyhSmith** [comment] 2019-12-18 19:52
@anttiah thanks for opening this issue and providing repo steps! I am having some trouble reproducing this issue after our latest release--it would be great to know what your settings.json looks like. It would also be helpful to know if you are using the PowerShell Extension or our preview version of the PowerShell Extension?

**Comment by anttiah** [comment] 2019-12-18 20:41
Hi @SydneyhSmith thank you for your prompt response. I'm using release version:
```
vscode-powershell Release History
v2019.12.0
Thursday, December 12, 2019
PowerShellEditorServices
🐛 👮‍ PowerShellEditorServices #1102 - Add PSAvoidAssignmentToAutomaticVariable to the default set of PSSA rules. (Thanks @bergmeister!)
🐛 👮‍ vscode-PowerShell #2214 - Fix PipelineIndentationStyle configuration issue. (Thanks @bergmeister!)
```

Before my tests I deleted directories `~\.vscode` and `~\AppData\Roaming\Code` and installed just the vscode-powershell extension. The only item in my settings.json is the one mentioned in repo steps.

HTH

**Comment by SydneyhSmith** [comment] 2019-12-19 21:40
Thanks for the additional information @anttiah I am able to preproduce this in our "stable" PowerShell extension but not in the PowerShell Preview extension...we recently published an update to our [Preview Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue? The good news is that we expect these changes to hit our "stable" PowerShell extension in our next release

**Comment by TylerLeonhardt** [comment] 2019-12-20 00:57
@bergmeister did we cherry pick this poorly again 😅

**Comment by anttiah** [comment] 2019-12-20 07:35
@SydneyhSmith Does not happen with the preview version.

Don't know if this is just a typo or cherry pick related but I noticed that preview version writes the `powershell.codeFormatting.whitespaceInsideBrace` line into settings.json with lower case `w` whereas release version writes it with upper case `W` -> `powershell.codeFormatting.WhitespaceInsideBrace`.

**Comment by anttiah** [comment] 2020-01-03 12:08
Issue is still occurring.

**Comment by bergmeister** [comment] 2020-01-03 16:26
I don't think it is a cherry picking problem, by quickly looking at the 2 PSES branches @TylerLeonhardt . @anttiah  is right though that the preview extension changed the settings to start all with a lowercase (PR #1867) 9 months ago.

**Comment by bergmeister** [comment] 2020-01-03 16:42
Ok, I've checked PSSA, which works fine ( `Invoke-Formatter '$a={$b}' -Verbose -Settings @{IncludeRules=@('PSUseConsistentWhitespace'); Rules=@{'PSUseConsistentWhitespace'=@{Enable=$true; CheckInnerBrace=$true}}}`).
Maybe it is a wiring issue again, I'll have a look again

**Comment by TylerLeonhardt** [comment] 2020-01-11 00:16
Fixed in that PR ^

**Closed by TylerLeonhardt** 2020-01-11 00:17 UTC
Labels: Area-Code Formatting, Area-Script Analysis, Issue-Bug
