### ISSUE TITLE
Startup Banner Breaks the Launch of Plugin

### ISSUE THREAD

**Issue by chen-wu** [PowerShell/vscode-powershell#2941] opened 2020-09-10 02:38 UTC
### System Details

System Details Output
```
The terminal process "C:\Users\AAA\.dotnet\tools\pwsh.exe '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <===== " -LogLevel 'Diagnostic' -LogPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1599704572-3de72f1b-995e-4885-8134-f657f636b7f51599703686800\EditorServices.log' -SessionDetailsPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-37972-536684' -FeatureFlags @() '" terminated with exit code: 1.
```

### Issue Description

The plugin and language service cannot start

#### Expected Behaviour

should be able to start

#### Actual Behaviour

error message displayed

### Attached Logs

```
9/10/2020 10:22:52 AM [NORMAL] - Language server starting --
9/10/2020 10:22:52 AM [NORMAL] -     PowerShell executable: C:\Users\AAA\.dotnet\tools\pwsh.exe
9/10/2020 10:22:52 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Diagnostic' -LogPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1599704572-3de72f1b-995e-4885-8134-f657f636b7f51599703686800\EditorServices.log' -SessionDetailsPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-37972-536684' -FeatureFlags @() 
9/10/2020 10:22:52 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Diagnostic' -LogPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1599704572-3de72f1b-995e-4885-8134-f657f636b7f51599703686800\EditorServices.log' -SessionDetailsPath 'c:\Users\AAA\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-37972-536684' -FeatureFlags @() 
9/10/2020 10:22:52 AM [NORMAL] - pwsh.exe started.
9/10/2020 10:22:52 AM [NORMAL] - Waiting for session file
9/10/2020 10:26:53 AM [NORMAL] - Timed out waiting for session file to appear.
9/10/2020 10:26:53 AM [NORMAL] - Language server startup failed.
9/10/2020 10:26:53 AM [ERROR] - The language service could not be started: 
9/10/2020 10:26:53 AM [ERROR] - Error: Timed out waiting for session file to appear.
```

### VSCode extensions:       
Angular.ng-template@0.1000.8 
cssho.vscode-svgviewer@2.0.0 
DotJoshJohnson.xml@2.5.1     
mhutchie.git-graph@1.25.0    
ms-vscode.powershell@2020.6.0
qcz.text-power-tools@1.15.0  

### PowerShell version:

PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

If I supress startup banner in settings, the plugin can be started correctly. I also checked the message in [session.ts](https://github.com/PowerShell/vscode-powershell/blob/45bcca8f9ae6cb1cbe23739c0a7da581b34c9b36/src/session.ts#L199)
After some testing, I found that the space and line break in this banner message will stop the language service from launching correctly. Not sure why.

**Comment by rjmholt** [comment] 2020-09-10 21:07
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2780

**Closed** 2020-09-14 22:00 UTC
Labels: Resolution-Duplicate
