### ISSUE TITLE
Script output does not get written to the debug console

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#284] opened 2016-09-07 16:11 UTC
### System Details
- Operating system name and version:
- VS Code version: 1.4.0
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: 

```
PS C:\Users\TrevorSullivan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

Sometimes I run a PowerShell script, and the Debug Console shows nothing.

Sometimes I run a PowerShell script, and the Debug Console shows output, but not Error stream output.

Sometimes I run a PowerShell script and the Debug Console shows output from the Output and Error streams, as expected.

This happens with both VSCode and VSCode Insiders (as of today's release).
### Reproduction Steps

Inconsistent results.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment] 2016-09-07 16:59
Yep, this is a general problem with output flushing at the moment.  I've got an issue filed at the PS Editor Services repo to track the work for this: https://github.com/PowerShell/PowerShellEditorServices/issues/138

**Comment by pcgeek86** [comment] 2016-09-07 18:43
@daviwil Thanks, this is a show-stopper for VSCode. I'm using the PowerShell Console host to run tests for now, instead. Still authoring in VSCode.

**Comment by bughit** [comment] 2016-09-07 21:31
can you make 0.6.2 available, it;s the last working verion

**Comment by daviwil** [comment] 2016-09-07 21:38
Hey @bughit, there's a set of steps you can follow here to get back to 0.6.2 (just change the version from 0.6.1 to 0.6.2):

https://github.com/PowerShell/vscode-powershell/issues/243#issuecomment-243296211

Is it the script output issue that's blocking you or something else?

**Comment by bughit** [comment] 2016-09-07 22:16
> Is it the script output issue that's blocking you
yes

**Comment by GHRoss** [comment] 2016-10-02 12:52
Has there been any progress made on this? It's sort of killing me.

**Comment by daviwil** [comment] 2016-10-02 14:33
Yep! I've made huge progress with moving everything to a new model where all console activity happens directly in the real PowerShell console running in the integrated terminal. I think I'll have a new update ready in a couple weeks. 

I'm really sorry this issue has been causing your trouble, soon you won't have to deal with it anymore :)

**Comment by GHRoss** [comment] 2016-10-08 19:10
Awesome, thanks David.

**Comment by sba923** [comment] 2016-11-17 21:05
Problem's still there with VSCode 1.7.1 (upgraded today) with version 0.7.2 of the extension...

Back to ISE for now ;-)

**Comment by RobertBernstein** [comment] 2016-11-25 16:57
Hoping this gets fixed in VSCode v1.7.2 and v0.7.2 of the extension soon.  Thanks!

**Comment by sba923** [comment] 2016-11-25 19:55
I hate to say, but with VSCode v1.7.2 and v0.7.2 of the extension the problem's still there...

**Comment by rkeithhill** [comment] 2016-11-25 19:56
Yes, it is still a problem.  You can workaround the issue by setting a breakpoint on the last line of script that executes.

**Comment by pcgeek86** [comment] 2016-11-28 15:45
@daviwil any ETA on the fix for this?

**Comment by daviwil** [comment] 2016-11-28 15:53
I'm working in it this week to be included with 0.8.0.  Will keep you posted!

**Comment by pcgeek86** [comment] 2016-11-28 16:09
@daviwil Nice!! I will test and tweet about it as soon as it drops!

**Comment by RobertBernstein** [comment] 2016-11-28 17:10
Thanks, @daviwil!

**Comment by daviwil** [comment] 2016-11-29 15:40
I've got a fix for this, it'll definitely be in 0.8.0: https://github.com/PowerShell/PowerShellEditorServices/pull/306

**Comment by GHRoss** [comment] 2016-11-29 16:02
Can we test somehow?

**Comment by daviwil** [comment] 2016-11-29 16:10
I'll send out a preview build a little later today, would be nice to have folks try it out.

**Comment by GHRoss** [comment] 2016-11-29 16:24
Cool, where would I be able to find this?

**Comment by daviwil** [comment] 2016-11-29 17:08
I'll post it to this issue so you'll see it.

**Comment by daviwil** [comment] 2016-11-29 20:21
OK, here's a preview package.  Ignore the version number here, I'm using an arbitrarily increased version just for the purpose of sending out a preview.  Also, just to be clear, **USE AT YOUR OWN RISK**.  This build was created on my dev machine as a convenience for you guys so make sure you do the proper virus scanning, etc before you use it.

Download here: [PowerShell-0.7.10.zip](https://github.com/PowerShell/vscode-powershell/files/620099/PowerShell-0.7.10.zip)
**IMPORTANT:** After downloading this file, rename the extension from `.zip` to `.vsix`!

To install the preview, go into VS Code and run the `Extensions: Install from VSIX...` command then select the VSIX file that you downloaded and renamed.  The extension should install, click the 'Reload' button afterward so that VS Code gets restarted.  At this point you should be able to run a short script with output statements as you would expect.

This build should be stable enough to use until 0.8.0 gets released next week, but definitely file issues if you find any problems.

**Comment by daviwil** [comment] 2016-11-29 21:56
@ConstantineK Do your reactions mean that it worked for you? :)

**Comment by ConstantineK** [comment] 2016-11-29 22:01
Have to test in a bit, just something I have been waiting for :D

**Comment by daviwil** [comment] 2016-11-29 22:02
Cool!  Let me know how it goes :)

**Comment by sba923** [comment] 2016-11-29 22:04
I've tested with a first, very small script of mine, works fine.

My plan is to try to stop using ISE for a while, and see what that gets me...

I'll keep you posted.

**Comment by daviwil** [comment] 2016-11-29 22:09
@sba923 thanks for letting me know!  Keep me posted

**Closed** 2016-11-29 22:23 UTC
Labels: bug

**Comment by rkeithhill** [comment] 2016-11-29 22:47
I did manage to get it to crash:
```
11/29/2016 3:44:19 PM [VERBOSE] - Method "LaunchScript" at line 82 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Execution completed, flushing output then terminating...

11/29/2016 3:44:19 PM [VERBOSE] - Method "WriteMessage" at line 59 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "output",
      "body": {
        "category": "stdout",
        "output": "Done!\n8\r\n\r\nPS C:\\Users\\hillr\\.vscode\\extensions\\ms-vscode.PowerShell-0.7.10\\examples\r\n"
      }
    }

11/29/2016 3:44:19 PM [VERBOSE] - Method "WriteMessage" at line 59 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "terminated",
      "body": null
    }

11/29/2016 3:44:19 PM [NORMAL] - Method "Shutdown" at line 101 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Debug adapter is shutting down...

11/29/2016 3:44:19 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "disconnect",
      "arguments": {
        "restart": false
      },
      "type": "request",
      "seq": 5
    }

11/29/2016 3:44:19 PM [VERBOSE] - Method "Shutdown" at line 57 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\Channel\TcpSocketServerChannel.cs

    TCP listener has been stopped

11/29/2016 3:44:19 PM [VERBOSE] - Method "Shutdown" at line 69 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\Channel\TcpSocketServerChannel.cs

    TCP client has been closed

11/29/2016 3:44:19 PM [NORMAL] - Method "StartDebugService" at line 172 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Previous debug session ended, restarting debug service...

11/29/2016 3:44:19 PM [ERROR] - Method "OnListenTaskCompleted" at line 334 of C:\dev\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.HandleDisconnectRequest(Object disconnectParams, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass25_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__34.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0()
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.HandleDisconnectRequest(Object disconnectParams, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass25_0`2.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__34.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__33.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0()
       at System.Threading.Tasks.Task.Execute()<---
```

**Comment by daviwil** [comment] 2016-11-29 23:31
@rkeithhill Consistently or just once?  That seems unrelated to this change but its in an area where I've seen crashes before

**Comment by rkeithhill** [comment] 2016-11-29 23:51
Just once.  Unfortunately, I haven't been able to repro it.

**Comment by GHRoss** [comment] 2016-11-30 11:11
Works for me, thanks David.

Does this build include any other fixes?

**Comment by daviwil** [comment] 2016-11-30 15:04
It includes a pretty big change that improves the user-friendliness of the PowerShell integration.  Most of it you won't see unless there's a problem with the extension, but you can see one change in the status bar:

![image](https://cloud.githubusercontent.com/assets/79405/20757377/dea47c32-b6ca-11e6-88be-669f9f94be12.png)

Clicking this brings up this handy menu:

![image](https://cloud.githubusercontent.com/assets/79405/20757437/20c2c498-b6cb-11e6-8824-4ec0e9d41150.png)

Would certainly appreciate some feedback :)

**Comment by GHRoss** [comment] 2016-11-30 15:06
That's awesome actually.

My intellisense is incredibly slow, but that's always been the case. Ha.

**Comment by daviwil** [comment] 2016-11-30 15:13
Shouldn't be slow, are you running it on a machine with limited resources (like a VM)?  Was it faster in an earlier version of the extension?

**Comment by GHRoss** [comment] 2016-11-30 15:35
I'm not, and I can't work out why it's so slow. I have to wait about 30 seconds to a minute to get any suggestions back.

**Comment by ozu945** [comment] 2016-11-30 16:11
got the same crash as rkeithhill, twice.  but now it doesn't happen again.
saw the dialog asking to restart the poweshell session, that's new.

**Comment by ConstantineK** [comment] 2016-11-30 21:52
Works for me, had a simple command and ran it without update, didnt flush, with the VSIX extension, works like a charm :D

**Comment by ConstantineK** [comment] 2016-12-01 16:42
Having a few situations this morning where the same behavior (output not flushing) is occuring, trying to create a reproducible scenario now.
