### ISSUE TITLE
Integrated shell crashes when updating profile

### ISSUE THREAD

**Issue by TheIncorrigible1** [PowerShell/vscode-powershell#1564] opened 2018-10-07 21:32 UTC
## Issue Description ##

Whenever I make a change to `$Profile.CurrentUserAllHosts`, the integrated console crashes, reporting:

> The PowerShell session has terminated due to an error, would you like to restart it?

When I attempted to change the logging to Diagnostic, the error stopped happening, so here are my current settings:

    "powershell.debugging.createTemporaryIntegratedConsole": true,
    "powershell.developer.editorServicesLogLevel": "Error",
    "powershell.developer.editorServicesWaitForDebugger": true,
    "powershell.helpCompletion": "Disabled",
    "powershell.powerShellAdditionalExePaths": [
        {
            "versionName": "Windows PowerShell",
            "exePath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        },
        {
            "versionName": "Windows PowerShell (x86)",
            "exePath": "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"
        },
        {
            "versionName": "PowerShell Core",
            "exePath": "C:\\Program Files\\PowerShell\\6\\pwsh.exe"
        }
    ],
    "powershell.powerShellDefaultVersion": "PowerShell Core",

[My profile is here in case this is relevant](https://gist.github.com/TheIncorrigible1/3cf99643a26d9feb36ab718302256c66).

## Attached Logs ##

    2018-10-07 17:29:41.923 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
        ProtocolEndpoint message loop terminated due to unhandled exception:
        
        System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
        Parameter name: Position 146:1 is outside of the line range of 1 to 145.
        at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
        at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
        at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
        at System.Threading.Tasks.Task.Execute()
        --- End of inner exception stack trace ---
        ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
        Parameter name: Position 146:1 is outside of the line range of 1 to 145.
        at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
        at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
        at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__36.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
        at System.Threading.Tasks.Task.Execute()<---
        

    2018-10-07 17:29:41.925 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'ProtocolEndpoint_UnhandledException', line 435:
        PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.27.2|
| PowerShell Extension Version | 1.9.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.228|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.228|
|BuildVersion|10.0.17134.228|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|beautify|HookyQR|1.4.4|
|csharp|ms-vscode|1.16.1|
|debugger-for-chrome|msjsdiag|4.10.2|
|html-css-class-completion|Zignd|1.17.1|
|latex-workshop|James-Yu|5.11.1|
|mssql|ms-mssql|1.4.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|PowerShell|ms-vscode|1.9.0|
|python|ms-python|2018.8.0|
|rest-client|humao|0.19.1|
|sass-indented|robinbentley|1.4.9|
|tslint|eg2|1.0.39|
|vsc-material-theme|Equinusocio|2.4.2|
|vscode-docker|PeterJausovec|0.3.1|
|vscode-eslint|dbaeumer|1.6.0|
|vscode-html-css|ecmel|0.2.0|
|vscode-icons|robertohuertasm|7.27.0|
|vscode-markdownlint|DavidAnson|0.20.0|
|vscode-npm-script|eg2|0.3.5|
|vscode-react-native|vsmobile|0.6.18|
|vsliveshare|ms-vsliveshare|0.3.735|
|xml|DotJoshJohnson|2.3.2|;

</details>

**Comment by rjmholt** [comment] 2018-10-08 16:37
This looks to be a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1561. Closing in favour of that issue.

**Closed by rjmholt** 2018-10-08 16:37 UTC
