### ISSUE TITLE
Errors don't show up in Terminal anymore.

### ISSUE THREAD

**Issue by BrianCHodges** [PowerShell/vscode-powershell#2591] opened 2020-03-29 21:30 UTC
Issue Type: <b>Bug</b>

Open new file.
Set to PowerShell
add this line --> throw "bang"
run the program. 
No output.
I have had to got back to ISE :(

Extension version: 2020.3.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by TylerLeonhardt** [comment] 2020-03-30 15:51
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2576 and fixed already pending a release.

The fix already in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension.

You can still use whatever version of PowerShell you'd like. This is the Preview build of the _vs code extension_.

**Comment by BrianCHodges** [comment] 2020-03-30 16:31
Thanks! Great work!

Brian


________________________________

**Closed** 2020-03-31 19:00 UTC
Labels: Resolution-Duplicate
