### ISSUE TITLE
Cannot access history buffer in PowerShell console while being at a breakpoint when debugging a powershell script.

### ISSUE THREAD

**Issue by MarkKharitonov** [PowerShell/vscode-powershell#1338] opened 2018-05-29 14:24 UTC
## Issue Description ##

I am experiencing a problem with the powershell integrated shell - it does not traverse the history buffer when pressing up and down arrows.
My issue is exactly the same as https://github.com/Microsoft/vscode/issues/41948, the comments to which imply that it all should work as expected, yet it does not - the up arrow does not work at all and all the commands must be typed from scratch.

## Attached Logs ##

[EditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/2048592/EditorServices.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.16299 |
| VSCode | 1.23.1|
| PowerShell Extension Version | 1.7.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.16299.431|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.16299.431|
|BuildVersion|10.0.16299.431|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.15.2|
|gitdiffer|aaghabeiki|0.0.3|
|PowerShell|ms-vscode|1.7.0|;

</details>

The issue was previously open for VS Code itself - https://github.com/Microsoft/vscode/issues/50073#issuecomment-392781139

Here is the video clip - https://drive.google.com/open?id=13RSxEzcsuXUoXBl7fSQBmDCsQk1VkmnA

**Comment by tylerl0706** [comment] 2018-05-29 14:38
Thanks for this, this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/550. This will be included when PSReadLine is added.

**Closed by tylerl0706** 2018-05-29 14:38 UTC
