### ISSUE TITLE
"Smart" function rename

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#260] opened 2016-08-25 14:33 UTC
When I rename a function, I want to rename it wherever there's a reference. Here's a quick screencast for how it's done in PowerShell Studio. This is so helpful for me and would be for others as well.

http://www.screencast.com/t/jupQC2yVLz

**Comment by Bill-Stewart** [comment] 2016-09-21 19:28
I think you can do this already by 1) selecting the function's name, 2) use the command editor.action.selectHighlights (default key mapping is Ctrl+Shift+L), then 3) type the replacement name.

**Comment by SydneyhSmith** [comment] 2020-03-17 18:41
Closing as a dupe of #1440

**Closed by SydneyhSmith** 2020-03-17 18:41 UTC
Labels: Area-IntelliSense, Issue-Enhancement
