### ISSUE TITLE
VSCode doesn't stepin into debug function but is left outside

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1788] opened 2019-03-13 06:57 UTC
### System Details

System Details Output
```
### VSCode version: 1.32.1 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3 x64

### VSCode extensions:
aeschli.vscode-css-formatter@1.0.1
atomiks.moonlight@0.7.0
CoenraadS.bracket-pair-colorizer-2@0.0.28
donjayamanne.githistory@0.4.6
eamodio.gitlens@9.5.1
ecmel.vscode-html-css@0.2.0
emmanuelbeziat.vscode-great-icons@2.1.47
GitHub.vscode-pull-request-github@0.5.0
Kelvin.vscode-sshfs@1.14.3
liximomo.remotefs@0.0.13
monokai.theme-monokai-pro-vscode@1.1.12
ms-vscode.PowerShell@1.11.0
PKief.material-icon-theme@3.6.3
shd101wyy.markdown-preview-enhanced@0.3.12
WakaTime.vscode-wakatime@1.2.13
yzhang.markdown-all-in-one@2.1.1


### PSES version: 1.11.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Since some time (most likely on an upgrade of VSCode to the last version) I'm having a hard time debugging multi-file modules. You set a breakpoint in a function in 1 file, run the debug in the .ps1 somewhere else and breakpoint stops correctly but you are shown it stopped on the function executing it, not the breakpoint part. The data is also incorrect at that stage (or hidden) and you have to try and find it. 

I am not sure if it has been reported before, I saw this on twitter a few days ago and confirmed with at least 1 other person experiencing this.

And to be honest it doesn't always happen. It happens randomly. 

I'll try to catch it with some screenshots next time it happens

**Comment by ChuckHeatherly** [comment] 2019-03-13 17:48
Can you look at this VS code issue and see if it's the same one? I'm not sure if it's the right one because other issues are mentioned in the comments but it's the first one I found when it was happening to me last month. I'm using VS Code on Linux btw.
[https://github.com/Microsoft/vscode/issues/68277](url)

**Comment by PrzemyslawKlys** [comment] 2019-03-13 17:54
Looks like it. Usually, for me, it looks like this. It hit a breakpoint on line 120 but it's showing function which called it first. Like call stack moved up. 

![image](https://user-images.githubusercontent.com/15063294/54302506-4f1fce80-45c1-11e9-9a23-ee07b5332e24.png)

This screenshot was prepared by me where I moved call stack manually but often I would get that in an automated, repeated way.

**Comment by ChuckHeatherly** [comment] 2019-03-13 18:07
For me, the breakpoint is in a different file than the one that I launch (I include the other file using the dot operator). So I have to chase down the other file in the call stack window, usually by clicking the top entry.

**Comment by PrzemyslawKlys** [comment] 2019-03-13 18:27
That's what I have. I have Example file called .ps1 which calls module which is built from multiple .ps1 files that I'm debugging. But the thing is it works now for me. So it's a bit random.

**Comment by TylerLeonhardt** [comment] 2019-03-13 18:52
Are these files that it's suppose to jump to outside of your workspace?

**Comment by ChuckHeatherly** [comment] 2019-03-13 18:54
No, all my files are in the same workspace.

**Comment by PrzemyslawKlys** [comment] 2019-03-13 18:56
No, in my case it's 1 workspace. 

```
Import-Module .\PSWriteHTML.psd1 -Force
$Processes = Get-Process | Select -First 5
```

To get it to work I'm using Import-Module as above.

**Comment by rkeithhill** [comment] 2019-03-14 03:22
@PrzemyslawKlys If it happens again, be sure to attach your log files and let us know the name of the file you were having issues stepping into.

**Comment by PrzemyslawKlys** [comment] 2019-03-17 21:24
![image](https://user-images.githubusercontent.com/15063294/54498126-36862000-4903-11e9-992e-0ca93b33e17a.png)
[1552854938-403f744b-cd4a-4128-9744-a29c9ae8fa7d1552854936220.zip](https://github.com/PowerShell/vscode-powershell/files/2975720/1552854938-403f744b-cd4a-4128-9744-a29c9ae8fa7d1552854936220.zip)


Sorry for very large picture.

**Comment by rkeithhill** [comment] 2019-03-17 21:31
Duplicate of #1750 This has been fixed (due in the next release) and a workaround is discussed in that issue.

**Closed by rkeithhill** 2019-03-17 21:31 UTC
Labels: Area-Debugging, Needs-Repro-Info
