### ISSUE TITLE
1.8.3 helpCompletion Bug

### ISSUE THREAD

**Issue by ephenix** [PowerShell/vscode-powershell#1504] opened 2018-08-30 23:40 UTC
## Issue Description ##

helpCompletion is copying the entire contents of the function

Confirmed this issue is only found in the 1.8.3 release.
I tested each release from 1.7.0 to 1.8.3; 1.8.2 was working.

Bug tested on two computers so far -- one Server 2016 machine and one Windows 10

```
function foo
{
    ## <---- Type this
    param(
        [String]
        $bar
    )
}
```

Result:

```
function foo
{
    {
    #
    param(
    [String]
    
    )
    param(
        [String]
        $bar
    )
}
```

Expected Result:

(after uninstalling and running this)
code --install-extension PowerShell-1.8.2.vsix

```
function foo
{
    <#
    .SYNOPSIS
    Short description
    
    .DESCRIPTION
    Long description
    
    .PARAMETER bar
    Parameter description
    
    .EXAMPLE
    An example
    
    .NOTES
    General notes
    #>
    param(
        [String]
        $bar
    )
}
```

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.26.1|
| PowerShell Extension Version | 1.8.3 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.228|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.228|
|BuildVersion|10.0.17134.228|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|8.5.6|
|PowerShell|ms-vscode|1.8.3|
</details>

**Comment by rjmholt** [comment] 2018-08-31 00:15
Hi @ephenix thanks for opening an issue. This issue is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1488 and will be fixed in the next release, which will hopefully be in the next week or so.

**Closed** 2018-08-31 00:15 UTC
