### ISSUE TITLE
Temporary Console not loading on preview extension

### ISSUE THREAD

**Issue by corbob** [PowerShell/vscode-powershell#2412] opened 2020-01-12 22:05 UTC
### System Details

System Details Output
VS Code Insiders with PowerShell Preview:
```
### VSCode version: 1.42.0-insider 960cddb992cc96d47f56b633b361909f1b5b3353 x64

### VSCode extensions:
bmaupin.theme-solarized-dark-high-contrast@1.0.2
clarkio.twitch-highlighter@0.2.3
CoenraadS.bracket-pair-colorizer-2@0.0.29
DavidAnson.vscode-markdownlint@0.33.0
dbaeumer.vscode-eslint@2.0.13
dracula-theme.theme-dracula@2.19.2
dunstontc.viml@0.1.7
eamodio.gitlens@10.2.0
EditorConfig.EditorConfig@0.14.4
evrowe.cold-snack@1.6.0
GrapeCity.gc-excelviewer@2.1.32
johob.pico8-vscode@0.0.1
justusadam.language-haskell@2.7.0
kisstkondoros.vscode-codemetrics@1.23.1
michaeljolley.vscode-twitch-themer@1.4.0
ms-mssql.mssql@1.8.0
ms-vscode-remote.remote-containers@0.96.0
ms-vscode.csharp@1.21.9
ms-vscode.powershell-preview@2019.12.0
ms-vscode.vscode-typescript-tslint-plugin@1.2.3
msjsdiag.debugger-for-chrome@4.12.5
richardmarks.vscode-perfect-dark-color-theme@0.0.1
ritwickdey.LiveServer@5.6.1
rrudi.vscode-dired@0.0.4
slevesque.vscode-autohotkey@0.2.2


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.19541
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

VS Code with PowerShell extension:
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
ms-vscode.powershell@2019.12.0


### PSES version: 1.13.2.0

### PowerShell version:

Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.19541.1000                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.19541.1000                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                


```

### Issue Description

I am experiencing a problem with the PowerShell preview and the `powershell.debugging.createTemporaryIntegratedConsole` setting. When using this, the terminal opens and then immediately closes with a popup from VS Code that it has exited with code 1. I have used screen recording to capture the error: `Start-EditorServices: The process cannot access the file 'c:\Users\corbob\.vscode-insiders\extensions\ms-vscode.powershell-preview-2019.12.0\logs\...\StartEditorServices.log' because it is being used by another process.` Eventually VS Code will indicate that it didn't launch successfully.

When working with the stable extension and stable VS Code the issue does not exist.

#### Expected Behaviour

Temporary console should load and debug the script.

#### Actual Behaviour

Terminal closes.

### Attached Logs

[TemporaryDebugger.zip](https://github.com/PowerShell/vscode-powershell/files/4051579/TemporaryDebugger.zip)

**Comment by TylerLeonhardt** [comment] 2020-01-13 15:26
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2402 and fixed in the next release.

**Closed** 2020-01-14 16:00 UTC
Labels: Resolution-Duplicate
