### ISSUE TITLE
Inproper hashtable collapsing

### ISSUE THREAD

**Issue by andrzejdz** [PowerShell/vscode-powershell#1644] opened 2018-12-10 12:42 UTC
### System Details

```
### VSCode version: 1.29.1 bc24f98b5f70467bc689abf41cc5550ca637088e x64

### VSCode extensions:
donjayamanne.githistory@0.4.4
ms-mssql.mssql@1.4.0
ms-vscode.PowerShell@1.10.1
sadeghpm.sql-snippets@0.0.4


### PSES version: 1.10.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with hashtable collapsing.

#### Actual Behaviour

During hashtable collapsing, signs '@{' seams to be ignored.

![obraz](https://user-images.githubusercontent.com/37471256/49733230-3f6eb200-fc81-11e8-89e4-b4c96a0ddd6d.png)
![obraz](https://user-images.githubusercontent.com/37471256/49733256-4e556480-fc81-11e8-8844-fa56b9fb6e9f.png)
![obraz](https://user-images.githubusercontent.com/37471256/49733272-59a89000-fc81-11e8-991f-71e8bf717b09.png)

**Comment by TylerLeonhardt** [comment] 2018-12-10 15:21
This is a dupe of https://github.com/PowerShell/vscode-powershell/issues/1631 there's currently an active PR to fix it:

https://github.com/PowerShell/PowerShellEditorServices/pull/805

**Closed by TylerLeonhardt** 2018-12-10 15:21 UTC
