### ISSUE TITLE
Wrong problem reported

### ISSUE THREAD

**Issue by HansWeihe** [PowerShell/vscode-powershell#2885] opened 2020-08-12 11:01 UTC
Issue Type: <b>Bug</b>

See PowerShell code below.
VS Code will report that "The variable 'AccountType' is assigned but never used in the 4 line.

```powershell
$AccountType = 0

$ServiceAccountPath | ForEach-Object {
    $AccountType = 1
}

If ($AccountType -eq 1) {
}
```

Extension version: 2020.6.0
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment] 2020-08-12 16:51
Duplicate of https://github.com/PowerShell/PSScriptAnalyzer/issues/1163

**Closed** 2020-08-13 19:00 UTC
Labels: Resolution-Duplicate
