### ISSUE TITLE
modified autoloaded Documents\WindowsPowerShell\Modules are not reloaded when debugging

### ISSUE THREAD

**Issue by bughit** [PowerShell/vscode-powershell#653] opened 2017-04-05 20:01 UTC
this used to work in older versions because I guess they started a new ps session each time

**Comment by daviwil** [comment] 2017-04-05 21:00
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/367.  I'll be providing an option to allow to to create a new session each time you debug your script so that you have a fresh runspace to work with.

**Comment by rkeithhill** [comment] 2017-04-05 21:01
Yup, this is another downside to not using a fresh console session for each debug session. I think the plan is to either add a setting for this or (even better) make this a debug configuration property e.g. `"reuseConsoleSession": false`.  

Personally I would have the default be false.  I usually want a new console session for each debug session.  It is the **safer** way to go.  However, by having this be a debug configuration property, we can create debug config snippets that allow the console session to be shared between different debug sessions.

**Closed** 2017-04-05 21:00 UTC
Labels: Area-Debugging, Issue-Enhancement, Resolution-Duplicate
