### ISSUE TITLE
Unassigned variable rule does not consider += operator to be an assignment

### ISSUE THREAD

**Issue by triplec110h** [PowerShell/vscode-powershell#776] opened 2017-05-22 18:38 UTC
### System Details

- Operating system name and version:
- VS Code version: 1.12.2
- PowerShell extension version: 1.1.0
- Output from `$PSVersionTable`:
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      0      0

code --list-extensions --show-versions
emmanuelbeziat.vscode-great-icons@2.1.4
ms-vscode.PowerShell@1.1.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with...
PSES says variable is assigned but never used. It is used just below - see screenshot
![2017-05-22_11-36-46](https://cloud.githubusercontent.com/assets/21696527/26323258/015f9d06-3ee3-11e7-9585-73fec0ddfef6.jpg)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment] 2017-05-22 18:53
Hey @kapilmb, is there a bug tracking this already?  Seems like I've seen one but I can't find it.

**Comment by kapilmb** [comment] 2017-05-22 18:55
This is a known bug with the `PSUseDeclaredVarsMoreThanAssignments` rule. It is been tracked at PowerShell/PSScriptAnalyzer#636.

**Comment by daviwil** [comment] 2017-05-22 18:57
Thanks!  I'll keep this bug open to track the issue for the next update, but the fix will come as a part of the next PSScriptAnalyzer update.

**Comment by johlju** [comment] 2017-05-22 19:31
Maybe you are thinking of #772? I closed it since it was by design (how Oeater script works). But yesterday I saw the same problem in a normal PowerShell module when the variable was used in a script block, but assigned outside of the script block. Haven't had the time to submit an issue for that yet.

**Comment by daviwil** [comment] 2017-05-22 20:21
Yeah! That's the one :)

**Comment by kapilmb** [comment] 2017-05-22 20:40
On the surface [#772](https://github.com/PowerShell/vscode-powershell/issues/772) looks similar to this case but they are different. In [#772](https://github.com/PowerShell/vscode-powershell/issues/772), there is no way for PSSA to know if `$testParmeters` is in the same scope as that of the following `it` statements, as PSSA doesn't know what Pester does with those script blocks. But in this case PSSA clearly has more knowledge about the `SIDMappingOutput` variable.

**Comment by johlju** [comment] 2017-05-26 09:51
I got another example of the problem @triplec110h describing.

Only one of the variable `$result` is saying 'is assigned but never used'.

![image](https://cloud.githubusercontent.com/assets/7189721/26489807/23bc4e8e-4209-11e7-914d-f5b2b97e92b2.png)

![image](https://cloud.githubusercontent.com/assets/7189721/26489905/8c1fd4e6-4209-11e7-937e-1c85908af7e6.png)

**Comment by kapilmb** [comment] 2017-05-26 18:36
@johlju Thanks for the example. This is a bug that we want address as soon as possible. But due to the complexity of the *right* solution we have not been able to devote enough cycles to solving it yet. But we will definitely try to address most if not all issues related to this rule, in the next few releases.

**Comment by bergmeister** [comment] 2018-03-30 22:45
@tylerl0706 The bug got fixed in the referenced PR above this comment.

**Comment by tylerl0706** [comment] 2018-03-30 23:35
Thanks @bergmeister! 🎉

**Closed by tylerl0706** 2018-03-30 23:35 UTC
Labels: Area-Script Markers, Issue-Bug
