### ISSUE TITLE
Errors in Powershell integrated console displayed "raw", not readable

### ISSUE THREAD

**Issue by AFontenoy** [PowerShell/vscode-powershell#2640] opened 2020-04-17 15:37 UTC
On one of my computers, when I run powershell code using VS Code, errors in integrated console are hardly readable.
It doesn't seem parsed at all.
It look like this :
`PS D:\SharePoint\_Git_Repos> d:\SharePoint\_Git_Repos\Sharepoint\Scripts\test.ps1
[91mfoo: [0mD:\SharePoint\_Git_Repos\Sharepoint\Scripts\test.ps1:1:1
[96mLine |
[96m   1 | [0m [96mfoo[0m
[96m     | [91m ~~~
[91m[96m     | [91mThe term 'foo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
[96m     | [91mincluded, verify that the path is correct and try again.`

I think that happend after installing Powershell 7, but I'm not shure.
I tryed to uninstall everything but Powershell with no luck.

Any ideas ?

**Comment by TylerLeonhardt** [comment] 2020-04-17 19:03
@AFontenoy what OS and version are you on?

**Comment by TylerLeonhardt** [comment] 2020-04-17 19:41
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2637#issuecomment-615430305

**Comment by daxian-dbw** [comment] 2020-04-17 23:21
For some reason, the VSCode terminal doesn't handle the VT100 escape sequences on the version of OS you are using ...
To work around the issue, set `$ErrorView = "NormalView"` to get back the old error reporting behavior without using VT100.

**Comment by daxian-dbw** [comment] 2020-04-17 23:47
@TylerLeonhardt Just to clarify that this is not an exact duplicate. The missing of VT100 support affect the default error view in PS7. Updating on PSReadLine doesn't help with it.

**Comment by TylerLeonhardt** [comment] 2020-04-18 00:01
Good point @daxian-dbw .

@AFontenoy can you open a normal PowerShell 7 console (outside of VS Code) and see if this repros?

**Comment by AFontenoy** [comment] 2020-04-20 10:30
> 
> 
> @AFontenoy what OS and version are you on?

@TylerLeonhardt It's on Windows Server 2008 R2 Std.

**Comment by AFontenoy** [comment] 2020-04-20 10:38
@daxian-dbw I set $ErrorView = "NormalView" and voila ! It looks as before.
Thanks !

**Comment by AFontenoy** [comment] 2020-04-20 10:38
@TylerLeonhardt In normal Powershell 7 console the problem is not showing.

**Comment by TylerLeonhardt** [comment] 2020-04-20 15:26
Still should leave this open because we should fix the issue where ErrorView is `concise`.

**Closed** 2020-04-20 20:41 UTC
Labels: Area-PSReadLine, Issue-Bug, Needs: Attention :wave:
