### ISSUE TITLE
Missing prompt when launching temporary interactive debugging session

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#1026] opened 2017-09-06 09:49 UTC
### System Details

- Operating system name and version: Windows 10.0.16353.1000 x64
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.2
- Output from `$PSVersionTable`:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.16353.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16353.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Reopening issue #942 - the command prompt still does not appear when stating an interactive debugging session

**Comment by kborowinski** [comment] 2017-09-06 10:06
I know why. The PowerShellEditor services included with PowerShell extension 1.4.2 are the same as in 1.4.1, so the bug is still there.

**Comment by daviwil** [comment] 2017-09-06 14:09
Hey Kris, sorry about that.  1.4.2 was a one-off client side only update to address some issues caused by the new 64-bit build of VS Code.  The original bug that I closed is still fixed but I haven't shipped those changes yet.  Was trying to get a "quick" update out to address 64-bit issues without pulling in unfinished work for 1.5.

I'll close this since the issue is fixed but unreleased.  Sorry for the trouble and confusion!  I'll try to get the 1.5 update out in the next couple of weeks.

**Closed by daviwil** 2017-09-06 14:09 UTC

**Comment by dee3sync** [comment] 2017-09-11 19:55
Using vs code v.1.16 on x64, the powershell integrated terminal does not launch.  Nothing appears in the logs even when verbose logging is set in the settings.

To fix this issue, I had to downgrade to code v.1.15 x64 and the powershell extension worked fine.  I see this issue was closed but still seems like a huge bug, is there another open ticket relating to this?

**Comment by kborowinski** [comment] 2017-09-12 09:17
@dee3sync - I think that your case is a different issue not related to bug with opening a _temporary_  interactive debugging session so I guess you should report it.
