### ISSUE TITLE
Indent in Pester It Statement with curly braces is confused

### ISSUE THREAD

**Issue by fromthewoods** [PowerShell/vscode-powershell#2728] opened 2020-05-29 20:41 UTC
Issue Type: <b>Bug</b>

Formatter doesn't treat script blocks inside It statements correctly in Pester:
 - I'm using 2 spaces for indentation
 - Periods '.' indicate spaces
```
..It 'should not format way' {
.{ & $runnerScript @badparams} | Should -Throw "an error"
..}
```
The above block of code should look like this:
```
..It 'should not format way' {
....{ & $runnerScript @badparams } | Should -Throw "an error"
..}
```

Extension version: 2020.5.0
VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:51:32.662Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment] 2020-06-02 21:09
Thanks @fromthewoods this looks likes a duplicate of https://github.com/PowerShell/PSScriptAnalyzer/issues/1496

**Closed** 2020-06-03 22:00 UTC
Labels: Resolution-Duplicate
