### ISSUE TITLE
Where-Object alias '?' auto-formatted to Foreach-Object '%'

### ISSUE THREAD

**Issue by thkn-hofa** [PowerShell/vscode-powershell#1869] opened 2019-04-11 11:44 UTC
### System Details

System Details Output
```
### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
alefragnani.project-manager@10.5.1
christian-kohler.path-intellisense@1.4.2
eamodio.gitlens@9.6.0
gerane.Theme-Zenburn@0.0.3
ms-vscode.azure-account@0.8.1
ms-vscode.powershell@1.12.0
ms-vsts.team@1.149.2
msazurermtools.azurerm-vscode-tools@0.5.0
ryannaddy.vscode-format@0.0.6

### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with auto-formatting. Whenever I have the alias '?' used and auto-formatting kicks in, it is replaced by '%', breaking my script.

My settings.json file:
```
{
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "workbench.colorTheme": "Zenburn",
    "powershell.scriptAnalysis.enable": false,
    "workbench.startupEditor": "newUntitledFile",
    "[powershell]": {
        "editor.defaultFormatter": "ms-vscode.powershell"
    },
    "editor.defaultFormatter": "ms-vscode.powershell",
    "team.showWelcomeMessage": false,
}
```

I have tried disabling all extensions and then enabling them one by one and it only happens when ms-vscode.powershell is enabled.

#### Expected Behaviour

It should NOT be replacing ? by %

#### Actual Behaviour

It IS replacing ? by %

### Attached Logs

I created a script file 'test.ps1' with the following code
```
Get-Process | % {
    $_.name -eq "firefox"
}
```

[vs-code.powershell.log.zip](https://github.com/PowerShell/vscode-powershell/files/3068405/vs-code.powershell.log.zip)

**Comment by bergmeister** [comment] 2019-04-11 12:14
This problem will be suppressed by the next update of the PowerShell extension (`1.12.1`), which is likely to be released today or tomorrow.

**Comment by rjmholt** [comment] 2019-04-11 15:55
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/1849

**Closed by rjmholt** 2019-04-11 15:55 UTC
Labels: verify-fix
