### ISSUE TITLE
Step-Over does not returns until i press a key inside the terminal on Ubuntu

### ISSUE THREAD

**Issue by WernerMairl** [PowerShell/vscode-powershell#824] opened 2017-06-02 05:04 UTC
### System Details

- Operating system name and version:
Ubuntu 16.04 (current LTS fresh installed) + Ubuntu Desktop
- VS Code version:
Version 1.12.2
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- PowerShell extension version:
1.2.1
- Output from `$PSVersionTable`:
PSVersion                      6.0.0-beta                         
PSEdition                      Core                               
BuildVersion                   3.0.0.0                            
CLRVersion                                                        
GitCommitId                    v6.0.0-beta.1                      
OS                             Linux 4.4.0-78-generic #99-Ubun... 
Platform                       Unix                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}            
PSRemotingProtocolVersion      2.3                                
SerializationVersion           1.1.0.1                            
WSManStackVersion              3.0     

### Issue Description
using F10 (Step-Over) to execute a line, the execution seems to hang/never returns!
workaround: set cursor into the terminal and press (any) key: Step-Over comes back and the execution cursor is on the next line... work can be continued.

Observations: the bahavior is not on every line, it seems specially if Write-XXX commands are involved 

i'm new on Linux so i'm not sure that i'm doing everything in the right way....
regards
Werner

**Comment by daviwil** [comment] 2017-06-02 22:01
This is very strange, thanks for reporting it!  I'll take a look.

**Comment by WernerMairl** [comment] 2017-06-04 03:53
tell me if or  how i can help....

**Comment by chrisdias** [comment] 2017-09-27 02:31
i'm seeing this too...

**Comment by jackmusick** [comment] 2017-10-06 13:05
#987 

This is the exact same thing I'm seeing. It's been a problem for a few versions, now. The only difference is that I'm experiencing after stepping into, every other time after pressing enter. This happens on macOS but not Windows.

**Comment by marcosowns** [comment] 2017-10-06 15:27
This is the exact same issue I have been experiencing for the last 2 months on Mac OS. Any help here would be appreciated.

**Comment by WernerMairl** [comment] 2017-10-13 08:47
Again 3 months later with a fresh/new environment!

Windows 10 HyperV
Ubuntu 16.04 Desktop amd64
installed VSCode (dep download and install via UI)
installed Powershell Core (beta 8) downloading dep and install via UI)

VS-Code 1.17.1
Powershell Plugin 1.4.3
Powershell 6.0.0.beta-8
--------------
what are the next steps to solve that ?
- Any trace that i can activate ?
- Any Linux/NodeJs/Atom/VSCode//Powershell expert available that can/will do a debug/inspection session on my machine (TeamViewer,Goto,WebEx whatever)

regards
Werner

**Comment by WernerMairl** [comment] 2017-10-15 04:01
next try: fresh installed jessie...same problem/behavior

anyone can confirm that behavior in the same linux versions - or i must assume that i'm causing that by "my way" to install the components ?

- jessie/ubuntu installed - with Keyboard German/AUT
- VS-Code installed by downloading dep => open with Package Manager
- Powershell Core installed by downloading dep => open with Package Manager
- start vscode, install extension, create a few lines of script.. try
-restart vscode - retry....

Werner

**Comment by WernerMairl** [comment] 2017-10-18 13:34
@daviwil, @pcgeek86  and.  others:

This issue seems to block the debugging on Linux 
I have re-tested with two different fresh installed Linux distributions - no way

Q: anyone has a Linux installation where debugging is working ?

If yes, please provide some details about the distro.... i need a workaround - everything that helps to debug under Linux can help!

If there is no one with a working Linux => suggest to make this a high priority issue

regards
Werner

**Comment by pcgeek86** [comment] 2017-10-18 16:20
Hi @WernerMairl, I don't actively develop the code for this project, and I don't work at Microsoft either, however I do help to curate issues on this project. Unfortunately, time doesn't presently allow me to dive deep in this particular area.

For the time being, since it seems you're interested in helping to drive a root cause analysis and resolution, I would suggest that you capture the verbose logs from the VSCode PowerShell extension. You can probably get started by reviewing those logs for anomalies, such as errors or warnings. David would be much better versed in reading these logs than I would be. Check out the README.md in the root of this GitHub project for directions to enable verbose logging, and where to find the log files on your Linux filesystem.

**Comment by rkeithhill** [comment] 2017-10-26 19:06
Closing this issue in vscode-powershell as we're tracking it in the PSES repo:  https://github.com/PowerShell/PowerShellEditorServices/issues/554

**Closed by rkeithhill** 2017-10-26 19:06 UTC
Labels: Area-Debugging, Area-Integrated Console, Issue-Bug

**Comment by WernerMairl** [comment] 2017-11-10 05:32
HELP!
There is anyone that can help me to push this issue into a higher priority or do more work on the details/investigations (any help is welcome) ?

The Issue now is on the right place (EditorService: https://github.com/PowerShell/PowerShellEditorServices/issues/554)
but i need some help....


My assumption: **Powershell Plugin is NOT usable on Linux and Mac over MONTHS and nobody cares** ?

Writing this here because it seems there is more people here and the Plugin is directly impacted!

regards
Werner

**Comment by rkeithhill** [comment] 2017-11-10 08:04
Sorry, I haven't given up on this bug yet.  Just had to wrestle with some other bugs for the upcoming 1.5.1 release.  I plan to spend time on this one over the weekend to see if there's a way to get this working.  I'd like to get this in for 1.5.1. We'll see how it goes.
