### ISSUE TITLE
terminal process exited with code:1

### ISSUE THREAD

**Issue by ajpaul18** [PowerShell/vscode-powershell#1404] opened 2018-07-07 08:40 UTC
Issue Type: <b>Bug</b>

During VS Code startup,Powershell Terminal exits with the following errors
1. Terminal process exited with code :1
2. The language service could not be started

Extension version: 1.7.0
VS Code version: Code - Insiders 1.23.0-insider (a656d397e424173c86f32703e0c0293bd8084da0, 2018-05-03T00:07:45.778Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz (8 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.99GB (5.32GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|40%|

</details>

**Comment by tylerl0706** [comment] 2018-07-07 16:19
Thanks for this. I noticed your VSCode version is quite behind... Can you upgrade to the latest and try again?

**Comment by rjmholt** [comment] 2018-07-07 19:13
Hi @ajpaul18, thanks for opening an issue. This looks like a startup crash in EditorServices, but we'll need to collect more information to work out what the root problem is.

Out of curiosity, does red text flash in the console before the crash occurs? If so, the best way to work out what it says is a screen recorder (like a screen to GIF recorder). (Making that diagnosis easier is on the list of things to improve!)

**Comment by rjmholt** [comment] 2018-07-07 19:14
Oh, yeah, like @tylerl0706 says, also worth upgrading VSCode!

**Comment by ajpaul18** [comment] 2018-07-09 02:22
![image](https://user-images.githubusercontent.com/30713772/42427508-2e63fa02-8372-11e8-8b73-93b5a2897b73.png)
![image](https://user-images.githubusercontent.com/30713772/42427536-5cfa91fa-8372-11e8-857f-818ee82e2f40.png)

I have updated to july 2018. Still the console crashes. 
@rjmholt There is no red text flashing in the console before the crash, the console crashes immediately in startup.

**Comment by rkeithhill** [comment] 2018-07-09 02:38
I believe the issue is that your home dir is named `Night's Watch`.  That single quote inside a single quoted path to the script is causing a parse error.  We would either need to double-up single quotes or switch to using double quotes.

**Comment by rjmholt** [comment] 2018-07-09 02:48
@ajpaul18 No need for red text, that message is the important bit.

We should probably do some string escaping for the start script call

**Comment by ajpaul18** [comment] 2018-07-09 02:54
Yes,the user name is the problem. i tried installing in another user account , it  worked fine.

**Comment by rkeithhill** [comment] 2018-07-09 02:54
We should be able to fix this though.

**Comment by ajpaul18** [comment] 2018-07-09 03:06
Update the regex in the start script?

**Comment by rkeithhill** [comment] 2018-07-09 03:08
It fails before it even starts the start script.  This needs to be fixed in the extension where we launch powershell.exe with those args.  I'm working on a fix right now but I don't have a good test case for this.  Perhaps you could test it for me?

**Comment by ajpaul18** [comment] 2018-07-09 04:42
@rkeithhill  & @tylerl0706  .. Thanks guys, the fix works. 
That issue was so annoying. Glad you guys could help me.  Cheers mates

**Comment by rkeithhill** [comment] 2018-07-09 04:45
Let's let the PR merge automatically close this issue.  :-)

**Closed** 2018-07-10 01:42 UTC
