### ISSUE TITLE
Sometimes using "Run Selection" is delayed

### ISSUE THREAD

**Issue by mattenz** [PowerShell/vscode-powershell#2342] opened 2019-12-03 00:14 UTC
Sometimes when trying to use "Run Selection" it delays actually running the selection, sometimes for many minutes. I can't really find out what's causing it the delay has nothing appears to happen and then after a while it just kicks off running what I had selected. It doesn't seem to matter if I just have one line selected or many.

Version info:
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

VS Version: 1.40.2
PS Extension: 2019.11.0

**Comment by rjmholt** [comment] 2019-12-03 18:20
Thanks for opening an issue @mattenz. Are you using the `powershell-preview` extension, or just the `powershell` extension. If it's the latter, there are known issues with latency due to how LSP messages are handled. We've made big changes in the preview extension to address this, and they'll be in the stable extension in January.

For now in the stable extension, you could try [disabling CodeLens](https://github.com/PowerShell/vscode-powershell/issues/1174#issuecomment-379232062) or [disabling script analysis](https://github.com/PowerShell/vscode-powershell/issues/1497#issuecomment-417141584).

With those in mind, this issue may be a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1326, so let us know which extension you're running and whether the proposals above help.

**Comment by mattenz** [comment] 2019-12-03 21:20
Yes this is the non-preview version of the extension. It does seem that turning off CodeLens resolves the issue. I did do a search around before submitting this but it seems I missed that particular listing 😅

**Comment by rjmholt** [comment] 2019-12-03 21:59
> I did do a search around before submitting this but it seems I missed that particular listing

No worries, it's hard to find; took me a bit to find it again. We should add it to our known issues, although it shouldn't be an issue for much longer.

If you'd like to try out the `powershell-preview` extension, you can evaluate whether it solves this issue for you.

**Closed** 2019-12-04 22:00 UTC
Labels: Resolution-Duplicate
