### ISSUE TITLE
Visual Studio Code powershell terminal display is broken

### ISSUE THREAD

**Issue by HyundongHwang** [PowerShell/vscode-powershell#833] opened 2017-06-06 14:52 UTC
### System Details

- windows version : 
windows 10 (Microsoft Windows NT 10.0.15063.0)

- VS Code version : 
version 1.12.2
commit 19222cdc84ce72202478ba1cec5cb557b71163de
date 2017-05-10T13:20:36.315Z

- vscode-powershell version :
1.2.1

```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
PS C:\Users\hhd20> code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
PS C:\Users\hhd20> code --list-extensions --show-versions
AlanWalk.markdown-toc@1.5.4
DavidAnson.vscode-markdownlint@0.7.2
donjayamanne.python@0.6.4
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@1.2.1
yzane.markdown-pdf@0.1.7
PS C:\Users\hhd20>
```

### Issue Description

I have the following problem.

I am using VisualStudioCode with powershell, and the line breaks as shown below.

![](https://s24.postimg.org/cuh2orbtx/screenshot_2017_06_05_at_09_32_04.png)

Do you have any idea why?

VisualStudioCode Version:

![](https://s24.postimg.org/mt21b8l9h/screenshot_2017_06_05_at_09_32_47.png)

My settings file:

    {
        "editor.fontFamily": "D2Coding",
        "editor.fontSize": 14,
        "editor.wordWrap": "on",
        "editor.mouseWheelZoom": true,
        "window.reopenFolders": "none",
        "workbench.colorTheme": "Visual Studio Dark",
        "workbench.welcome.enabled": false,
        "window.zoomLevel": 0,
        "editor.cursorStyle": "line-thin",
        "terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"
    }

### Attached Logs

The logs directory did not exist.

**Comment by daviwil** [comment] 2017-06-06 14:57
Hey @HyundongHwang, have you tried the [Visual Studio Code Insiders](https://code.visualstudio.com/insiders) release?  I think I saw a fix for this issue being worked on there.  If it doesn't work with that build, let me know and I'll investigate.

**Comment by HyundongHwang** [comment] 2017-06-06 15:06
@daviwil 
I installed vscode insider as you said.
But the problem is continuing in a different way.

![](http://s16.postimg.org/xgpadyd79/screenshot_2017_06_07_at_00_04_57.png)

**Comment by daviwil** [comment] 2017-06-06 15:11
Hey @Tyriar, do you know if there's a solution to the integrated terminal rendering issue shown in the screenshot @HyundongHwang posted here? 

@HyundongHwang can you give us the output when you run this command in the terminal:

```
chcp
```

**Comment by HyundongHwang** [comment] 2017-06-06 15:18
@daviwil, @Tyriar

I do not know very well, but codepage seems to be a clue.

```powershell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\hhd20> chcp
활C:\U성 코드 페이지: 949                                                           PS C:\U
```

`활C:\U성 코드 페이지`  is `activated code page` in english.

**Comment by daviwil** [comment] 2017-06-06 15:21
Thanks!  Does the output improve after you enter this command?

```
chcp 65001
```

If so, you might consider making it part of your [PowerShell profile](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx) so that it gets loaded when you start up PowerShell.

**Comment by HyundongHwang** [comment] 2017-06-06 16:24
@daviwil, @Tyriar

Changing the codepage does not solve the problem.
First, I'll show you the problem screen shot below.
(I think the screen shot is better than the text capture because it is a UI problem)

![](http://s21.postimg.org/3n9ilrupj/screenshot_2017_06_07_at_01_21_43.png)

There is an additional problem.
In the powershell environment of vscode, profile.ps1 is not loaded.
Because of this, adding the `chcp 65001` syntax to profile.ps1 is no longer useful.
(But it loads well in the outside powershell environment.)
I am looking at profile.ps1 in the system32 directory for the sake of understanding the phenomenon. Surprisingly, the results from vscode and outside are different!
Query results in the vscode environment show that profile.ps1 does not exist. Is vscode capable of caching the environment?

- vscode's powershell

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\hhd20> $pshome
C:\Windows\System32\WindowsPowerShell\v1.0
PS C:\Users\hhd20> ls C:\Windows\System32\WindowsPowerShell\v1.0 | select fullname

FullName
--------
C:\Windows\System32\WindowsPowerShell\v1.0\en
C:\Windows\System32\WindowsPowerShell\v1.0\en-US
C:\Windows\System32\WindowsPowerShell\v1.0\Examples
C:\Windows\System32\WindowsPowerShell\v1.0\ko
C:\Windows\System32\WindowsPowerShell\v1.0\ko-KR
C:\Windows\System32\WindowsPowerShell\v1.0\Modules
C:\Windows\System32\WindowsPowerShell\v1.0\Schemas
C:\Windows\System32\WindowsPowerShell\v1.0\SessionConfig
C:\Windows\System32\WindowsPowerShell\v1.0\Certificate.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Diagnostics.Format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\DotNetTypes.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Event.Format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\FileSystem.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\getevent.types.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\HelpV3.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShellCore.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShellTrace.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe.config
C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1_old
C:\Windows\System32\WindowsPowerShell\v1.0\PSEvents.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pspluginwkr.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pwrshmsg.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pwrshsip.dll
C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\types.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\typesv3.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\WSMan.Format.ps1xml
```

- outside powershell
```
Active code page: 65001
개인 및 시스템 프로필을 로드하는 데 1809ms가 걸렸습니다.
PS C:\WINDOWS\system32> $pshome
C:\Windows\SysWOW64\WindowsPowerShell\v1.0
PS C:\WINDOWS\system32> ls C:\Windows\System32\WindowsPowerShell\v1.0 | select
 fullname

FullName
--------
C:\Windows\System32\WindowsPowerShell\v1.0\en
C:\Windows\System32\WindowsPowerShell\v1.0\en-US
C:\Windows\System32\WindowsPowerShell\v1.0\Examples
C:\Windows\System32\WindowsPowerShell\v1.0\ko
C:\Windows\System32\WindowsPowerShell\v1.0\ko-KR
C:\Windows\System32\WindowsPowerShell\v1.0\Modules
C:\Windows\System32\WindowsPowerShell\v1.0\Schemas
C:\Windows\System32\WindowsPowerShell\v1.0\SessionConfig
C:\Windows\System32\WindowsPowerShell\v1.0\Certificate.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Diagnostics.Format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\DotNetTypes.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Event.Format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\FileSystem.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\getevent.types.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\HelpV3.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Core_00000...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Diagnostic...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Host_56d66...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Management...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Security_a...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.Utility_1d...
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.WSMan.Management_7662...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShellCore.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShellTrace.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe.config
C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
C:\Windows\System32\WindowsPowerShell\v1.0\PSEvents.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pspluginwkr.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pwrshmsg.dll
C:\Windows\System32\WindowsPowerShell\v1.0\pwrshsip.dll
C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml
C:\Windows\System32\WindowsPowerShell\v1.0\types.ps1xml
```

**Comment by Tyriar** [comment] 2017-06-06 17:46
This is a duplicate of https://github.com/Microsoft/vscode/issues/19665, it's due to Windows Creators Update, make sure you update your Windows when it's available to fix it.

**Comment by HyundongHwang** [comment] 2017-06-08 06:16
@Tyriar @daviwil
Surprisingly, the terminal at android studio has the same symptoms.

![](http://s21.postimg.org/hxwwq0rp3/screenshot_2017_06_08_at_15_16_28.png)

**Comment by Tyriar** [comment] 2017-06-08 19:48
@HyundongHwang it's a problem with Windows so has a very wide impact and affects many applications. As I understand t the fix is rolling out to stable builds of Windows now.

**Comment by daviwil** [comment] 2017-06-13 14:51
Closing this since it's a Windows issue that's affecting everyone, not just VS Code.

**Closed by daviwil** 2017-06-13 14:51 UTC
