### ISSUE TITLE
Autogenerated comment help not working

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2971] opened 2020-09-24 00:08 UTC
### System Details

System Details Output
```

### VSCode version: 1.50.0-insider 9e505675670d65138405321a60b0df4ddec28799 x64

### VSCode extensions:
DavidAnson.vscode-markdownlint@0.36.3
eamodio.gitlens@10.2.2
eg2.tslint@1.0.44
jchannon.csharpextensions@1.3.1
k--kato.docomment@0.1.18
ms-azure-devops.azure-pipelines@1.174.2
ms-dotnettools.csharp@1.23.2
ms-vscode-remote.remote-containers@0.141.0
ms-vscode-remote.remote-ssh@0.55.0
ms-vscode-remote.remote-ssh-edit@0.55.0
ms-vscode-remote.remote-ssh-explorer@0.55.0
ms-vscode-remote.remote-wsl@0.44.5
ms-vscode-remote.vscode-remote-extensionpack@0.20.0
ms-vscode.azure-account@0.9.3
ms-vscode.cpptools@1.0.0
ms-vscode.powershell-preview@2020.9.0
msjsdiag.debugger-for-chrome@4.12.10
Togusa09.tmlanguage@0.9.0
twxs.cmake@0.0.17
vscodevim.vim@1.16.0


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Autogenerated comment help isn't picking up on my little double-hash.

Settings:

![image](https://user-images.githubusercontent.com/7009879/94086031-9d20af80-fdbe-11ea-87bb-6267a3b16c69.png)

#### Expected Behaviour

Comment-based help autogenerates based on the comments.

#### Actual Behaviour

![commenthelp](https://user-images.githubusercontent.com/7009879/94086077-bf1a3200-fdbe-11ea-944b-a8cb50019701.gif)

### Attached Logs

[1600905308-a6de8545-c3ac-437b-98b3-0a3d639013941600728137917.zip](https://github.com/PowerShell/vscode-powershell/files/5272631/1600905308-a6de8545-c3ac-437b-98b3-0a3d639013941600728137917.zip)

**Comment by TylerLeonhardt** [comment] 2020-09-24 03:22
Dupe of https://github.com/PowerShell/vscode-powershell/issues/769 ?

**Comment by rjmholt** [comment] 2020-09-24 04:25
Ah, interesting!

**Comment by rjmholt** [comment] 2020-09-24 04:26
I wonder if this is actually something that PSSA needs to solve

**Closed** 2020-09-25 07:00 UTC
Labels: Resolution-Duplicate
