### ISSUE TITLE
Terminal Pane Resize Is Not Working

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/vscode-powershell#1260] opened 2018-04-06 12:40 UTC
Not sure if this is correct place to report an issue.
If I try to resize  try to resize terminal pane with `Ctrl+Shift+LeftArrow` or `Ctrl+Shift+RightArrow` it does not seem to be working.
![image](https://user-images.githubusercontent.com/5260172/38421737-d3eb92e8-39b0-11e8-9860-fc614e3fbd4e.png)

### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment] 2018-04-10 17:39
Thanks for this!

This will be added with PSReadLine support. That work is being tracked here:
#535

closing this as a dupe.

**Comment by tylerl0706** [comment] 2018-04-10 17:46
Actually, this is something else.

Question, @YuriySamorodov. Did you modify this setting at all?:
`terminal.integrated.commandsToSkipShell`

**Comment by tylerl0706** [comment] 2018-04-17 21:15
Gentle ping, @YuriySamorodov 🙂

**Comment by YuriySamorodov** [comment] 2018-04-17 21:34
@tylerl0706 Not at all. Here are my settings:
![image](https://user-images.githubusercontent.com/5260172/38899370-49d2e2f2-42a0-11e8-8673-028bb60531c7.png)

**Comment by tylerl0706** [comment] 2018-04-17 22:32
Thanks for that! In the settings, what does it say for

`terminal.integrated.commandsToSkipShell`

It should be the default value but I just want to confirm.

**Comment by YuriySamorodov** [comment] 2018-04-17 22:35
@tylerl0706 
In fact there are many values under `terminal.integrated.commandsToSkipShell`
Here they are:
```
 "terminal.integrated.commandsToSkipShell": [
    "editor.action.toggleTabFocusMode",
    "workbench.action.debug.continue",
    "workbench.action.debug.pause",
    "workbench.action.debug.restart",
    "workbench.action.debug.run",
    "workbench.action.debug.start",
    "workbench.action.debug.stepInto",
    "workbench.action.debug.stepOut",
    "workbench.action.debug.stepOver",
    "workbench.action.debug.stop",
    "workbench.action.focusActiveEditorGroup",
    "workbench.action.focusFirstEditorGroup",
    "workbench.action.focusSecondEditorGroup",
    "workbench.action.focusThirdEditorGroup",
    "workbench.action.navigateDown",
    "workbench.action.navigateLeft",
    "workbench.action.navigateRight",
    "workbench.action.navigateUp",
    "workbench.action.openNextRecentlyUsedEditorInGroup",
    "workbench.action.openPreviousRecentlyUsedEditorInGroup",
    "workbench.action.quickOpen",
    "workbench.action.quickOpenPreviousEditor",
    "workbench.action.quickOpenView",
    "workbench.action.showCommands",
    "workbench.action.tasks.build",
    "workbench.action.tasks.restartTask",
    "workbench.action.tasks.runTask",
    "workbench.action.tasks.showLog",
    "workbench.action.tasks.showTasks",
    "workbench.action.tasks.terminate",
    "workbench.action.tasks.test",
    "workbench.action.terminal.clear",
    "workbench.action.terminal.copySelection",
    "workbench.action.terminal.deleteWordLeft",
    "workbench.action.terminal.deleteWordRight",
    "workbench.action.terminal.findWidget.history.showNext",
    "workbench.action.terminal.findWidget.history.showPrevious",
    "workbench.action.terminal.focus",
    "workbench.action.terminal.focusAtIndex1",
    "workbench.action.terminal.focusAtIndex2",
    "workbench.action.terminal.focusAtIndex3",
    "workbench.action.terminal.focusAtIndex4",
    "workbench.action.terminal.focusAtIndex5",
    "workbench.action.terminal.focusAtIndex6",
    "workbench.action.terminal.focusAtIndex7",
    "workbench.action.terminal.focusAtIndex8",
    "workbench.action.terminal.focusAtIndex9",
    "workbench.action.terminal.focusFindWidget",
    "workbench.action.terminal.focusNext",
    "workbench.action.terminal.focusNextPane",
    "workbench.action.terminal.focusPrevious",
    "workbench.action.terminal.focusPreviousPane",
    "workbench.action.terminal.hideFindWidget",
    "workbench.action.terminal.kill",
    "workbench.action.terminal.moveToLineEnd",
    "workbench.action.terminal.moveToLineStart",
    "workbench.action.terminal.new",
    "workbench.action.terminal.newInActiveWorkspace",
    "workbench.action.terminal.paste",
    "workbench.action.terminal.resizePaneDown",
    "workbench.action.terminal.resizePaneLeft",
    "workbench.action.terminal.resizePaneRight",
    "workbench.action.terminal.resizePaneUp",
    "workbench.action.terminal.runActiveFile",
    "workbench.action.terminal.runSelectedText",
    "workbench.action.terminal.scrollDown",
    "workbench.action.terminal.scrollDownPage",
    "workbench.action.terminal.scrollToBottom",
    "workbench.action.terminal.scrollToNextCommand",
    "workbench.action.terminal.scrollToPreviousCommand",
    "workbench.action.terminal.scrollToTop",
    "workbench.action.terminal.scrollUp",
    "workbench.action.terminal.scrollUpPage",
    "workbench.action.terminal.selectAll",
    "workbench.action.terminal.selectToNextCommand",
    "workbench.action.terminal.selectToPreviousCommand",
    "workbench.action.terminal.split",
    "workbench.action.terminal.toggleTerminal",
    "workbench.action.togglePanel"
  ]
```

**Comment by tylerl0706** [comment] 2018-04-17 22:38
Ok so the messages I expect are in there. Does this work in the default Powershell terminal within VSCode?

**Comment by YuriySamorodov** [comment] 2018-04-17 22:41
@tylerl0706 yes, SelectAll copy/paste with Ctrl-C/Ctrl-V work flawlessly.

**Comment by tylerl0706** [comment] 2018-04-18 16:11
Sorry, I was a bit vague, here's what I meant.

In the terminal you'll see this "PowerShell Integrated Console":

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/2644648/38944115-e5ebe192-42e7-11e8-9b7a-c647893fbf27.png">

Can you set that (click on it, it's a drop down) to just "powershell" and not the "PowerShell Integrated Console" and tell me if `Ctrl+Shift+LeftArrow` or `Ctrl+Shift+RightArrow` work?


Context if you're curious:

The "powershell" tab is just a regular terminal that ships with VSCode. It doesn't have the fancy features of the PowerShell Integrated Console (like the "F8 to run your selection" ability).

If these keybindings are also not working in the "powershell" terminal, then this is actually a bug in VSCode itself and not the VSCode PowerShell extension.

**Comment by YuriySamorodov** [comment] 2018-04-18 16:39
@tylerl0706 
Chose "powershell" terminal. Still does not work (I have tried both left hand side and right hand side Ctrl/Shift keys). Please note this is another VS Code instance on another PC, however behavior the same. And I have the latest stable vscode installed everywhere.
Can you please guide me to the correct location to report this bug?

**Comment by tylerl0706** [comment] 2018-04-18 18:38
@YuriySamorodov thanks for the info! I can say with confidence that this is a VSCode issue and not an issue with the PowerShell extension.

You're going to want to open an issue over here:
https://github.com/microsoft/vscode


Make sure that you link this issue to the new one you create so they can see our discussion! Let me know when you've opened that so we can close this one here in the PowerShell extension repo.

**Comment by tylerl0706** [comment] 2018-07-31 21:26
Closing this since it was root caused to VSCode

**Closed by tylerl0706** 2018-07-31 21:26 UTC
Labels: Needs-Repro-Info
