### ISSUE TITLE
Intellisense in Terminal while in debug state not working

### ISSUE THREAD

**Issue by jasonshave** [PowerShell/vscode-powershell#815] opened 2017-06-01 14:04 UTC
Coming from the world of PowerShell ISE, we could use the command history (up arrow) to cycle through previously run commands and cobble together new code in the Terminal window while debugging. VSCode doesn't appear to have this capability yet it works when you stop the debugger.

Along the same lines, Intellisense would be great as well in the Terminal window while debugging.

**Comment by daviwil** [comment] 2017-06-01 14:07
You don't get IntelliSense in the PowerShell Integrated Console while debugging?  That should be working.  History is definitely busted right now, though, #550 is tracking that issue.

If IntelliSense truly isn't working I'd recommend capturing debug logs and either post them here or send them to me, `daviwil` at `microsoft.com`:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by jasonshave** [comment] 2017-06-01 16:26
That's correct. If I try CTRL+<spacebar> I don't get IntelliSense while in debug mode (in the terminal tab). Should I be trying something else? Also, I'll send logs but if you could direct me how to capture them I'd appreciate it. If you want to hit me directly, try jassha at Microsoft.com on SFB.

**Comment by daviwil** [comment] 2017-06-02 22:02
Hey Jason, you can follow the link I included in my previous comment, that tells you how to capture the logs.

**Comment by jasonshave** [comment] 2017-06-04 16:06
Sorry! Missed that. Logs sent :)

**Comment by tylerl0706** [comment] 2017-12-06 17:48
Hey there, just doing some triaging. So the original issue in this issue is a dupe of #550 but I want to keep this open to track the IntelliSense issue.

**Comment by JVimes** [comment] 2019-11-15 16:41
When stopped on a breakpoint, nothing works except for typing commands. There's no undo/redo, text selection using the keyboard, or F8 and Ctrl+R to access history.

**Comment by TylerLeonhardt** [comment] 2019-11-15 21:21
Have you tried the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? Can you install that and give it a try?

**Comment by JVimes** [comment] 2019-11-16 17:22
After 20 minutes of effort, I can't get the preview extension to hit a breakpoint in my module. The non-preview extension also isn't working today, and I swear I'm doing the same steps as yesterday.

**Comment by TylerLeonhardt** [comment] 2019-11-16 19:31
Ok let's not derail this issue as it's about intellisense. Please open a new issue and [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) so we can get a better idea for what's going on. Also provide the script if you can and how you're launching the debugger.

**Comment by TylerLeonhardt** [comment] 2020-03-11 06:22
This should all be supported in the latest version of the PowerShell extension so I'm going to close this. Let us know if we missed something!

**Closed by TylerLeonhardt** 2020-03-11 06:22 UTC
Labels: Area-Debugging, Area-IntelliSense, Issue-Bug
