### ISSUE TITLE
EditorServices.log logfile takes extremely large amount of disk size [macOS]

### ISSUE THREAD

**Issue by peterblazejewicz** [PowerShell/vscode-powershell#679] opened 2017-04-13 19:13 UTC
- Operating system name and version:
macOS 10.12.4 (16E195)
- VS Code version:
Version 1.12.0-insider (1.12.0-insider) a5e9d3b5e8e7e9a89dd6624a70aab031f189a6fa
- PowerShell extension version:
0.11.0
- Output from `$PSVersionTable`:
```
$PSVersionTable                                                                                                         

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      6.0.0-alpha                                                                                                                   
PSEdition                      Core                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   3.0.0.0                                                                                                                       
GitCommitId                    v6.0.0-alpha.10                                                                                                               
CLRVersion                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1 
```

### Issue Description

I am experiencing a problem with extremely huge output size of extension log.
Path: `/Users/piotrblazejewicz/.vscode-insiders/extensions/ms-vscode.powershell-0.11.0/logs/1492023659-6b4269a7-46c9-4e07-8b88-f619373de0aa1492023335791`
Size: `19 202 038 517 bytes (19,2 GB on disk)`

I've reviewed released for 0.12.* and didn't spot info about possible fix.

Thanks!

**Comment by daviwil** [comment] 2017-04-13 19:17
Wow!  How long has this session been running?  Do you have Verbose logging turned on?

**Comment by peterblazejewicz** [comment] 2017-04-13 19:19
I don't know. I'm using PowerShell on OS X from time-to-time (rather sporadic use to be honest). I do use VSCode all the time on OS X though. Won't be able to provide more info from this log as installing new version of extension clears that directory (I've just learned this after upgrading now to 0.12.*)

**Comment by PrzemyslawKlys** [comment] 2020-04-15 06:21
@peterblazejewicz  is this still the case with newest version? Can you check and close or update?

**Comment by peterblazejewicz** [comment] 2020-04-15 06:34
@PrzemyslawKlys let me check this out (still using VSCode Insider bits and regular one on Mac OS)

**Comment by yurim108** [comment] 2021-09-24 08:28
Same problem on Windows 10, VS Code Version 1.60.2.
EditorServices.log size is 30 Gb and still growing...
Is there any setting to limit the size? Can file be just deleted?

**Comment by andschwa** [comment] 2021-09-28 19:29
@yurim108 that is not the PowerShell extension. You're looking at logs for the extension [AL Language](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al) (note the extension path, you're in the folder `ms-dynamics-smb.al-<version>`).

Since this bug as been waiting on reproduction for a year, and your issue is with another extension, I'm marking as resolved. Thanks!

**Closed** 2021-09-28 22:00 UTC
Labels: Issue-Bug, Area-Logging, Resolution-Fixed

**Comment by Grueslayer** [comment] 2021-11-04 13:07
My log file is about 13 GB big `02.11.2021  12:26    13.606.411.956 EditorServices.log` and still growing, first entry is from my first usage on `08/12/2020 11:45:05 [/1] Editor Services Host v5.0.4.50830 starting (pid 27964)`.

There should be a solution with max filesize or entry date to keep the logs in a normal range (I will not look into the log for a problem 1,5 year ago)

**Comment by Grueslayer** [comment] 2021-11-05 07:58
Sorry.... I think this isn't caused by this extension, too. I'll have a deeper look into it.

**Comment by andschwa** [comment] 2021-11-05 16:24
I was going to say, I think it's coincidental that the file name is `EditorServices.log` (which we do use), since the header in the file is not something I believe we write:

> Editor Services Host v5.0.4.50830 starting

Our editor services are at version 3.0 🙃

**Comment by PrzemyslawKlys** [comment] 2021-11-05 16:37
Also your extension when it gets updated deletes all logs. So the log can only get that big if no updates were done for either preview or production version for a very long time which is not possible with your current release times.
