### ISSUE TITLE
VSCODE v1.59.1 - POWERSHELL - F5 and F8 not working as intented

### ISSUE THREAD

**Issue by akselbork** [PowerShell/vscode-powershell#3515] opened 2021-08-20 09:22 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When choosing a line in a PowerShell script and pressing F8, nothing happens.
Then by moving the focus to the terminal and pressing "Enter" the line will be executed, at becomes visible in the terminal.

This is the same for F5

So every execution has to be made i "double steps"

No problem if the command is entered directly into the terminal

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.59.1
3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
ironmansoftware.powershell-universal@2.1.1
justin-grote.powershell-extension-pack@0.0.5        
ms-vscode.powershell@2021.8.0
ms-vscode.powershell-preview@2021.8.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Open PS1 file 
2. Select line
3. Press F8
4

**Comment by PrzemyslawKlys** [comment] 2021-08-20 10:22
It doesn't work for me either. The New PowerShell preview is broken. When presssing F5 in 5.1 or in PS 7 the PowerShell icon in the bottom is progressing but nothing happens.

**Comment by fbehrens** [comment] 2021-08-20 19:45
I have the same when running cmmand `Powershell: Run Selvetion` after the update of `Powershell Preview` to `2021.8.1`.

After rollback to `2021.8.0` it works again.

```
vscode: 1.59.1
powershell: 7.1.4
os: windows 10 Version 1909
```

**Comment by andschwa** [comment] 2021-08-20 23:01
Duplicate of #3513, will be fixed Monday with a new update to the preview. Sorry about that! Wondering how to add a regression test around this, and super open to ideas on that topic.

**Closed** 2021-08-22 01:00 UTC
Labels: Issue-Bug, Resolution-Duplicate
