### ISSUE TITLE
Language service crashes on dot-sourced path in script

### ISSUE THREAD

**Issue by wellsluo** [PowerShell/vscode-powershell#224] opened 2016-07-13 07:30 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10.1511
- PowerShell Extension version: 0.6.1

Reproduced on at least 2 Windows 10 machines. 

Symptom
======
1. "Find All References" show empty window or "No result" window. So as "Go to definition". 
2. Auto complete doesn't work to show related PowerShell cmdlet.
3. Ctrl+ mouse hover on function name, doesn't show underline and can't click to jump function declaration. 

Steps to Reproduce:

1.  Open VSCode
2.  Open PS1 script. 

EditorServices.log file shows unhandled exception:
=======================================================
7/13/2016 14:51:17 [NORMAL] - Method "Main" at line 145 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host v0.6.1.356 starting (pid 13060)...
    
      Host application details:
    
        Name: Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version: 0.6.1

7/13/2016 14:51:17 [NORMAL] - Method "Initialize" at line 186 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    PowerShell runtime version: 5.0.10586.122

7/13/2016 14:51:18 [NORMAL] - Method "Main" at line 165 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host started!

7/13/2016 14:51:22 [ERROR] - Method "CurrentDomain_UnhandledException" at line 178 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    FATAL UNHANDLED EXCEPTION:
    
    System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyFindReferences(ScriptFile scriptFile, Dictionary`2 referencedScriptFiles)
       at Microsoft.PowerShell.EditorServices.Workspace.ExpandScriptReferences(ScriptFile scriptFile)
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetDefinitionOfSymbol>d__16.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleDefinitionRequest>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit()
       at Microsoft.PowerShell.EditorServices.Host.Program.Main(String[] args)
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyFindReferences(ScriptFile scriptFile, Dictionary`2 referencedScriptFiles)
       at Microsoft.PowerShell.EditorServices.Workspace.ExpandScriptReferences(ScriptFile scriptFile)
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetDefinitionOfSymbol>d__16.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleDefinitionRequest>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyFindReferences(ScriptFile scriptFile, Dictionary`2 referencedScriptFiles)
       at Microsoft.PowerShell.EditorServices.Workspace.ExpandScriptReferences(ScriptFile scriptFile)
       at Microsoft.PowerShell.EditorServices.LanguageService.<GetDefinitionOfSymbol>d__16.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<HandleDefinitionRequest>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
    <---
    

========================================================

**Comment by wellsluo** [comment] 2016-07-13 09:27
Performed further test, found the crash was caused the dot source operator.   Refer following sample code, remove the second line, there will be no problem. 

Sample file
========
```
Get-ChildItem
. ".\test.ps1"

Function test1
{
    write-host "test1"

}

Function test2
{
    write-host "test2"
}



test1
test2

```

**Comment by daviwil** [comment] 2016-07-13 14:49
Hi @wellsluo, thanks for the report!  I'll see if I can figure out what the issue is there.

**Comment by daviwil** [comment] 2016-09-07 17:17
Hey @wellsluo, I think I might have fixed this issue in release 0.7.2, can you try it out and let me know if your problem is resolved?  See this issue for more details: https://github.com/PowerShell/vscode-powershell/issues/274

**Comment by itzik-h** [comment] 2016-09-08 08:51
Tested with 0.7.2 - The language service is not crashing.
It reports this error in the log:
`[ERROR] - Method "ResolveRelativeScriptPath" at line 332 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs`
Yet there is some other problem: The path the log stat as problematic is not a path at all - it is a function!.
I have created a simple test case:
1. Put the two ps files from the zip in a folder and open the folder in vscode.
2. In test_file_a.ps1 click on the function name `test` and press  `shift+F12` to trigger the bug.
3. Inspect the log. A log sample is attached.

[bug_test.zip](https://github.com/PowerShell/vscode-powershell/files/461192/bug_test.zip)
[EditorServices.log.txt](https://github.com/PowerShell/vscode-powershell/files/461195/EditorServices.log.txt)

**Comment by daviwil** [comment] 2016-09-08 13:53
Hmmm, weird!  Thanks for sending the logs and test files, I'll take a look at this today.

**Comment by daviwil** [comment] 2016-09-08 22:30
Hey @itzik-h, can you tell me what this code is supposed to do:

```powershell
        Add-Member -InputObject $new_test_obj -MemberType ScriptMethod -Name "Init" -Value {
        .{
        param (	
            [Parameter(Mandatory=$true)]
            [ValidateNotNullOrEmpty()]
	        [string]
            $a
        ,
        	
            [Parameter(Mandatory=$true)]
            [ValidateNotNullOrEmpty()]
	        [string]
            $b
        ) 
        Process
        {
            $this.a = a
            $this.b = b
        }
        }@args
        }
```

The dots `.` that you're using before the opening curly brackets `{` seem to be causing the language service to think those are dot-sourcing references.  I'm going to fix that issue on my side, but I'm genuinely curious about what that this code is supposed to accomplish!

**Comment by itzik-h** [comment] 2016-09-09 06:16
This code will add a function to an object (a sort of a class workaround for PowerShell ver < 5).
If you omit the "." -> when you call `init` it will return the function body itself instead of running it.
(This is obviously just a sample function and it is not doing any thing special, I just noticed the bug with functions similar to this one).

**Comment by daviwil** [comment] 2016-09-09 13:48
Cool, thanks for the explanation!  I've got the issue fixed now, it will go out with the next update (0.7.3) in a few days.

**Comment by daviwil** [comment] 2016-09-12 22:47
Since I believe @wellsluo's issue is fixed, let's track your issue over at #171 now @itzik-h.  I'll close this issue for now, @wellsluo, let me know if the issue is still present for you in 0.7.2!

**Closed by daviwil** 2016-09-12 22:47 UTC
Labels: bug, verify-fix

**Comment by wellsluo** [comment] 2016-10-13 06:12
Thanks David!  I tested on 0.7.2, bug is fixed.

**Comment by daviwil** [comment] 2016-10-13 21:01
Awesome, thanks for confirming!
