### ISSUE TITLE
Error on Debug Adapter: Error: connect ETIMEDOUT \\.\pipe\... after second execution in PowerShell Integrated Terminal

### ISSUE THREAD

**Issue by hugh-martin** [PowerShell/vscode-powershell#3505] opened 2021-08-10 19:35 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Any second execution of PowerShell code results in an error in the PowerShell Extension logs and a failure to execute any code in the PowerShell Integrated Terminal until it is killed and restarted.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.59.0
379476f0e13988d90fab105c5c19e7abc8b1dea8
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
ms-vscode.powershell@2021.8.0
```

### Steps to Reproduce

Disable all extensions except the PowerShell extension.
Create new file (no need to save it, but saving it will result in the same issue).
Wait for the PowerShell Integrated Terminal to start.
Add a small bit of PowerShell code; Get-Disk in this case, which was chosen arbitrarily.
Run the script (with or without debugging).
Wait for the script to execute successfully.
Run the script (with or without debugging) a second time.
Wait for the script to time out (~30 seconds).
Check the PowerShell Extension logs for something similar to the following:
Error on Debug Adapter: Error: connect ETIMEDOUT \\.\pipe\PSES_x0wt2evy.fli

### Visuals

[Code screenshots.zip](https://github.com/PowerShell/vscode-powershell/files/6964090/Code.screenshots.zip)

### Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/6964091/logs.zip)

**Comment by hugh-martin** [comment] 2021-08-10 19:51
I disabled the PowerShell extension, installed the PowerShell Preview extension (ms-vscode.powershell-preview@2021.8.0) and got the same results.

**Comment by andschwa** [comment] 2021-08-10 21:31
@hugh-martin and @youngr137, could this be a duplicate of #2821?

**Comment by hugh-martin** [comment] 2021-08-11 12:36
@andschwa, I do not believe so.  I don't see any errors or timeouts in vscode-powershell.log from #2821.  Also, in my case, I avoided using debug at all, which seems to be the focus of that issue.

**Comment by hugh-martin** [comment] 2021-08-11 15:46
FYI, I cannot duplicate the issue with PowerShell extension v2021.6.2.  Switching back to v2021.8.0 of the PowerShell extension brings the issue back.

**Comment by andschwa** [comment] 2021-08-11 15:58
Oh that's interesting! Ok, can you let me know if it reproduces with [v2021.7.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2021.7.0-preview)? This would help me narrow it down!

**Comment by andschwa** [comment] 2021-08-17 20:18
So that narrows down the bug to be either a change between PowerShell Editor Services [v2.4.6 and v2.4.7](https://github.com/PowerShell/PowerShellEditorServices/compare/v2.4.6...v2.4.7), as there isn't a substantial code change to the extension that I can see between [v2021.7.0-preview and v2021.8.0](https://github.com/PowerShell/vscode-powershell/compare/v2021.7.0-preview...v2021.8.0) (except perhaps package updates?).

**Comment by andschwa** [comment] 2021-08-17 20:21
@rjmholt, @dkattan, any ideas? I'll try to repro locally.

**Comment by hugh-martin** [comment] 2021-08-17 21:26
For whatever it's worth, I have been working with PowerShell extension v2021.6.2 for several days now and the problem has not re-occurred.  Thanks again for the efforts.

**Comment by andschwa** [comment] 2021-08-19 20:12
Just FYI this is on my docket to investigate as the next big problem happening.

**Comment by andschwa** [comment] 2021-08-23 21:06
I've been attempting to look at this and have not been able to reproduce it yet. [PowerShell Preview 2021.8.2](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell-preview) is out now, would you test and see if this still reproduces?

**Comment by hugh-martin** [comment] 2021-08-23 21:36
I am happy to report that it is not happening with PowerShell Preview 2021.8.2 and PowerShell 7.1.3.

**Comment by andschwa** [comment] 2021-08-23 22:18
Woo-hoo!

**Closed** 2021-08-24 01:00 UTC
Labels: Issue-Bug, Area-Debugging, Resolution-Fixed
