### ISSUE TITLE
Autoformat setting for all lower case or all upper case keywords

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#547] opened 2017-03-15 14:24 UTC
### Feature Request

Loving the new format settings for 0.10.0 release. Would it be possible to add control over case of [keywords](https://msdn.microsoft.com/en-us/powershell/reference/4.0/microsoft.powershell.core/about/about_language_keywords)? 

### Examples

I add to my settings something like:
```
"powershell.codeFormatting.allLowercaseKeywords": true,
```
That setting would turn this:

```powershell
Begin {
    Write-Verbose "I'm starting now"
}
PROCESS {
    IF ($notify -eq $true) {
        Write-Verbose "Do something"
    }
    Else {
        write-verbose "Do something"
    }
}
end {
    Write-Verbose "Do something else"
}
```

into this:
```powershell
begin {
    Write-Verbose "I'm starting now"
}
process {
    if ($notify -eq $true) {
        Write-Verbose "Do something"
    }
    else {
        Write-Verbose "Do something"
    }
}
end {
    Write-Verbose "Do something else"
}
```

**Comment by bgelens** [comment] 2017-03-15 14:28
I'm with you with this one :) I hate it when keywords scream at me

**Comment by wsmelton** [comment] 2017-03-15 14:30
It would be nice if we could even add it for operators as well...annoys me to no end to see `if ($var -EQ 1)`.

**Comment by daviwil** [comment] 2017-03-15 23:34
Good idea!

**Comment by ChrisWarwick** [comment] 2017-06-11 12:11
Please (please!) add Pascal case as an option for keywords too (Foreach, If, etc etc). I realise I'm not in the majority here but it's a style I've used forever and I guess it would be easy to add to the above enhancement (and I'm sure there are other weirdos out there who would like this... :-))

Thanks!

**Comment by TheIncorrigible1** [comment] 2018-05-11 23:48
@ChrisWarwick I would vote for a true PascalCase (ForEach, ElseIf).  I think that should be the three settings (PascalCase, lowercase, uppercase).  I was pretty disappointed to run across this today while exploring automatic code formatting and keywords are forgotten.

**Comment by tylerl0706** [comment] 2018-05-14 19:33
@bergmeister is this something we could handle in PSSA?

**Comment by bergmeister** [comment] 2018-05-14 20:10
@tylerl0706 Yes, it would be a style rule, not a code analysis rule. There is already a similar issue here that falls into this category: https://github.com/PowerShell/PSScriptAnalyzer/issues/767
It is up for grabs :-)
P.S. It seems the VSCode repo has another similar issue to this one as well: https://github.com/PowerShell/vscode-powershell/issues/960

**Comment by tylerl0706** [comment] 2018-05-14 21:05
Thanks, @bergmeister! That's what I thought. I'm going to close this issue in favor of the one in PSSA since this would be addressed there :)

**Closed by tylerl0706** 2018-05-14 21:05 UTC
Labels: Issue-Enhancement

**Comment by wsmelton** [comment] 2018-05-14 21:10
So will PSSA implement the ability to apply the rule when we format a file?

**Comment by bergmeister** [comment] 2018-05-14 21:19
@wsmelton The issue is marked as up for grabs, so anyone can feel free to do it. From my side, I think there are bigger fishes to fry, so from my side it is not a priority. I am only the community maintainer of it and I cannot speak for the MSFT side.

**Comment by tylerl0706** [comment] 2018-05-14 21:33
I'm not really spending a lot of time in PSSA - that's more on @JamesWTruher and @kalgiz (when she gets back from vacation). 

Generally speaking, if there are a lot of thumbs up (👍), we'll likely prioritize it higher. 

This might go without saying... if you want something really badly, and we don't have the engineering power to do it, *pull requests are always welcome* 😄 and we have smart folks like @bergmeister and the other two mentioned to help guide folks through the process!

**Comment by wsmelton** [comment] 2018-05-14 22:45
I'm more concerned with implementation of it. If I open a 350 line script that someone used say PowerShell Studio to develop it. PS Studio can default to doing something like `ForEach` which is not my preference. If the feature is implemented using PSSA that means all it will do is flag the `ForEach` as a problem...which I don't use PSSA other than in VS Code and I don't recall any shortcut for "go fix all". On the other side if this is implemented in VS Code + PS Extension, I have the ability to `format document` and it all is taken care of...

**Comment by rkeithhill** [comment] 2018-05-14 23:04
@wsmelton The PowerShell extension uses PSSA for all its automatic formatting.  So the feature/fix needs to be added to PSSA first, then the PowerShell extension for VSCode will pick it up via a PSSA update.

**Comment by bergmeister** [comment] 2018-05-15 04:47
I should add that PSSA is consumed indirectly by PowerShellEditorServices, therefore any Editor has theoretically the capability to make use of it. Apart from that the cmdlets by PSSA can be used manually to auto-format one or multiple scripts in one go.
