### ISSUE TITLE
Ignore problems on commented out line

### ISSUE THREAD

**Issue by roblourens** [PowerShell/vscode-powershell#1253] opened 2018-03-31 20:43 UTC
_From @ixixit on March 2, 2018 23:5_

### Issue Type
Bug

### Description

Hello!  In this powershell script, I've created an if block which is commented out, and has no statement block following it.  It is correctly detected as a comment line in the syntax, but the problem section reports it as an active problem, though it is not active in the script due to the # comment block.

```
# if ((Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse -Exclude '*.zip' | Measure-Object | ForEach-Object {$_.Count}) -ne 0)
if ((Test-Path -Path "$LogDir\$TempDir" -PathType Container) -And ((Get-ChildItem "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count}) -gt 1))
{
    $FileCount =  (Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count})
}
```
Problems: [Powershell] Missing statement block after if (condition).

Secondly, if I create a second if line afterwards, and reverse the comment block, problems says there are no problems!

```
if ((Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse -Exclude '*.zip' | Measure-Object | ForEach-Object {$_.Count}) -ne 0)
# if ((Test-Path -Path "$LogDir\$TempDir" -PathType Container) -And ((Get-ChildItem "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count}) -gt 1))
{
    $FileCount =  (Get-ChildItem -Path "$LogDir\$TempDir" -File -Recurse | Measure-Object | ForEach-Object{$_.Count})
}
```
Problems: No problems have been detected in the workspace so far.

If I revert to the original condition, and remove the active if line, problems reports an unexpected else, which is correct, but not illustrated in this example..

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.79GB (10.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.6.0

</details>
Reproduces without extensions

_Copied from original issue: Microsoft/vscode#44954_

**Comment by roblourens** [comment] 2018-03-31 20:43
_From @ixixit on March 5, 2018 15:54_

Sorry about the font sizes.  Not sure why that particular IF line went crazy.

**Comment by ixixit** [comment] 2018-03-31 20:45
No worries, I'm glad we can try to fix it!

**Comment by tylerl0706** [comment] 2018-04-01 07:54
Hi @ixixit, thanks for the report and thanks to @roblourens for bringing it over here!

Can you supply us with the logs when you see this issue? The info on how to do that is here:
https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

It's super important to set the logs to Verbose. If you can set the logs to Diagnostic, that'd be even better if it's ok on your performance!

**Comment by tylerl0706** [comment] 2018-04-17 21:14
I can't seem to repro this but it looks related to https://github.com/PowerShell/vscode-powershell/issues/1232

I'm going to close this as a dupe of that. If you see otherwise, feel free to attach the logs here and I can reopen!

(or attach logs in the other issue)

**Closed by tylerl0706** 2018-04-17 21:14 UTC
