### ISSUE TITLE
Different Handling of $PSScriptRoot for Debugging

### ISSUE THREAD

**Issue by MrFly72** [PowerShell/vscode-powershell#4085] opened 2022-07-19 13:31 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Today $PSScriptRoot is only a Non-Null-Value when the script is started by "F5".
If you use only parts or even one line, $PSScriptRoot is $Null.

### Proposed Design

It would be cool, if the VSCode Powershell Extension would handle the $PSScriptRoot Variable a little different:
1. When running normally, it is working good (F5-Mode) --> $PSScriptRoot is filled with the correct path
2. If the user runs part of a code, there has to be a decision made:
- If the part of the code comes from a editor-window which has already been saved, --> Take the path of the file (like F5 would do) into $PSScriptRoot
- If the editor-window has not been saved --> Take the current path inside of $PSScriptRoot.

This would I believe help tons of developers while debugging code, as I know a lot of them copying lines of code, replace $PSScriptRoot temporarily (and afterwards forget about that) etc.

**Comment by SeeminglyScience** [comment] 2022-07-19 14:50
Duplicate of #633

Thanks for the suggestion! Tracking in the marked issue above

**Comment by SeeminglyScience** [comment] 2022-07-19 14:51
Thanks for the suggestion! Tracking in the marked issue above

**Closed** 2022-07-20 16:01 UTC
Labels: Issue-Enhancement, Resolution-Duplicate
