### ISSUE TITLE
Could not start languaje service. Source: Powershell (Extension)

### ISSUE THREAD

**Issue by dgomez-ancert** [PowerShell/vscode-powershell#3238] opened 2021-03-11 16:58 UTC
Issue Type: <b>Bug</b>

The powershell extension don't work correctly (formatter, highlighting, etc.).

11/3/2021 17:54:10 [NORMAL] - Visual Studio Code v1.54.1 64-bit
11/3/2021 17:54:10 [NORMAL] - PowerShell Extension v2021.2.2
11/3/2021 17:54:10 [NORMAL] - Operating System: Windows 64-bit
11/3/2021 17:54:10 [NORMAL] - Language server starting --
11/3/2021 17:54:10 [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
11/3/2021 17:54:10 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615481650-f904606f-61e9-4522-b52e-3bb5c0d2739f1615481649212\EditorServices.log' -SessionDetailsPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-3904-731591' -FeatureFlags @() 
11/3/2021 17:54:10 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615481650-f904606f-61e9-4522-b52e-3bb5c0d2739f1615481649212\EditorServices.log' -SessionDetailsPath 'c:\Users\dgomez\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-3904-731591' -FeatureFlags @() 
11/3/2021 17:54:10 [NORMAL] - powershell.exe started.
11/3/2021 17:54:10 [NORMAL] - Waiting for session file
11/3/2021 17:54:12 [NORMAL] - Session file found
11/3/2021 17:54:12 [NORMAL] - Registering terminal close callback
11/3/2021 17:54:12 [NORMAL] - Registering terminal PID log callback
11/3/2021 17:54:12 [NORMAL] - powershell.exe PID: 3096
11/3/2021 17:54:12 [NORMAL] - Language server started.
11/3/2021 17:54:12 [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_3me215xr.i1x","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_ejur3oeb.aq2"}
11/3/2021 17:54:12 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_3me215xr.i1x...
11/3/2021 17:54:12 [NORMAL] - Language service connected.
11/3/2021 17:54:12 [ERROR] - Could not start language service: 
11/3/2021 17:54:12 [ERROR] - Error: Connection to server got closed. Server will not be restarted.

Extension version: 2021.2.2
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.48GB free)|
|Process Argv|--crash-reporter-id e1f1ed49-b62a-4942-ad48-957f72504923|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by andschwa** [comment] 2021-03-11 18:17
Duplicate of #3227. New VS Code version 1.54.2 will be released today, resolving this.

**Closed** 2021-03-12 19:00 UTC
Labels: Needs: Triage :mag:, Resolution-Duplicate
