### ISSUE TITLE
Debug adapter process terminated unexpectedly and PowerShell session has terminated due to an error at the same time and all time

### ISSUE THREAD

**Issue by Cognic** [PowerShell/vscode-powershell#1078] opened 2017-10-30 15:48 UTC
System Details

- Operating system name and version: Windows Server 2016, Version 1607
- VS Code version: 1.17.2
- PowerShell extension version: 1.5.0
- Output from `$PSVersionTable`:
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.1532                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.1532                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1 

```


code -v : 
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5

$pseditor.EditorServicesVersion:
Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      0      0

code --list-extensions --show-versions:
azemoh.one-monokai@0.3.4
donjayamanne.python@0.7.0
joshpeng.sublime-babel-vscode@0.2.9
joshpeng.theme-onedark-sublime@0.3.6
jprestidge.theme-material-theme@1.0.1
magicstack.MagicPython@1.0.12
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.5.0
robertohuertasm.vscode-icons@7.17.0
rokoroku.vscode-theme-darcula@1.0.13
tht13.python@0.2.3

$PSVersionTable:
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.1532                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.1532                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1 

```

Issue Description:

"Debug adapter process has terminated unexpectedly"
"The PowerShell session has terminated due to an error, would you like to restart"

These two errors keeps popping up every time I run something from VScode, not even while debugging. 
VSCode has been my primary editor for long but these days its very annoying to keep switching between VSCode for writing and ISE for debugging and running. Please fix.

Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1427819/logs.zip)

**Comment by ZHumphries** [comment] 2017-11-02 11:35
I get exactly the same error when attempting to attach to a powershell process to debug.

**Comment by TheIncorrigible1** [comment] 2017-11-02 16:01
Same VSCode and extension versions.  PowerShell debugging does not work.  No output to the debug console, session crashes constantly.  Completely useless for debugging *still*.  It's a bit frustrating to have to go back to the ISE to properly test anything.

**Comment by rkeithhill** [comment] 2017-11-05 19:32
I see what the problem is here.  I believe we can get this fixed for the next drop.

**Comment by rkeithhill** [comment] 2017-11-06 01:39
I was puzzled how to repro this.  Finally figured it out.  If you diff a PS1 file and then in the diff viewer, set a breakpoint in the right pane, a breakpoint of the form `Untitled-X` will show up in the breakpoints view.  We can't set a line breakpoint unless we have a full file path.  So long story short, we'll fix the crash but breakpoints set in the right pane of the Git diff viewer will not work.

**Comment by Cognic** [comment] 2017-11-07 03:25
Thanks Keith for picking it up. I have closed the untitled-X file and opened a saved script and tried to debug and its still the same error. Thought of letting you know. Thanks.

**Comment by rkeithhill** [comment] 2017-11-07 03:27
Can you attach the zipped log file for such a session?

**Comment by MRWeather** [comment] 2017-11-07 17:33
If you set a breakpoint in a non-saved file, then close that file without saving, the breakpoint remains in the breakpoint list and the debugger crashes. Even disabling the Untitled-x breakpoint causes the debugger to crash. If you remove all breakpoints and add a breakpoint to a saved file, the debugger works as expected. 
Seems like it should either prevent breakpoints on unsaved files (since they don't seem to work anyway) or remove any breakpoints on unsaved files when the file is closed and not saved. $.02

**Comment by rkeithhill** [comment] 2017-11-07 18:47
@MRWeather  I believe I have that particular crash fixed.  I think @Cognic is running into a different bug now but hard to tell unless I can get the log files.

**Comment by MRWeather** [comment] 2017-11-07 19:16
OK. It sounded the same to me - for me it wasn't the open unsaved file, but a breakpoint for any unsaved file that was causing the problem. If @Cognic had a breakpoint for an unsaved file, closing the file and opening a different one without removing the bad breakpoint would not do anything. 

Either way, thanks for working on this - I hope you get lots of appreciation :)

**Comment by rkeithhill** [comment] 2017-11-07 20:28
No worries.  Glad to have to the extra info!

**Comment by Cognic** [comment] 2017-11-08 09:16
@rkeithhill Attached the logs. Thanks.

[logs_v1.zip](https://github.com/PowerShell/vscode-powershell/files/1453232/logs_v1.zip)

**Comment by ZHumphries** [comment] 2017-11-08 11:51
for me its reproducible by simply opening a clean install of VSCode and attaching the debugger to an external powershell process. (Without opening any files/directories first)

**Comment by rkeithhill** [comment] 2017-11-08 16:02
@ZHumphries  That is a different bug related to debugging that is being tracked [here](https://github.com/PowerShell/PowerShellEditorServices/issues/551)

**Comment by rkeithhill** [comment] 2017-11-08 16:07
@Cognic  This looks to be the exact same issue as before:
```
11/8/2017 10:10:13 AM [VERBOSE] - Method "ReadMessage" at line 123 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    Received Request 'setBreakpoints' with id 3

11/8/2017 10:10:13 AM [VERBOSE] - Method "ResolveFilePath" at line 354 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: untitled:Untitled-3

11/8/2017 10:10:13 AM [ERROR] - Method "OnListenTaskCompleted" at line 391 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: The given path's format is not supported.
       at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleSetBreakpointsRequest>d__25.MoveNext()
```
I wonder if you're seeing what @MRWeather points out above.  That is, you don't have an "Untitled-3" window open but at some point you did and you set a breakpoint in it and closed that window. But the breakpoint hung around.  If you look in the Breakpoints view, do you see a breakpoint set on "Untitled-3"?  If so, right-click and remove that breakpoint.  That should get you debugging again.

**Comment by Cognic** [comment] 2017-11-09 14:23
@rkeithhill Sorry I forgot to mention that I have tried what @MRWeather pointed out and didn't work. 
Now there was a new version got pushed 1.18.0 which seems to have fixed the debugging issue. Thank you.

**Comment by rkeithhill** [comment] 2017-11-09 16:22
Ah, looks like they fixed the VSCode side of the debugger.  I'm still going to commit my changes to make the PowerShell side more resilient to this.

**Comment by MRWeather** [comment] 2017-11-09 16:36
The  breakpoint on an unsaved file is still an issue for me even with the new VSCode.

**Comment by rkeithhill** [comment] 2017-12-05 03:29
I believe this particular issue has been fixed.  If I haven't heard otherwise in a few days, I'm going to close this issue.

**Comment by MRWeather** [comment] 2017-12-07 20:23
I believe it is fixed. I have tested the conditions that I reported and the debugger doesn't crash. 

I still think it is odd that you can set a breakpoint in an unsaved file when it won't break on it. And if you save after setting a breakpoint, the Untitled-x breakpoint remains in the list of breakpoints. 
I know these warrant another issue. 
So the symptom is fixed, I have no problem with this issue being closed.

**Comment by rkeithhill** [comment] 2017-12-07 22:17
@MRWeather Thanks for following up.  Yeah, there are some oddities with the interaction (or lack thereof) with VSCode debug breakpoint UI and the target debugger - which doesn't actually get invoked until the user starts debugging.

**Closed by rkeithhill** 2017-12-07 22:17 UTC
