### ISSUE TITLE
Stopping on a breakpoint influence script behavior using last execution status variable "$?"

### ISSUE THREAD

**Issue by ggirard07** [PowerShell/vscode-powershell#2455] opened 2020-02-03 16:12 UTC
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.2.0
ms-azure-devops.azure-pipelines@1.165.1
ms-vscode.azure-account@0.8.8
ms-vscode.powershell@2020.1.0
msazurermtools.azurerm-vscode-tools@0.8.3
vsciot-vscode.azure-iot-edge@1.20.0
vsciot-vscode.azure-iot-toolkit@2.15.0
vsciot-vscode.azure-iot-tools@0.3.0
vsciot-vscode.vscode-iot-device-cube@0.1.4
vsciot-vscode.vscode-iot-workbench@0.11.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When breaking in a script execution from VS Code, the debugger seems to influence the value of the predefined variable containing the last execution status `$?`. For example, If I am breaking on a `if` statement checking this variable, result is always `$true` while during a real world execution it might not.

**Steps to reproduce:**
1. Create a script with following content
2. Execute the script from the traditional Powrshell console
3. Open the script in VS Code and put a breakpoint on the `if` statement
4. Execute the script again in a debug session in VS Code (`Powershell : Interative Session` in my case)

#### Expected Behaviour

`if` statement should be evaluated to `$false` and output should looks like
```powershell
PS C:\Users\me\Desktop\Test PWSH> .\test.ps1
 Volume in drive C is OS
 Volume Serial Number is 0C92-C673

 Directory of C:\

File Not Found
```

#### Actual Behaviour

`if` statement is always evaluated to `$true` and output proves script behavior has been altered due to extra line
```powershell
PS C:\Users\me\Desktop\Test PWSH> .\test.ps1
 Volume in drive C is OS
 Volume Serial Number is 0C92-C673

 Directory of C:\

File Not Found

Hit Line breakpoint on 'C:\Users\me\Desktop\Test PWSH\test.ps1:2'

[DBG]: PS C:\Users\me\Desktop\Test PWSH> 
This should not happen... unless you are the type of guy having a 'foo' folder at the root of your C drive ;)
```

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4148824/logs.zip)

**Comment by rjmholt** [comment] 2020-02-03 17:19
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2347

**Closed** 2020-02-04 19:00 UTC
Labels: Resolution-Duplicate
