### ISSUE TITLE
Enable running PowerShell with Arguments (ex: -sta) 

### ISSUE THREAD

**Issue by PeterHodges15** [PowerShell/vscode-powershell#2476] opened 2020-02-18 17:08 UTC
Issue Type: <b>Feature Request</b>

n Settings.JSON I can specify:
```json
"powershell.powerShellAdditionalExePaths": [
{
"exePath": "C:\Program Files\PowerShell\7-preview\pwsh.exe",
"versionName": "7-preview",
},
```
But this does not enable me to start up Powershell with certain arguments.
Namely I want to start like:
```json
"powershell.powerShellAdditionalExePaths": [
{
"exePath": "C:\Program Files\PowerShell\7-preview\pwsh.exe",
"Arguments": "-sta",
"versionName": "7-preview",
},
```
so that the thread starts in "Single-Threaded Apartment" (This cannot be changed once started)
I would expect that if you highlighted sections of code and ran them, you will remain in STA mode.
If you ran the script from within VSC, you would remain in STA mode.
Extension version: 2020.1.0
VS Code version: Code - Insiders 1.43.0-insider (595f98455be0aac7372a0ae7841efae9b91b848e, 2020-02-18T13:52:42.988Z)
OS version: Windows_NT x64 10.0.18363

**Comment by rjmholt** [comment] 2020-02-18 18:44
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1470.

It turns out the VSCode API makes this easy for us, so it should be possible to do

**Comment by PeterHodges15** [comment] 2020-02-18 18:53
Great.  If you get it in, I will get latest, build and test it out.

**Comment by rjmholt** [comment] 2020-02-18 18:59
> If you get it in, I will get latest, build and test it out.

It's currently marked as up-for-grabs, but I'll see if I can look into it later in March

**Closed** 2020-02-19 22:00 UTC
Labels: Resolution-Duplicate
