### ISSUE TITLE
2019.9.0 Will not load if C:\Program Files\PowerShell Exists

### ISSUE THREAD

**Issue by andyhoffman12** [PowerShell/vscode-powershell#2239] opened 2019-10-10 17:11 UTC
### System Details

System Details Output
```
& {"### VSCode version: $(code -v)"; "`n### VSCode extensions:`n$(code --list-extensions --show-versions | Out-String)"; "`n### PSES version: $($pseditor.EditorServicesVersion)"; "`n### PowerShell version:`n$($PSVersionTable | Out-String)"}
### VSCode version: 1.39.0 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515 x64

### VSCode extensions:
alexcvzz.vscode-sqlite@0.8.0      
DavidWang.ini-for-vscode@0.0.4    
DotJoshJohnson.xml@2.5.0
GrapeCity.gc-excelviewer@2.1.32   
ionutvmi.reg@1.0.1
jakobmats.caml-light@0.0.4        
leighlondon.eml@0.3.2
ms-vscode-remote.remote-wsl@0.39.9
ms-vscode.powershell@2019.9.0     
slevesque.vscode-autohotkey@0.2.2 
tommasov.hosts@1.1.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
**Probably Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2217**

The powershell extension is not loading on my workstation. Uninstalling both the extension and vscode + removing the extension files from disk and reinstalling does not resolve.

After some troubleshooting I determined that if C:\Program Files\PowerShell\ exists it will block the extension from loading. I suspect that this was due to the fact that on my system I previously had powershell core 6.0 installed but removed due to other issues ( I primarily write for windows 7/2008r2 machines). That removal left behind the C:\Program Files\PowerShell\ directory, Core was uninstalled a long time ago, 6+ months, and the extension had been working fine at that time..
When the error began around the release of 2019.9.0 I noticed the problem but didn't analyze at the time. This issue does not occur with 2019.5.0 in my testing. (rolling back the extension using VSCode). Updating back to 2019.9.0 causes this issue to return.

#### Expected Behaviour

Edit a powershell file and the integrated console loads

#### Actual Behaviour

Opening a .ps1 file nothing happens. No console loads and the indicator at the bottom right never changes and the powershell version icon is not present.
Pressing F5 results in:
'Cannot debug or run a PowerShell script until the PowerShell session has started. Wait for the PowerShell session to finish starting and try again.'
No amount of waiting will resolve this issue, and again no typical activity of Initializing... appearing in the lower right.

## logs from the Developer tools from vs code
```
abstractExtensionService.ts:396 Activating extension 'ms-vscode.powershell' failed: Cannot read property 'exePath' of undefined.
_logMessageInConsole @ abstractExtensionService.ts:396
console.ts:137 [Extension Host] Activating extension `ms-vscode.powershell` failed:  Cannot read property 'exePath' of undefined
t.log @ console.ts:137
console.ts:137 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'exePath' of undefined
	at Object.getDefaultPowerShellPath (c:\Users\AndrewHoffman\.vscode\extensions\ms-vscode.powershell-2019.9.0\out\src\platform.js:76:59)
	at SessionManager.getPowerShellExePath (c:\Users\AndrewHoffman\.vscode\extensions\ms-vscode.powershell-2019.9.0\out\src\session.js:239:26)
	at SessionManager.start (c:\Users\AndrewHoffman\.vscode\extensions\ms-vscode.powershell-2019.9.0\out\src\session.js:84:39)
	at activate (c:\Users\AndrewHoffman\.vscode\extensions\ms-vscode.powershell-2019.9.0\out\src\main.js:133:24)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:667:613)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:667:264)
	at T._doActivateExtension.Promise.all.then.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:666:404)
```

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3713741/vscode-powershell.log)

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3713730/EditorServices.log)

**Comment by rjmholt** [comment] 2019-10-10 20:04
Thanks for opening this @andyhoffman12. You're correct that this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2217

**Closed** 2019-10-11 21:00 UTC
Labels: Resolution-Duplicate
