### ISSUE TITLE
PowerShell Preview Integrated Console v2021.4.2 - Hangs on starting

### ISSUE THREAD

**Issue by juergsteiger** [PowerShell/vscode-powershell#3348] opened 2021-05-13 14:53 UTC
The PowerShell Preview Integrated Console v2021.4.2 **hangs on starting**. Disable the PowerShell Preview Extension (2021.4.2) and enabling the PowerShell Extension (2021.2.2) solves the issue.

### System Details
See VersionInformation.txt

### Issue Description

When I start VSCode with the PowerShell Preview Extension (2021.4.2) enabled, the PowerShell Preview Integrated Console v2021.4.2 hangs on starting. 

There is a warning symbol in the upper right corner of the terminal with the text:

Extensions want to make the following changes to the terminal's environment:
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-3cf07e0802-sock

The [relaunch terminal] hyperlink in this warning symbol is not working.

Disable the PowerShell Preview Extension (2021.4.2) and enabling the PowerShell Extension (2021.2.2) solves the issue.

[LogAndJPGs.zip](https://github.com/PowerShell/vscode-powershell/files/6473197/LogAndJPGs.zip)

### Attached Logs

Logs and JPGs are attached in a Zip file

**Comment by andschwa** [comment] 2021-05-18 20:42
Ah, thank you, this is a duplicate of #3306 (confirmed through the logs and screenshots, thanks for those!).

**Comment by andschwa** [comment] 2021-05-19 21:10
Hey @juergsteiger can you try to repro with the VSIX in the zip at the link in this comment? https://github.com/PowerShell/vscode-powershell/issues/3306#issuecomment-844469471

**Comment by juergsteiger** [comment] 2021-05-20 16:17
Hi Andrew

I just added this comment:

Tested on my personal and on the company machine the whole day. It worked perfect.

Looks for me the issue is solved. Great!

Von: Andrew Schwartzmeyer ***@***.***>
Gesendet: Mittwoch, 19. Mai 2021 23:10
An: PowerShell/vscode-powershell ***@***.***>
Cc: Jürg Steiger ***@***.***>; Mention ***@***.***>
Betreff: Re: [PowerShell/vscode-powershell] PowerShell Preview Integrated Console v2021.4.2 - Hangs on starting (#3348)


Hey @juergsteiger<https://github.com/juergsteiger> can you try to repro with the VSIX in the zip at the link in this comment? #3306 (comment)<https://github.com/PowerShell/vscode-powershell/issues/3306#issuecomment-844469471>

**Closed** 2021-05-21 19:00 UTC
Labels: Resolution-Duplicate
