### ISSUE TITLE
Constant CPU load

### ISSUE THREAD

**Issue by ya-alexander** [PowerShell/vscode-powershell#1464] opened 2018-08-02 15:14 UTC
Issue Type: <b>Performance Issue</b>

Hi,

whenever I run a PS script in VS Code, the CPU load keeps staying at around 15-20% although the execution of the script already finished. It seems that Windows PowerShell is causing the actual load. Do you have any tips to remedy that behavior?

![image](https://user-images.githubusercontent.com/29278083/43593064-3b25602e-9677-11e8-8eb5-7be17f1f7e1b.png)

Thanks,
Alex

Extension version: 1.8.2
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (24.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rkeithhill** [comment] 2018-08-02 15:17
What happens if you disable script analysis with the setting `"powershell.scriptAnalysis.enable": false`?

**Comment by ya-alexander** [comment] 2018-08-06 04:44
Thanks for your quick reply. Unfortunately, disabling script analysis does not help. CPU load is still high although the script has finished running.

**Comment by ya-alexander** [comment] 2018-08-10 05:36
@rjmholt Thanks a lot. I tried disabling CodeLens and, at least for now, can confirm that it helped a bit. Windows PowerShell is still using 6-8% of CPU, but that is way less than the > 15% before. Do you have any more tips like that :-)

**Comment by RussPitcher** [comment] 2018-08-29 08:52
I've been having a similar issue when working on a 3000-line script with one hyper-threaded core from my 2-core laptop regularly nailed at 100% on a PowerShell process under VSCore and very laggy performance.  I also noticed that the status bar almost constantly had 'Formatting PowerShell document...' running. 

Disabling CodeLens helped, but not a great deal.  Disabling script analysis has made a massive difference.

**Comment by rjmholt** [comment] 2018-08-29 23:12
Yeah disabling ScriptAnalysis is the other tip.

It looks like different features are performance bottlenecks on different machines.

If anyone is hitting an issue like this, try disabling individual features (should be similar to how CodeLens is disabled) and report back here -- it's much easier for us to determine the cause of performance issues with information like that on hand.

**Comment by dpaulson45** [comment] 2018-08-30 20:55
I think i might be seeing the same issue. I just filed #1503 for PowerShell using a large amount of CPU. Let me know if i can do anything to assist with debug/repro.

**Comment by rjmholt** [comment] 2018-08-30 23:05
@dpaulson45 Can you try disabling script analysis and tell us what you find? Then re-enable it and try disabling CodeLens. Then disable both. And report back on what effect each has? Thanks!

**Comment by dpaulson45** [comment] 2018-09-11 22:02
@rjmholt after disabling script analysis the CPU issue doesn't occur after i reload Visual Studio Code. CodeLens doesn't appear to matter if this is enabled or disabled.

**Comment by DarkLite1** [comment] 2018-10-01 12:36
Same issue here, very high memory consumption (4GB) when running VS Code Insiders (latest). The only thing I use it for is developing PowerShell scripts. When checking the `Task manager` I noticed that it's the process `Windows PowerShell` that consumes this memory. Closing VS Code instantly releases the memory.

The weird thing is, I'm not even running code when the memory is high. The PowerShell terminal in VS Code is just sitting there doing nothing while the memory is still being consumed by PowerShell as appears in the `Task Manager`.

**Comment by MattLParker** [comment] 2018-12-12 13:04
My #1648 was closed and referenced here, however it seems that my issue is completely unrelated to this. 
![image](https://user-images.githubusercontent.com/26982285/49871572-98a32680-fde4-11e8-9b8b-383b3aecf423.png)

**Comment by MattLParker** [comment] 2018-12-18 16:15
Since my other was closed, I'll comment here. It appears that when using import-pssession with a -prefix 
it seems to continually hang due to the large number of new commands that it is importing.
in my test I am doing a single function that connects to two seperate exchange enviroments, both with a custom prefix. So for example I will have a get-01mailbox and get-02mailbox. It seems that it will continually try importing, then failing and repeating the process.

**Comment by Hypernut** [comment] 2019-02-15 11:24
Same thing here. Fresh start of VScode, the "integrated console" is immediately using 25% CPU. ProcessEpxlorer shows that it is constantly opening and closing threads. Memory usage is increasing slowly but constanly.

**Comment by cmcit-bferg** [comment] 2019-03-26 13:54
Same issue. 8th gen i7, 35-40% CPU load for several minutes when I start vscode or switch .ps1 files. Disabling CodeLens had no noticeable effect whatsoever.
Disabling ScriptAnalyzer dropped CPU usage to ~20%.

Also worth noting, my terminal does not render until I start typing.

**Comment by rkeithhill** [comment] 2019-03-26 14:18
Please update to PSScriptAnalyzer 1.18.0 and see if the problem persists.  
```
Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
```

**Comment by Hypernut** [comment] 2019-03-26 14:37
Yep that fixed it for me.
Oddly `get-module -listavailable` shows the new version in `WindowsPowerShell\Module`s, but  still the old version 1.17 in `.vscode\extensions\ms-vscode.powershell-1.11.0\modules `

**Comment by DarkLite1** [comment] 2019-03-26 14:52
@Hypernut same experience here: `Get-Module -ListAvailable` shows version `1.17.1` and in the PowerShell module folder there is only the new one, version `1.18.0`.

**Comment by Hypernut** [comment] 2019-03-26 14:57
I think the one in the extension-folder only gets updated when the powershell extension as a whole gets updated. But that would also mean the powershell console in vscode uses a different module than the editor in vscode?

**Comment by cmcit-bferg** [comment] 2019-03-26 14:58
Running the command @Hypernut gave made no change--in fact, the test was significantly worse, but I think there's just an extreme amount of variability in behavior here. Yes, I restarted vscode after running it.

![image](https://user-images.githubusercontent.com/46008360/55007605-0fd88100-4fb6-11e9-9994-f386a4e2c89c.png)

**Comment by Hypernut** [comment] 2019-03-26 15:03
I dont know why, but it took some time before it calmed down. :)
Check if you have the latest version installed with `get-module -ListAvailable -name PSScriptAnalyzer`

**Comment by cmcit-bferg** [comment] 2019-03-26 15:10
@Hypernut Like the others, I have 1.18.0 in my path, but 1.17.1 in home\.vscode\extensions...

**Comment by rkeithhill** [comment] 2019-03-26 17:27
> I think the one in the extension-folder only gets updated when the powershell extension as a whole gets updated. 

Correct

> But that would also mean the powershell console in vscode uses a different module than the editor in vscode?

They both should be the same - 1.18.  The one that the editor uses is loaded into runspace 4 which you cans see by running this `(Get-Runspace 4).CreatePipeline("gmo", 0).Invoke()` from the PSIC.

**Comment by rkeithhill** [comment] 2019-03-26 17:28
The basic idea is that the extension will uses the latest version you have installed but it does provide a version in case you don't have any version installed.

**Comment by cmcit-bferg** [comment] 2019-04-03 14:51
After update, CPU usage spikes a little higher than before but for a much shorter period of time. VSC is now using PSScriptAnalyzer 1.18.0

**Comment by rjmholt** [comment] 2019-04-03 18:02
To address questions about where and how PSScriptAnalyzer is loaded:

- The Integrated Console is the same PowerShell process running in-editor script analysis. It's also possible to run `powershell` or `pwsh` in the VSCode console, which doesn't speak to the extension at all. You can check which you're in, look for the `$psEditor` variable.
- The PowerShell extension takes the environment PSModulePath and adds the extension's own modules folder to the end of it, so the modules it ships are available but don't take precedence.
- Currently, the PSScriptAnalyzer the extension loads is the highest available on the module path, so that if there's a PSSA release with bug fixes, you can try that out without any code changes in the extension. (We want to change this to lock to the minor version, so that a new version doesn't break an old extension version)
- This means the PSScriptAnalyzer you get in the Integrated Console will be the first on the module path, but the one running in-editor analysis will be the highest version on the module path. Most of the time these will be the same.

**Comment by rkeithhill** [comment] 2019-04-03 18:08
And to check which version got loaded for in-editor analysis, run this command: `(Get-Runspace 4).CreatePipeline("gmo", 0).Invoke()`

**Comment by SydneyhSmith** [comment] 2020-02-06 22:46
Going to close this as a result of the major architectural changes we made in the omnisharp port.

**Closed by SydneyhSmith** 2020-02-06 22:46 UTC
Labels: Area-Threading, Issue-Performance, verify-fix
