### ISSUE TITLE
Oddities with vscode PS (sorry for the poor title)

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#988] opened 2017-08-09 01:00 UTC
### System Details

- Operating system name and version: Windows 10 16257
- VS Code version: 1.14.2
- PowerShell extension version:1.41
- Output from `$PSVersionTable`:

```
C:\Users\swin.HPELITEBOOK> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16257.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16257.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e

$pseditor.EditorServicesVersion
(no result)

code --list-extensions --show-versions
C:\Users\swin.HPELITEBOOK> code --list-extensions --show-versions
donjayamanne.python@0.7.0
HookyQR.beautify@1.1.1
humao.rest-client@0.15.1
mohsen1.prettify-json@0.0.3
ms-vscode.PowerShell@1.4.1
shanoor.vscode-nginx@0.3.1

$PSVersionTable
See above
```

### Issue Description

I am experiencing a problem with odd behaviour in PS Scripts. Initially, the debugger was throwing an error on a line of code that no longer existed, however this seem to have cleared, yet PS scripts no longer recognised matching brackets within the script (not sure if this should be reported to folding?), but I also often find that I need to close an restart  VScode as the debugger is doing odd things, such as :

- it remembers old brake points that have been set and removed
- you can no long scroll in the integrated PS terminal.
- Can no longer expand/contract element of code.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1210022/logs.zip)

**Comment by swinster** [comment] 2017-08-09 13:21
Often, things fall over if I accidentally edit code when the debugger is still running, halted at a break point.

**Comment by DarkLite1** [comment] 2017-08-10 10:29
Seems to be related to #950

**Comment by swinster** [comment] 2017-08-10 11:20
Albeit running 5.1 :(

**Comment by daviwil** [comment] 2017-08-14 23:28
@swinster unfortunately (as @DarkLite1 also figured out), VS Code doesn't lock the file that you run under the debugger so you might end up editing it by accident.  I'll take a look at your logs and see whether there's something else causing the crash you saw.

**Comment by JustinGrote** [comment] 2020-04-22 17:50
@TylerLeonhardt @SydneyhSmith 
This can be closed, the only still-relevant item I can find is a dupe of https://github.com/PowerShell/vscode-powershell/issues/2371

**Closed** 2020-04-23 21:20 UTC
Labels: Area-Debugging, Issue-Bug, Needs: Attention :wave:
