### ISSUE TITLE
Intellisense hangs

### ISSUE THREAD

**Issue by MSFTandrelom** [PowerShell/vscode-powershell#2567] opened 2020-03-17 17:51 UTC
Issue Type: <b>Bug</b>

Intellisense hangs when auto-completing the comandlet with Loading... message

Extension version: 2020.3.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (12.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment] 2020-03-17 17:53
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2522

**Closed** 2020-03-24 07:00 UTC
Labels: Resolution-Duplicate
