### ISSUE TITLE
PSIC startup fails due to dot-sourcing in Constrained Language Mode

### ISSUE THREAD

**Issue by jotrueck** [PowerShell/vscode-powershell#2547] opened 2020-03-11 06:03 UTC
### System Details
System Details Output
```
### VSCode version: 1.43.0 78a4c91400152c0f27ba4d363eb56d2835f9903a x64

### VSCode extensions:
DotJoshJohnson.xml@2.5.0
eriklynd.json-tools@1.0.2
ms-vscode.powershell@2020.3.0
vangware.dark-plus-material@2.2.3
vscode-icons-team.vscode-icons@10.0.0
ZainChen.json@1.0.4


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The Powershell Integrated Console Starts with Erroroutput

#### Expected Behaviour

The Powershell Integrated Console Starts without Error

#### Actual Behaviour
Whenever VSC is started with installed Powershell extension it fails

### Attached Logs

```
Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 247 in EndProcessing:
System.Management.Automation.CmdletInvocationException: Für diesen Befehl ist keine DOT-Quellentnahme möglich, da er in einem anderen Sprachmodus definiert wurde. Lassen Sie den Operator "." weg, um
diesen Befehl ohne Import des Inhalts aufzurufen. ---> System.NotSupportedException: Für diesen Befehl ist keine DOT-Quellentnahme möglich, da er in einem anderen Sprachmodus definiert wurde. Lassen
Sie den Operator "." weg, um diesen Befehl ohne Import des Inhalts aufzurufen.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   bei System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   bei System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   bei System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   bei System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   bei Microsoft.PowerShell.EditorServices.Hosting.EditorServicesLoader.LogPowerShellDetails()
   bei Microsoft.PowerShell.EditorServices.Hosting.EditorServicesLoader.LogHostInformation()
   bei Microsoft.PowerShell.EditorServices.Hosting.EditorServicesLoader.LoadAndRunEditorServicesAsync()
   bei Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

== Press any key to close terminal ==

11.3.2020 06:37:05 [NORMAL] - Visual Studio Code v1.43.0 64-bit
11.3.2020 06:37:05 [NORMAL] - PowerShell Extension v2020.3.0
11.3.2020 06:37:05 [NORMAL] - Operating System: Windows 64-bit
11.3.2020 06:37:05 [NORMAL] - Language server starting --
11.3.2020 06:37:05 [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
11.3.2020 06:37:05 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\logs\1583905025-872584e6-8d00-44ab-9f21-8c20f2a1b1c01583905021387\EditorServices.log' -SessionDetailsPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-8988-831212' -FeatureFlags @() 
11.3.2020 06:37:05 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\logs\1583905025-872584e6-8d00-44ab-9f21-8c20f2a1b1c01583905021387\EditorServices.log' -SessionDetailsPath 'c:\Users\trueckj\.vscode\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-8988-831212' -FeatureFlags @() 
11.3.2020 06:37:05 [NORMAL] - powershell.exe started.
11.3.2020 06:37:05 [NORMAL] - Waiting for session file
11.3.2020 06:39:05 [NORMAL] - Error occurred retrieving session file
11.3.2020 06:39:05 [NORMAL] - Language server startup failed.
11.3.2020 06:39:05 [ERROR] - The language service could not be started: 
11.3.2020 06:39:05 [ERROR] - Timed out waiting for session file to appear.

```

**Comment by TylerLeonhardt** [comment] 2020-03-11 06:12
This is a duplicate of https://github.com/PowerShell/PowerShellEditorServices/issues/1221.

**Comment by rjmholt** [comment] 2020-03-11 18:45
See also https://github.com/PowerShell/PowerShellEditorServices/issues/754

**Comment by rjmholt** [comment] 2020-03-11 18:46
https://github.com/PowerShell/vscode-powershell/issues/606

**Closed** 2020-03-24 07:00 UTC
Labels: Resolution-Duplicate
