### ISSUE TITLE
VS Code Crashes: Assertion Failed!

### ISSUE THREAD

**Issue by JulianTillmann** [PowerShell/vscode-powershell#1988] opened 2019-05-27 06:57 UTC
### System Details

To help diagnose your issue, the following details are helpful:
- OS: Windows 10 1809, Build 17763.503
- VS Code: 1.34
- PowerShell Extension: 1.12.1
- Output from `$PSVersionTable`:

### VSCode extensions:
andrzejzwierzchowski.al-code-outline@1.0.6
DotJoshJohnson.xml@2.4.0
file-icons.file-icons@1.0.17
heaths.vscode-guid@1.4.7
mikeburgh.xml-format@1.0.2
ms-dynamics-smb.al@3.0.126610
ms-vscode.cpptools@0.23.1
ms-vscode.powershell@1.12.1
ms-vsts.team@1.149.2
PKief.material-icon-theme@3.8.0
vsciot-vscode.vscode-arduino@0.2.25
waldo.crs-al-language-extension@1.1.3

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with the PowerShell Extension in VS Code. When I Restart VS Code while keeping a .ps1 file open in Editor the whole VSCode crashes. 

#### Expected Behaviour

It shouldn't crash

#### Actual Behaviour

1. I get an Assertion error
![image](https://user-images.githubusercontent.com/35929603/58400418-391b9900-805b-11e9-977a-13c896e27a65.png)
2. The VS Code crashes
![image](https://user-images.githubusercontent.com/35929603/58400522-8e57aa80-805b-11e9-8554-2f0efa9ce57f.png)

This happens repeatedly, I can only fix this by disabling the Extension or renaming the ps1 file so it isn't opened. 

### Attached Logs
All Logs from today
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3222241/logs.zip)

**Comment by SydneyhSmith** [comment] 2019-05-28 16:56
@JulianTillmann thanks for reporting this issue, I am trying to reproduce--when you are restarting VSCode, how are you doing this?

**Comment by rjmholt** [comment] 2019-05-28 17:07
@JulianTillmann, if you uninstall the PowerShell extension from VSCode, does this problem still occur?

**Comment by rjmholt** [comment] 2019-05-28 21:13
This looks like it might be https://github.com/microsoft/vscode/issues/35117.

Can you try out VSCode Insiders to see if this still occurs?

**Comment by JulianTillmann** [comment] 2019-05-29 05:39
@SydneyhSmith VS-Code is closed because of the crashing and I simply click on the VSC Icon. The "Reopen"-Button has the same  behaviour

@rjmholt uninstalling or disabeling the PowerShell Extension lets me start VSCode normally. But I want to use the Extension, so that is not an Option 

I don't know if #35117 is the same issue, I don't use any zooming. Simply having a ps1-file still open when last closing VSCode generates this Problem ~80% of the time. I also have 4 colleagues who have the same issues.

**Comment by rjmholt** [comment] 2019-05-29 05:50
It sounds like this is a problem in VSCode that's being triggered because of a UI functionality that the PowerShell extension causes use of.

The error message you post looks like a deep error in VSCode's own node-driven terminal failing a native code assertion when it calls into a Windows OS API (I believe VSCode has been moving toward supporting modern terminal APIs in recent Windows versions). Essentially, something the PowerShell extension does not touch or code for directly, but which is more likely to occur because the extension is installed.

In which case, the fix can't come from us.

My suspicion is that this has already been addressed upstream in VSCode but is not yet available in stable builds. Please try your normal workflow using the [latest VSCode Insiders install](https://code.visualstudio.com/insiders/) and let us know if the problem persists.

**Comment by rjmholt** [comment] 2019-06-07 18:28
@JulianTillmann @NAVFreak just want to follow up here -- I believe VSCode 1.35 has been released. If you update VSCode, does that fix this bug?

**Comment by SydneyhSmith** [comment] 2019-06-13 20:17
Going to close this as resolved by VSCode 1.35 but will re-open if this is still an issue--Thanks!

**Closed by SydneyhSmith** 2019-06-13 20:17 UTC
Labels: Needs-Repro-Info, vscode-bug

**Comment by NAVFreak** [comment] 2019-06-13 22:30
Vs code Daily builds doesn't have this problem

Den tor 13 juni 2019 22:17 skrev Sydney Smith <notifications@github.com>:
