### ISSUE TITLE
Login-AzureRmAccount

### ISSUE THREAD

**Issue by ahusking** [PowerShell/vscode-powershell#799] opened 2017-05-31 05:55 UTC
### System Details

- Operating system name and version: Windows 10 - 1607, Build 14393.1198
- VS Code version: 1.12.2
- PowerShell extension version: 1.1.0
- Output from `$PSVersionTable`:

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

When i run the Login-AzureRmAccount command the dialogue box isn't shown.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by pcgeek86** [comment] 2017-05-31 14:39
Closing as duplicate of #541.

**Closed by pcgeek86** 2017-05-31 14:39 UTC

**Comment by daviwil** [comment] 2017-05-31 14:41
Thanks Trevor!

@ahusking the problem here is that the dialog appears *under* the VS Code window, you should be able to find it in the taskbar or by Alt+Tab'ing.  We'll get the underlying issue fixed within the new few releases.
