### ISSUE TITLE
autoCorrectAliases replaces "process {" with "Get-Process {"

### ISSUE THREAD

**Issue by DEberhardt** [PowerShell/vscode-powershell#3261] opened 2021-03-29 10:58 UTC
Issue Type: <b>Bug</b>

Hello,

first, I don't know whether this setting is due to the Extension or VsCode itself. Please advise if this needs to be raised in the VsCode repo.

This issue does not occur with the default setting for Auto-Correcting Aliases:
 ```json
  // Replaces aliases with their aliased name.
  "powershell.codeFormatting.autoCorrectAliases": false,
```

I have `autoCorrectAliases` set to `TRUE` and I love this feature :)

This happens under very specific circumstances, i.E. when code-Errors are present.

I have an advanced script with  BEGIN/PROCESS/END block and during changing the description of a Parameter for example, the syntax is incomplete resulting in the code being read differently (usually this is an open comment with ' or " (when replacing them with the other or adding emphasis within the comment).

my `process` block function name gets replaced with `Get-Process` resulting the whole Script to be unusable.

```powershell
❯ Get-Alias process
Get-Alias : This command cannot find a matching alias because an alias with the name 'process' does not exist.
At line:1 char:1
+ Get-Alias process
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (process:String) [Get-Alias], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFoundException,Microsoft.PowerShell.Commands.GetAliasCommand
```

Process.exe _is_ an executable, but no substitute for Get-Process...

Can this replacement please be excluded? 

Extension version: 2021.2.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (17.19GB free)|
|Process Argv|--crash-reporter-id efc3d77d-4b9d-44d6-894f-bd5aee3260eb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30280384
pythontbcf:30265426
pythonvspyt943cf:30280190
openwsldoc:30280162
vscoresta800cf:30279782
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by rjmholt** [comment] 2021-03-29 14:54
Duplicate of https://github.com/PowerShell/PSScriptAnalyzer/issues/1402

**Closed** 2021-03-30 20:33 UTC
Labels: Needs: Triage :mag:

**Comment by andschwa** [comment] 2021-09-13 17:42
Hi @DEberhardt, the latest release of the extension comes with PSScriptAnalyzer v1.20.0, which should no longer erroneously highlight a `process` block as an error like this. Can you verify for us? Thanks!

**Comment by DEberhardt** [comment] 2021-09-14 19:43
Hello,
thank you for the feedback, I just checked and I am on v1.20.0
```powershell
❯ Get-module PSScriptAnalyzer -ListAvailable

    Directory: C:\Users\David\.vscode\extensions\ms-vscode.powershell-2021.9.0\modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.20.0     PSScriptAnalyzer                    {Get-ScriptAnalyzerRule, Invoke-ScriptAnalyzer, Invoke-Formatter}
```

and though it is always hard to prove non-existence of something, I think I managed to do so:
![image](https://user-images.githubusercontent.com/44290340/133322997-00850dca-811a-4143-8cad-ade1cf1c6fae.png)

Thank you for fixing this one, it has annoyed me greatly.
Hope this conveys my gratitude 😎 
![image](https://user-images.githubusercontent.com/44290340/133323352-d04a3c49-ad76-4ffc-be5a-f85e4de732b9.png)


thanks,
David

**Comment by DEberhardt** [comment] 2021-09-14 19:43
#please-close

**Comment by andschwa** [comment] 2021-09-14 19:51
Shaka. When the walls fell. 👍

**Comment by DEberhardt** [comment] 2021-09-14 19:58
More like, "Shaka. When the bug is squashed" 😸
