### ISSUE TITLE
Extension needs tremendous RAM

### ISSUE THREAD

**Issue by pilgi3** [PowerShell/vscode-powershell#2092] opened 2019-07-16 11:38 UTC
Issue Type: <b>Bug</b>

I openend different *.ps1 files, but only in read mode.
No script was started and after some time the extension suddenly needed a lot of RAM.
Visual Code was installed on Server 2016 and is a device installation (no user setup).
This behavior has not been observed in the past.

Extension version: 2019.5.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|24.00GB (12.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by pilgi3** [comment] 2019-07-16 11:39
![taskmgr](https://user-images.githubusercontent.com/44865075/61291539-0d9d6b00-a7cf-11e9-8b44-178b6d720faa.jpg)

**Comment by rjmholt** [comment] 2019-07-16 15:44
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/1552.

This happens for a couple of reasons. One is because of the extension trying to resolve references in your ps1 files. To work where references come from, we must resolve file paths and modules and use PowerShell to do so. Another cause is PSScriptAnalyzer diagnosing and formatting, which again performs module look ups to determine things like aliases.

We're doing some work in the extension currently that we hope will pay off in terms of improved performance here.

You might experience some improvement by turning off CodeLens, which should be covered in the linked issue.

**Closed by rjmholt** 2019-07-16 15:44 UTC

**Comment by pinkylabs** [comment] 2022-02-09 16:27
I was looking into the same issues and noticed that it (above mentioned script) seems it scans all over the hard drives on places I even forgot they exist ;) Maybe 'we must resolve file paths' step is what I'm hitting into. The memory ends up around 600M on the scan is completed. As soon as I start a dummy script in the editor the scanning starts again. (Observing with Sysinternal's ProcessMonitor)
