### ISSUE TITLE
Inserting help is broken

### ISSUE THREAD

**Issue by GarryONeill** [PowerShell/vscode-powershell#1493] opened 2018-08-21 11:15 UTC
## Issue Description ##

Using VS Code to write PowerShell scripts. When writing an Advance function I used to be able to type '##' (that's a double hash) at the top of the function between the function name and the [cmdletbinding()] and it would automatically add the PowerShell help descriptions.

Now when I do this it doesn't add the help but breaks all of my formatting. This appears to be an issues with the PowerShell plugin?

This is broken in the lastest build as it is not working on both of my computers.

Can someone please fix this awesome feature. Thanks!

Kind regards
Garry

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.26.1|
| PowerShell Extension Version | 1.8.3 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.228|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.228|
|BuildVersion|10.0.17134.228|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|espresso|vitaliy|1.7.3|
|kixtart|cyann|0.0.1|
|mssql|ms-mssql|1.4.0|
|PowerShell|ms-vscode|1.8.3|
|Theme-Array|gerane|0.0.2|
|Theme-azure|gerane|0.0.2|
|Theme-BlueDawn|gerane|0.0.2|
|Theme-Boron|gerane|0.0.4|
|Theme-DarkRoomContrast|gerane|0.0.2|
|Theme-dimmed-night|gerane|0.0.3|
|Theme-FlatDark|gerane|0.0.2|
|theme-light-vs-mac|jamiewest|0.4.5|
|Theme-Ocean-Dark-Soda|gerane|0.0.2|
|theme-railgun|be5invis|2.3.0|
|Theme-Smyck|gerane|0.0.2|;

</details>

**Comment by GarryONeill** [comment] 2018-08-21 11:45
I can confirm the current version 1.8.3 broke this feature. I managed to install a previous version, 1.8.2, and the shortcut "##" to insert help works.

**Comment by tylerl0706** [comment] 2018-08-21 14:43
This is a dupe of https://github.com/PowerShell/vscode-powershell/issues/1488.

The fix is in master, it's just pending a release which I'll do sometime this week. Thanks!

**Closed by tylerl0706** 2018-08-21 14:43 UTC

**Comment by GarryONeill** [comment] 2018-08-22 10:39
Awesome, thanks :)

**Comment by GarryONeill** [comment] 2018-09-01 06:41
This is still broken in the new version. Still having the same issue. Thanks
