### ISSUE TITLE
Outline doesn't show classes

### ISSUE THREAD

**Issue by bazgr** [PowerShell/vscode-powershell#2087] opened 2019-07-15 10:52 UTC
### System Details

- MacOS 10.14
- VS Code 1.36.1
- PS Extension 2019.5.0

### Issue Description

I recently started writing classes in Powershell and noticed that the outline only includes functions but not classes.

#### Expected Behaviour

Classes should appear in the outline view.

#### Actual Behaviour

Classes don't appear in the outline view.

I don't know if it's supposed to work and an actual bug or if it's a feature request, feel free to recategorize it if necessary.

**Comment by TylerLeonhardt** [comment] 2019-07-15 14:32
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/3

Classes support wasn't in the extension because we still supported v3/v4 in the stable version of the extension.

In the preview version, we're only supporting v5.1 and up so support for classes can finally be added back (there are commented out places in the code where this feature existed already. It was commented out when we supported v3/v4)

**Comment by TylerLeonhardt** [comment] 2019-07-15 14:32
Closing this as a dupe.

**Closed by TylerLeonhardt** 2019-07-15 14:32 UTC
