### ISSUE TITLE
Support All Native Code Folding Commands

### ISSUE THREAD

**Issue by BinaryWizard904** [PowerShell/vscode-powershell#2700] opened 2020-05-14 16:25 UTC
Visual Studio Code offers several useful code folding commands that currently do nothing when editing PowerShell files: _Fold All Regions_, _Unfold All Regions_, _Fold All Block Comments_, and _Unfold All Block Comments_.  I request you add support support for these commands.

Both would be quite useful to me. Being able to easily fold _just_ #region sections would prevent overfolding when dealing with #regions nested in try/catch/finally, if, or switch blocks alongside code not contained in a #region.  Similarly, being able to fold _just_ block comments would greatly ease editing files that contain numerous functions with long and detailed comment-based-help sections (I have some scripts that contain several advanced functions, each with multi-page comment-based-help blocks).

You can replicate this issue via the following:

1. Add the example PowerShell function below to a document in VS Code.
2. Open the Command Palette
3. Attempt to run the _Fold All Regions_ or _Fold All Block Comments_ commands.
4. Observe that no folding occurred.

```powershell
<#
.SYNOPSIS
    Short description
.DESCRIPTION
    Long description
.PARAMETER a
    Parameter description
.PARAMETER b
    Parameter description
.EXAMPLE
    An example
.NOTES
    General notes
#>
function test-function ($a, $b) {
    #region handle a
        if($a -lt $b) {$a++}
    #endregion handle a

    #region handle b
        if($b -gt 10) {$b--}
    #endregion handle b

    return $a+$b
}
```

**Comment by TylerLeonhardt** [comment] 2020-05-14 20:27
That's interesting... I thought this was supported because we do specify if a fold is a comment/region fold. @glennsarti do you remember anything about this?

**Comment by BinaryWizard904** [comment] 2020-05-15 15:37
@SydneyhSmith Added example code and steps for how to reproduce this to my initial post.

**Comment by corbob** [comment] 2020-05-15 19:30
I can confirm that neither of the fold all block comments or fold regions works for me. For what it's worth: the folding of block comments does work in a TypeScript file.

**Comment by glennsarti** [comment] 2020-05-16 12:01
@TylerLeonhardt I don't specifically remember but you've (PS team) have done some pretty hardcore refactoring since I first did it.

![image](https://user-images.githubusercontent.com/5819622/82119106-62728f00-97ae-11ea-9344-a23851aafb5d.png)

* Using the example above you can see that VSCode knows about some foldable areas (that's the down chevron in the gutter)

* Un/Fold All Regions continues to work, so it definitely looks like the language server is emitting the wrong result.

* @TylerLeonhardt  Are these tests still running? https://github.com/PowerShell/PowerShellEditorServices/blob/8e8728b94e1832d98350a91d430c8d1165f00871/test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs#L19

Because they are checking for FoldingRangeKind.

* A debug log from a Extension session looking for the responses to folding request would help here.  Unfortunately the current debug logging does not include the JSON output messages :-( and it has no trace facility (?) So that'll need to be done by a PES developer.

https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange

PS - @BinaryWizard904 Probably doesn't matter too much this time, but adding versions of PowerShell, version of PS Extension and whether you're running insider would really help next time!

**Comment by TylerLeonhardt** [comment] 2020-05-16 18:46
The issue was in the library we depend on. I have a PR out now:
https://github.com/OmniSharp/csharp-language-server-protocol/pull/241

**Comment by TylerLeonhardt** [comment] 2020-05-16 18:58
This has been merged in. The next version of the PowerShell Preview extension should have this change.

**Closed** 2020-05-16 20:00 UTC
Labels: Area-Folding, Resolution-External
