### ISSUE TITLE
Command flags not visible

### ISSUE THREAD

**Issue by Consoli0** [PowerShell/vscode-powershell#2636] opened 2020-04-15 23:40 UTC
### System Details

System Details Output
```
### VSCode version: 1.44.0 2aae1f26c72891c399f860409176fe435a154b13 x64

### VSCode extensions:
acidic9.glua@0.1.7
akamud.vscode-theme-onedark@2.2.1
alexcvzz.vscode-sqlite@0.8.1
dbaeumer.vscode-eslint@2.1.3
esbenp.prettier-vscode@4.4.0
gerane.Theme-Solarized-dark@0.0.5
ginfuru.ginfuru-better-solarized-dark-theme@0.9.4
glitch.glitch@0.1.6
icrawl.discord-vscode@3.13.0
KnisterPeter.vscode-github@0.30.3
ms-azuretools.vscode-docker@1.0.0
ms-vscode-remote.remote-wsl@0.44.2
stringham.move-ts@1.12.0
StroupBSlayen.vscord@0.5.2
tiibun.vscode-docker-ws@0.4.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The color of command flags, they are invisible due to being the same color as the background, I use Solarized Dark, and command flags seem to use the same/a similar color, therefore they are invisible

#### Expected Behaviour

Command flags are invisible 

#### Actual Behaviour

It should show command flags in a visible color

Am new to posting here, forgive me if I did something wrong

**Comment by corbob** [comment] 2020-04-16 00:39
I'm going to say that this is either an issue with PSReadLine, or with Solarized Dark itself. For instance when using Solarized Dark with Windows Terminal I get the same thing: 
![image](https://user-images.githubusercontent.com/30301021/79402031-981e2100-7f3f-11ea-846e-3341bc71b372.png) (in fact, this is one of the reasons I stopped using Solarized because I couldn't be bothered to sort out the color issue)

Of course, I'm not actually able to reproduce this issue in vscode 1.45 🤔

**Comment by rjmholt** [comment] 2020-04-16 00:50
I believe you can reconfigure the colours in your `$profile`; @TylerLeonhardt or @SteveL-MSFT may have some advice there

**Comment by TylerLeonhardt** [comment] 2020-04-16 21:07
Yep, I have this in my `$PROFILE`:

```
Set-PSReadLineOption -ContinuationPrompt "  " -Colors @{ Operator = "`e[95m"; Parameter = "`e[95m" }
```

This issue is really a request for PSReadLine to support this:
https://github.com/PowerShell/PSReadLine/issues/464

in other words, better "theme-ing". We can close this issue since PSReadLine should handle this and not the PowerShell extension.

**Closed by TylerLeonhardt** 2020-04-16 21:07 UTC
Labels: Needs: Triage :mag:

**Comment by Consoli0** [comment] 2020-04-16 21:11
Thanks!
