### ISSUE TITLE
PowerShell on Mac OS X: Intellisense not working for cmdlets

### ISSUE THREAD

**Issue by alexandrudima** [PowerShell/vscode-powershell#250] opened 2016-08-22 07:34 UTC
Moved from Microsoft/vscode#10731

---

From @DSotnikov

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Add PowerShell extension,
2. Open a PowerShell script, 
3. Type Get-P and press Ctrl-space - expected outcome is to see Get-Process - instead shows No Suggestions.

**Comment by daviwil** [comment] 2016-08-22 13:49
Thanks Alex!

Hey @DSotnikov, I am going to make a guess and say that you might not have OpenSSL installed on your machine.  This will cause the language and debug services to fail to load.  If you have Homebrew installed you can just run `brew install openssl`and then restart VS Code.  Let me know if that works!

**Comment by DSotnikov** [comment] 2016-08-22 14:21
Yes, that helped! Thank you so much!

You can close the ticket now.

**Comment by daviwil** [comment] 2016-08-22 20:18
Glad to hear it!  Closing the issue now.

**Closed by daviwil** 2016-08-22 20:18 UTC

**Comment by Liquidmantis** [comment] 2016-08-25 14:35
Thanks!  I've had the same issue and this fixed it.  Maybe a note should be added to the install steps?

**Comment by DSotnikov** [comment] 2016-08-25 15:43
David added a note to
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md#editing-with-visual-studio-code

**Comment by daviwil** [comment] 2016-08-25 16:08
Let me know if I should also add that note to this project's README.md so that it shows up on the extension info page in VS Code. I wonder if users will even follow the link to the installation document?

**Comment by Liquidmantis** [comment] 2016-08-25 18:28
Thanks!  Much appreciated.  I ended up on that page while troubleshooting my issue as it seemed logical that I hadn't installed or configured something correctly so that seems sufficient to me personally.  I don't know that it makes sense to clutter the README with duplicate information.  If someone isn't going to follow the link to the installation document they probably wouldn't read the README either.  That said, it might not hurt to have some added emphasis with a general purpose catch-all statement recommending that you follow the installation documentation to ensure proper installation and configuration.  It "just works" on Windows and OpenSSL is a non-intuitive prereq.  But honestly, if you're setting up to do Powershell development on Linux/macOS you should expect to need to read some documentation. :D

**Comment by DSotnikov** [comment] 2016-08-25 18:32
IMHO, ideally VSCode would check for OpenSSL (if it is a prerequisite) and
complain about the prerequisite not being met.

Right now, both VSCode and PowerShell extension get installed just fine and
then intellisense and debugging are failing with errors that are hard to
correlate with lack of OpenSSL.

Dmitry

**Comment by daviwil** [comment] 2016-08-25 19:04
That's a good point.  The OpenSSL requirement is actually coming from PowerShell, but I wonder if there'd be an easy way for the extension to check for it without launching PowerShell...  Looks like checking for the existence of `/usr/local/opt/openssl` could be a good start.  What do you think?

**Comment by daviwil** [comment] 2016-08-25 19:07
Tracking that request here: https://github.com/PowerShell/vscode-powershell/issues/264

**Comment by MarlonRodriguez** [comment] 2016-08-27 00:25
I posted on #264 but just in case someone out there is looking for the fix for MacPorts:
`ln -s /opt/local/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /opt/local/lib/libssl.1.0.0.dylib /usr/local/lib/
`

**Comment by christianhv** [comment] 2016-09-12 23:40
Hello, 

I have installed OpenSSL and "symlinked", but I am still not able to debug in VSCode. 

What should be any other thing to take into account?

Suggestions?

Christian

**Comment by daviwil** [comment] 2016-09-14 15:00
@christianhv can you capture logs and e-mail them to me?  If you've done those steps and it still doesn't work then maybe there's another problem.

**Comment by Helocheck** [comment] 2016-11-23 15:50
Hello, 

I'm facing the issue despite following instruction here https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#1-powershell-intellisense-does-not-work-cant-debug-scripts

I've installed Openssl via homebrew but when trying to use intellisense I get a "no suggestion" despite SSL libraries and links being there. 

To be noted I still get the OpenSSL warning when opening VSC. 

Not sure if I missed or overlooked something.

**Comment by tomaaa** [comment] 2016-12-10 01:28
Same thing here and I tried everything on the forum

**Comment by daviwil** [comment] 2016-12-10 02:09
@tomaaa can you please capture and send logs by following these instructions:

https://github.com/PowerShell/vscode-powershell/blob/master/README.md#2-capture-verbose-logs-and-send-them-to-us

**Comment by tomaaa** [comment] 2016-12-11 06:22
Reproducing the problem doesn't seems to generate logging. I added the "powershell.developer.editorServicesLogLevel": "Verbose" in settings.json.

**Comment by daviwil** [comment] 2016-12-11 16:52
@Helocheck @tomaaa there was a bug in the way I was checking for the Homebrew installation of OpenSSL, this was fixed on Friday:  https://github.com/PowerShell/vscode-powershell/issues/292.  I think your problems should be fixed when we release the 0.8.0 update this week (shooting for Wednesday).  If you still have trouble after that, let me know and I will diagnose further.

**Comment by tomaaa** [comment] 2016-12-11 16:55
Excellent, I will check again this week.
Thanks
