### ISSUE TITLE
Enable function and variable renaming support

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#727] opened 2017-05-10 21:30 UTC
Now that VS Code has a "rename" action for symbols in a file, we can wire it up to allow renaming a function and all its occurrences across the workspace.

**Comment by johntiger1** [comment] 2017-12-06 16:42
https://github.com/PowerShell/vscode-powershell/issues/261

**Comment by tylerl0706** [comment] 2017-12-06 18:47
Thanks @johntiger1! Closing this as a dupe of #261.

**Closed by tylerl0706** 2017-12-06 18:47 UTC
Labels: Area-Code Navigation, Issue-Enhancement
