### ISSUE TITLE
Wrong reference count for nested functions

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#2646] opened 2020-04-20 10:32 UTC
### System Details

System Details Output
```
### VSCode version: 1.45.0-insider ec0d19789f89d4c25895f4a0cf364276cfb0c6ed x64

### VSCode extensions:
alexcvzz.vscode-sqlite@0.8.1
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer-2@0.0.29
DavidAnson.vscode-markdownlint@0.34.0
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.2.1
hbenl.vscode-test-explorer@2.18.0
ilich8086.Untabify@0.0.2
maziac.asm-code-lens@1.4.3
maziac.dezog@1.2.3
maziac.z80-instruction-set@0.6.3
maziac.z80-unit-tests@1.0.1
mechatroner.rainbow-csv@1.7.0
ms-python.python@2020.3.71659
ms-vscode.powershell-preview@2020.4.4-CI.50512
streetsidesoftware.code-spell-checker@1.8.0
theNestruo.z80-asm-meter@1.1.0
vscode-icons-team.vscode-icons@10.1.1


### PSES version: 2.2.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Wrong reference count (double the actual number) for nested functions:

![nesting_1](https://user-images.githubusercontent.com/16168755/79741647-e5184380-8301-11ea-8cfc-8dacf55a779e.jpg)

![nesting_2](https://user-images.githubusercontent.com/16168755/79741725-05e09900-8302-11ea-8493-5ab3434057bf.jpg)

![nesting_3](https://user-images.githubusercontent.com/16168755/79741733-08db8980-8302-11ea-9050-dccbaf5440c1.jpg)

#### Expected Behaviour

The code lens should show the correct reference count

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4503170/logs.zip)

**Comment by SydneyhSmith** [comment] 2020-04-21 21:13
Thanks @kborowinski does this look like a duplicate of #1465 to you?

**Comment by kborowinski** [comment] 2020-04-21 22:27
@SydneyhSmith They may look similar but I don't think that this issue is a duplicate.

**Comment by andschwa** [comment] 2023-02-07 21:29
Hey @kborowinski can you confirm if this is fixed in the latest preview?

**Comment by kborowinski** [comment] 2023-02-07 21:45
@andschwa Yep, it works as expected! Thanks!

**Closed** 2023-02-08 01:01 UTC
Labels: Issue-Bug, Area-Symbols & References, Resolution-Fixed
