### ISSUE TITLE
Symbol discovery: class methods 

### ISSUE THREAD

**Issue by Antasik** [PowerShell/vscode-powershell#1274] opened 2018-04-17 10:09 UTC
### System Details

- Operating system name and version: Win 10 1709
- VS Code version: 1.22.2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:

`PSVersion                      5.1.16299.248`
`PSEdition                      Desktop`
`PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}`
`BuildVersion                   10.0.16299.248`
`CLRVersion                     4.0.30319.42000`
`WSManStackVersion              3.0`
`PSRemotingProtocolVersion      2.3`
`SerializationVersion           1.1.0.1`

### Issue Description

Symbol discovery feature doesn't work for PowerShell 5 class methods. Scrolling big file is a bit frustrating ;)

**Comment by tylerl0706** [comment] 2018-04-17 22:01
Thanks for the report! It's a dupe of the PowerShellEditorServices issue here: https://github.com/PowerShell/PowerShellEditorServices/issues/14

Give that a +1 so that we can prioritize it!

Thanks again 😄

**Closed by tylerl0706** 2018-04-17 22:01 UTC
