### ISSUE TITLE
Write-Progress is not showing any indicator

### ISSUE THREAD

**Issue by KevinLeeBuchan** [PowerShell/vscode-powershell#1442] opened 2018-07-19 12:34 UTC
**Summary of the new feature**

In PowerShell ISE, PowerGUI, or in the PowerShell console window, Write-Progress shows a dialog with a messaging showing script progress details.  Would like to see some support for this in VSCode.

**Proposed technical implementation details (optional)**

While progress is intended to be displayed by the script, show a three line display just above the "Problems/Output/Debug/Terminal" tabs at the bottom.  The top two lines should show the "Activity" and "Status" text and the third line would be for the optional progress indicator.

**Comment by rjmholt** [comment] 2018-07-19 14:08
Hi @KevinLeeBuchan, this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/140.

`Write-Progress` support is currently being worked on as part of the integration of PSReadLine into the extension: https://github.com/PowerShell/vscode-powershell/issues/535.

**Closed by rjmholt** 2018-07-19 14:08 UTC

**Comment by KevinLeeBuchan** [comment] 2018-07-19 14:17
Sorry for the duplicative suggestion. 

Keep up the GREAT work!

---

**Comment by rjmholt** [comment] 2018-07-19 14:20
Thanks! I know development on this has been a while in the making, but you can follow the work here: https://github.com/PowerShell/PowerShellEditorServices/pull/672
