### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1536] opened 2018-09-19 20:28 UTC
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSWinDocumentation\Ignore> code -v
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
openssl config failed: error:02001003:system library:fopen:No such process
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSWinDocumentation\Ignore> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      4      0


PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSWinDocumentation\Ignore> code --list-extensions --show-versions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
aaron-bond.better-comments@1.3.0
abusaidm.html-snippets@0.2.1
AlanWalk.markdown-toc@1.5.6
alefragnani.Bookmarks@9.1.0
azemoh.one-monokai@0.3.7
ban.spellright@2.5.32
batisteo.vscode-django@0.17.0
bierner.markdown-preview-github-styles@0.1.3
daiyy.quick-html-previewer@0.3.0
DavidAnson.vscode-markdownlint@0.20.0
DavidWang.ini-for-vscode@0.0.4
donjayamanne.githistory@0.4.2
donjayamanne.jupyter@1.1.4
donjayamanne.python-extension-pack@1.4.0
DotJoshJohnson.xml@2.3.2
eamodio.gitlens@8.5.6
emilast.LogFileHighlighter@2.4.1
emmanuelbeziat.vscode-great-icons@2.1.42
Equinusocio.vsc-material-theme@2.4.2
felixfbecker.php-debug@1.12.5
formulahendry.code-runner@0.9.4
gerane.Theme-dimmed-monokai@0.0.2
gharveymn.nightswitch@1.1.0
GitHub.vscode-pull-request-github@0.1.5
GrapeCity.gc-excelviewer@2.1.26
hdg.live-html-previewer@0.3.0
hnw.vscode-auto-open-markdown-preview@0.0.4
HookyQR.beautify@1.4.3
IBM.output-colorizer@0.1.2
ikappas.phpcs@1.0.5
ionutvmi.reg@0.0.2
JerryHong.autofilename@0.1.3
joaompinto.asciidoctor-vscode@0.15.1
johnpapa.winteriscoming@0.7.1
Kelvin.vscode-sshfs@1.9.2
kisstkondoros.vscode-codemetrics@1.17.1
KnisterPeter.vscode-github@0.30.0
magicstack.MagicPython@1.0.12
mariorodeghiero.vue-theme@1.1.0
mechatroner.rainbow-csv@0.5.0
mkloubert.vs-deploy@14.0.0
mkloubert.vscode-remote-workspace@0.32.1
ms-mssql.mssql@1.4.0
ms-python.python@2018.8.0
ms-vscode.csharp@1.16.1
ms-vscode.PowerShell@1.8.4
ms-vsliveshare.vsliveshare@0.3.709
ms-vsts.team@1.136.0
quicktype.quicktype@12.0.42
redhat.java@0.31.0
robertohuertasm.vscode-icons@7.26.0
Shan.code-settings-sync@3.1.2
stkb.rewrap@1.9.1
streetsidesoftware.code-spell-checker@1.6.10
streetsidesoftware.code-spell-checker-polish@1.0.0
TomasHubelbauer.zip-file-system@1.0.0
vangware.dark-plus-material@1.4.0
VisualStudioExptTeam.vscodeintellicode@1.0.4
vscjava.vscode-java-debug@0.13.0
vscjava.vscode-java-pack@0.3.0
vscjava.vscode-java-test@0.8.0
vscjava.vscode-maven@0.11.0
WakaTime.vscode-wakatime@1.2.3
wayou.vscode-todo-highlight@1.0.4
whizkydee.material-palenight-theme@1.9.3
wholroyd.jinja@0.0.8
xaver.clang-format@1.6.2
yzhang.markdown-all-in-one@1.6.0
zhuangtongfa.Material-theme@2.16.5
Zignd.html-css-class-completion@1.11.0
openssl config failed: error:02001003:system library:fopen:No such process
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSWinDocumentation\Ignore> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17754.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17754.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with... crashing command. I decided to quickly test some commands in terminal window. It was working fine. Then at some point it stopped. The moment I was trying to type command that would reach edge it would crash with 

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 3000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()
```

Here's a brief movie but it may not show you everything. 

![vscode](https://user-images.githubusercontent.com/15063294/45779265-d9aef300-bc5a-11e8-996b-cbdfeef81907.gif)

**Comment by rjmholt** [comment] 2018-09-19 20:32
This looks like a PSRL issue maybe -- @SeeminglyScience might have a better diagnosis

**Comment by SeeminglyScience** [comment] 2018-09-19 20:41
I believe there's an open issue somewhere already, but yeah it will be solved with PSRL.

If I remember correctly this is due to the current implementation relying on the window position related `Console` API's for going to the next line.  But it didn't account for window position staying the same after hitting the buffer size.  So that error will pop up after ~3k lines have been written.

As a work around, `Clear-Host` will fix it.  Even though the text isn't *really* cleared, it still resets the buffer size from the console's perspective.

**Comment by rjmholt** [comment] 2018-09-28 21:05
Going to close this as a dupe of https://github.com/PowerShell/vscode-powershell/issues/702

**Closed by rjmholt** 2018-09-28 21:05 UTC
Labels: Area-Integrated Console, Issue-Bug

**Comment by kknight-valorem** [comment] 2019-11-26 17:10
I'm having this issue as well.  Just started occurring around 11/24/2019.  Haven't been able to isolate it for repro yet.

**Comment by MpresaFamDeveloper** [comment] 2022-02-07 11:42
I was running my app and my teammates suggested we upgrade to the latest version of flutter so that the app does not crash when it is integrated. right after I upgraded using CMD I got this error with the following code in it.
![image](https://user-images.githubusercontent.com/86482210/152781685-8588d93c-687e-4249-8948-67e75646fc53.png)

Error Description: 

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\Dev\Banking App (Shukela)\banking_app> new Row(
>>   mainAxisAlignment: MainAxisAlignment.spaceBetween,
>>   children: <Widget>[
>>     new Flexible(
>>       child: new TextField(
>>           decoration: InputDecoration(
>>               contentPadding: EdgeInsets.all(10)
>>           )
>>       ),
>>     ),
>>     SizedBox(width: 20.0,),
>>     new Flexible(
>>       child: new TextField(
>>           decoration: InputDecoration(
>>               contentPadding: EdgeInsets.all(10)
>>           )
>>       ),
>>  
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space ) , Enter
 Space Space Space Space ) , Enter
 Space Space Space Space S i z e d B o x ( w i d t h : Space 2 0 . 0 , ) , Enter
 Space Space Space Space n e w Space F l e x i b l e ( Enter
 Space Space Space Space Space Space c h i l d : Space n e w Space T e x t F i e l d ( Enter
 Space Space Space Space Space Space Space Space Space Space d e c o r a t i o n : Space I n p u t D e c o r a t i o n ( Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space c o n t e n t P a d d i n g : Space E d g e I n s e t s . a l l ( 1 0 ) Enter
 Space Space Space Space Space Space Space Space Space Space ) Enter
 Space Space Space Space Space Space ) , Enter
 Space Space Space Space ) ,

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\Dev\Banking App (Shukela)\banking_app> new Row(
>>   mainAxisAlignment: MainAxisAlignment.spaceBetween,
>>   children: <Widget>[
>>     new Flexible(
>>       child: new TextField(
>>           decoration: InputDecoration(
>>               contentPadding: EdgeInsets.all(10)
>>           )
>>       ),
>>     ),
>>     SizedBox(width: 20.0,),
>>     new Flexible(
>>       child: new TextField(
>>           decoration: InputDecoration(
>>               contentPadding: EdgeInsets.all(10)
>>           )
>>       ),

**Comment by JustinGrote** [comment] 2022-02-07 14:50
@MpresaFamDeveloper I don't think what you're seeing is related to this issue, did you just come here via Google? This is for the Visual Studio Code Powershell Extension.
