### ISSUE TITLE
debugger breaks on removed breakpoints

### ISSUE THREAD

**Issue by bughit** [PowerShell/vscode-powershell#654] opened 2017-04-05 20:11 UTC
### System Details

- Operating system name and version: win7 x64
- VS Code version: 1.10.2
- PowerShell extension version: 0.12.1
- Output from `$PSVersionTable`: 
```
Name                           Value                                                                                                                                          
----                           -----                                                                                                                                          
PSVersion                      3.0                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                
BuildVersion                   6.2.9200.16481                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0}                                                                                                                                
PSRemotingProtocolVersion      2.2                                                                                                                                            
```

### Issue Description
- set a breakpoint
- debug current file
- it breaks
- remove breakpoint (click on breakpoint icon)
- debug current file
- still breaks

**Comment by daviwil** [comment] 2017-04-05 20:54
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/625, please subscribe to that issue to be notified when the issue is fixed.  I'm hoping to resolve it for the next feature update in a couple of weeks.

**Closed by daviwil** 2017-04-05 20:54 UTC
Labels: Area-Debugging, Issue-Bug, Resolution-Duplicate
