### ISSUE TITLE
Intellisense keeps stopping

### ISSUE THREAD

**Issue by kevins550** [PowerShell/vscode-powershell#2712] opened 2020-05-19 16:22 UTC
Issue Type: <b>Bug</b>

When editing multiple .ps1 files from right-click "open in vscode" the second file or third file causes intellisense to stop working.  Releaoding VSCode with a single file restores the functionality

Extension version: 2020.4.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (0.90GB free)|
|Process Argv|C:\source\cast.pwsh.modules\BuildCastProfile.ps1|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by TylerLeonhardt** [comment] 2020-05-19 16:32
Duplicate of #2627

**Closed** 2020-05-20 19:00 UTC
Labels: Resolution-Duplicate
