### ISSUE TITLE
Cmdlet aliases are expanded automatically when formatting document

### ISSUE THREAD

**Issue by mkht** [PowerShell/vscode-powershell#1842] opened 2019-04-03 14:56 UTC
#### VSCode version
```
1.32.3 a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 x64
```

#### VSCode extensions
```
ms-vscode.powershell@1.12.0
```
No other extensions is installed.  
The vscode settings have not changed anything.

#### PSES version
```
1.12.0.0
```

#### PowerShell version:
```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
All aliases in my PS codes are expanded unexpectedly when executing "Format Document".

I tried formatting the code below.
```PowerShell
1..10|%{$_*2}
```

#### Expected result
I expect this code will format like this.
```PowerShell
1..10 | % { $_ * 2 }
```

#### Actual result
But vscode-powershell@1.12.0.0 formatted.
```PowerShell
1..10 | ForEach-Object { $_ * 2 }
```

I know that formatting is provided by the PSScriptAnalyzer module.  
However, I think this issue is specific to vscode-powershell.  
I execute these commands in the Windows PowerShell terminal. (Not in the integrated terminal)

```PowerShell

PS C:\> Install-Module PSScriptAnalyzer -Scope CurrentUser
PS C:\> Get-Module PSScriptAnalyzer -ListAvailable

    Directory: C:\Users\Administrator\Documents\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.18.0     PSScriptAnalyzer                    {Get-ScriptAnalyzerRule, Invoke-ScriptAnalyzer, Invoke-Formatter}

PS C:\> Invoke-Formatter '1..10|%{$_*2}'
1..10 | % { $_ * 2 }
```

In this result, The original formatter of the PSScriptAnalyzer@1.18.0 is not expand aliases automatically.  

Is this bug?  Does anyone have an idea of how to work around it?

**Comment by SydneyhSmith** [comment] 2019-04-03 15:44
@mkht thanks for reporting this, I am able to reproduce it when I use Core but not with Windows (maybe just a coincidence?), which is interesting because you are running Windows...I am wondering if you have any cusotm settings in your VSCode profile?

**Comment by rjmholt** [comment] 2019-04-03 17:49
@bergmeister do you know what settings you use to control this in PSScriptAnalyzer?

**Comment by bergmeister** [comment] 2019-04-03 18:58
The avoid alias rule is not included by default for Invoke-Formatter, therefore I think it is the hashtable that the extension supplies as the -settings param to PSSA that includes this rule. But I'd need to look at code first

**Comment by rjmholt** [comment] 2019-04-03 20:49
Yeah it seems like this is an extension configuration thing.

Here's the list of rules we include:
https://github.com/PowerShell/PowerShellEditorServices/blob/8c66fa912ecfac4e93345ca96dc49d1787f81f1d/src/PowerShellEditorServices/Analysis/AnalysisService.cs#L33-L48

We do log the rules, so if there are logs we might be able to answer the question. Either way, if we have a repro for this, then it should be a relatively simple fix.

**Comment by mkht** [comment] 2019-04-04 00:54
I tried only Windows PowerShell, not tried Core.  
Confirmed that the issue reproduce on the Windows 10 Pro 1809 with VSCode 1.32.3 installed cleanly and has no any custom settings.

I attach the extension logs. 
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3041268/logs.zip)

**Comment by sandscap-sc** [comment] 2019-04-04 23:54
Ref #496

**Comment by mkht** [comment] 2019-04-05 16:02
I still could not find the cause of the issue.
However, I found two workarounds.

The first is to use custom PSSA rule settings.
I create the following configuration file and specify in `powershell.scriptAnalysis.settingsPath`.
Then aliases are no longer automatically expanded.

```PowerShell
# This setting is exactly same as the "CodeFormatting" setting in the PSSA@1.18.0
@{
    IncludeRules = @(
        'PSPlaceOpenBrace',
        'PSPlaceCloseBrace',
        'PSUseConsistentWhitespace',
        'PSUseConsistentIndentation',
        'PSAlignAssignmentStatement',
        'PSUseCorrectCasing'
    )

    Rules        = @{
        PSPlaceOpenBrace           = @{
            Enable             = $true
            OnSameLine         = $true
            NewLineAfter       = $true
            IgnoreOneLineBlock = $true
        }

        PSPlaceCloseBrace          = @{
            Enable             = $true
            NewLineAfter       = $true
            IgnoreOneLineBlock = $true
            NoEmptyLineBefore  = $false
        }

        PSUseConsistentIndentation = @{
            Enable          = $true
            Kind            = 'space'
            PipelineIndentation = 'IncreaseIndentationAfterEveryPipeline'
            IndentationSize = 4
        }

        PSUseConsistentWhitespace  = @{
            Enable          = $true
            CheckInnerBrace = $true
            CheckOpenBrace  = $true
            CheckOpenParen  = $true
            CheckOperator   = $true
            CheckPipe       = $true
            CheckSeparator  = $true
        }

        PSAlignAssignmentStatement = @{
            Enable         = $true
            CheckHashtable = $true
        }

        PSUseCorrectCasing     = @{
            Enable             = $true
        }
    }
}
```

The second is to install an older version of PSSA module on the system.
```PowerShell
Install-Module PSScriptAnalyzer -MaximumVersion 1.17 -Force -Scope AllUsers
```
This method also avoided the issue.

**Comment by chuanjiao10** [comment] 2019-04-05 16:31
I have a similar question. Can anyone tell me how to solve it?  @mkht 

In my path there is grep.exe findstr.exe
My ps1 code will be formatted incorrectly.
Ps | grep xxx ---->grep.exe
Findstr ---->findstr.exe

I need block this formatting rule
I want to know that custom rules constrain the file path, and the way it is written.

**Comment by bergmeister** [comment] 2019-04-07 11:08
Today, I could finally get some more information:
First of all, this issue can only be repro-ed within the integrated PowerShell session of the extension. There seem to be 2 issues;

- The PSUseCorrectCasing rule of PSSA is the one that applies the correction but when I attaches the debugger to it, the rule itself has no issue BUT the CommandInfo that it retrieves from PSSA's CommandInfo cache is wrong, it asks for 'gci' but gets the 'get-childitem' CommandInfo of type Cmdlet. This is more complex and needs more time to be understood or fixed 
- I added a "powershell.codeformatting.useCorrectCasing" setting to the vscode extension to allow switching this rule on and off. For some reason the integration of this configuration has broken and the rule cannot be turned off any more (which would be the way to suppress this bug in the meantime). At the time when I created the PR, I tested this manually so something must've changed since then. We should focus our efforts to make this new setting work again and turn it off by default.

**Comment by rjmholt** [comment] 2019-04-10 00:41
> Would you rather prefer new features to be not enabled by default in the first iteration?

Yeah, I think making the feature available in the first iteration and then enabling it in the second iteration is the wisest choice. It's not an uncommon pattern. A good example is the way Rust handles [feature stabilisation](https://rust-lang.github.io/rustc-guide/stabilization_guide.html).

**Comment by bergmeister** [comment] 2019-04-10 21:17
I found the issue that is causing some of the other alias to cmdlet expansion in the `UseCorrectCasing` rule. It is due to [this](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/CommandInfoCache.cs#L59) legacy line that adds CommandInfo objects to the cache where the key is the alias and the value is the looked up value. The rule is then retrieving this incorrect cache value. Removing this legacy code has been a pain for a while now but at least this shows now cases where we should try to change the behaviour and understand better what the code should and should not do. A quick solution might be that the legacy method uses its own cache or we try to get rid of this legacy, I myself originally voted for keeping the legacy behaviour as I feared it might lead to a regression in existing code, but now that we understand the problem better, we can fix it in a way that makes the code better and reduce the area of commonly shared legacy code.

**Comment by SydneyhSmith** [comment] 2019-04-11 21:37
Closing this as it is being tracked with issue https://github.com/PowerShell/PSScriptAnalyzer/issues/1209 
and should be fixed with https://github.com/PowerShell/vscode-powershell/pull/1852 the fix will be out in the next release.

**Closed by SydneyhSmith** 2019-04-11 21:37 UTC
Labels: Area-Code Formatting, Issue-Bug

**Comment by ili101** [comment] 2019-12-19 11:44
So now that you disabled the automatic expending by default so `1..10|%{$_*2}` no longer expends to `1..10 | ForEach-Object { $_ * 2 }` how do I tern this feature back on?
I tried adding to the setting the following line:
`    "powershell.scriptAnalysis.settingsPath": "C:\\Users\\illym\\.vscode\\extensions\\ms-vscode.powershell-preview-2019.12.0\\modules\\PSScriptAnalyzer\\1.18.3\\Settings\\PSGallery.psd1"`
but it didn't work, please help.

**Comment by bergmeister** [comment] 2019-12-19 11:49
@ili101 With the new `powershell.codeFormatting.autoCorrectAliases` setting as per [release notes](https://github.com/PowerShell/vscode-powershell/releases).
I suggest you revert the PSSA settings path change.

**Comment by ili101** [comment] 2019-12-19 17:47
@bergmeister I looked over the setting list twice and missed it somehow... thank you.
Unfortunately after enabling it I found out it's good thing it's off because like the old bugs leading to it being disabled using it still brakes my scripts :/
`& ..\..\Target.ps1` becomes `& Get-..\..\Target.ps1` https://github.com/PowerShell/PSScriptAnalyzer/issues/1369
