### ISSUE TITLE
Extension host terminates when editing code offline

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#372] opened 2016-12-13 14:49 UTC
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: vscode-powershell
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.479
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.479
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Today, I've received a few 'Extension host terminated' errors when I was editing the code while being disconnected from the network (LAN not connected and WiFi adapter disabled). When I hit this it reminded me about issue #353 (if wonder if these are related), although in my case I wasn't trying to run a debugger but just was editing some PS code. 

### Attached Logs

Logs sent over email.

**Comment by daviwil** [comment] 2017-03-24 21:05
Hey @Glober777, do you still see this issue in more recent builds of VS Code and the PS extension?

**Comment by Glober777** [comment] 2017-03-26 12:00
Hey @daviwil, I haven't faced with this issue since I submitted a bug for it, however I haven't been using VSCode offline either.

**Comment by daviwil** [comment] 2017-03-26 15:21
No problem!  I'll try to reproduce this sometime and see if I hit the same issue before I close this bug.

**Comment by BernieWhite** [comment] 2017-04-05 22:42
There is still an issue there @daviwil @Glober777. I don't receive a error message. However the extension reports "Starting PowerShell..." and never completes.

VSCode: 1.10.2
ms-vscode.PowerShell: 0.12.1

PSVersion: 5.1.14393.953
PSEdition: Desktop
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0...}
BuildVersion: 10.0.14393.953
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

vscode-powershell.log
-----
[8:30:47] Language server starting...
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe started --
[8:30:51] Language server started.
Connecting to language service on port 14818...

editorservices.log
-----
6/04/2017 8:30:49 AM [NORMAL] - Method "StartLogging" at line 124 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    PowerShell Editor Services Host v0.12.0.0 starting (pid 7700)...
    
      Host application details:
    
        Name:      Visual Studio Code Host
        ProfileId: Microsoft.VSCode
        Version:   1.0.0
        Arch:      64-bit
    
      Operating system details:
    
        Version: Microsoft Windows NT 10.0.14393.0
        Arch:    64-bit

6/04/2017 8:30:49 AM [NORMAL] - Method "Initialize" at line 214 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    PowerShell runtime version: 5.1.14393.953, edition: Desktop

6/04/2017 8:30:50 AM [NORMAL] - Method "FindPSScriptAnalyzerModule" at line 261 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Analysis\AnalysisService.cs

    PSScriptAnalyzer found at C:\Users\bewhite\.vscode\extensions\ms-vscode.PowerShell-0.12.1\modules\PSScriptAnalyzer\PSScriptAnalyzer.psd1

6/04/2017 8:30:51 AM [NORMAL] - Method "StartLanguageService" at line 158 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Language service started, listening on port 14818

6/04/2017 8:30:51 AM [NORMAL] - Method "StartDebugService" at line 213 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\EditorServicesHost.cs

    Debug service started, listening on port 21345

**Comment by daviwil** [comment] 2017-04-05 23:10
Thanks @BernieWhite!  Your logs look clean, but perhaps we're missing some context without Verbose logs turned on.  Can you turn on verbose logs and try it again?

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

Judging from what I see here, the language server fully starts up but maybe there's some problem preventing the integrated console from showing the initial prompt.

**Comment by claudiospizzi** [comment] 2017-05-29 14:20
Hi David

Same issue on my system. If I start Visual Studio Code with the PowerShell extension when I'm completely offline, like in the train, the PowerShell host is starting forever:
![image](https://cloud.githubusercontent.com/assets/1934246/26553018/055d19b8-448a-11e7-82c9-be3d1a04a8e9.png)

This are the log files:
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/1036026/EditorServices.txt)
[vscode-powershell.txt](https://github.com/PowerShell/vscode-powershell/files/1036025/vscode-powershell.txt)

I can see that the PowerShell Editor Service is listening on 127.0.0.1:23623
![image](https://cloud.githubusercontent.com/assets/1934246/26553089/6921e280-448a-11e7-99a4-7cc374e98a65.png)

And the good old telnet to the local port 23623 works too. So no localhost network issue.

**Comment by giordyb** [comment] 2017-10-21 13:21
I'm having the same issue, is there anything I can do to help troubleshooting this?

**Comment by tylerl0706** [comment] 2018-05-22 17:35
This should be fixed in #1327 since we are no longer relying on TCP sockets in the extension.

**Closed by tylerl0706** 2018-05-22 17:35 UTC
Labels: Issue-Bug, vscode-bug
