### ISSUE TITLE
No Debug Console output when no breakpoint set on script

### ISSUE THREAD

**Issue by mcwidg3t** [PowerShell/vscode-powershell#309] opened 2016-10-05 12:50 UTC
### System Details
Windows 10 Pro Insider Preview (Build 14931)
VS Code 1.6.0-insider
vscode-Powershell 0.7.2

PSVersion                      5.1.14931.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14931.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Running a script in debugger produces no output in the debug console. Setting a breakpoint in the script fixes the issue and output is displayed.

This produces no output.
![image](https://cloud.githubusercontent.com/assets/9482266/19113631/861af99a-8b02-11e6-928e-1840a21a0efe.png)

This produces output.
![image](https://cloud.githubusercontent.com/assets/9482266/19113656/993c6130-8b02-11e6-97fa-8f9bf827f573.png)

**Comment by rkeithhill** [comment] 2016-10-05 14:31
Duplicate of issue #284  We believe this issue will be fixed in an update coming in late October or early November.

**Closed by rkeithhill** 2016-10-05 14:31 UTC

**Comment by daviwil** [comment] 2016-10-05 14:39
Yeah, the script is probably finishing so fast that the output never makes it to the editor.  I'm working on a larger fix for that right now :)  More details (hopefully) later today!

**Comment by mcwidg3t** [comment] 2016-10-05 15:03
Good news, thanks for the update.
