### ISSUE TITLE
Add a default for saveBeforeStart setting

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3338] opened 2021-05-06 20:56 UTC
All you have to do is add:

```json
"configurationDefaults": {
      "[powershell]": {
        "debug.saveBeforeStart": "nonUntitledEditorsInActiveGroup"
      }
    },
```
under `contributes` in the package.json.

here's an example: 
https://github.com/microsoft/vscode/blob/bce4d71f648a963cad905ee0ecc7b353ddd3f199/extensions/markdown-language-features/package.json#L311

Then Untitled file debugging will no longer prompt to save :)

Note: VS Code made this setting "language-aware" literally today. So this will work starting with tomorrow's insider build. There's no downside of this being set for those folks on older versions of VS Code so this change can really go in whenever.

cc @isidorn

**Comment by andschwa** [comment] 2021-05-18 20:47
Is this a duplicate of #3200?

**Comment by SydneyhSmith** [comment] 2021-05-18 20:57
Yep, looks like this would resolve https://github.com/PowerShell/vscode-powershell/issues/3200

**Comment by TylerLeonhardt** [comment] 2021-05-18 22:02
This is a better solution than the other :)

**Comment by andschwa** [comment] 2021-05-20 18:13
@TylerLeonhardt Is this new enough?

29c61570a5b9a669f777bb28b5acd5c37d99edbe
Date: 2021-05-20T05:41:52.156Z (12 hrs ago)

It doesn't seem to be working...maybe I have something else going on.

**Comment by andschwa** [comment] 2021-05-20 18:26
I've double checked what I added to `package.json` against https://github.com/microsoft/vscode/pull/117100...hm, I'll open a draft PR and maybe I erred?

**Comment by TylerLeonhardt** [comment] 2021-05-20 21:09
Yeah it looks like that setting isn't working as expected. @isidorn, any thoughts?

**Comment by isidorn** [comment] 2021-05-21 08:45
Thanks for doing this PR.
There was an issue on the VS Code side that I tackled via https://github.com/microsoft/vscode/commit/779f9876bc0a29fa2cfd811e5c613e05c5ec8e21

So now it should work. I tried it out with.
You can verify with vscode insiders from Monday. Thanks a lot 👏

**Closed** 2021-05-25 01:08 UTC
Labels: Area-Configuration, Issue-Bug, Needs: Attention :wave:, Up-for-Grabs
