### ISSUE TITLE
Powershell: Select Script Analyzer Rules -> edit + confirm ->The PowerShell session has terminated due to an error, would you like to restart it?

### ISSUE THREAD

**Issue by falkheiland** [PowerShell/vscode-powershell#1269] opened 2018-04-14 20:44 UTC
### System Details

- Operating system name and version: Win 10 Home 10.0.16299.0
- VS Code version: 1.22.2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`: 
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.16299.251                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.16299.251                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v: 1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
x64

$pseditor.EditorServicesVersion: ''
code --list-extensions --show-versions:
bierner.markdown-preview-github-styles@0.1.2
DavidAnson.vscode-markdownlint@0.14.1
dbankier.vscode-instant-markdown@1.4.1
DotJoshJohnson.xml@1.9.2
ecmel.vscode-html-css@0.2.0
Equinusocio.vsc-material-theme@1.5.1
formulahendry.terminal@0.0.10
humao.rest-client@0.18.1
kirozen.dokuwiki@1.4.0
luggage66.VBScript@0.0.2
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@1.3.1
ms-vscode.PowerShell@1.6.0
ms-vscode.Theme-MarkdownKit@0.1.4
robertohuertasm.vscode-icons@7.22.0
Shan.code-settings-sync@2.9.0
thenikso.github-plus-theme@1.1.2

$PSVersionTable
```

### Issue Description

1. new file (PS) -> F1 -> Powershell: Select Script Analyzer Rules -> Check New Rule -> Confirm -> The PowerShell session has terminated due to an error, would you like to restart it? (Source Powershell Extension) 

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/1911037/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/1911038/vscode-powershell.log)

**Comment by rkeithhill** [comment] 2018-04-14 20:54
Duplicate of #1155 which has been fixed on master.  This fix should appear in the next update (after 1.6.0).

**Closed by rkeithhill** 2018-04-14 20:54 UTC
