### ISSUE TITLE
Removing breakpoint during runtime causes debugger to hang

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1944] opened 2019-05-04 09:41 UTC
### System Details

System Details Output
```
### VSCode version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64

### VSCode extensions:
aaron-bond.better-comments@2.0.3
aeschli.vscode-css-formatter@1.0.1
alefragnani.project-manager@10.5.1
atomiks.moonlight@0.8.3
CoenraadS.bracket-pair-colorizer-2@0.0.28
daiyy.quick-html-previewer@0.3.0
donjayamanne.githistory@0.4.6
eamodio.gitlens@9.6.3
ecmel.vscode-html-css@0.2.0
emmanuelbeziat.vscode-great-icons@2.1.47
esbenp.prettier-vscode@1.9.0
george-alisson.html-preview-vscode@0.2.5
GitHub.vscode-pull-request-github@0.6.0
GlenBuktenica.unicode-substitutions@2.0.1
hdg.live-html-previewer@0.3.0
HookyQR.beautify@1.5.0
ironmansoftware.powershellprotools@4.5.1
jasonlhy.vscode-browser-sync@1.3.1
johnpapa.read-time@0.2.0
johnpapa.vscode-peacock@2.1.1
Kelvin.vscode-sshfs@1.16.2
liximomo.remotefs@0.0.15
mechatroner.rainbow-csv@1.0.0
monokai.theme-monokai-pro-vscode@1.1.13
ms-vscode.powershell@1.12.1
ms-vscode.powershell-preview@2.0.2
ms-vsts.team@1.149.2
PKief.material-icon-theme@3.7.0
sdras.night-owl@1.1.3
Shan.code-settings-sync@3.2.9
shd101wyy.markdown-preview-enhanced@0.3.13
softwaredotcom.swdc-vscode@0.15.4
WakaTime.vscode-wakatime@2.0.8
yzhang.markdown-all-in-one@2.3.1
Zignd.html-css-class-completion@1.18.0


### PSES version: 1.12.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

When you debug PowerShell and set breakpoints everything works. If debugger hits breakpoint and you remove any breakpoints it will continue to run fine (so it's in a stopped state). However, if you continue debugging and you will remove breakpoint while it's between breakpoints (for example code would have 5-10 seconds till next breakpoint) it will hang session and none of the commands will continue to work. It's like it hits that **removed breakpoint** and you aren't able to continue from there. 

#### Expected Behaviour

Allow removing breakpoints during debug while code is still running, or prevent that. 

#### Actual Behaviour

Hang

### Attached Logs

[1556962441-320c14cb-1b76-4e5b-aa60-20c06ee662971556959894516.zip](https://github.com/PowerShell/vscode-powershell/files/3144199/1556962441-320c14cb-1b76-4e5b-aa60-20c06ee662971556959894516.zip)

**Comment by rjmholt** [comment] 2019-05-06 16:21
This may be a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1494.

**Comment by SydneyhSmith** [comment] 2019-05-14 21:28
Closing as a duplicate #1494

**Closed by SydneyhSmith** 2019-05-14 21:28 UTC
Labels: Triage
