### ISSUE TITLE
breakpoints with run selection (F8) not working

### ISSUE THREAD

**Issue by OneCyrus** [PowerShell/vscode-powershell#455] opened 2017-01-21 08:54 UTC
breakpoints are ignored while only running the selection (F8) and not the full file (F5).

### System Details

- Operating system name and version: W10 1607
- VS Code version: 1.9.0 (Insider from 1/20/17)
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

Setting a breakpoint and running with F5 stops at the breakpoint. Running only the selection (F8) doesn't stop at the breakpoint.

**Comment by daviwil** [comment] 2017-01-21 16:32
That is by design.  F8 does not run the code inside of the debugger.  VS Code only sends breakpoints to me when you use F5 to run your script within the context of the debugger.  I will try to address this with the integrated console work since you should be able to activate the debugger and then use F8 to run script selections.

**Comment by OneCyrus** [comment] 2017-01-23 09:19
thanks for the response! I'm looking for forward to a next version with improved debugging experience. we are getting really close with the feature set to use vscode instead of ISE.

**Comment by daviwil** [comment] 2017-05-19 18:32
This just got fixed in the 1.1.0 update, let me know if it works for you after you upgrade!

**Closed by daviwil** 2017-05-19 18:32 UTC

**Comment by OneCyrus** [comment] 2017-05-19 19:41
just tried it and it looks perfect. no issues.  thank you!

**Comment by daviwil** [comment] 2017-05-19 19:59
Awesome, thanks for confirming!
