### ISSUE TITLE
"PowerShell Launch Current File w/Args Prompt" does not work when VS Live Share extension is enabled

### ISSUE THREAD

**Issue by aetos382** [PowerShell/vscode-powershell#1332] opened 2018-05-22 07:05 UTC
### System Details

- Operating system name and version: Windows 10 Pro 1803 (17134.48)
- VS Code version: 1.23.1
- PowerShell extension version: 1.7.0
- Output from `$PSVersionTable`:

| Name | Value |
| ---- | ----- |
|PSVersion|5.1.17134.48|
|PSEdition|Desktop|
|PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0...}|
|BuildVersion|10.0.17134.48|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v

1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      7      0      0

code --list-extensions --show-versions

ms-vscode.PowerShell@1.7.0
ms-vsliveshare.vsliveshare@0.3.198

$PSVersionTable
same as above
```

### Issue Description

Select the debug configuration "PowerShell Launch Current File w/Args Prompt" and press F5, the error ”command 'SpecifyScriptArgs' not found" may occur and the input box for entering command line is not displayed.

![ss](https://user-images.githubusercontent.com/2569664/40347070-e1ad1c10-5dd9-11e8-841d-9962d856e75a.png)

If the VS Live Share extension is disabled, the input box for entering the command line opens normally.

### Attached Logs

[1526972616-e58721df-185c-44de-8ff1-48588130085c1526972613084.zip](https://github.com/PowerShell/vscode-powershell/files/2025348/1526972616-e58721df-185c-44de-8ff1-48588130085c1526972613084.zip)

**Comment by rkeithhill** [comment] 2018-05-22 20:52
I believe this is a duplicate of #1315 which has been fixed in daily builds but hasn't been released yet.  Hopefully, in the next few weeks we will publish an update with this fix.

**Closed by rkeithhill** 2018-05-22 20:52 UTC

**Comment by aetos382** [comment] 2018-05-23 01:52
No, I think this issue is not a duplicate of #1315.

This problem is that the input box for entering the command line does not open.
Error messages are also different.
And only occurs if the VS Live Share extension is enabled.

In #1315, although the input box is displayed, it can not be executed even if you enter the command line.
Also occur even if the VS Live Share extension is not installed.

**Comment by tylerl0706** [comment] 2018-05-24 21:11
@aetos382 if you don't mind, can you try one of the CI builds here to see if it fixes your issue or not:
https://ci.appveyor.com/project/PowerShell/vscode-powershell/build/artifacts

to install the vsix, open the command pallet in VSCode (ctrl+shift+p) and type "vsix" - you'll see the option.

**Comment by aetos382** [comment] 2018-05-28 02:48
@tylerl0706 Thanks.

I tried with 1.7.0-insiders-549, this problem does not occur.

**Comment by tylerl0706** [comment] 2018-05-28 03:36
Fantastic!

**Comment by asdorius** [comment] 2018-07-03 15:39
Hello everyone,

I just tried with the latest build 1.7.0-insiders-643 from the link you provided @tylerl0706 . This didn't work and so I also tried with the one @aetos382 reported working, 1.7.0-insiders-549.

Both of those have the same problem @aetos382 describes, if VS Live Share is enabled. At least "on my machine"... Could someone take another look at this?

Windows 10 Pro 1803 (17134)
VS Code 1.24.1 

I can provide more system information and/or open another issue if that helps.

**Comment by rkeithhill** [comment] 2018-07-03 16:04
I was just using launch w/args last night on my dev instance - which has LiveShare installed (and enabled).  Or are you actively using LiveShare?

**Comment by asdorius** [comment] 2018-07-03 18:17
This is some weird behavior then. I don't have a clue right now what might be causing it on my end. I'm not sharing something with LiveShare while trying to launch, either.

It's not killing my workflow right now and I don't really have time to dig deeper into this in the next few days. Just wanted to let you guys know that there might still be something off. Of course, if someone wants to investigate I'll be happy to help and provide more info.
