### ISSUE TITLE
Visually collapsing a function doesn't always work correctly

### ISSUE THREAD

**Issue by fldvrees** [PowerShell/vscode-powershell#1662] opened 2018-12-18 09:51 UTC
Issue Type: <b>Bug</b>

The collapsing of a function with a hash inside it doesn't work correctly.

Test program:
```
function foo() {
    $a = @{}
    return $a
}
Write-Host "end"

```
Result after visually collapsing the foo function:
```
function foo() {
    $a = @{}...
Write-Host "end"
```

Expected result:
```
function foo() {...
}
Write-Host "end"
```

Extension version: 1.10.1
VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled

**Comment by DanrwAU** [comment] 2018-12-18 12:36
Can confirm having the same issue 👍 
https://github.com/PowerShell/vscode-powershell/issues/1661

**Comment by SydneyhSmith** [comment] 2018-12-18 17:25
@fldvrees Thanks for reporting this issue, its always helpful to have more examples/repros. I am going to close it as a duplicate of #1631 but please track the issue there. Thanks!

**Closed by SydneyhSmith** 2018-12-18 17:25 UTC
Labels: Area-Folding, Issue-Bug
