### ISSUE TITLE
Editor Services Crashes when Large Amount of Text is Removed

### ISSUE THREAD

**Issue by gabrieljtaylor** [PowerShell/vscode-powershell#1524] opened 2018-09-11 20:03 UTC
## Issue Description ##

I am experiencing frequent and consistent crashes of the PowerShell extension whenever a large amount of text (that includes the last line of a script) is removed, either via deletion or via the text being pasted over. This is happening consistently and always produces the same error in the EditorServices log (see the error below or via the attached file).

I assume this is related to something within the extension parsing the script text and being unhappy with too much being removed at one time (possibly PSScriptAnalyzer?), though the error message doesn't make it clear _what_ action is being performed when the extension crashes.

The EditorServices log shows the following error message:

> 2018-09-11 13:03:06.644 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
>     ProtocolEndpoint message loop terminated due to unhandled exception:
>     
> System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>     Parameter name: index

(Call stack removed from this quote; refer to the attached file for the call stack)

## Attached Logs ##

[PowerShellExtensionCrashLogs.zip](https://github.com/PowerShell/vscode-powershell/files/2372522/PowerShellExtensionCrashLogs.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.27.1|
| PowerShell Extension Version | 1.8.4 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.228|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.228|
|BuildVersion|10.0.17134.228|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|8.5.6|
|mssql|ms-mssql|1.4.0|
|notepadplusplus-keybindings|ms-vscode|1.0.2|
|PowerShell|ms-vscode|1.8.4|
|xml|DotJoshJohnson|2.3.2|;

</details>

**Comment by rjmholt** [comment] 2018-09-11 21:12
Thanks for opening an issue @gabrieljtaylor. This is a duplicate of https://github.com/PowerShell/PowerShellEditorServices/issues/739.

**Closed by rjmholt** 2018-09-11 21:12 UTC
