### ISSUE TITLE
Usage of Region Wrapper Command

### ISSUE THREAD

**Issue by SundeepPaluru** [PowerShell/vscode-powershell#1448] opened 2018-07-24 11:19 UTC
Issue Type: <b>Bug</b>

The usage of of Wrapper Command "region" is depreciated. Post VSCode Update

Regards
-Sundeep

Extension version: 1.8.1
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.80GB (7.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rkeithhill** [comment] 2018-07-24 18:01
Duplicate of #1428 which has been fixed.  Fix will show up in the next release due sometime later this week - I hope.

**Closed by rkeithhill** 2018-07-24 18:01 UTC

**Comment by rjmholt** [comment] 2018-07-27 18:43
@SundeepPaluru  The fix for this should be in the release published this morning
