### ISSUE TITLE
Powershell extension intellisense not came up

### ISSUE THREAD

**Issue by atiedemann** [PowerShell/vscode-powershell#927] opened 2017-06-28 09:16 UTC
Hello @All,

I'm working with vscode to script my Power Shell scripts but the last days my intellisense of Cmdlets or parameters are not working.

I type import-cs and wait until 30 seconds and nothing comes up.
The same way with parameters....

If I completly remove the extension Powershell 1.4.1 than intellisense are working fine but than not Script Analyser is present and so on. :-(

I check the same issue on a different machine with the same result.
I hope anyone can help me.

Many thanks
Arne

### System Details
[1498640602-ed165210-2f74-43fb-ae48-5fddad6c84561498640598532.zip](https://github.com/PowerShell/vscode-powershell/files/1108146/1498640602-ed165210-2f74-43fb-ae48-5fddad6c84561498640598532.zip)

- Operating system name and version: Windows 10 US Enterprise
- VS Code version: 1.13.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1358
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1358
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> code -v
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
PS C:\> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

PS C:\> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.9.1
DotJoshJohnson.xml@1.9.2
ms-vscode.PowerShell@1.4.1
ms-vscode.Theme-MarkdownKit@0.1.4

**Comment by daviwil** [comment] 2017-06-28 14:11
Strangely I don't see any IntelliSense requests getting sent from the extension.  During the session that you sent the logs for, did you try using Ctrl+Space in the file buffer?

**Comment by atiedemann** [comment] 2017-06-28 16:08
Hi David,

Yes of curse! After I press CTRL+Space I wait several seconds (>=30) and nothin happens.
Thanks
Arne

Gesendet von meinem Windows 10 Phone

Von: David Wilson<mailto:notifications@github.com>
Gesendet: Mittwoch, 28. Juni 2017 16:22
An: PowerShell/vscode-powershell<mailto:vscode-powershell@noreply.github.com>
Cc: Arne Tiedemann<mailto:arne.tiedemann@tiedemanns.info>; Author<mailto:author@noreply.github.com>
Betreff: Re: [PowerShell/vscode-powershell] Powershell extension intellisense not came up (#927)


Strangely I don't see any IntelliSense requests getting sent from the extension. During the session that you sent the logs for, did you try using Ctrl+Space in the file buffer?

**Comment by daviwil** [comment] 2017-06-28 17:06
Does this happen in any file you try it in or only in a specific file?  What if you create a new .ps1 file and try typing inside of it?  Just trying to rule out any issues with the specific file or workspace you're working in.

**Comment by atiedemann** [comment] 2017-06-28 17:58
Hi David,

yes this is exacly the same way on each machine.
But when I create a blank file all is fine until I have code of 50 lines.

I think it is depended on ScriptAnalyser because when I resolve any recommandations from Script analyser Intellisense works better but not really fast. If I have from the view of Script analyser a clean Code intellisense need two seconds to display.

In an absolutly clean file intellisense works directly on typing – for a parameter.

I hope this information helps to troubleshoot.

Thanks
Arne


Von: David Wilson [mailto:notifications@github.com]
Gesendet: Mittwoch, 28. Juni 2017 19:07
An: PowerShell/vscode-powershell <vscode-powershell@noreply.github.com>
Cc: Arne Tiedemann <arne.tiedemann@tiedemanns.info>; Author <author@noreply.github.com>
Betreff: Re: [PowerShell/vscode-powershell] Powershell extension intellisense not came up (#927)


Does this happen in any file you try it in or only in a specific file? What if you create a new .ps1 file and try typing inside of it? Just trying to rule out any issues with the specific file or workspace you're working in.

**Comment by coendewit** [comment] 2017-06-30 09:28
Same here on both of my machines. I tried deinstalling the extension, deinstalling VS Code, deinstalling VS Code and deleting extension folder.

Code analyzer works, but intellisense and go to definition do not.

### Logging
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/1114688/vscode-powershell.zip)

### $psversiontable:
Name | Value
---- | -----
PSVersion | 5.0.10586.672
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0...}
BuildVersion | 10.0.10586.672
CLRVersion | 4.0.30319.42000
WSManStackVersion | 3.0
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1

### code -v
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89

### code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.1

**Comment by coendewit** [comment] 2017-06-30 10:49
Just confirming that the powershell project causes the failure. Opening just a subfolder of the project solves the problem.

**Comment by atiedemann** [comment] 2017-07-10 06:04
Thanks for your reply an this workarround.
I think it will be good when the Script Analyser only work at the editing file not on all open files in VScode.

Have a nice day
Arne

**Comment by poortom1004** [comment] 2019-03-29 14:18
I had a brand new install of VS code and the powershell extension.  tab-complete and intellisense didn't work until I read here that having a 50-line script enabled intellisense.

**Comment by scrthq** [comment] 2019-03-29 16:40
@poortom1004 with the new install, you enabled `Editor: Tab Completion` before trying, right? I believe that's disabled by default with new installs. 50-line script shouldn't matter, Intellisense should be immediately available when invoked as far as I'm aware; this issue is also 2 years old:

![image](https://user-images.githubusercontent.com/12724445/55248235-5bd63080-5217-11e9-80b1-4a66bece7631.png)

**Comment by SydneyhSmith** [comment] 2019-04-02 21:30
@poortom1004 @scrthq this is not a known issue, and we are having difficulty reproducing, is there anything in your VScode settings?

**Comment by rjmholt** [comment] 2019-04-03 05:35
> I had a brand new install of VS code and the powershell extension. tab-complete and intellisense didn't work until I read here that having a 50-line script enabled intellisense.

Intellisense should just work; it doesn't depend on the length of the script.

However, it may be that the extension hasn't started. Do you see the Integrated Console in the bottom (not ordinary PowerShell)? You can test this by seeing if the `$psEditor` variable is populated (if it is, then you are in the Integrated Console).

If the Integrated Console is not present, the extension likely hasn't started. To start it you need to open a PowerShell file (open a file with a ps1, psm1 or psd1 extension in VSCode or open a new file and [change its language mode to PowerShell](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file)).

If you definitely have a PowerShell file open and still get no intellisense, it may be you are experiencing a bug. In that case, you should open a new issue and attach your logs.

I'm going to close this issue, since it's an old unrelated issue that is either fixed or captured by a newer issue with better discussion.

**Closed by rjmholt** 2019-04-03 05:35 UTC
Labels: Area-IntelliSense, Issue-Bug, Triage
