### ISSUE TITLE
Play button not working in PowerShell Preview v2021.8.1

### ISSUE THREAD

**Issue by tedsdou** [PowerShell/vscode-powershell#3519] opened 2021-08-23 18:20 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Play button to run script causes terminal to hang.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.59.1
3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.8.0
ms-vscode.powershell-preview@2021.8.1
```

### Steps to Reproduce

Have a script loaded, saved or not and hit the play button.  PowerShell spins up and hangs.  I’ve tried 5.1, 7.1.4 and getting the same result.  Reverting to non-preview, is my current workaround.

### Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/7034025/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/7034027/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/7034028/vscode-powershell.log)

**Comment by andschwa** [comment] 2021-08-23 18:28
Duplicate of #3513, which I actually just successfully tested a fix for.

**Comment by andschwa** [comment] 2021-08-23 21:01
[PowerShell Preview 2021.8.2](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell-preview) will be out in just a few minutes, would you test and confirm this issue has been fully resolved? Thanks!

**Comment by tedsdou** [comment] 2021-08-23 21:06
Tested and verified.  Thanks for the speedy fix!

**Closed** 2021-08-23 22:00 UTC
Labels: Issue-Bug, Area-Debugging, Resolution-Fixed
