### ISSUE TITLE
Temporary PowerShell Integrated Console - not showing Write-Host output

### ISSUE THREAD

**Issue by ohadschn** [PowerShell/vscode-powershell#1758] opened 2019-02-14 13:57 UTC
## Issue Description ##

I'm running the following script:
```powershell
Write-Host "foo"
Write-Warning "some warning"
Write-Error "some error"
```

In the regular PowerShell Integrated Console, it's working as expetced. However, when executing in the temporary console, I'm only getting the error output in _[TEMP] PowerShell Integrated Console_:

```
C:\Users\ohads\Documents\PowerShell\Test-Simple.ps1 : some error
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-Simple.ps1
 ```

I don't have a `%USERROFILE%\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1`, and I don't think it would have been loaded even if it existed: https://github.com/PowerShell/vscode-powershell/issues/1468 (and I don't know what profile would possibly cause this behavior, as `Write-Host `cannot be redirected AFAIK).

This is not 100% consistent, playing with the order and amount of writes to the different streams, I'm getting mixed results - sometimes warnings are printed, sometimes all `Write-Host`, sometimes some of them (the later ones in the script).

## Attached Logs ##

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2865243/logs.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.31.1|
| PowerShell Extension Version | 1.11.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17763.316|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.316|
|BuildVersion|10.0.17763.316|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.11.0|;

I also tried the experimental version, same behavior
</details>

**Comment by SydneyhSmith** [comment] 2019-02-15 22:49
@ohadschn thanks for reporting this, we will have to do more investigation into the root cause. If you notice any patterns as to when this issue occurs please let us know.

**Comment by deadlydog** [comment] 2019-05-06 00:28
Even in the regular PowerShell Integrated Terminal I notice I often have to click into the terminal and hit enter or other keys before any text will show up. I think it's extra noticeable in the temporary console because it creates a new terminal each time you execute code, so you don't have a chance to "enter input" to force the output to show up before it executes code.

I'm using VS Code version 1.33.1 with the PowerShell extension v1.12.1 on Windows 10.

**Comment by cnEUL** [comment] 2019-06-03 07:14
Hello,
in 1.34 i have no output on the temp console. Only if i hit very fast when starting the debug process. on a win 2012 i have a correct running 1.32.4. So i downgraded my 1.34, but the result is the same. So the only diffrence i see is the operating system. Its working on windows 2012, but not on windows 10 - 1809.

**Comment by deadlydog** [comment] 2019-06-05 22:45
I believe the issue is fixed in Windows 10 1902+. Upgrading my Windows version fixed it for me @cnEUL.

**Comment by nithundamodaran** [comment] 2020-02-27 14:15
i have similar observation , am sadly on 1.29 due to some restriction , win 10 build version is 17763

**Comment by strickdd** [comment] 2020-12-11 18:39
Not sure it's related, but I have problems where Write-Output has to be piped to Write-Host in order to display in the PowerShell Integrated Console.

`Get-ADUser strickdd`
Nothing printed

`Get-ADUser strickdd | Write-Host`
Prints out AD information for strickdd

*VSCode About Info*
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363


```
[strickdd] C:\git\Greybeard>$PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment] 2022-03-31 00:37
Looks like this was fixed by updating Windows...please re-open if that's not the case.

**Closed** 2022-03-31 01:00 UTC
Labels: Issue-Bug, Area-Integrated Console, OS-Windows, Resolution-Fixed
