### ISSUE TITLE
VS Code v 1.43.2 keeps throwing an error 3221225725 and restarts Powershell

### ISSUE THREAD

**Issue by Firmbyte** [PowerShell/vscode-powershell#2609] opened 2020-04-03 17:49 UTC
* Slack Community Chat: https://powershell.slack.com (you can sign-up at http://slack.poshcode.org/ for an invite)
* Gitter Chat: https://gitter.im/PowerShell/vscode-powershell

When I open VS Code, even without running any scripts, it throws this error 'Process is terminated due to StackOverflowException'. I click on close the program and I'm presented with the option to restart the PowerShell extension. When it restarts, in a second or two, the same error 3221225725 reoccurrs.

I've tried uninstalling the Powershell extention, uninstalling VS Code, and then reinstalling but error reoccurrs constantly.

`Problem Event Name: CLR20r3
Problem Signature 01: powershell.exe
Problem Signature 02: 10.0.14409.1005
Problem Signature 03: 584a185c
Problem Signature 04: System.Management.Automation
Problem Signature 05: 10.0.14409.1018
Problem Signature 06: 5bac3bc0
Problem Signature 07: 7aae
Problem Signature 08: 0
Problem Signature 09: System.StackOverflowException
OS Version: 6.3.9600.2.0.0.272.7
Locale ID: 1033
Additional Information 1: d34e
Additional Information 2: d34e763b2334d493da43dffdedbbc013
Additional Information 3: 61b9
Additional Information 4: 61b9b0a0f4cfa4e08cfb59e255b305e7`

**Comment by SydneyhSmith** [comment] 2020-04-07 21:04
Thanks @Firmbyte It would be really helpful if you could also attach the diagnostic logs and the payload logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by Firmbyte** [comment] 2020-04-07 21:25
Thank you for your support!

VSCode version
1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64

PowerShell Extensions
ms-vscode.powershell@2020.3.0

Editor version
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      0

PSVersion
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4447049/logs.zip)

**Comment by SydneyhSmith** [comment] 2020-04-16 21:15
Thanks @Firmbyte it would be great to know if you have any settings you are using in VSCode, it would also be great to know if you are opening this in a workspace...it would also be good to know if this re-pros without the PowerShell extension installed...thanks!

**Comment by Firmbyte** [comment] 2020-04-17 20:14
Sydney,
I don't know about the workspace thing?
As far as I remember the settings are default, but if there's a way to set
them to default, I'll do it ?
The extensions I've got installed is PowerShell.

Regards,
*Iain Barnetson*

**Comment by TylerLeonhardt** [comment] 2020-04-17 20:53
@Firmbyte 

> I don't know about the workspace thing?

A workspace is just another word for a folder. Do you have a folder open in VS Code?:

It looks like this (which you can see by clicking the 2 pages button on the left):
![image](https://user-images.githubusercontent.com/2644648/79613061-ab9dc900-80b2-11ea-996b-b08a29a534d0.png)

**Comment by Firmbyte** [comment] 2020-04-18 01:40
I usually work with my script folder open....

[image: image.png]

Regards,
*Iain Barnetson*

**Comment by TylerLeonhardt** [comment] 2020-04-18 01:43
@Firmbyte unfortunately, images in emails don't make their way to the issue! Can you reattach from https://github.com/PowerShell/vscode-powershell/issues/2609

**Comment by Firmbyte** [comment] 2020-04-18 03:46
![2020-04-17_2039](https://user-images.githubusercontent.com/8867903/79627381-4ae7ae00-80fd-11ea-91fe-d5560b527aa2.png)

**Comment by Firmbyte** [comment] 2020-04-18 03:48
jpg attached to case.


Regards,
*Iain Barnetson*

**Comment by SydneyhSmith** [comment] 2020-04-21 21:22
Thanks for the additional information...we are still having trouble determining the root cause, but this type of error can sometimes occur with symbolic link issues...do you have reparse points or UNC shares in this folder your script is in?

**Comment by Firmbyte** [comment] 2020-04-21 21:30
No, none, just a standard local folder structure.

[image: image.png]


Regards,
*Iain Barnetson*

**Comment by TylerLeonhardt** [comment] 2020-04-21 23:13
@Firmbyte looks like you attached another image by email... images in emails don't make their way to the issue! Can you reattach from #2609

**Comment by Firmbyte** [comment] 2020-04-21 23:52
Sorry! I forgot.

Regards,
*Iain Barnetson*

**Comment by Firmbyte** [comment] 2020-04-28 16:43
Just an update: I uninstalled VS Code and rebooted the host. Reinstalled
but still get same errors.


Regards,
*Iain Barnetson*

**Comment by Firmbyte** [comment] 2020-04-28 16:52
This is from the log today, for last 'crash'...

4/28/2020 11:46:40 AM [NORMAL] - Language server starting --
4/28/2020 11:46:40 AM [NORMAL] -     PowerShell executable:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
4/28/2020 11:46:40 AM [NORMAL] - Waiting for session file
4/28/2020 11:46:40 AM [NORMAL] - powershell.exe started.
4/28/2020 11:46:40 AM [NORMAL] -     PowerShell Editor Services args:
Import-Module
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1';
Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId
'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules
@('PowerShellEditorServices.VSCode') -BundledModulesPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules'
-EnableConsoleRepl -LogLevel 'Normal' -LogPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588092400-79f9576e-3e8c-4307-929c-dc31c24d71fd1588092398092\EditorServices.log'
-SessionDetailsPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-6532-774232'
-FeatureFlags @()
4/28/2020 11:46:40 AM [NORMAL] -     PowerShell args: -NoProfile
-NonInteractive -ExecutionPolicy Bypass -Command Import-Module
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1';
Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId
'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules
@('PowerShellEditorServices.VSCode') -BundledModulesPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules'
-EnableConsoleRepl -LogLevel 'Normal' -LogPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588092400-79f9576e-3e8c-4307-929c-dc31c24d71fd1588092398092\EditorServices.log'
-SessionDetailsPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-6532-774232'
-FeatureFlags @()
4/28/2020 11:46:42 AM [NORMAL] - Session file found
4/28/2020 11:46:42 AM [NORMAL] - Registering terminal close callback
4/28/2020 11:46:42 AM [NORMAL] - Registering terminal PID log callback
4/28/2020 11:46:42 AM [NORMAL] - powershell.exe PID: 10764
4/28/2020 11:46:42 AM [NORMAL] - Language server started.
4/28/2020 11:46:42 AM [NORMAL] -
{"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_xq4xnzta.yb5","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_vceatvld.k3i"}
4/28/2020 11:46:42 AM [NORMAL] - Connecting to language service on pipe
\\.\pipe\PSES_xq4xnzta.yb5...
4/28/2020 11:46:42 AM [NORMAL] - Language service connected.
4/28/2020 11:46:44 AM [WARNING] - Invalid Version: null
4/28/2020 11:47:08 AM [NORMAL] - powershell.exe terminated or terminal UI
was closed


Regards,
*Iain Barnetson*

**Comment by SydneyhSmith** [comment] 2020-04-28 21:22
Thanks for the additional info @Firmbyte we dug back into your logs today and think that the issue may be happening in codelens, could you please try disabling it and let us know if your issue still repros....to do this add to your settings: `"editor.codeLens": false`

**Comment by Firmbyte** [comment] 2020-04-29 14:02
I think I've disabled this, in the Settings I've unchecked the 'Controls
whether the editor shows CodeLens' for both User and WorkSpace.
I'll update later, thanks!

Regards,
*Iain Barnetson*

**Comment by Firmbyte** [comment] 2020-04-29 19:39
It's still happening....

4/29/2020 2:32:21 PM [NORMAL] - Language server starting --
4/29/2020 2:32:21 PM [NORMAL] -     PowerShell executable:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
4/29/2020 2:32:21 PM [NORMAL] - powershell.exe started.
4/29/2020 2:32:21 PM [NORMAL] -     PowerShell args: -NoProfile
-NonInteractive -ExecutionPolicy Bypass -Command Import-Module
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1';
Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId
'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules
@('PowerShellEditorServices.VSCode') -BundledModulesPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules'
-EnableConsoleRepl -LogLevel 'Normal' -LogPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588188741-1cd2433f-60a8-4680-a59f-3e7da3ceb88b1588166959498\EditorServices.log'
-SessionDetailsPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-4424-511188'
-FeatureFlags @()
4/29/2020 2:32:21 PM [NORMAL] - Waiting for session file
4/29/2020 2:32:21 PM [NORMAL] -     PowerShell Editor Services args:
Import-Module
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1';
Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId
'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules
@('PowerShellEditorServices.VSCode') -BundledModulesPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules'
-EnableConsoleRepl -LogLevel 'Normal' -LogPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588188741-1cd2433f-60a8-4680-a59f-3e7da3ceb88b1588166959498\EditorServices.log'
-SessionDetailsPath
'c:\Users\ibarnetson\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-4424-511188'
-FeatureFlags @()
4/29/2020 2:32:23 PM [NORMAL] - Session file found
4/29/2020 2:32:23 PM [NORMAL] - Registering terminal close callback
4/29/2020 2:32:23 PM [NORMAL] - Registering terminal PID log callback
4/29/2020 2:32:23 PM [NORMAL] - powershell.exe PID: 12576
4/29/2020 2:32:23 PM [NORMAL] - Language server started.
4/29/2020 2:32:23 PM [NORMAL] -
{"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_1h43ese2.ghc","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_g2alrsrc.3ea"}
4/29/2020 2:32:23 PM [NORMAL] - Connecting to language service on pipe
\\.\pipe\PSES_1h43ese2.ghc...
4/29/2020 2:32:23 PM [NORMAL] - Language service connected.
4/29/2020 2:32:25 PM [WARNING] - Invalid Version: null
4/29/2020 2:37:14 PM [NORMAL] - powershell.exe terminated or terminal UI
was closed
4/29/2020 2:37:21 PM [NORMAL] - PSIC is not active terminal. Running in
active terminal using 'runSelectedText'
4/29/2020 2:37:25 PM [NORMAL] - PSIC is not active terminal. Running in
active terminal using 'runSelectedText'

Regards,
*Iain Barnetson*

**Comment by Firmbyte** [comment] 2020-04-29 19:54
Just reoccurred 3 times in quick succession.
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4554223/logs.zip)

**Comment by TylerLeonhardt** [comment] 2020-04-30 18:00
@Firmbyte can you please follow the 
instuctions here for attaching the logs: 

[attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

it includes setting two VS Code settings so we can get diagnostic logs that will help us debug this further.

**Comment by Firmbyte** [comment] 2020-05-03 11:56
I couldn't find this portion: "Provide Language Server Protocol payload
logs"
All the other information was already provided and hasn't changed.
PS D:\Scripts> code --list-extensions --show-versions
ms-vscode.powershell@2020.4.0

Logs from the extensions attached.

Regards,
*Iain Barnetson*

**Comment by andschwa** [comment] 2021-04-13 22:45
This VS Code version is now very out of date, marking as resolved.

**Comment by Firmbyte** [comment] 2021-04-13 23:45
same problem occurring on every version since 1.43.2, up to and including the 1.54.3 that I'm using now.

**Comment by SydneyhSmith** [comment] 2021-04-27 21:01
Thanks @Firmbyte could you please attach a GIF of the crash if possible

**Closed** 2021-08-19 19:01 UTC
Labels: Issue-Bug, Needs: Repro Info 🤔
