### ISSUE TITLE
PowerShell module fail to start in 1.43.2 .

### ISSUE THREAD

**Issue by mraj0401** [PowerShell/vscode-powershell#2594] opened 2020-03-30 18:17 UTC
Hello - 
I have updated my VS Code today to Version: 1.43.2 (system setup) and other details as follows,
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600

When I start the Powershell Module I got error like as below ..

3/30/2020 1:07:06 PM [NORMAL] - powershell.exe started.
3/30/2020 1:07:06 PM [NORMAL] - Waiting for session file
3/30/2020 1:09:06 PM [NORMAL] - Error occurred retrieving session file
3/30/2020 1:09:06 PM [NORMAL] - Language server startup failed.
3/30/2020 1:09:06 PM [ERROR] - The language service could not be started: 
3/30/2020 1:09:06 PM [ERROR] - Timed out waiting for session file to appear.

In windows event viewer , I got log like below ...

A privileged service was called.

Subject:
	Security ID:		
	Account Name:		
	Account Domain:		
	Logon ID:		0x30D24E

Service:
	Server:	Security
	Service Name:	-

Process:
	Process ID:	0x2454
	Process Name:	C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

Service Request Information:
	Privileges:		SeTcbPrivilege

Is there any additional steps to enable PS module in VS C?
Thanks and appreciate your help guys .... 

With Thanks,
Raj

**Comment by SydneyhSmith** [comment] 2020-03-31 21:06
Hi @mraj0401 it would be helpful if you could also provide diagnostic logging --instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by mraj0401** [comment] 2020-03-31 22:27
Hi @SydneyhSmith , Thanks for pitch in on my issue .. here is the Diagnostic log details 

3/31/2020 5:21:31 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\logs\1585693291-78446967-8fab-49eb-a44f-0fe39e7e47c01585693193144\EditorServices.log' -SessionDetailsPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-14536-138965' -FeatureFlags @() 
3/31/2020 5:21:31 PM [NORMAL] - Language server starting --
3/31/2020 5:21:31 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\MRaj0401\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\logs\1585693291-78446967-8fab-49eb-a44f-0fe39e7e47c01585693193144\EditorServices.log' -SessionDetailsPath 'c:\Users\user01\.vscode\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-14536-138965' -FeatureFlags @() 
3/31/2020 5:21:31 PM [NORMAL] -     PowerShell executable: C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
3/31/2020 5:21:31 PM [NORMAL] - powershell.exe started.
3/31/2020 5:21:31 PM [NORMAL] - Waiting for session file
3/31/2020 5:23:31 PM [NORMAL] - Error occurred retrieving session file
3/31/2020 5:23:31 PM [NORMAL] - Language server startup failed.
3/31/2020 5:23:31 PM [ERROR] - The language service could not be started: 
3/31/2020 5:23:31 PM [ERROR] - Timed out waiting for session file to appear.

**Comment by mraj0401** [comment] 2020-04-01 20:13
Hello - Today I did some research on this issue and I captured some VS code / PS startup log and I attached 
[VSC_PS_StartUP_error.txt](https://github.com/PowerShell/vscode-powershell/files/4417369/VSC_PS_StartUP_error.txt)

**Comment by TylerLeonhardt** [comment] 2020-04-02 17:44
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2526

Can you please send me your event logs for Windows PowerShell? I wonder if that has anything important... ALSO If you see the issue & you have an anti-virus, can you please check the logs of your AV for anything suspicious?

Thanks for your patience... this has been very hard to troubleshoot without a repro on my end.

**Comment by mraj0401** [comment] 2020-04-02 21:18
Yes I reverted the PS version in VS Code as per below link ..and it worked ... 

https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-596127948

**Closed** 2020-04-03 22:00 UTC
Labels: Resolution-Duplicate
