### ISSUE TITLE
$Error '__Invoke-ReadLineForEditorServices' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2767] opened 2020-06-14 14:03 UTC
Issue Type: <b>Bug</b>

When using the debugger the $Error variable get filled with records of the error:
```
ErrorRecord                 : The term '__Invoke-ReadLineForEditorServices' is not recognized as the name of a cmdlet, function, script file, or operable program.
                              Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
CommandName                 : __Invoke-ReadLineForEditorServices
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output,
                              PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output,
                              PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.InvokeWithDebugger(IEnumerable`1 input, IList`1 output, PSInvocationSettings settings,
                              Boolean invokeMustRun)
                                 at System.Management.Automation.ScriptDebugger.ProcessCommand(PSCommand command, PSDataCollection`1 output)
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.PowerShell5Operations.ExecuteCommandInDebugger[TResult](PowerShellConte
                              xtService powerShellContext, Runspace currentRunspace, PSCommand psCommand, Boolean sendOutputToHost, Nullable`1& debuggerResumeAction) in
                              D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\Session\PowerShell5Operations.cs:line 61
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandInDebugger[TResult](PSCommand psCommand, Boolean
                              sendOutputToHost) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 1955
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder
                              errorMessages, ExecutionOptions executionOptions) in
                              D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 713
Message                     : The term '__Invoke-ReadLineForEditorServices' is not recognized as the name of a cmdlet, function, script file, or operable program.
                              Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Data                        : {}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
```

Can lead to unexpected behavior when using `$Error[0]` or `Get-Error -Newest 1` and getting different results when using the debugger or not

![Error](https://user-images.githubusercontent.com/6960531/84595436-8cc47480-ae60-11ea-90af-9ebc786cd8f0.gif)
[1592142049-f665f186-1ae9-4187-89fd-2a5a00a5d59b1592141717209.zip](https://github.com/PowerShell/vscode-powershell/files/4776518/1592142049-f665f186-1ae9-4187-89fd-2a5a00a5d59b1592141717209.zip)
 

Extension version: 2020.6.1
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (2 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by SydneyhSmith** [comment] 2020-06-16 21:18
Thanks @ili101 for the detailed information, we agree that this is an issue--I will mark this as a duplicate of https://github.com/PowerShell/PowerShellEditorServices/issues/1296

**Closed** 2020-06-19 22:00 UTC
Labels: Resolution-Duplicate

**Comment by mono808** [comment] 2020-09-29 10:38
still getting the $error array filled with this error in vs code debugger. no solution yet?

**Comment by SydneyhSmith** [comment] 2020-09-29 20:54
@mono808 you can track the progress of this work with this issue PowerShell/PowerShellEditorServices#1296

**Comment by Kupferschmid** [comment] 2020-10-27 11:10
$Error '__Invoke-ReadLineForEditorServices'  Issue still exists!

**Comment by cvillegashak** [comment] 2020-12-28 18:13
Issue still exists.

**Comment by corbob** [comment] 2020-12-29 07:38
To any in the future that may find this issue due to searching the error: If PowerShell/PowerShellEditorServices#1295 is still open, then this issue will exist. It is unfortunate, but there is currently nothing that can be done in this issue, so commenting that it still exists does little to resolve the issue.

**Comment by TysonP** [comment] 2021-03-17 21:48
I found that defining a nothing function with the same name has eliminated the symptom for me. 

**function __Invoke-ReadLineForEditorServices {""}**
