### ISSUE TITLE
Preview + Stable Extension: Enter does not work in IC with PSv7.1 preview 7

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#2943] opened 2020-09-10 14:34 UTC
### System Details

System Details Output
```
### VSCode version: 1.48.2 a0479759d6e9ea56afa657e454193f72aef85bd0 x64

### VSCode extensions:
2gua.rainbow-brackets@0.0.6
adamhartford.vscode-base64@0.1.0
amazonwebservices.aws-toolkit-vscode@1.13.0
andreaslenzen.vbscript-language-server-client@1.1.0
Azurite.azurite@3.8.0
ban.spellright@3.0.52
bbenoist.vagrant@0.5.0
DavidAnson.vscode-markdownlint@0.36.3
donjayamanne.githistory@0.6.9
eamodio.gitlens@10.2.2
Equinusocio.vsc-community-material-theme@1.4.2
Equinusocio.vsc-material-theme@33.0.0
equinusocio.vsc-material-theme-icons@1.2.0
eriklynd.json-tools@1.0.2
golang.go@0.16.2
GrapeCity.gc-excelviewer@3.0.40
hashicorp.terraform@2.2.3
hediet.vscode-drawio@0.7.2
mindaro-dev.file-downloader@1.0.0
mindaro.mindaro@0.1.120200825
ms-azure-devops.azure-pipelines@1.174.2
ms-azuretools.vscode-azureappservice@0.18.0
ms-azuretools.vscode-azurefunctions@0.24.0
ms-azuretools.vscode-docker@1.5.0
ms-dotnettools.csharp@1.23.2
ms-dotnettools.vscode-dotnet-runtime@0.1.2
ms-kubernetes-tools.vscode-aks-tools@0.0.6
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
ms-mssql.mssql@1.9.0
ms-python.python@2020.8.108011
ms-vscode.azure-account@0.9.2
ms-vscode.azurecli@0.5.0
ms-vscode.cpptools@0.29.0
ms-vscode.powershell-preview@2020.7.0
msazurermtools.azurerm-vscode-tools@0.12.0
PKief.material-icon-theme@4.3.0
redhat.vscode-xml@0.13.0
redhat.vscode-yaml@0.10.1
Shan.code-settings-sync@3.4.3
tht13.html-preview-vscode@0.2.5
twxs.cmake@0.0.17
Tyriar.shell-launcher@0.4.1
vitaliymaz.vscode-svg-previewer@0.6.0
vscoss.vscode-ansible@0.5.2
wayou.vscode-todo-highlight@1.0.4
wingrunr21.vscode-ruby@0.27.0
yzane.markdown-pdf@1.4.4


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

When typing in the IC directly, Enter key does not work anymore

![doesnotwork](https://user-images.githubusercontent.com/10071039/92745427-a8b5b480-f382-11ea-8c2b-5b8537956458.gif)

**I don't have this issue with 7.0.3**

I captured the logs while pressing enter a bunch and then Ctrl+C

#### Expected Behaviour

Should work.

#### Actual Behaviour

Does not work

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/5202389/vscode-powershell.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5202390/StartEditorServices.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5202391/EditorServices.log)

**Comment by rjmholt** [comment] 2020-09-10 15:41
I'm not able to reproduce this myself, but we'll try on macOS as well

![enter](https://user-images.githubusercontent.com/7009879/92756080-530ce800-f341-11ea-8ec6-cf9af85726c8.gif)

**Comment by bgelens** [comment] 2020-09-10 17:27
Thanks @rjmholt! FYI, no change when not loading my profile. Also tried the stable PowerShell extension, same issue

**Comment by TylerLeonhardt** [comment] 2020-09-10 18:06
you can go back to preview6 or `powershell.integratedConsole.useLegacyReadLine` still works until we get to the bottom of this.

**Comment by bgelens** [comment] 2020-09-10 18:10
I'm fine working with 7.0.3 daily. Noticed it as I'm preparing a demo for tomorrow "whats new in 7.1" :)

I'll leave my setup as is in case you require some additional info / actions from my side

**Comment by TylerLeonhardt** [comment] 2020-09-10 18:12
Thanks for bringing this to our attention!

**Comment by bgelens** [comment] 2020-09-10 19:31
Small update: If I hit enter right after the IC is available (started), it will work a couple of times (like in a 1 sec window)

**Comment by TylerLeonhardt** [comment] 2020-09-16 01:57
I've been swamped with Ignite stuff but I'll focus on this right after that's done.

**Comment by TylerLeonhardt** [comment] 2020-09-18 00:50
This appears to be an underlying issue with .NET: https://github.com/dotnet/runtime/issues/42418

**Comment by TylerLeonhardt** [comment] 2020-09-19 03:57
They ack'd. Closing this as external. .NET 5 RC.2 will likely have this sorted. This could be the next preview of PowerShell or the one after. cc @SteveL-MSFT @daxian-dbw @rjmholt

**Closed** 2020-09-19 03:58 UTC
Labels: Area-Integrated Console, Issue-Bug, Resolution-External

**Comment by bgelens** [comment] 2020-10-21 20:01
@TylerLeonhardt @SteveL-MSFT @daxian-dbw  @rjmholt Can confirm the problem is resolved with RC2!
