### ISSUE TITLE
Autocomplete removes backslash from start of UNC path

### ISSUE THREAD

**Issue by msm-fc** [PowerShell/vscode-powershell#2211] opened 2019-09-24 23:06 UTC
Issue Type: <b>Bug</b>

When a path is suggested in autocomplete, pressing Tab to autocomplete or clicking on the suggestion will remove the first of the two required backslashes of the UNC path. 

Extension version: 2019.9.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by corbob** [comment] 2019-09-25 03:43
I think this is a duplicate of #2116 which might need the vscode-bug tag removed, as it appears it was determined that it's an issue with the textmate specification that vscode follows, and so the extension needs to work around it itself 🤷‍♂

**Comment by TylerLeonhardt** [comment] 2019-09-25 05:37
@corbob is correct. Thanks for opening this though!

I have a general idea for a fix, just have to sit down and do it.

**Comment by TylerLeonhardt** [comment] 2019-09-25 05:37
Closing as duplicate of #2116

**Closed by TylerLeonhardt** 2019-09-25 05:37 UTC
Labels: Needs: Triage :mag:
