### ISSUE TITLE
Unable to step into class in debug time or hit breakpoint in class

### ISSUE THREAD

**Issue by rudolfvesely** [PowerShell/vscode-powershell#1752] opened 2019-02-08 20:28 UTC
Hi all,

I hope this will be helpful. Please let me know if you have any questions.

- Operating system name and version: Linux, KDE Plasma 5
- VS Code version: 1.31
- PowerShell extension version: 1.11.0

```
### VSCode version: 1.31.0 x64

### VSCode extensions:
adammaras.overtype@0.2.0
ms-vscode.PowerShell@1.11.0
yzhang.markdown-all-in-one@1.7.0


### PSES version: 

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Linux 4.19
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description
I'm unable to step into class in debug time or hit breakpoint in class. This wasn't problem in previous versions.

#### How to test
Create function and class
Instantiate object in function
Try to step into line where you instantiate object, for example `[ClassName]::new('foor', 'bar')`

#### Expected Behaviour
Step into

#### Actual Behaviour
Nothing

**Comment by rudolfvesely** [comment] 2019-02-09 09:53
I've just tested that the bug is not present in VSCode 1.30.2. In other words version 1.31.0 broke something in the PowerShell extension 1.11 and 2.0 Preview.

**workaround**: downgrade VSCode

**Comment by AndyP2** [comment] 2019-02-09 19:34
I wonder if this is related to issue #1750, which also suggests a change made in vscode 1.31 has broken stepping through code in the powershell debugger.

**Comment by rudolfvesely** [comment] 2019-02-10 06:58
Good point Andy, the class that I mentioned is "used" using `using module` so it's in different directory.

**Comment by SydneyhSmith** [comment] 2019-02-11 20:06
Thanks for reporting this @rudolfvesely it would also be really helpful if you could attach any logs you have when this occurs, instructions for how to do this are [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by SydneyhSmith** [comment] 2019-02-12 22:09
Going to close this as a duplicate of #1750 please follow that issue for any developments, thanks!

**Closed by SydneyhSmith** 2019-02-12 22:09 UTC
Labels: Area-Debugging, Triage, vscode-bug
