### ISSUE TITLE
Write-Output does not display

### ISSUE THREAD

**Issue by anwather** [PowerShell/vscode-powershell#151] opened 2016-04-20 02:52 UTC
Example code below - nothing appears in the debug console until I set and disable a breakpoint. Write-Host works fine.
Function Get-MyProcess
{

$x = Get-Process -Name TabTip
Write-Output "$($x.ProcessName)"
}

Get-MyProcess

**Comment by anwather** [comment] 2016-04-21 01:35
[Bug recording.pptx](https://github.com/PowerShell/vscode-powershell/files/229084/Bug.recording.pptx)

**Comment by rkeithhill** [comment] 2016-04-21 01:44
We believe we know what the issue is.  A fix for this should be forthcoming in a 0.5.1 release.

**Comment by daviwil** [comment] 2016-04-25 15:01
Yep!  This is something caused by some recent changes in VS Code's debugger interface.  We're pretty sure that this will be fixed in 0.6.0 (to be released in a week or less).

**Comment by daviwil** [comment] 2016-05-11 00:01
Just verified that this is fixed for 0.6.0.  I'll close this bug once the update has shipped.

**Comment by daviwil** [comment] 2016-05-13 01:57
0.6.0 is now released!  Let me know if you run into any further trouble.

**Closed by daviwil** 2016-05-13 01:57 UTC
Labels: bug

**Comment by dsmeltz** [comment] 2016-09-06 13:57
v0.7.2

I'm using two Write-Output calls immediately after calling Invoke-RestMethod.  The two statements output to the console as expected in ISE.  When running the same script in VS Code, the two Write-Ouput statements don't output anything unless I set a break point on the first one and step over them one at a time.  These two statements are at the end of the file.

**Comment by daviwil** [comment] 2016-09-06 17:27
Hey @dsmeltz, this is a known issue that we are investigating.  You can subscribe to this issue to be notified of future updates: https://github.com/PowerShell/PowerShellEditorServices/issues/138

**Comment by szotyii** [comment] 2016-09-14 10:09
v0.7.2
Any luck with the investigation?
Thanks!

**Comment by daviwil** [comment] 2016-09-14 14:37
I've got a better way in mind to solve this problem, going to try and make it happen for the next big release (0.8.0)!

**Comment by szotyii** [comment] 2016-09-17 13:28
When can we expect the next big release?
Thanks!

**Comment by daviwil** [comment] 2016-09-17 14:39
I'm shooting for the first couple weeks of October.
