### ISSUE TITLE
2020.1.0 Preview: Language Server could not be started (5.1.17763.771)

### ISSUE THREAD

**Issue by fbehrens** [PowerShell/vscode-powershell#2426] opened 2020-01-20 10:21 UTC
```
1/20/2020 11:09:18 AM [NORMAL] - Visual Studio Code v1.41.1 64-bit
1/20/2020 11:09:18 AM [NORMAL] - PowerShell Extension v2020.1.0
1/20/2020 11:09:18 AM [NORMAL] - Operating System: Windows 64-bit
1/20/2020 11:09:18 AM [NORMAL] - Language server starting --
1/20/2020 11:09:18 AM [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
1/20/2020 11:09:18 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.1.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\logs\1579514958-4f178636-5a4c-46fe-aa4d-a3f9e92fd2aa1579514947453\EditorServices.log' -SessionDetailsPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\sessions\PSES-VSCode-8212-474545' -FeatureFlags @('PSReadLine') 
1/20/2020 11:09:18 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.1.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\logs\1579514958-4f178636-5a4c-46fe-aa4d-a3f9e92fd2aa1579514947453\EditorServices.log' -SessionDetailsPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-preview-2020.1.0\sessions\PSES-VSCode-8212-474545' -FeatureFlags @('PSReadLine') 
1/20/2020 11:09:49 AM [NORMAL] - powershell.exe terminated or terminal UI was closed
1/20/2020 11:11:33 AM [NORMAL] - Language server startup failed.
1/20/2020 11:11:33 AM [ERROR] - The language service could not be started: 
1/20/2020 11:11:33 AM [ERROR] - Timed out waiting for session file to appear.
```

`C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe` is 5.1.17763.771

The normal (not Preview) Extensin is working:
```
1/20/2020 11:18:55 AM [NORMAL] - Visual Studio Code v1.41.1 64-bit
1/20/2020 11:18:55 AM [NORMAL] - PowerShell Extension v2020.1.0
1/20/2020 11:18:55 AM [NORMAL] - Operating System: Windows 64-bit
1/20/2020 11:18:55 AM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
1/20/2020 11:18:55 AM [NORMAL] - Language server starting --
1/20/2020 11:18:55 AM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
1/20/2020 11:18:55 AM [NORMAL] -     args: c:\tools\VSCode\data\extensions\ms-vscode.powershell-2020.1.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.1.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-2020.1.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-2020.1.0\logs\1579515535-7b48009e-ee37-4a55-b7ed-74ecfedd63181579515527746\EditorServices.log' -SessionDetailsPath 'c:\tools\VSCode\data\extensions\ms-vscode.powershell-2020.1.0\sessions\PSES-VSCode-8212-300155' -FeatureFlags @('PSReadLine')
1/20/2020 11:19:00 AM [NORMAL] - powershell.exe started, pid: 17884
1/20/2020 11:19:06 AM [NORMAL] - Language server started.
1/20/2020 11:19:06 AM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_amcx2hyd.12v","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_2fcb4hgb.zpe"}
1/20/2020 11:19:06 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_amcx2hyd.12v...
1/20/2020 11:19:06 AM [NORMAL] - Language service connected.
```

**Comment by doug4772** [comment] 2020-01-20 14:29
I'm having the same issue.  Logged here: https://github.com/PowerShell/vscode-powershell/issues/2417

**Comment by SydneyhSmith** [comment] 2020-01-21 21:47
@fbehrens thanks for opening this issue I am going to mark it as a dupe of #2417 could you please copy your information into that issue? It would be great if you could also provide diagnostic logging 
--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)...also please include what version of windows you are on...thanks!

**Closed** 2020-01-22 22:00 UTC
Labels: Resolution-Duplicate
