### ISSUE TITLE
PowerShell Editor Services fails to initialize when PowerShell prompts user to accept script execution

### ISSUE THREAD

**Issue by domhnal** [PowerShell/vscode-powershell#522] opened 2017-03-03 12:50 UTC
### System Details

- Operating system name and version: Win 10 Pro x64
- VS Code version:  1.10.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
I get the error 'PowerShell could not be started' when I open a PowerShell script. 

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/816780/logs.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by domhnal** [comment] 2017-03-03 12:58
Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       AllSigned
   UserPolicy       AllSigned
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned

**Comment by daviwil** [comment] 2017-03-03 14:34
Hey @domhnal, sorry for the trouble.  The issue is caused when the language service tries to change the current ExecutionPolicy on a machine with a group policy override of the ExecutionPolicy.  I'll get this fixed soon.

Related issues:

- https://github.com/PowerShell/PowerShellEditorServices/issues/192
- https://github.com/PowerShell/vscode-powershell/issues/454

**Comment by daviwil** [comment] 2017-03-24 20:54
Hey @domhnal, does this issue still show up in the latest release of the PowerShell extension (0.11.0)?  I think I might have fixed it, would be good to know what you see now.  Thanks!

**Comment by domhnal** [comment] 2017-03-28 02:30
Hi David,

It seems to be working now, but it took a bit of extra work.  I resigned the PS1 script in the extension and manually imported the modules in the extension so I could accept the security warning.  It seems to be working best kind now.

Cheers,
Bruce

Sent from Windows Mail

**Comment by daviwil** [comment] 2017-03-28 15:27
Hmmm...  In theory it shouldn't be necessary for you to re-sign the startup script since it's signed as Microsoft.  Are there particularly stringent security policies in place on your machine?  Interesting to know that you needed to accept the import of the module before it could be loaded in the extension.  Currently this wouldn't happen by default because I'm running PowerShell with the NonInteractive flag.  Maybe there's some way I could detect this state and prompt correctly?

**Comment by domhnal** [comment] 2017-03-28 17:54
Once I loaded the PowerShell extension, the PowerShell process that would start in the terminal window of vscode would immediately stop.  Re-signing the Start-EditorServices script got me a bit further, but then I got some actual error messages.  I then opened a PowerShell prompt and manually imported the new modules and selected always trust at the security warning.  When I restarted vscode it all worked.  I’ve since uninstalled and reinstalled the extension and without having to do anything extra, it still works.  Looks like you need to check if running signed code requires any additional approval and prompt if required.

Bruce
Sent from my Windows 10 phone

**Comment by rjmholt** [comment] 2020-03-17 18:25
Closing as defunct

**Closed by rjmholt** 2020-03-17 18:25 UTC
Labels: Issue-Bug
