### ISSUE TITLE
Intellisense doesn't work after pressing F5 and not pressing ENTER in console

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2439] opened 2020-01-26 10:33 UTC
Issue Description
=====

This one is pretty weird and I understand that title may not be really describing it. Basically take any code run it with F5 and after the code is done IntelliSense won't work right away. You need to go to console and press ENTER and it comes back. It may be triggered with something else as well just haven't noticed with what but I've been hitting this issue more and more now. 

![F5Bug2](https://user-images.githubusercontent.com/15063294/73133907-76dc2180-402f-11ea-9849-b6f017eb4e6c.gif)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

[1580034495-7dee34c4-5a4b-4eb9-b0e7-bd1faa1a6f881580034316619.zip](https://github.com/PowerShell/vscode-powershell/files/4113347/1580034495-7dee34c4-5a4b-4eb9-b0e7-bd1faa1a6f881580034316619.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.41.1|
| PowerShell Extension Version | 2020.1.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.1|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|codesnap|adpyke|1.0.27|
|excel-to-markdown-table|csholmq|1.2.0|
|gistfs|vsls-contrib|0.0.48|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.0|
|html-preview-vscode|george-alisson|0.2.5|
|markdown-all-in-one|yzhang|2.7.0|
|markdown-preview-enhanced|shd101wyy|0.5.1|
|markdown-shortcuts|mdickin|0.12.0|
|material-icon-theme|PKief|3.9.2|
|moonlight|atomiks|0.10.0|
|nebula-theme|ChirtleLovesDolls|1.3.2|
|pdf|tomoki1207|0.5.1|
|powershell-preview|ms-vscode|2020.1.0|
|project-manager|alefragnani|10.10.0|
|reg|ionutvmi|1.0.1|
|synthwave-x-fluoromachine|webrender|0.0.9|
|theme-monokai-pro-vscode|monokai|1.1.14|
|vscode-cloak|johnpapa|0.2.0|
|vscode-color|anseki|0.4.5|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-power-mode|hoovercj|2.2.0|
|vscode-pull-request-github|GitHub|0.14.0|
|vscode-wakatime|WakaTime|2.2.1|
|vscode-yaml|redhat|0.6.1|
|xml|DotJoshJohnson|2.5.0|

**Comment by rjmholt** [comment] 2020-01-27 19:23
I suspect this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2364. Not sure why it occurs yet, but basically the pipeline isn't made available for intellisense immediately after debugging finishes. Your insight about prompt cancellation might be important actually.

**Closed** 2020-01-28 20:00 UTC
Labels: Resolution-Duplicate
