### ISSUE TITLE
Debugging hangs if script has syntax errors

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#2713] opened 2020-05-19 18:17 UTC
### System Details

System Details Output
```
### VSCode version: 1.45.1 5763d909d5f12fe19f215cbfdd29a91c0fa9208a x64

### VSCode extensions:
alefragnani.Bookmarks@11.2.0
anseki.vscode-color@0.4.5
[1589910870-8c153114-8590-4b1f-a3af-f31bcd83a35a1589910867420.zip](https://github.com/PowerShell/vscode-powershell/files/4652337/1589910870-8c153114-8590-4b1f-a3af-f31bcd83a35a1589910867420.zip)
[1589911142-471de95c-9aa2-4be8-a228-d5161deca21b1589911139246.zip](https://github.com/PowerShell/vscode-powershell/files/4652338/1589911142-471de95c-9aa2-4be8-a228-d5161deca21b1589911139246.zip)


austin.code-gnu-global@0.2.2
CoenraadS.bracket-pair-colorizer@1.0.61
DotJoshJohnson.xml@2.5.0
DougFinke.vscode-PSStackoverflow@0.0.2
Gruntfuggly.todo-tree@0.0.175
mechatroner.rainbow-csv@1.7.0
ms-vscode-remote.remote-wsl@0.44.2
ms-vscode.cpptools@0.28.0
ms-vscode.powershell@2020.4.0
ms-vscode.powershell-preview@2020.5.0
msjsdiag.debugger-for-chrome@4.12.7
nobuhito.printcode@3.0.0
oderwat.indent-rainbow@7.4.0
RandomFractalsInc.geo-data-viewer@1.9.0
tht13.html-preview-vscode@0.2.5
VisualStudioExptTeam.vscodeintellicode@1.2.7
yzhang.markdown-all-in-one@2.8.0
zovorap.ab-html-formatter@0.0.2


### PSES version: 2.1.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

### Issue Description

When I start a debugging session for a PowerShell script that contains a syntax error, such as:

````
# this script has a syntax error, I know!

@[PSCustomObject]@{
    Name = Value
    Name2 =
}
````

the session hangs.

If I manage to break it using Ctrl+C, the Terminal pane endlessly fills up with (?) prompts -- see video ![2020-05-19-19-49-39](https://user-images.githubusercontent.com/12860484/82362968-7831bf80-9a0d-11ea-962c-c070dc97572b.gif)

[Edit: with Windows PowerShell 5.1 this quickly ends with `Process is terminated due to StackOverflowException.`]

This repro's both with the release (2020.4.0) and preview (2020.5.0) versions of the PowerShell extension.

#### Expected Behaviour

The debugging session should report that the script has a syntax error and stop.

#### Actual Behaviour

The session hangs.

### Attached Logs

[1589910870-8c153114-8590-4b1f-a3af-f31bcd83a35a1589910867420.zip](https://github.com/PowerShell/vscode-powershell/files/4652341/1589910870-8c153114-8590-4b1f-a3af-f31bcd83a35a1589910867420.zip)
[1589911142-471de95c-9aa2-4be8-a228-d5161deca21b1589911139246.zip](https://github.com/PowerShell/vscode-powershell/files/4652342/1589911142-471de95c-9aa2-4be8-a228-d5161deca21b1589911139246.zip)

**Comment by SydneyhSmith** [comment] 2020-05-19 21:07
@sba923 thanks so much for all the detailed information, we were able to reproduce this bug using PowerShell 7.

**Comment by sba923** [comment] 2020-05-20 11:47
You're very welcome. This must've been introduced by a recent change. New PSSA?

**Comment by SydneyhSmith** [comment] 2020-05-21 21:30
@sba923 looks like we are not handling files with parse errors well...likely not related to PSSA

**Comment by sba923** [comment] 2020-07-31 10:26
This is an old issue that damages the PS-development-in-VScode *a lot* if you ask me.

Is there anything I can do to help?

**Comment by SydneyhSmith** [comment] 2020-08-11 21:28
@sba923 thanks for bringing this issue back up and offering to help! I am having a lot of trouble reproducing it on the latest version of the PowerShell preview extension and wanted to confirm that you are still seeing this?

**Comment by sba923** [comment] 2020-10-18 07:50
The problem is still there with v2020.6.0 of the extension running in VScode 1.50.1 with PS7.1-rc1.

What's different is that `Ctrl+C` now doesn't do anything, the only escape is to exit VScode.

**Comment by TylerLeonhardt** [comment] 2020-10-20 19:11
> What's different is that Ctrl+C now doesn't do anything

Is this on macOS? This was an issue with .NET 5 unfortunately... it's fixed and will be in 7.1-rc2

**Comment by sba923** [comment] 2020-10-20 19:41
Nope, this is on Windows 10 20H1

**Comment by SydneyhSmith** [comment] 2022-07-18 19:11
This issue isnt reproducing for me anymore on PowerShell 7 or Windows Powershell...let me know if you are still hitting this

**Closed** 2022-07-18 22:01 UTC
Labels: Issue-Bug, Area-Debugging, Resolution-Fixed

**Comment by sba923** [comment] 2022-07-19 04:55
@SydneyhSmith I can't repro with either PowerShell 7.2.5 or Windows PowerShell 5.1, with version 2022.6.3 or Preview 2022.7.0 of the extension.

I'll keep monitoring for this.
