### ISSUE TITLE
Cursor jumps up to previous line after pressing enter

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/vscode-powershell#1786] opened 2019-03-12 06:54 UTC
Issue Type: <b>Bug</b>

I am at the end of a comment line and wish to press enter and starting a new line of code.

I press enter. For a fraction of a second, everything is as it should be - the cursor is on the right place on the next line.

Then suddenly it is back on the previous line, and not even at the end of the line (2 characters offset, apparently).

If I start typing fast enough, it stays where it should. Otherwise, not.

If I press enter multiple times fast enough, it will still bump me back up to the original line.

Screen capture of issue happening: https://i.imgur.com/VNyj87I.gifv

My settings file:

```json
{
	"files.autoSave": "afterDelay",
	"editor.wordWrap": "on",
	"editor.tabSize": 4,
	"editor.wrappingIndent": "none",
	"editor.minimap.enabled": false,
	"editor.find.seedSearchStringFromSelection": false,
	"editor.find.autoFindInSelection": true,
	"editor.formatOnType": true,
	"editor.formatOnPaste": true,
	"files.trimTrailingWhitespace": true,
	"powershell.integratedConsole.showOnStartup": false,
    "eslint.enable": true,
    "git.confirmSync": false,
    "workbench.colorTheme": "Visual Studio Light",
	"plantuml.exportSubFolder": false,
	"plantuml.exportFormat": "png",
	"git.enableSmartCommit": true,
	"extensions.ignoreRecommendations": false,
	"window.zoomLevel": 0,
	"git.autofetch": true,
	"explorer.confirmDragAndDrop": false,
	"plantuml.jarArgs": [
		"-SfixCircleLabelOverlapping=true"
	],
	"workbench.startupEditor": "newUntitledFile",
	"team.showWelcomeMessage": false
}
```

Extension version: 1.11.0
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.88GB free)|
|Process Argv|--folder-uri file:///c%3A/Source/CmsTinkering.Configuration|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SydneyhSmith** [comment] 2019-03-12 22:04
@sandersaares that is very strange behavior, thanks for reporting this. We are this error might be coming from ```"editor.formatOnType": true``` could you try disabling this and see if you are still having this issue?

**Comment by sandersaares** [comment] 2019-03-13 06:53
I confirm that the behavior does not reproduce with `formatOnType=false`

**Comment by SydneyhSmith** [comment] 2019-03-27 17:46
Closing this issue as resolved

**Closed by SydneyhSmith** 2019-03-27 17:46 UTC
Labels: Needs-Repro-Info

**Comment by sandersaares** [comment] 2019-03-28 04:34
That is a workaround, not a resolution.

**Comment by PetyaFerreiraDeveloper** [comment] 2021-02-15 09:46
Hey, i had the same issue.
i found out it was caused by an extension i have enabled in my VS Code. The extension name is: JS-CSS-HTML formatter.
after i disabled the extension the VS Code started working normally
