### ISSUE TITLE
write-progress is not showing progress bar in vscode

### ISSUE THREAD

**Issue by SilverknightMel** [PowerShell/vscode-powershell#1376] opened 2018-06-20 22:53 UTC
### System Details

- Operating system name and version: Windows 2016
- VS Code version: 1.24.1
- PowerShell extension version:1.7.0
- Output from `$PSVersionTable`:
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem write-progress is not showing progress bar in vscode.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment] 2018-06-21 01:05
dupe of #140

**Closed by tylerl0706** 2018-06-21 01:05 UTC
