### ISSUE TITLE
references not found when used in class

### ISSUE THREAD

**Issue by mwallner** [PowerShell/vscode-powershell#876] opened 2017-06-14 11:24 UTC
### System Details

- Operating system name and version: Windows 7 Enterprise SP1
- VS Code version: 1.13.0
- PowerShell extension version: 1.3.2
- Output from `$PSVersionTable`:
```
PS E:\> code -v
1.13.0
376c52b955428d205459bea6619fc161fc8faacf
PS E:\> $pseditor.EditorServicesVersion
PS E:\> code --list-extensions --show-versions
DotJoshJohnson.xml@1.8.0
EditorConfig.EditorConfig@0.9.3
jchannon.csharpextensions@1.3.0
ms-vscode.cpptools@0.11.4
ms-vscode.PowerShell@1.3.2
qinjia.seti-icons@0.1.3
PS E:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### references not found when used in class
As visible in the following screenshot, there is "1 reference" found for the function `Get-ResultStateBGClass` - this one usage is also visiable right below in the function `Get-ResultStateAlertBGClass`:
![image](https://user-images.githubusercontent.com/5354972/27129831-011290d2-5104-11e7-9453-2db9ea8841b9.png)

But, in the same file, some lines down there's a class which also uses the function `Get-ResultStateBGClass` within a function:
![image](https://user-images.githubusercontent.com/5354972/27129914-55e5b18e-5104-11e7-9f99-fe2bb5eae79b.png)

(so there should be two references for `Get-ResultStateBGClass`...)

This is reproducable with this very easy setup:
```
function Get-Foo {
  return "foo"
}

class Bar {
  [string] BarGetFoo {
	  $var = Get-Foo 
  }
}
```

**Comment by JustinGrote** [comment] 2020-04-22 16:42
Slightly modified example to proper code but this issue is still valid
```powershell
function Get-Foo {
    return "foo"
}
class Bar {
    [string] BarGetFoo() {
        return Get-Foo #This does not get properly referenced to the definition
    }
}

Get-Foo #This does
```
![image](https://user-images.githubusercontent.com/15258962/80008979-46185680-847d-11ea-98bf-2167815c30fe.png)

**Comment by TylerLeonhardt** [comment] 2020-04-22 17:13
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/3 once we add proper support for classes (eventually.........) this should be resolved.

**Closed** 2020-04-23 19:00 UTC
Labels: Area-Symbols & References, Issue-Bug, Resolution-Duplicate
