### ISSUE TITLE
'Compare with Saved' crashes the PowerShell session

### ISSUE THREAD

**Issue by ajansveld** [PowerShell/vscode-powershell#1002] opened 2017-08-22 13:57 UTC
### System Details

- Operating system name and version: Windows 10 (10.0.14393)
- VS Code version: 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2)
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.1532
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1532
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using the "Compare with Saved" feature on a PowerShell script the extension stops with a "The PowerShell session has terminated due to an error, would you like to restart it?" message.

I *think* the bug is actually in the language server, but raising it here for visibility (sorry for the cross-post).

### Attached Logs

See https://github.com/PowerShell/PowerShellEditorServices/issues/544.

**Comment by daviwil** [comment] 2017-08-22 14:05
No problem!  I actually just started looking into this one again, expect a fix in the next update.

**Comment by daviwil** [comment] 2017-10-27 14:22
I've got a fix prepared for this, will go out with today's update! Closing it as a duplicate of PowerShell/PowerShellEditorServices#342.

**Closed by daviwil** 2017-10-27 14:22 UTC
Labels: Area-General, Issue-Bug
