### ISSUE TITLE
Clear-Host doesn't clear buffer

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#3342] opened 2021-05-07 13:14 UTC
### System Details

System Details Output
```
### VSCode version: 1.56.0 cfa2e218100323074ac1948c885448fdf4de2a7f x64

### VSCode extensions:
MS-CEINTL.vscode-language-pack-de@1.56.1
ms-vscode.powershell@2021.2.2


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Entering `Clear-Host` in the VS Code terminal doesn't clear buffer:

![Clear-Host won't work](https://user-images.githubusercontent.com/9283914/117454743-c275be80-af46-11eb-8863-a7bb08b93ec6.gif)

#### Expected Behaviour

After I entered `cls`, or `Clear-Host`, the scoll buffer should be cleared. Scrolling upwards using the mouse scroll wheel should not reveal previous lines.

#### Actual Behaviour

After I entered `cls`, or `Clear-Host`, scrolling the terminal panel upwards using the mouse wheel reveals previous lines.

**Comment by SydneyhSmith** [comment] 2021-05-12 18:27
Thanks @SetTrend in your GIF it looks like you are not in the integrated console...has the extension started up?

**Comment by rjmholt** [comment] 2021-05-12 18:31
Just to add some extra information here:

- xterm.js is a VT100 terminal emulator, which doesn't support terminal clearing APIs. So ordinary `pwsh.exe` won't be able to clear it. The same is true for `pwsh` on *nix systems.
- The PS Integrated Console _does_ support `Clear-Host` when that configuration is enabled (and you're using the PSIC) by sending a message to VSCode to actually clear the terminal.

**Comment by SetTrend** [comment] 2021-05-13 09:02
Ah, I see ... Thank you for enlighening me.

Are there chances that the behaviour of the integrated console changed recently? From the screenshot above you can see that I checked `Show On Startup`. I would expect the integrated console to replace all the other ones when I open the terminal. I have no use for these once I install the _PowerShell_ extension.

**Comment by rjmholt** [comment] 2021-05-13 15:42
>  I would expect the integrated console to replace all the other ones when I open the terminal.

This is the part that currently doesn't happen. The extension _extends_ VSCode rather than clobbering it. We're not looking to make any changes here, since other users have other expectations.

The default terminal and shell are separate to the extension and [are configured separately](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration).

VSCode only loads extensions when an activation event for that extension occurs -- prior to that the extension has no control and must wait to be activated, so something must occur for the PSIC to launch (i.e. you can't just override your ordinary shell with it). Activation events for the PowerShell extension are:

https://github.com/PowerShell/vscode-powershell/blob/d3253e998f3e9d3d07fc8889bd06dd5ddd8cca8a/package.json#L29-L47

The important points here are:

- These activation events are static, so can't be configured between users. That means that activation events we choose must apply to all users
- [VSCode specifically recommends against using the startup activation events](https://code.visualstudio.com/api/references/activation-events#Start-up)

So essentially you have to trigger the PowerShell extension to activate in some way before any of our code or configurations can come into play, limiting our ability to serve the scenario of having the integrated console globally override the builtin shell.

**Comment by SetTrend** [comment] 2021-05-16 16:48
Thank you for enlightening me on this situation, @rjmholt.

In the documentation hyperlink you provided I couldn't find a note about discouraging from using startup events, e.g. for [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished).

Wouldn't it be desirable and feasible to replace the Boolean option _Start Automatically_ with a DropDown option, to optionally provide a third kind of startup - starting up with VS Code on [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished), like this:

![PowerShell - Start Automatically](https://user-images.githubusercontent.com/9283914/118405180-d328e180-b676-11eb-8445-0850af535a8c.png)

Having the proposed `onProgramLaunch` option selected, the integrated console is then supposed to replace the default terminal.

**Comment by rjmholt** [comment] 2021-05-18 20:47
> In the documentation hyperlink you provided I couldn't find a note about discouraging from using startup events

From the `*` event documentation:

> To ensure a great user experience, please use this activation event in your extension only when no other activation events combination works in your use-case.

In the `onStartupFinished` event it also says:

> This is similar to the * activation event

Essentially the issue is that starting the PSIC at startup for everyone with the PowerShell extension installed is a very aggressive user experience.

Also like I said above, these can't be configured; a dropdown won't work to give you the option to turn this on or off:

> These activation events are static, so can't be configured between users. That means that activation events we choose must apply to all users [of the extension everywhere]

Essentially I don't think what you're asking for can be achieved easily.

I'll close this issue, since the underlying cause of the original problem has been resolved.

**Closed by rjmholt** 2021-05-18 20:47 UTC
Labels: Needs-Repro-Info, Needs: Attention :wave:

**Comment by SetTrend** [comment] 2021-05-19 08:47
@rjmholt:

The solution would be simple: A small shim could test the configuration at start-up and either quit or load/launch the PowerShell extension.

Would you mind if I created a feature request?

**Comment by andschwa** [comment] 2021-06-14 20:58
Looks like that issue was #3407

**Comment by fmotion1** [comment] 2023-10-07 06:22
Also having this issue. Clear-Host doesn't clear the buffer in the integrated console.

**Comment by mkamoski** [comment] 2024-11-27 17:17
- Same issue here.
- Totally unacceptable-- Clear-Host does NOT clear host??  What ??
- This is the kind of thing that makes open-source dev tools stink.

**Comment by andyleejordan** [comment] 2024-11-27 21:00
Hi @mkamoski, `Clear-Host` clears the scrollback for me. If you're having an issue with the lastest extension and PowerShell versions, can you please create a new issue and show us?

**Comment by mkamoski** [comment] 2024-11-27 22:59
> Hi @mkamoski, `Clear-Host` clears the scrollback for me. If you're having an issue with the lastest extension and PowerShell versions, can you please create a new issue and show us?

Clear-Host is not working in Visual Studio Code, for me.
Set it up yesterday, so it should the latest-and-greatest.
VScode is kludgy anyway, so that could be the issue.
I don't mean to spin wheels here, so its fine-- it does work with the latest PS bits for VS19 so I am good.
...

**Comment by JustinGrote** [comment] 2024-11-28 02:44
@mkamoski if you change your mind and want to demonstrate, win+shift+r is a really easy way to record a demo of what you're seeing, and you can cut and paste it directly into Github.
