### ISSUE TITLE
F8 stops working randomly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2695] opened 2020-05-13 13:43 UTC
Issue Description
=====

I am experiencing a problem with... F8 (run selected code) not doing anything. Restarting the PowerShell session resolves this issue. Not sure why this happens. But I'm pretty sure it's related to https://github.com/PowerShell/vscode-powershell/issues/2627 as usually at this point any autocomplete doesn't work. 

At the same time F5 works as required. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

[1589356870-6906701f-2456-4b22-b157-d0c8a0d20de91589034518232.zip](https://github.com/PowerShell/vscode-powershell/files/4622265/1589356870-6906701f-2456-4b22-b157-d0c8a0d20de91589034518232.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.0|
| PowerShell Extension Version | 2020.4.3 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.1.2|
|code-settings-sync|Shan|3.4.3|
|excel-to-markdown-table|csholmq|1.2.2|
|gistfs|vsls-contrib|0.0.67|
|gitdoc|vsls-contrib|0.0.6|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|html-preview-vscode|george-alisson|0.2.5|
|markdown-all-in-one|yzhang|2.8.0|
|markdown-preview-enhanced|shd101wyy|0.5.3|
|markdown-shortcuts|mdickin|0.12.0|
|material-icon-theme|PKief|4.1.0|
|pdf|tomoki1207|0.6.0|
|powershell-preview|ms-vscode|2020.4.3|
|project-manager|alefragnani|10.12.0|
|rainbow-csv|mechatroner|1.7.0|
|reg|ionutvmi|1.0.1|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.35.1|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-versionlens|pflannery|0.27.0|
|vscode-wakatime|WakaTime|4.0.0|
|vscode-yaml|redhat|0.7.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment] 2020-05-13 14:29
> At the same time F5 works as required.

This is fantastic information. There will be another release of the Preview extension today where we updated the library that we use to handle requests. I'd like you to give that a go.

**Comment by PrzemyslawKlys** [comment] 2020-05-13 14:49
Is it "fantastic" as useless or does it really give you some insight into a problem? You got me a bit confused about the usefulness of this. Maybe I could be more descriptive of my problems in the future - just need more information about what would you like me to provide (except a way to reproduce - as this is hard to do sometimes).

Sure, I will do. Thank you!

**Comment by TylerLeonhardt** [comment] 2020-05-13 15:24
It's incredibly helpful. The debug messages get sent over a different channel.

If that's working just fine, that means:
* debug channel is working
* the PowerShell instance we use for everything is working

BUT the channel we use for language features (intellisense, codelens, folding, F8, etc) is not working... That channel is provided by the Omnisharp library... And the latest version (allegedly) fixed channel issues.

So that makes me feel more confident that the release that goes out today will have a fix for you.

**Comment by PrzemyslawKlys** [comment] 2020-05-13 21:31
Didn't fix, unfortunately. Just hit the issue. Formatting stopped working, F8 doesn't work, IntelliSense doesn't work.

**Comment by TylerLeonhardt** [comment] 2020-05-13 22:10
Ok we'll have to wait for

**Comment by adambrubaker** [comment] 2020-05-14 14:07
I am experiencing this exact issue as well.  I'm following this thread and I'm happy to add any logs or extra data points if needed.

Thanks

**Comment by SydneyhSmith** [comment] 2020-05-14 21:11
Going to mark this as a duplicate of #2627 where we will continue to track this issue--thanks!

**Closed** 2020-05-14 21:12 UTC
Labels: Resolution-Duplicate
