### ISSUE TITLE
VS Code does not run PowerShell jobs correctly

### ISSUE THREAD

**Issue by marksrasmussen** [PowerShell/vscode-powershell#120] opened 2016-03-17 22:09 UTC
``` powershell
$test = {
  function makeform {     
          [void][reflection.assembly]::LoadWithPartialName("System.Windows.Forms")    
          [System.Windows.Forms.Application]::EnableVisualStyles();    

          $form = New-Object Windows.Forms.Form    
          $form.Text = 'Test Form'    

          $form.Add_Shown({$form.Activate()})    
          $form.ShowDialog()    
  }
}

Start-Job { makeform } -InitializationScript $test
```

```
---------------------------------
PS C:\WINDOWS\system32> D:\AMS\scripts\MaybeBug.ps1
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command               
--     ----            -------------   -----         -----------     --------             -------               
7      Job7            BackgroundJob   Running       True            localhost             makeform

----------------------------------
Visual Stu
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
1      Job1            BackgroundJob   Failed        False           localhost             makeform    
```

**Comment by daviwil** [comment] 2016-03-17 22:23
Hey @marksrasmussen, there may be some behavior we need to add to support PowerShell jobs.  Thanks for the example script!  I'll try to get this fixed for a future release.

**Comment by mcmiv413** [comment] 2016-04-18 14:42
Just wanted to include some error information, I got bit by this bug today.

Start-Job -Name testjob2 -ScriptBlock {get-process -Name "Code" | select processname,id,starttime}

receive-job -name testjob2

[localhost] The background process reported an error with the following message: 
Cannot process an element with node type "Text". 
Only Element and EndElement node types are supported.at 
System.Management
.Automation
.Remoting
.OutOfProcessUtils
.ProcessData(String data, DataProcessingDelegates callbacks).
    + CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : 2100,PSSessionStateBroken

**Comment by daviwil** [comment] 2016-04-18 14:44
What a strange error...  Not sure if it's a job problem or something else.  Will look into it!

**Comment by JanCervak** [comment] 2016-05-17 16:34
The issue is still present in the current marketplace release (0.6.1 - 5/17/2016).

**Comment by rkeithhill** [comment] 2016-05-17 17:00
Sorry, this item is still on the backlog.  To keep track of the status of this bug, keep an eye on the `Milestone` field to the upper right.  

Hopefully we can get it at least figured out for the next release and possibly fixed if the "fix" is simple enough.  :-)  I think we are shooting for a faster release frequency which may help as well.

**Comment by maximpashuk** [comment] 2016-05-24 12:21
Having the same issue as @mcmiv413, my integration scripts actively using powershell jobs, so this will be nice to have full support of jobs in vscode-powershell.

**Comment by pcgeek86** [comment] 2017-04-23 02:22
@rkeithhill @daviwil Just circling back on this to clean up. I am able to successfully invoke PowerShell Background Jobs on Mac OS X from the latest version of the VSCode PowerShell Extension. I'm currently running:

```
PS /Users/tsulli/Amazon> code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
```

```
PS /Users/tsulli/Amazon> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
PS /Users/tsulli/Amazon> code --list-extensions --show-versions
Alexander.theme-sublime-oceanicnext@0.0.3
Nuuf.theme-hackershaze@1.3.1
PeterJausovec.vscode-docker@0.0.13
abusaidm.html-snippets@0.1.0
akamud.vscode-theme-onedark@1.3.2
aws-scripting-guy.cform@0.0.9
azemoh.one-monokai@0.2.4
christian-kohler.npm-intellisense@1.3.0
dlech.chmod@1.0.0
donjayamanne.python@0.6.3
ecmel.vscode-html-css@0.1.2
eg2.vscode-npm-script@0.1.9
fknop.vscode-npm@3.3.0
jakeboone02.mediawiki@2.1.0
jprestidge.theme-material-theme@1.0.1
ms-vscode.cpptools@0.10.5
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2
searKing.preview-vscode@1.1.5
```

<img width="816" alt="screen shot 2017-04-22 at 7 19 49 pm" src="https://cloud.githubusercontent.com/assets/466713/25310083/f2927852-2790-11e7-8d86-7a0427e48cc9.png">

Cheers,
Trevor Sullivan

**Comment by GoateePFE** [comment] 2017-08-16 20:27
On MacOS with VSCode 1.15.1 and PowerShell Extension version 1.4.1 and PowerShell Core Beta 5...
I am able to start a job from the terminal window or by pressing F8 on a line in the editor. However, if I use the F8 method, then the terminal window does not respond until I press ENTER an additional time. If I run Start-Job in the terminal window directly then the prompt returns immediately. The same behavior is true when using the "&" appended at the end of the line to start a job.

**Comment by tylerl0706** [comment] 2017-12-07 22:40
Hi @GoateePFE, can you elaborate on what you mean by the F8 method?

**Comment by pcgeek86** [comment] 2017-12-08 02:19
@tylerl0706 In the Windows PowerShell Integrated Scripting Editor (ISE), F8 became the standard shortcut to run the "current line" that the cursor is on (if there is no editor selection) or "current selection" (if there is an editor selection).

So, I'm guessing that what @GoateePFE means by "F8 method" is that he's simply putting the cursor on a line with a `Start-Job` command and simply hitting F8 to invoke that line, as opposed to manually typing the `Start-Job` command into the VSCode Integrated Terminal.

**Comment by GoateePFE** [comment] 2017-12-08 15:06
@tylerl0706 The comments of @pcgeek86 are correct.

**Comment by tylerl0706** [comment] 2017-12-09 04:55
Thanks for that guys! I can repro exactly what @pcgeek86 said. So something fixed the other scenarios but this one is still broken. We'll have to look into this.

Thanks for the update!

**Comment by rkeithhill** [comment] 2017-12-09 05:08
I bet this is the same bug as https://github.com/PowerShell/PowerShellEditorServices/issues/554.  It only happens on non-Windows systems.  I know right where the issue lies (documented in the aforementioned issue and my first attempt to fix it - https://github.com/PowerShell/PowerShellEditorServices/pull/557).

**Comment by tylerl0706** [comment] 2018-01-29 19:45
@rkeithhill this issue _should_ be fixed now with https://github.com/PowerShell/PowerShellEditorServices/pull/592

But it also looks like @SeeminglyScience might be addressing an issue with that PR?

**Comment by rkeithhill** [comment] 2018-01-29 20:13
Yup, I'd say the original issue is fixed. Close it.

**Comment by tylerl0706** [comment] 2018-01-29 20:57
Awesome! Keep your eyes out for this in the next release!

**Closed by tylerl0706** 2018-01-29 20:57 UTC
Labels: Issue-Bug

**Comment by ohadschn** [comment] 2019-03-07 15:38
Regarding the `The background process reported an error with the following message:
Cannot process an element with node type "Text".
Only Element and EndElement node types are supported` error see: https://stackoverflow.com/questions/33936510/start-job-including-custom-cmdlet-terminates-with-strange-error
