### ISSUE TITLE
Start-EditorServices.ps1 causes a 2nd terminal to open. New terminal has execution policy set to RemoteSigned

### ISSUE THREAD

**Issue by BristleBeard** [PowerShell/vscode-powershell#1090] opened 2017-11-05 19:12 UTC
### System Details

- Operating system name and version: Windows 10 Pro 1709
- VS Code version: 1.17.2
- PowerShell extension version: 1.50
- Output from `$PSVersionTable`:
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
$pseditor.EditorServicesVersion 1.5.0.0
akamud.vscode-theme-onedark@2.1.0
emilast.LogFileHighlighter@1.2.0
GrapeCity.gc-excelviewer@1.1.15
jprestidge.theme-material-theme@1.0.1
ms-vscode.PowerShell@1.5.0
pawelgrzybek.bimbo-theme@0.3.0
robertohuertasm.vscode-icons@7.17.0
Shan.code-settings-sync@2.8.5
tariky.easy-snippet-maker@0.0.6
zhuangtongfa.Material-theme@2.10.18
```

### Issue Description

When I open VS Code my terminal opens automatically with 'powershell'. If I open an existing script or start a new PS file, a 2nd terminal opens up running 'PowerShell Integrated Console'. Now I have two terminals, and the new one has a RemoteSigned execution restriction. My `profile.ps1` executes again, causing the line `Set-ExecutionPolicy Bypass -Scope CurrentUser` to throw an error. The 'PowerShell Integrated Console' terminal also does not retain previous command history or color coding.

My non-default powershell extensions settings are these:
```
"powershell.enableProfileLoading": true
"powershell.codeFormatting.preset": "OTBS"
```

I've been unable to find where the execution policy is getting changed to RemoteSigned but I'm wondering if these two default settings are the cause of the additional terminal:
```
"powershell.startAutomatically": true
"powershell.integratedConsole.showOnStartup": true
```
### Attached Screenshots
![image](https://user-images.githubusercontent.com/1373436/32418093-dddad1ba-c228-11e7-9869-2dec2b049ba1.png)

![image](https://user-images.githubusercontent.com/1373436/32418194-d2f97e70-c22a-11e7-98f6-45722febd0cb.png)

![image](https://user-images.githubusercontent.com/1373436/32418199-e27c84c8-c22a-11e7-95a5-e9bd4a88f7bc.png)

**Comment by rkeithhill** [comment] 2017-11-05 19:22
This is a dupe of #1084.  The latest release had an issue where the script file was tweaked after signing, rendering the signature hash invalid.  There should be an update coming soon to resolve this issue.

BTW the PowerShell Integrated Console is similar to the ISE console where the debug session runs in that console.  It can manipulated during debug and the debug state remains after the debug session finishes - just like in ISE.

**Closed by rkeithhill** 2017-11-05 19:22 UTC
Labels: Area-Integrated Console

**Comment by BristleBeard** [comment] 2017-11-19 02:44
Please re-open this issue. It still exists in 1.51 and #1084 has been since closed.

**Comment by daviwil** [comment] 2017-11-20 14:12
@BristleBeard The second terminal is the "PowerShell Integrated Terminal" which is connected to the PowerShell extension's editing and debugging experience, you definitely want it to be open.  The reason why you see 2 terminals open is because VS Code falsely remembers a terminal being open the last time it was closed and pre-emptively opens a terminal for powershell.exe when it starts back up, before the PowerShell extension has a chance to start.

Is the RemoteSigned execution policy an issue for you?  Can you solve this issue by calling Set-ExecutionPolicy in the $profile of the PowerShell Integrated Terminal (it's different than the default PowerShell profile)?
