### ISSUE TITLE
[Powershell Preview regression bug] Debugger hangs when a breakpoint inside a scriptblock is hit

### ISSUE THREAD

**Issue by Jawz84** [PowerShell/vscode-powershell#2448] opened 2020-01-29 07:40 UTC
Issue Description
=====

I am experiencing a problem with the debugger. It hangs when a breakpoint inside a scriptblock is hit.

Steps to reproduce:

- Paste the script as a new ps1 file, and run it.
- In the Integrated terminal type 'Stop-Service -Name \<tab\>' 
- The debug session is started, but it does not accept further interaction.

```powershell
$s = {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    Set-PSBreakpoint -command Get-Service
    $services = Get-Service | Where-Object {$_.Status -eq "Running" -and $_.Name -like "$wordToComplete*"}
    $services | ForEach-Object {
        New-Object -Type System.Management.Automation.CompletionResult -ArgumentList $_.Name,
            $_.Name,
            "ParameterValue",
            $_.Name
    }
}
Register-ArgumentCompleter -CommandName Stop-Service -ParameterName Name -ScriptBlock $s
```

Beyond this point, you can only kill the integrated terminal. It will not accept any other input. 
![image](https://user-images.githubusercontent.com/26464885/73336529-58199d00-4272-11ea-9b11-c883b8846fe2.png)

NOTE:
This only happens in the PowerShell Preview Extension. The GA PowerShell extension does not have this bug.

The bug is also not reproducible in a stand alone console in PowerShell 5.1, Powershell 6.2.3, or 7.0.0.rc2, or PowerShell_ise (5.1). It is specific to the Preview version of the extension. 

Attached Logs
=====

[1580281742-dc8c91be-e55c-4eed-822f-c087bed38b011580281219461.zip](https://github.com/PowerShell/vscode-powershell/files/4126658/1580281742-dc8c91be-e55c-4eed-822f-c087bed38b011580281219461.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 
| VSCode | 1.41.1|
| PowerShell Extension Version | 2020.1.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0-rc.2|
|PSEdition|Core|
|GitCommitId|7.0.0-rc.2|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0-rc.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.8|
|azure-pipelines|ms-azure-devops|1.165.1|
|azurecli|ms-vscode|0.4.6|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|cmake|twxs|0.0.17|
|code-settings-sync|Shan|3.4.3|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.9|
|csharpfixformat|Leopotam|0.0.84|
|docomment|k--kato|0.1.8|
|gitlab-ci-validator|cstuder|1.0.0|
|gitlens|eamodio|10.2.0|
|Go|ms-vscode|0.12.0|
|LiveServer|ritwickdey|5.6.1|
|powershell-preview|ms-vscode|2020.1.0|
|python|ms-python|2020.1.58038|
|remote-containers|ms-vscode-remote|0.94.0|
|remote-ssh|ms-vscode-remote|0.48.0|
|remote-ssh-edit|ms-vscode-remote|0.48.0|
|remote-wsl|ms-vscode-remote|0.41.7|
|swagger-viewer|Arjun|2.2.2|
|terraform|mauve|1.4.0|
|vscode-azurefunctions|ms-azuretools|0.20.2|
|vscode-azureterraform|ms-azuretools|0.3.0|
|vscode-icons|vscode-icons-team|9.7.0|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-pull-request-github|GitHub|0.14.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.19.0|
|vscode-svg-previewer|vitaliymaz|0.5.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vsliveshare|ms-vsliveshare|1.0.1510|
|vsonline|ms-vsonline|1.0.1507|
|xml|DotJoshJohnson|2.5.0|

**Comment by rjmholt** [comment] 2020-01-31 23:55
May be related to https://github.com/PowerShell/vscode-powershell/issues/2246.

Worth noting that generally most scriptblocks will behave as normal, but there are a few exacerbating factors here:

- The scriptblock is used as an argument completer, so it gets called deep within PowerShell via PSReadLine
- The breakpoint set is a command breakpoint
- The breakpoint seems to be set within the completer scriptblock itself, creating a new breakpoint each time a completion is asked for

**Comment by rjmholt** [comment] 2020-01-31 23:58
I've just managed to reproduce this. Will investigate

**Comment by rjmholt** [comment] 2020-02-01 01:43
So a preliminary look shows the following:

- The thread moving to resume the debugger is waiting for the frame to exit [here](https://github.com/PowerShell/PowerShellEditorServices/blob/38fd616d9dccbd30e1250222010e756fd1235984/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L1300-L1309)
- A thread waiting for the current PowerShell execution to complere [here](https://github.com/PowerShell/PowerShellEditorServices/blob/38fd616d9dccbd30e1250222010e756fd1235984/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L2460)
- A PowerShell execution thread running the PSReadLine prompt script, which is waiting to acquire the pipeline thread handle

**Comment by rjmholt** [comment] 2020-02-01 02:02
So:

- ReadLine is waiting on the completion, which is blocked by the debugger
- The debugger is waiting on the stack frame to pop, which is blocked by ReadLine

First naive theoretical solution: flag when the command being run is the prompt to tell the debugger not to wait for the stack frame to resume

**Comment by SeeminglyScience** [comment] 2020-02-01 02:13
It's probably going to go further than that.  Since PSRL is still running, the ReadLine runspace handle will be taken.  That handle queue isn't set up to be nested like the normal execute handles.  None of the read line stuff is set up for that scenario iirc.

Plus even if you get all that sorted, the `PSEventManager` will still be busy processing the original completion call, so once the debugger stop happens, any calls to intellisense or similar will deadlock. Honestly, trying to set it all up as PowerShell events was a mistake on my part.  A private contract field that stores a delegate should be added to PSRL that we would use in place of the over complicated `OnIdle` system.

**Comment by andschwa** [comment] 2022-01-20 00:02
@Jawz84 Hello, and thank you for your patience! The latest [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) is now out, and includes the reworking of our pipeline and threading architecture in https://github.com/PowerShell/PowerShellEditorServices/issues/1295. Could you verify if this issue still reproduces using [v2022.1.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.1.0-preview)? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by Jawz84** [comment] 2022-01-20 13:56
Thanks for getting back to me about this. I'm going to try this out, but can't guarantee a timeframe at this point. Will aim for coming weekend.

Met vriendelijke groet,

Jos Koelewijn
________________________________

**Comment by Jawz84** [comment] 2022-01-21 19:38
Let me start out by saying: thanks for the huge amount of work, that has undoubtably gone into the complete overhaul. 💙

I've tried to reproduce on 2022.1.0-preview. This time, the behaviour was different. The debugger did attach after the 'tab' keystroke. After that, I was able to F10 step through, until I hit this error on line 11 (closing curly for scriptblock `$s`): This error is shown in the terminal:

```text
Last 21 Keys:

 s t o p - s e r v i c e Spacebar - n a m e Spacebar Tab Tab

### Exception

System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
   at System.Threading.WaitHandle.ObtainSafeWaitHandles(ReadOnlySpan`1 waitHandles, Span`1 safeWaitHandles, Span`1 unsafeWaitHandles)   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)                                           
```

>NOTE: the keystrokes recorded here in the terminal are complete, yet they don't reflect the F10 keypresses in the debugger (ofcourse).

After this error, the debugger detaches, and control is given back to the terminal. The terminal is usable as normal after this. VSCode does not hang or become unresponsive. There is one little quirk though: the debug start/stop control is still visible, and showing as if the debugger session is still running:

![image](https://user-images.githubusercontent.com/26464885/150589685-466be98c-3883-447c-acd5-ccc9b1bfba30.png)

I think it's a major improvement!

**Comment by Jawz84** [comment] 2022-01-21 19:44
I just noticed after posting, that the powershell integrated console had an orange exclamation triangle, and when I hovered over it, this displayed:
![image](https://user-images.githubusercontent.com/26464885/150589990-21793a96-a1d1-4326-8769-a949f72c0e5b.png)

I've tried to reproduce this after. I haven't yet been able to do so.

**Comment by andschwa** [comment] 2022-01-21 22:06
> Let me start out by saying: thanks for the huge amount of work, that has undoubtably gone into the complete overhaul. 💙
> 
> I've tried to reproduce on 2022.1.0-preview. This time, the behaviour was different. The debugger did attach after the 'tab' keystroke. After that, I was able to F10 step through, until I hit this error on line 11 (closing curly for scriptblock `$s`): This error is shown in the terminal:
> 
> ```
> Last 21 Keys:
> 
>  s t o p - s e r v i c e Spacebar - n a m e Spacebar Tab Tab
> 
> ### Exception
> 
> System.ObjectDisposedException: Safe handle has been closed.
> Object name: 'SafeHandle'.
>    at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
>    at System.Threading.WaitHandle.ObtainSafeWaitHandles(ReadOnlySpan`1 waitHandles, Span`1 safeWaitHandles, Span`1 unsafeWaitHandles)   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)                                           
> ```
> 
>  > NOTE: the keystrokes recorded here in the terminal are complete, yet they don't reflect the F10 keypresses in the debugger (ofcourse).
> 
> After this error, the debugger detaches, and control is given back to the terminal. The terminal is usable as normal after this. VSCode does not hang or become unresponsive. There is one little quirk though: the debug start/stop control is still visible, and showing as if the debugger session is still running:
> 
> ![image](https://user-images.githubusercontent.com/26464885/150589685-466be98c-3883-447c-acd5-ccc9b1bfba30.png)
> 
> I think it's a major improvement!

This is _super_ helpful because it looks just like #3751. Given that, I'm going to mark this particular issue as resolved, and thank you for the second repro of that early safe handle disposal bug (which is already triaged and slated to be fixed). Thank you!

**Comment by andschwa** [comment] 2022-01-21 22:07
> I just noticed after posting, that the powershell integrated console had an orange exclamation triangle, and when I hovered over it, this displayed: ![image](https://user-images.githubusercontent.com/26464885/150589990-21793a96-a1d1-4326-8769-a949f72c0e5b.png)
> 
> I've tried to reproduce this after. I haven't yet been able to do so.

HAHA I have seen that exactly once as well and never been able to repro. It doesn't seem to _break_ anything, and I don't know why it's happening because that environment variable isn't something we touch.

**Comment by JustinGrote** [comment] 2022-01-22 00:01
I've seen it several times but haven't figured out a good repro either.

**Closed** 2022-01-22 01:00 UTC
Labels: Issue-Bug, Area-Debugging, Resolution-Fixed

**Comment by Jawz84** [comment] 2022-01-22 07:13
Agreed, thanks. Great work everyone!
