### ISSUE TITLE
Getting Help from Command Explorer not working

### ISSUE THREAD

**Issue by DeanGross** [PowerShell/vscode-powershell#1646] opened 2018-12-10 19:23 UTC
### System Details

System Details Output
```
### VSCode version: 1.29.1 bc24f98b5f70467bc689abf41cc5550ca637088e x64

### VSCode extensions:
abusaidm.html-snippets@0.2.1
anseki.vscode-color@0.4.5
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
DavidAnson.vscode-markdownlint@0.22.0
docsmsft.docs-article-templates@0.1.4
docsmsft.docs-authoring-pack@0.1.1
docsmsft.docs-markdown@0.2.0
docsmsft.docs-preview@0.3.16
DotJoshJohnson.xml@2.3.2
eamodio.gitlens@9.0.3
EditorConfig.EditorConfig@0.12.5
eg2.tslint@1.0.40
eg2.vscode-npm-script@0.3.5
eliostruyf.spfx-debug@0.0.3
eliostruyf.spfx-essentials@4.0.0
eliostruyf.spfx-script-check@1.0.0
eliostruyf.spfx-snippets@1.7.1
eliostruyf.vscode-spfx-localization@1.2.1
eliostruyf.vscode-spfx-task-runner@1.1.1
MariusAlchimavicius.json-to-ts@1.5.5
ms-azuretools.vscode-azureappservice@0.10.0
ms-azuretools.vscode-azurefunctions@0.13.0
ms-docfx.DocFX@0.1.3
ms-vscode.azure-account@0.6.2
ms-vscode.PowerShell@1.10.1
ms-vsts.team@1.144.1
msjsdiag.debugger-for-chrome@4.11.1
RencoreGmbH.rencore-tenant-wide-spfx-extension-deployment@1.0.2
RencoreGmbH.vscode-spfx-deploy-package@1.1.0
RencoreGmbH.vscode-spfx-script-check@1.1.0
robertohuertasm.vscode-icons@7.28.0
steoates.autoimport@1.5.3
streetsidesoftware.code-spell-checker@1.6.10
Tyriar.theme-sapphire@0.8.0


### PSES version: 1.10.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.16299.785
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.785
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with...the PowerShell Command Explorer. When I right click on some commands and then choose Show Help for Command, the associated web site displays instead of the actual help files

#### Expected Behaviour

-- Description of what *should* be happening --
The help file for the cmdlet should display in the terminal window.

It works fine for get-PnPdevice, but does not work for Get-PnPContext 

#### Actual Behaviour

-- Description of what actually happens --
website at https://docs.microsoft.com/en-us/sharepoint/dev/community/community opens

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment] 2018-12-11 22:41
Hi @DeanGross, thanks for opening an issue.

`Get-PnpDevice` comes from the [PnpDevice](https://docs.microsoft.com/en-us/powershell/module/pnpdevice/get-pnpdevice?view=win10-ps) module, whereas `Get-PnpContext` comes from the [Sharepoint-Pnp](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpcontext?view=sharepoint-ps) module.

When the command explorer doesn't find local help, it falls back to opening an issue in your browser by design, by using the `HelpInfoUri` link in the module manifest. You should try `Update-Help` to get the local help for this module. Otherwise, it may be worth opening an issue on the [Sharepoint-Pnp](https://github.com/SharePoint/PnP-PowerShell) module.

I'm going to close this issue, since this is the intended behaviour of the Command Explorer.

The Command Explorer is also a community-contributed feature and we always accept PRs to improve it. /cc @corbob

**Closed by rjmholt** 2018-12-11 22:41 UTC
