### ISSUE TITLE
powershell.codeFormatting.pipelineIndentationStyle is ignored when formatting code

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#2732] opened 2020-05-30 23:52 UTC
I am experiencing a problem with the `powershell.codeFormatting.pipelineIndentationStyle` setting: No matter what value I set it to, it seems to be ignored:

![PowerShell](https://user-images.githubusercontent.com/9283914/83341229-39d7b280-a2e1-11ea-8b7b-443b8590d909.png)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.1|
|PSEdition|Core|
|GitCommitId|7.0.1|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2020.4.0|
|vscode-hexdump|iliazeus|1.8.2|
|vscode-language-pack-de|MS-CEINTL|1.45.1|

**Comment by SydneyhSmith** [comment] 2020-06-02 21:07
Thanks @SetTrend this looks like a duplicate of https://github.com/PowerShell/PSScriptAnalyzer/issues/1496

**Comment by SetTrend** [comment] 2020-06-02 22:04
Thanks, Sydnay, for replying.

I'm not sure, because in the other issue I can't see no pipeline character. The sample code provided therein is dealing with curly braces indendation, not with pipelining.

The other issue may probably be closed due to the option setting not being applicable to the provided sample code.

What do you think? If you believe both issues are dealing with the same issue and will be treated equally, please feel free to close my issue.

**Closed** 2020-06-04 01:00 UTC
Labels: Needs: Attention :wave:, Resolution-Duplicate
