### ISSUE TITLE
PowerShell Integrated Console not displaying prompt

### ISSUE THREAD

**Issue by anwather** [PowerShell/vscode-powershell#930] opened 2017-06-28 20:39 UTC
### System Details

- Operating system name and version: Windows 10 Version 16226
- VS Code version: 1.13.1
- PowerShell extension version:v1.4.1
```
    Name                           Value
    ----                           -----
    PSVersion                      5.1.16226.1000
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.16226.1000
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
```
ms-vscode.PowerShell@1.4.1
### Issue Description

When Code launches the PowerShell Integrated terminal is displayed as in the attached image. The prompt never appears. 

### Attached Logs

Image of issue attached.
![snip_20170629083734](https://user-images.githubusercontent.com/11281622/27659060-3d3bd70a-5ca6-11e7-9529-7dda44376d5b.png)

**Comment by dpo007** [comment] 2017-07-01 18:32
I'm experiencing exactly the same thing. Only difference is my Win10 build is currently 16193.1001.

**Comment by bgelens** [comment] 2017-07-01 19:15
Same as #742 Temporary workaround is explained in that issue

**Comment by rdtechie** [comment] 2017-07-06 10:39
Having the same issue with insider build 16232. The workaround that @bgelens is referencing to still works.

**Comment by kborowinski** [comment] 2017-07-07 10:10
I have the same issue on Windows 7 and Windows 10 but only when trying to debug in a temporary PowerShell Integrated Console.

OS: Windows 7 / Windows 10
VS Code: 1.13.1 / 1.14.0
PowerShell Extension: 1.4.1

**Comment by daviwil** [comment] 2017-07-11 09:50
Closing as duplicate of #742.  Thanks Ben!

**Closed by daviwil** 2017-07-11 09:50 UTC
