### ISSUE TITLE
PowerShell Integrated Console crashes upon startup

### ISSUE THREAD

**Issue by neumaian** [PowerShell/vscode-powershell#1444] opened 2018-07-20 09:55 UTC
### System Details

- Operating system name and version: macOS High Sierra 10.13.6
- VS Code version: 1.25.1
- PowerShell extension version: 1.8.1
- Output from `$PSVersionTable`:

PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
Unable to get following information due to crash:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

Upon startup of VS Code and loading of a PS Script the integrated console tries to start. Immediately the following happens:

PowerShell Integrated Console

stat: cannot read file system information for '%A': No such file or directory

Permissions to the pipe file were not set properly. Expected: 600 Actual:   File: "/var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_08e5bc47-6a7a-4bf0-a6d3-29382d684af4"     ID: 100000400000018 Namelen: ?       Type: apfs Block size: 4096       Fundamental block size: 4096 Blocks: Total: 61202533   Free: 29361808   Available: 28934011 Inodes: Total: 9223372036854775807 Free:9223372036853114215 for file: /var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_08e5bc47-6a7a-4bf0-a6d3-29382d684af4

With a message "The language service could not be started:"

Tested with both, PS 6.1.0 Preview 2 and 6.0.3

The permissions of the mentioned file above:
srw------- 1 adrian staff 0 Jul 20 11:47 CoreFxPipe_PSES_08e5bc47-6a7a-4bf0-a6d3-29382d684af4

### Attached Logs
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2213384/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2213385/vscode-powershell.log)

**Comment by tylerl0706** [comment] 2018-07-20 14:13
Thanks for this! Can you run `stat -f "%A" $PipeFile` and let me know what you get?

**Comment by neumaian** [comment] 2018-07-21 05:16
Here you go:

PS /Users/adrian> stat -f "%A" $PipeFile                                     
620

**Comment by neumaian** [comment] 2018-07-30 14:53
Problem exists with 1.8.2 as well.

**Comment by neumaian** [comment] 2018-07-30 15:02
With 1.7.0, everything is okay.

**Comment by ehagen** [comment] 2018-07-31 18:58
I have same problem on osx High Sierra 10.13.6 when staring debug session (F5 in vscode)

VSCode version 1.25.1
Powershell module: 1.8.2.

Error:
chmod: /var/folders/jq/wvssr6x90cdb2h1b4ly5n6l80000gn/T/CoreFxPipe_PSES_10ab90e9-4beb-4729-b1a9-d9f9cb63e63e: No such file or directory
stat: /var/folders/jq/wvssr6x90cdb2h1b4ly5n6l80000gn/T/CoreFxPipe_PSES_10ab90e9-4beb-4729-b1a9-d9f9cb63e63e: stat: No such file or directory

Permissions to the pipe file were not set properly. Expected: 600 Actual:  for file: /var/folders/jq/wvssr6x90cdb2h1b4ly5n6l80000gn/T/CoreFxPipe_PSES_10ab90e9-4beb-4729-b1a9-d9f9cb63e63e

PWSH version:
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.3
PSEdition                      Core
GitCommitId                    v6.0.3
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Previous version 1.7* worked okay

**Comment by tylerl0706** [comment] 2018-07-31 21:10
@neumaian + @ehagen: I have a feeling that something is touching the named pipe file before vscode can connect to it. Can you both turn on Diagnostic logging and attach the logs here?

Here are the steps: https://github.com/powershell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

Note: this will add a 3rd file to the log directory. We need all 3 please.

Very strange that you're running into this... my daily driver is a mac and I've not run into this. We'll figure it out.

**Comment by tylerl0706** [comment] 2018-08-01 07:25
Sorry I should have clarified - Can you switch it from "Verbose" to "Diagnostic"?

**Comment by neumaian** [comment] 2018-08-01 07:26
No change with PS 6.1.0 Preview 4 btw, have changed now to Diagnostic, waiting for Logfiles.

**Comment by neumaian** [comment] 2018-08-01 07:27
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2248422/EditorServices.log)
[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2248423/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2248424/vscode-powershell.log)

The Logs are now with PS 6.1.0 Preview 4

**Comment by tylerl0706** [comment] 2018-08-01 08:02
Can you run:

```powershell
Test-Path /var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_bd3eb46c-9480-403a-a641-9633b7dff71f
```

And let me know what you get back?

**Comment by neumaian** [comment] 2018-08-01 10:34
PS /Users/adrian> Test-Path /var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_bd3eb46c-9480-403a-a641-9633b7dff71f
True

**Comment by ehagen** [comment] 2018-08-01 17:34
Installed 6.1 preview 4 and issue stays. I use setting: "powershell.debugging.createTemporaryIntegratedConsole": true,
and I have C# for Visual Studio Code (powered by OmniSharp) also installed and active in same workspace.

**Comment by tylerl0706** [comment] 2018-08-01 17:59
ok so there seem to be two issues here. For context, here is the function that sets the permissions of the pipe:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/module/PowerShellEditorServices/Start-EditorServices.ps1#L220-L244

1. @neumaian has an issue where... the result of stat is different than what we expect:

```
ExitWithError "Permissions to the pipe file were not set properly. Expected: $DEFAULT_USER_MODE Actual: $mode for file: $PipeFile"
```
prints out:
```
Permissions to the pipe file were not set properly. Expected: 600 Actual:   File: "/var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_e355777d-c447-4c86-8bf7-2640ee1d0fdd"     ID: 100000600000018 Namelen: ?       Type: apfs Block size: 4096       Fundamental block size: 4096 Blocks: Total: 61202533   Free: 29803586   Available: 28851502 Inodes: Total: 9223372036854775807 Free: 9223372036853103063 for file: /var/folders/s0/4w848hkn4wj44s5gwc2pgsmh0000gn/T/CoreFxPipe_PSES_e355777d-c447-4c86-8bf7-2640ee1d0fdd
```

Notice that the `$mode` variable is full of garbage instead of being set to just a number like 600?

@neumaian are you aware of any other `stat` utilities on your machine/in your profile? Or really anything that could interfere with chmod/stat?

2. @ehagen on the other hand seems to be running into an issue where the pipe file isn't even being created/is disappearing before vscode can connect to it. Can you please supply the logs so we can look into this further? 

Here are the steps: https://github.com/powershell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us please set it to "Diagnostic" instead of "Verbose".

I still can't repro either of your situations on my own macbook pro - @rjmholt can you try to repro?

**Comment by neumaian** [comment] 2018-08-01 20:55
It's just an assumption of mine, but I prefer the GNU Coreutils over the more BSDish commands of macOS on the console. And the stat of macOS (located under /usr/bin/stat) and the stat from coreutils are taking different command line parameters, so that may be the issue here seeing all this garbage instead of just 600. Have to test my theory tomorrow though. The one thing i don't understand here, why is 1.7.0 working whereas 1.8.* is not? Has there been any change in regard of executing the stat command?

**Comment by tylerl0706** [comment] 2018-08-01 20:59
@neumaian yeah the change was made in 1.8.0 to go from using TCP to communicate to using Named Pipes. The stat call is a new addition in 1.8.0 to ensure security is being enforced.

If you want to change the Start-EditorServices file to use `/usr/bin/stat` that might be a good way to test this.

Let me know what you find out!

**Comment by tylerl0706** [comment] 2018-08-01 21:02
I just tried on Fedora 28... stat -f "%A" $pipeName gives exactly what your log says. That's the problem.

I think for macOS we should add the path to stat ( `/usr/bin/stat`) to prevent the issue you're running into.

**Comment by tylerl0706** [comment] 2018-08-01 21:04
Ideally PowerShell should have an abstraction for this as getting file permissions would be useful, but I've not found a good way to do that.

**Comment by neumaian** [comment] 2018-08-02 06:51
I can confirm the following fixes the problem:

--- Start-EditorServices.ps1.orig	2018-08-02 08:48:00.000000000 +0200
+++ Start-EditorServices.ps1	2018-08-02 08:48:44.000000000 +0200
@@ -235,7 +235,7 @@
         $mode = stat -c "%a" $PipeFile
     }
     elseif ($IsMacOS) {
-        $mode = stat -f "%A" $PipeFile
+        $mode = /usr/bin/stat -f "%A" $PipeFile
     }
 
     if ($mode -ne $DEFAULT_USER_MODE) {

**Comment by rjmholt** [comment] 2018-08-15 21:09
This should work now with the latest release. I'll close the issue for now and if the issue is ongoing we can reopen.

**Closed by rjmholt** 2018-08-15 21:09 UTC
Labels: Area-General, Issue-Bug, OS-macOS
