### ISSUE TITLE
Preview 2019.11.0/1 Read-Host paste dropping letters.

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2291] opened 2019-11-06 23:37 UTC
Issue Type: <b>Bug</b>

Same as in https://github.com/PowerShell/vscode-powershell/issues/1753 but only when pasting and sometime it misses random letters and not just the first one.   

1. Copy something.
2. Run a file with Read-Host with F5.
3. Paste in console.
![Paste](https://user-images.githubusercontent.com/6960531/68282672-bc1d3280-0082-11ea-96c8-1ab92672f354.gif) 

Extension version: 2019.11.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by SydneyhSmith** [comment] 2019-11-12 22:21
@ili101 thanks for opening this issue! We are able to reproduce this and are investigating what may be causing this.

**Comment by SydneyhSmith** [comment] 2020-01-30 22:47
@ili101 we have published a fix for this, please let us know if you are still hitting this issue--thanks!

**Comment by ili101** [comment] 2020-02-23 22:20
Still a problem on 2020.2.0 Preview

**Comment by TylerLeonhardt** [comment] 2020-02-25 01:36
This doesn't repro on non-Windows. I'll have to try when I get into the office tomorrow.

@SeeminglyScience any thoughts?

**Comment by SeeminglyScience** [comment] 2020-02-25 02:20
Maybe race condition here?

https://github.com/PowerShell/PowerShellEditorServices/blob/4c12d38a3f08d92c90846fa1dbb8a71495c4ad48/src/PowerShellEditorServices/Services/PowerShellContext/Console/WindowsConsoleOperations.cs#L35-L54

Maybe because the handle is released before the field is nulled?

Shot in the dark, if that doesn't pan out let me know and I'll take a closer look.

**Comment by TylerLeonhardt** [comment] 2020-02-25 18:30
This only seems to affect the _first_ call to Read-Host and only when running with debugging (F5)

**Comment by SeeminglyScience** [comment] 2020-02-25 18:35
Oh you know what, I bet the PSRL `ReadKey` thread isn't getting cancelled.

**Comment by TylerLeonhardt** [comment] 2020-02-25 18:37
But wouldn't subsequent F5's have the same issue then?

**Comment by TylerLeonhardt** [comment] 2020-02-26 02:48
Ok I've got a PR out for this!

**Closed** 2020-02-26 17:46 UTC
Labels: Area-Debugging, Area-PSReadLine, Issue-Bug, Preview Extension, Resolution-Fixed
