### ISSUE TITLE
Error trying to attach to host process

### ISSUE THREAD

**Issue by powercode** [PowerShell/vscode-powershell#1415] opened 2018-07-09 12:30 UTC
![image](https://user-images.githubusercontent.com/3505151/42450219-bb84ed0e-8383-11e8-839e-1598c3103385.png)

Attaching works when hardcoding the PID in a launch task.

### System Details

- Win 10.0.16299
- VS Code version: 1.25.0
- PowerShell extension version: 1.7.0
- Output from `$PSVersionTable`:

```
code -v
1.25.0
0f080e5267e829de46638128001aeb7ca2d6d50e
x64

$pseditor.EditorServicesVersion : 1.7.0.0

austin.code-gnu-global@0.2.2
DavidAnson.vscode-markdownlint@0.18.0
dbaeumer.vscode-eslint@1.4.12
donjayamanne.githistory@0.4.1
DotJoshJohnson.xml@2.3.1
eamodio.gitlens@8.4.1
EditorConfig.EditorConfig@0.12.4
mitaki28.vscode-clang@0.2.2
mrcrowl.hg@1.2.3
ms-python.python@2018.6.0
ms-vscode.cpptools@0.17.6
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.7.0
robertohuertasm.vscode-icons@7.24.0
slevesque.perforce@3.1.0
tintoy.msbuild-project-tools@0.2.39
twxs.cmake@0.0.17

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with attaching to a host process.

The attach works with a hard coded pid, but not when using the VSCode dialog to select a process.

**Comment by rkeithhill** [comment] 2018-07-09 15:01
Duplicate of #1322  This has been fixed and will show up in the next release.

**Closed by rkeithhill** 2018-07-09 15:01 UTC
