### ISSUE TITLE
PowerShell process consumes CPU

### ISSUE THREAD

**Issue by dpaulson45** [PowerShell/vscode-powershell#1503] opened 2018-08-30 20:52 UTC
Issue Type: <b>Bug</b>

After a while of using Visual Studio Code with the PowerShell extention in enabled, the PowerShell process consumes a large amount of CPU like it is stuck in a loop. This is bad performance when i am not even utilizing the actual PowerShell process during my time of writing out PowerShell scripts.

Extension version: 1.8.3
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (18.69GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\dpaul\Documents\GitHub\PublicPowerShellScripts\Functions\Compress-Folder\Compress-Folder.ps1|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjmholt** [comment] 2018-08-30 23:05
Dupe of https://github.com/PowerShell/vscode-powershell/issues/1464

**Closed by rjmholt** 2018-08-30 23:05 UTC
