### ISSUE TITLE
Autocomplete doesn't suggest "pscustomobject"

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/vscode-powershell#1075] opened 2017-10-27 14:05 UTC
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.17.2
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

$pseditor.EditorServicesVersion
```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
```
code --list-extensions --show-versions
donjayamanne.githistory@0.2.3
ms-vscode.PowerShell@1.4.3

### Issue Description
When I return a pscustomobject I'm offered a variety of suggestions, but none of them are "pscustomobject".

![image](https://user-images.githubusercontent.com/91378/32107982-22391d7e-bb28-11e7-9180-f49d7c50d8ab.png)

I'd suggest that it should :-)

**Comment by rjmholt** [comment] 2019-01-08 23:43
@timoline I suspect that's a snippet completion.

So the story here is that our completions come from PowerShell's completers but are named based on the type they map to (PSReadLine does the same as it turns out). So if you type `[psc<Tab>` it shows you `PSObject` because in the type accelerator table that's what it maps to.

Try this in the PowerShell console:

```
> Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
> [psc<Tab>
```

Notice there's also no `PSCustomObject` there as well, because PSReadLine makes the same assumption &mdash; that a type accelerator is described fully by the type it maps to.

I think the only sensible solution is to specifically handle the `PSCustomObject` case when we display the completion...

**Comment by rjmholt** [comment] 2019-01-08 23:45
Oh, I should add:

If you type `[psc<Tab>` and select the `PSObject` option, you will get `[pscustomobject]`. The completion is correct, it's just named badly because the type `[pscustomobject]` maps to in the type accelerator table is `PSObject` (it sort of breaks the "type accelerator" concept, since `[psobject]` also points to that type, but they still do different things).

**Comment by SydneyhSmith** [comment] 2020-03-17 18:35
Closing as a duplicate of #1149

**Closed by SydneyhSmith** 2020-03-17 18:35 UTC
Labels: Area-IntelliSense, Issue-Enhancement
