### ISSUE TITLE
Temporary Powershell integrated terminal in VSCode crashes Ubuntu

### ISSUE THREAD

**Issue by solomonsunder** [PowerShell/vscode-powershell#2471] opened 2020-02-14 09:30 UTC
### System Details

- Operating System: Ubuntu 18.04.4 LTS
- VS Code Version: 1.42
- Powershell Extension Version: 2020.1.0

> code -v
> 1.42.0
> ae08d5460b5a45169385ff3fd44208f431992451
> x64

> $PSVersionTable
> Name                           Value
> ----                           -----
> PSVersion                      6.2.4
> PSEdition                      Core
> GitCommitId                    6.2.4
> OS                             Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
> Platform                       Unix
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

> 
> $pseditor.EditorServicesVersion
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 1      13     3      0

> $(code --list-extensions --show-versions | Out-String)
> amazonwebservices.aws-toolkit-vscode@1.6.1
> ms-azuretools.vscode-azureterraform@0.3.0
> ms-azuretools.vscode-docker@0.10.0
> ms-python.python@2020.2.63072
> ms-vscode-remote.remote-containers@0.101.0
> ms-vscode-remote.remote-ssh@0.49.0
> ms-vscode-remote.remote-ssh-edit@0.49.0
> ms-vscode-remote.remote-wsl@0.42.3
> ms-vscode-remote.vscode-remote-extensionpack@0.19.0
> ms-vscode.azure-account@0.8.8
> ms-vscode.csharp@1.21.11
> ms-vscode.powershell@2020.1.0
> redhat.vscode-xml@0.10.1

### Issue Description

Powershell Temporary Integrated Terminal does not startup when the debug icon is clicked. Gives below error:

>     PowerShell Integrated Console
> 
>     /bin/chmod: cannot access '/tmp/CoreFxPipe_PSES_zhv4igvh.xwb': No such file or directory
> 
>     /usr/bin/stat: cannot stat '/tmp/CoreFxPipe_PSES_zhv4igvh.xwb': No such file or directory
> 
>     Permissions to the pipe file were not set properly. Expected: 600 Actual: for file:
> 
>     /tmp/CoreFxPipe_PSES_zhv4igvh.xwb

### Attached Logs
[DebugSession-3.log](https://github.com/PowerShell/vscode-powershell/files/4203741/DebugSession-3.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4203742/EditorServices.log)
[Start-EditorServices-DebugSession-3.log](https://github.com/PowerShell/vscode-powershell/files/4203743/Start-EditorServices-DebugSession-3.log)
[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4203744/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4203745/vscode-powershell.log)

###Related Issue
https://github.com/PowerShell/vscode-powershell/issues/1422

**Comment by rjmholt** [comment] 2020-02-14 13:39
Hi @solomonsunder, have you tried out your scenario with the `PowerShell Preview`? That uses a totally different mechanism to create the named pipe, so this issue may well be fixed there.

The preview extension will be delivered to to stable in the next week or so, so keep an eye out for the next update there too.

**Comment by TylerLeonhardt** [comment] 2020-02-14 17:12
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/1422

**Closed** 2020-02-15 19:00 UTC
Labels: Resolution-Duplicate
