### ISSUE TITLE
PowerShell Extension 2020.4.0 Crashes VS Code during load

### ISSUE THREAD

**Issue by tonsanchez** [PowerShell/vscode-powershell#2638] opened 2020-04-17 07:49 UTC
### System Details

1. Windows 10, 1903
2. VS Code v1.44.1 (System Setup)
3. PowerShell Extension v2020.4.0
4. Symantec Endpoint Protection 14.2.5323.2000
4. $PSVersionTable

```
PSVersion 5.1.18362.628
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.18362.628
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

### Issue Description

Fresh installed everything, right after launching VS Code and searched for PowerShell in Marketplace. Installing it crashes VS Code (I needed to force it to close and manually deleting the extension folder in %userprofile%\.vscode to be able to launch VS Code properly).

### Logs

```
4/17/2020 3:25:06 PM [NORMAL] - powershell.exe started.
4/17/2020 3:25:06 PM [NORMAL] - Waiting for session file
4/17/2020 3:27:06 PM [NORMAL] - Error occurred retrieving session file:
Timed out waiting for session file to appear.
4/17/2020 3:27:06 PM [NORMAL] - Language server startup failed.
4/17/2020 3:27:06 PM [ERROR] - The language service could not be started: 
4/17/2020 3:27:06 PM [ERROR] - Timed out waiting for session file to appear.
```

**Comment by EdCallahan** [comment] 2020-04-17 13:37
Similar problem here: https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-611122644

**Comment by tonsanchez** [comment] 2020-04-17 14:32
FWIW, I had the same set installed on my personal rig WITHOUT Symantec Endpoint Protection (Same Windows version, same VS Code and PowerShell extension version) and I did not encounter the issue. This is only happening on PowerShell extension, as other extensions I installed (e.g. C/C++ and Python) worked just fine with my workstation laptop.

**Comment by EdCallahan** [comment] 2020-04-20 22:35
What if you try and start with PowerShell 5.1 x86 @tonsanchez? Do do that on my computer I can edit "$env:AppData\Code\User\settings.json" and set the default powershell version with:

"powershell.powerShellDefaultVersion": "Windows PowerShell (x86)"

I run with very little delay running x86, and even faster with PowerShell 7.0. The crippling delay is only from PowerShell 6.1 x64 on my boxes.

**Comment by TylerLeonhardt** [comment] 2020-04-21 00:15
@tonsanchez if Symantec has any sort of logs that you can retrieve, that would be _greatly_ appreciated. There's something we ship/do that it and other AVs don't like and I wanna know what it is.

**Comment by tonsanchez** [comment] 2020-04-21 09:09
> "powershell.powerShellDefaultVersion": "Windows PowerShell (x86)"

Tried this one and VS Code was able to successfully load the PowerShell extension.

**Comment by EdCallahan** [comment] 2020-04-21 16:11
@tonsanchez it sounds like our problems are probably the same. Are you running Avecto/BeyondTrust on the workstation you are having problems with? I'm wondering if the problem doesn't lay there.

**Comment by SydneyhSmith** [comment] 2020-04-21 21:08
Thanks everyone I am going mark this as a duplicate of #2526

**Comment by tonsanchez** [comment] 2020-04-22 08:19
> @tonsanchez it sounds like our problems are probably the same. Are you running Avecto/BeyondTrust on the workstation you are having problems with? I'm wondering if the problem doesn't lay there.
> 
> Here's another case of this problem with someone running Avecto: #2066

That's right. My workstation laptop is also running Avecto/BeyondTrust.

**Closed** 2020-04-23 22:00 UTC
Labels: Resolution-Duplicate
