### ISSUE TITLE
Startup of Integrated Terminal does not show cursor/prompt initially

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#1682] opened 2019-01-05 17:50 UTC
Issue Type: <b>Bug</b>

Starting up the PowerShell Extension's integrated terminal does not seem to show the initial start of the host (e.g. header, initial prompt). I have to hit enter about 4 times (repeated test a couple of times).

The below example is just restarting the extension while in VS Code, but it does the same thing if I reload VS Code itself:

![integratedconsole_start](https://user-images.githubusercontent.com/11204251/50727390-ee1adc80-10df-11e9-8189-83a0d29ef4e1.gif)

Extension version: 1.10.2
VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:17:20.719Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.92GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by wsmelton** [comment] 2019-01-05 17:53
Adding the logs for reference. I am using PS Core for both VS Code terminal and the extension terminal. I do not see this behavior in VS Code for "the" terminal.

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2729722/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2729723/vscode-powershell.log)

**Comment by SydneyhSmith** [comment] 2019-01-08 22:22
@wsmelton thanks for reporting this and including logs! Is there anything in your profile that writes to the host?

**Comment by wsmelton** [comment] 2019-01-09 02:04
I don't have anything that writes to the host on import in my profile. I set some `PSDefaultParameters` and a handful of other variables, then have some functions included.

I can't upload my profile script so just pasted below:

```powershell
Import-Module posh-git
if (Get-Module posh-git) {
    $GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true
    $GitPromptSettings.BeforeForegroundColor = [ConsoleColor]::Cyan
    $GitPromptSettings.DefaultPromptEnableTiming = $true
    $GitPromptSettings.DefaultPromptSuffix = '`n> '
}

$SubKey = 'redacted'
$ghGeneralToken = 'redacted'

$pwd = "P@ssword12345" | ConvertTo-SecureString -AsPlainText -Force
$containerCred = New-Object System.Management.Automation.PSCredential -ArgumentList 'sa', $pwd
$PSDefaultParameterValues = @{
    "dbatools*:SqlCredential" =$containerCred
    "dbatools*:Source"        = "localhost,1417"
    "dbatools*:Destination"   = "localhost,1418"
    "*:Subscription"          ='dbatools'
    "*:AutomationAccountName" ="dbatools-aa"
    "*:ResourceGroupName"     ="ag-testing"
}

function Update-AzMinimum {
    Update-Module Az.Profile, Az.Storage, Az.Automation, Az.Sql, Az.OperationalInsights -Force
}

function rdp {
    [cmdletbinding()]
    param (
        $server,
        [switch]$fullScreen
    )

    if ($fullScreen) {
        mstsc -v $server -f
    } else {
        mstsc -v $server /w 1825 /h 980
    }
}

function New-SqlContainer {
    param(
        [string]$path = 'c:\temp\sql19\docker-compose.yml'
    )

    docker-compose -f $path up -d --build --force-recreate
}


$slackSqlCommunity = 'redacted'



Copy-Item ((Join-Path -Path (Split-Path $profile) -ChildPath Microsoft.PowerShell_profile.ps1)) -Destination 'C:\Users\wshaw\OneDrive\Documents\Scripts\PowerShell\Current_Microsoft.PowerShell_Core_profile.ps1'

# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
    Import-Module "$ChocolateyProfile"
}
```

**Comment by wsmelton** [comment] 2019-01-09 02:07
I have disabled all my extensions, except the PowerShell one and still get the same result.

Current build I'm on now:
```
Version: 1.31.0-insider (system setup)
Commit: 7b375fcb821bee9342656c39492223c7b5fc8830
Date: 2019-01-08T09:30:46.424Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by SeeminglyScience** [comment] 2019-01-09 14:07
@wsmelton Can you check if your profile is being marked as from the internet? e.g.

![Blocked Properties Example](https://user-images.githubusercontent.com/24977523/50904226-cb453c80-13ed-11e9-8158-f13435ff3bc2.png)

**Comment by wsmelton** [comment] 2019-01-09 16:59
@SeeminglyScience when files are within your profile on Windows there is no unblocking option or "marked as from the internet", all files become trusted.

![image](https://user-images.githubusercontent.com/11204251/50915102-ae186a00-13fd-11e9-9db6-3bc7a7ff60fd.png)

**Comment by wsmelton** [comment] 2019-01-09 17:00
I'm more than happy to do a screen share if someone wants to dig around on my system with this....it is my own device and not a company's.

**Comment by SeeminglyScience** [comment] 2019-01-09 18:21
@wsmelton 

> when files are within your profile on Windows there is no unblocking option or "marked as from the internet", all files become trusted.

Thanks for checking! Yeah you don't see the option to unblock if the file isn't marked as from the internet.  FYI all that matters in that determination is the [alternate data stream](https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/) for [zone identifier](https://msdn.microsoft.com/en-us/library/dn392609.aspx).  For example, the `Downloads` folder in your profile likely has a bunch of files marked as remote.  I had a hunch that the line in your profile that copied your profile from OneDrive might be causing the profile to be marked as untrusted.  I don't use OneDrive personally though, so I couldn't test if added the ADS.

> Adding the logs for reference. I am using PS Core for both VS Code terminal and the extension terminal. I do not see this behavior in VS Code for "the" terminal.

So just to clarify you see this behavior in both the "PowerShell Integrated Console" *and* the default terminal?  Which is the third terminal where you do not see the behavior?

If you see it outside of the integrated console, can you see if it still occurs when *all* extensions (including this one) are disabled?

Could you also try with your profile file renamed or commented out?

**Comment by wsmelton** [comment] 2019-01-09 20:52
I do not see this behavior in the default pwsh/integrated console for VS Code, only the host with the extension.

I have had the line for OneDrive in there for a long time, and it is only recent update of the extension and/or VS Code that has caused this issue to occur.

I reverted the extension back to 1.10.1 and this issue goes away.

**Comment by wsmelton** [comment] 2019-01-09 20:57
Ah, interesting point....having 1.10.2 extension installed.

My original setup was with PS Core and the extension was simply using my PowerShell profile (`$env:USERPROFILE\Documents\PowerShell\Microsoft.PowerShell_profile.ps1`). So I went ahead and created the `$env:USERPROFILE\Documents\PowerShell\Microsoft.VSCode_profile.ps1` and simply have it dot source my main profile (had to do with Windows PowerShell as well so I don't duplicate updates).

Now the prompt is immediately provided after the extension starts up.

**Comment by wsmelton** [comment] 2019-01-10 13:21
Ok, never mind. After a few restarts of VS Code (and at some point my machine) the VS Code profile being in place does not fix it.

**Comment by corbob** [comment] 2019-01-21 22:55
I don't think this actually has anything to do with the extension. I've been experiencing this for months, and it occurs with the integrated terminal when set to cmd: 
![vscode terminal funniness](https://user-images.githubusercontent.com/30301021/51502718-1ebf6f00-1d8c-11e9-97e5-cd8100bbea96.gif)

**Comment by wsmelton** [comment] 2019-01-21 23:39
Ha, it works fine for me in Code's terminal.

**Comment by DigitalPZ** [comment] 2019-02-15 12:47
I am having the exact same issue as shown above. Terminal opens and is blank. 
![image](https://user-images.githubusercontent.com/30343838/52857556-851e7f80-30f5-11e9-9d3f-9745f2145ffa.png)

If I scroll up I see the Windows Powershell startup messages but there is no prompt. I can type a command like dir and after it executes the prompt shows up.

**Comment by rkeithhill** [comment] 2019-02-15 16:00
I see the issue in the default terminal (pwsh in my case) which leads me to believe (along with @corbob ) that this is not an issue with the extension.

**Comment by wsmelton** [comment] 2019-02-15 16:01
The issue does not exist for me in default terminal, at least on PS Core. It open up with no delay.

**Comment by rkeithhill** [comment] 2019-02-15 16:07
This is what I see when I open a workspace in VSCode.  I have my default, integrated terminal set to pwsh on Windows:

![image](https://user-images.githubusercontent.com/5177512/52868449-9d47cc00-3100-11e9-812a-f631d0755a4c.png)

After I focus in the terminal and press <kbd>Enter</kbd>, I get my normal prompt:

![image](https://user-images.githubusercontent.com/5177512/52868499-bd778b00-3100-11e9-99da-781456e4eb14.png)

**Comment by DigitalPZ** [comment] 2019-02-15 16:07
> The issue does not exist for me in default terminal, at least on PS Core. It open up with no delay.

Is there a way to switch over to PS Core? I think I'm just using whatever was installed with Windows 10.

**Comment by rkeithhill** [comment] 2019-02-15 16:08
Yup, add this to your user settings:
```
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6\\pwsh.exe",
```

**Comment by wsmelton** [comment] 2019-02-15 16:09
Yeah oddly enough Keith I don't have that issue. Focused or not I have
always gotten the prompt on pwsh.

**Comment by DigitalPZ** [comment] 2019-02-15 16:11
Keith, where do I find those user settings you are referring to? Is this settings for VS Code?

**Comment by gwojan** [comment] 2019-02-15 16:32
Ugh. This problem didn't start for me until I upgraded my work laptop to Windows 10 1809, FWIW.

**Comment by DigitalPZ** [comment] 2019-02-15 16:40
> Ugh. This problem didn't start for me until I upgraded my work laptop to Windows 10 1809, FWIW.

I bet you have something there. My work laptop does not have the problem and is on an older version of Windows 10. My home PC is on 1809 as well and has the problem.

**Comment by DigitalPZ** [comment] 2019-02-15 16:53
Just switched over to PS Core and still have the same problem. On Windows 10 Enterprise V 1809, Build 17763.316

**Comment by janegilring** [comment] 2019-02-15 17:37
According to @tyriar this is an issue in Windows: https://github.com/Microsoft/vscode/issues/57803

**Comment by rkeithhill** [comment] 2019-02-16 01:23
Yup, it appears to be an issue with console host in 1809 - not the extension.  Looks like it will be fixed in Windows 10 19H1.

**Closed by rkeithhill** 2019-02-16 01:23 UTC
Labels: Area-Integrated Console, Issue-Performance

**Comment by janegilring** [comment] 2019-02-16 10:26
One possible workaround is adding "cls" to the PowerShell profile. Not optimal, but might save some keystrokes until the issue is fixed in Windows.

**Comment by DigitalPZ** [comment] 2019-02-16 12:26
> One possible workaround is adding "cls" to the PowerShell profile. Not optimal, but might save some keystrokes until the issue is fixed in Windows.

Not pretty but it worked for me. Thx.
