### ISSUE TITLE
Option to disable the PSIC Logo

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/vscode-powershell#2378] opened 2019-12-19 13:57 UTC
**Summary of the new feature**

As a user I want Not to see the large PSIC logo which appeared in Preview December 2019. *

I'd also advise choosing a name for like "PIC" for PowerShell integrated console might be better than something which reads aloud as "Pee Sick." :-) 

**Proposed technical implementation details (optional)**
NoLogo option in the settings JSON. 
 

* I'm sorry, genuinely, for what must seem like being a miserable s.o.b about this kind of thing. I can't use a screen if there is something flashing on it (before add blockers I actually had to hold a hand up in front of the screen to be able to use some web sites). Rainbow text has an effect on me like fingernails on a blackboard on other people. Monochrome logos aren't as bad...  I don't know if it is a condition with a name (other than than "being a s.o.b".)

**Comment by JustinGrote** [comment] 2019-12-19 15:15
Dupe of #2370

**Comment by TylerLeonhardt** [comment] 2019-12-19 18:07
Yeah let's close this as a dupe of #2370.

**Closed by TylerLeonhardt** 2019-12-19 18:07 UTC
Labels: Needs: Triage :mag:

**Comment by jhoneill** [comment] 2019-12-19 20:39
Oops. Didn't read the list of issues properly.
