### ISSUE TITLE
-ShowWindow parameter in Get-Help 

### ISSUE THREAD

**Issue by CharlesSpencer** [PowerShell/vscode-powershell#973] opened 2017-07-24 19:46 UTC
### System Details

- Operating system name and version: Windows 10 Enterprise 64-bit 1703
- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion 1.1.0.1
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
PS I:\Admin\Scripts> code -v
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ code -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS I:\Admin\Scripts> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

PS I:\Admin\Scripts> code --list-extensions --show-versions
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ code --list-extensions --show-versions
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS I:\Admin\Scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion 1.1.0.1

### Issue Description

I am experiencing a problem with the -ShowWindow parameter of the PowerShell Get-Help cmdlet.  The parameter works successfully in PowerShell ISE.  In Visual Studio Code, I get the error

PS I:\Admin\Scripts> get-help get-command -ShowWindow
get-help : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ get-help get-command -ShowWindow
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Help], TargetInvocationException
      + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,Microsoft.PowerShell.Commands.GetHelpCommand

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment] 2017-08-14 23:20
Duplicate of issue https://github.com/PowerShell/vscode-powershell/issues/753.

**Closed by daviwil** 2017-08-14 23:20 UTC
Labels: Resolution-Duplicate
