### ISSUE TITLE
Integrated Console fails to load when Newtonsoft.Json fails to parse valid settings.json

### ISSUE THREAD

**Issue by brettpostin** [PowerShell/vscode-powershell#2812] opened 2020-07-17 11:34 UTC
Issue Description
=====

With the following in settings.json:

```
    "files.exclude": {
        "**/*.js": {"when": "$(basename).ts"}
    },
```

The PowerShell Integrated Console fails to load, it just hangs before reaching the command prompt. Removing the above setting fixes the issue, however it is a valid setting to hide generated .js files in a typescript project.

Logs
=====

In EditorServices.log:
```
2020-07-17 12:25:19.294 +01:00 [FTL] Failed to handle request workspace/didChangeConfiguration
Newtonsoft.Json.JsonReaderException: Error reading boolean. Unexpected token: StartObject. Path 'files.exclude['**/*.js']'.
```

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.47.2|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|csharp|ms-dotnettools|1.22.1|
|powershell|ms-vscode|2020.6.0|
|sonarlint-vscode|SonarSource|1.16.0|
|vscode-azurefunctions|ms-azuretools|0.23.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vsliveshare|ms-vsliveshare|1.0.2427|

**Comment by rjmholt** [comment] 2020-07-20 23:51
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2658

**Closed** 2020-07-22 01:00 UTC
Labels: Resolution-Duplicate
