### ISSUE TITLE
Comment Help Badly Broken

### ISSUE THREAD

**Issue by mattpwhite** [PowerShell/vscode-powershell#1540] opened 2018-09-21 15:44 UTC
### System Details
```
[PS 5.1] ~ $ code -v
1.27.1
5944e81f3c46a3938a82c701f96d7a59b074cfdc
x64
[PS 5.1] ~ $ $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      4      0


[PS 5.1] ~ $ code --list-extensions --show-versions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
DotJoshJohnson.xml@2.3.2
eamodio.gitlens@8.5.6
k--kato.docomment@0.1.2
ms-vscode.cpptools@0.18.1
ms-vscode.csharp@1.16.1
ms-vscode.PowerShell@1.8.4
robertohuertasm.vscode-icons@7.26.0
[PS 5.1] ~ $ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.1292
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1292
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Using `##` to insert a help block seems to be broken pretty badly.  See below.

![broken-help](https://user-images.githubusercontent.com/3004040/45891428-95733e00-bd93-11e8-9f4b-be7255a98c77.gif)

### Attached Logs
[1537544346-abc98747-b062-4656-813c-b7a3fb0a1f0b1537544225572.zip](https://github.com/PowerShell/vscode-powershell/files/2406021/1537544346-abc98747-b062-4656-813c-b7a3fb0a1f0b1537544225572.zip)

**Comment by rjmholt** [comment] 2018-09-21 16:50
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1509.

Originally caused by https://github.com/PowerShell/PowerShellEditorServices/pull/715, and fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/740.

**Closed by rjmholt** 2018-09-21 16:50 UTC

**Comment by mattpwhite** [comment] 2018-09-21 17:13
Sorry for the dupe (and the bug, which I guess was mine) :/

**Comment by rjmholt** [comment] 2018-09-21 17:28
Haha, no worries! It ain't fixed til it's released -- so I'm hoping we can do that next week at some point.

We got comment help *above* the function working and released first, so one "workaround" is to expand the comment help snippet *above* the function and then cut/paste it below the function.
