### ISSUE TITLE
PowerShell not showing correct error

### ISSUE THREAD

**Issue by Al-Mond** [PowerShell/vscode-powershell#1666] opened 2018-12-19 22:25 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rjmholt** [comment] 2018-12-20 00:12
> We have written the needed data into your clipboard because it was too large to send. Please paste.

Not sure what this means.

Can you provide more information?

Please see our [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md).

**Comment by Al-Mond** [comment] 2018-12-21 19:32
Sorry, something turned that whole thing into nonsense. Let me write it out again. 

This is something I've noticed with the AD modules, but I think I've seen similar posts somewhere (I couldn't find them). If I run this command in VSCode Insiders 1.31.0:

New-ADGroup -Name $deptGrp -Path $grpPath 

There's the error it dumps:
Generic types are not supported for input fields at this time.
At line:1 char:1
+ New-ADGroup -Name $deptGrp -Path $grpPath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : Argument

If I do the same thing in ISE, it prompts me for the other mandatory switch, -groupScope.

**Comment by rjmholt** [comment] 2018-12-22 01:48
Can you try getting the result of `$error[0] | fl * -Force` after such a command?

It sounds like you might be experiencing an invocation error that is by design but that PSReadLine and the ISE step in to catch and prompt for more input in some way. What happens when you run such a command in the PowerShell console (not the Integrated Console and not ISE)

**Comment by Al-Mond** [comment] 2018-12-27 17:38
Here's the output of the $error[0] command: 

`PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: Generic types are not supported for input fields at this time. --->
                        System.Management.Automation.PSArgumentException: Generic types are not supported for input fields at this time.
                           at Microsoft.PowerShell.EditorServices.Console.FieldDetails..ctor(String name, String label, Type fieldType, Boolean
                        isMandatory, Object defaultValue)
                           at Microsoft.PowerShell.EditorServices.Console.FieldDetails.Create(FieldDescription fieldDescription, ILogger logger)
                           at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
                           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
                           at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.Prompt(String promptCaption, String
                        promptMessage, Collection`1 fieldDescriptions)
                           at System.Management.Automation.Internal.Host.InternalHostUserInterface.Prompt(String caption, String message,
                        Collection`1 descriptions)
                           at System.Management.Automation.CmdletParameterBinderController.PromptForMissingMandatoryParameters(Collection`1
                        fieldDescriptionList, Collection`1 missingMandatoryParameters)
                           at System.Management.Automation.CmdletParameterBinderController.HandleUnboundMandatoryParameters(Int32
                        validParameterSetCount, Boolean processMissingMandatory, Boolean promptForMandatory, Boolean isPipelineInputExpected,
                        Collection`1& missingMandatoryParameters)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                        CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections,
                        FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : Argument
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}`

When I open up a PowerShell console and run it, it prompts me for the mandatory parameter GroupScope. 

 Thanks!

**Comment by rjmholt** [comment] 2019-01-08 23:05
> When I open up a PowerShell console and run it, it prompts me for the mandatory parameter GroupScope.

Yeah I think PSReadLine is handling this in a user-friendly way. If you do:
```
> rmo PSReadLine
> New-ADGroup -Name $deptGrp -Path $grpPath 
```
in a PowerShell console, I'd expect the same error (provided PSReadLine is actually unloaded).

In which case, this might well be fixed by https://github.com/PowerShell/vscode-powershell/issues/535, and if not, would be much easier to fix after that's in.

**Comment by SydneyhSmith** [comment] 2019-03-27 17:13
Closing this as PSReadline is now available in the PowerShell Preview extension, will re-open if this doesn't solve the probelm..also tracking the lack of PS Readline in the PowerShell extension with this issue #1793

**Closed by SydneyhSmith** 2019-03-27 17:13 UTC
Labels: Area-PSReadLine, Issue-Enhancement
