### ISSUE TITLE
Integrated Terminal can't interact with Azure API

### ISSUE THREAD

**Issue by jontreynes** [PowerShell/vscode-powershell#926] opened 2017-06-27 17:59 UTC
### System Details

- Operating system name and version:
- VS Code version: 1.13.1
- PowerShell extension version: 
ms-vscode.PowerShell@1.4.1
msazurermtools.azurerm-vscode-tools@0.3.5
- Output from `$PSVersionTable`: 
Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...
running login-azurermaccount in the integrated terminal. It just hangs there...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment] 2017-06-28 14:14
The window is there, hit Alt+Tab and you'll see it.  Closing as a duplicate of issue #541

**Closed by daviwil** 2017-06-28 14:14 UTC
