### ISSUE TITLE
No console error output shown.

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#2583] opened 2020-03-24 23:10 UTC
Issue Description
=====

I am experiencing a problem whereby I don't get any output from a `throw()` statement.

**Update**
This is more wide spread than just throw. Cmdlets and .NET calls also do not show any error. The script exits silently.

Take the very basic script which is saved as a `.ps1` and the containing folder has been added to the VS Code workspace:

```
$DirectoryPath = "C:\Windows\System32\WindowsPowerShell\v1.0"
$DirContent = Get-ChildItem -Path $DirectoryPath
$DirContent

$FileNameToCheckFor = "powershell1.exe"

$Path = Join-Path $DirectoryPath $FileNameToCheckFor

if(-Not(Test-Path -Path $Path))
{
    Throw("File not found: '{0}'" -f $Path)
}

Write-Host("Path found: '{0}'" -f $Path)
```
I think it is fair to say, most Windows machines out there won't have the file `powershell1.exe` in the given path, therefore, I'd expect the script to stop with an error message along the lines of:
```
File not found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell1.exe'
At C:\Temp\Test-Scripts\src\scripts\Test-VSCDebugger.ps1:11 char:5
+     Throw("File not found: '{0}'" -f $Path)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (File not found:...owershell1.exe':String) [], RuntimeException
    + FullyQualifiedErrorId : File not found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell1.exe'
```

The script does stop and I don't see the `Write-Host` string returned.

The exact same script in ISE works as expected.

Here is a screen capture showing the difference between `Throw()` and `Write-Error`.
![PS_Throw_Issue](https://user-images.githubusercontent.com/26305145/77484974-e39f4c80-6e23-11ea-8ab0-88dcb93e83f9.gif)
As you can see, there is no output from `Throw()`.

To rule out PSRL, I've added `"powershell.integratedConsole.useLegacyReadLine": true` to my VS Code settings.json - which makes no difference.

As per update, this issue is also affecting cmdlets and .NET calls. Such as:
```
(New-Object System.Net.WebClient).DownloadFile("https://releases.hashicorp.com/terraform-provider-azuread/0.8.0/terraform-provider-azuread_0.8.0_windows_386.zip", "C:\DirThatDoesntExist\terraform-provider-azuread_0.8.0_windows_386.zip")
```
or
```
Get-ChildItem -Path C:\PathTheDoesntExist
```
It also doesn't pick up syntax errors:
```
if(-not (Test-Path -Oops "C:\Temp")
```

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.43.1|
| PowerShell Extension Version | 2020.3.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.628|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.628|
|BuildVersion|10.0.18362.628|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.8|
|azure-pipelines|ms-azure-devops|1.165.1|
|csharp|ms-dotnettools|1.21.15|
|csharpextensions|jchannon|1.3.1|
|powershell|ms-vscode|2020.3.0|
|terraform|mauve|1.4.0|
|vscode-azurefunctions|ms-azuretools|0.21.0|
|vscode-docker|ms-azuretools|1.0.0|
|vscode-nuget-package-manager|jmrog|1.1.6|

**Comment by TylerLeonhardt** [comment] 2020-03-26 18:29
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2576 and fixed already pending a release.

The fix already in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension.

You can still use whatever version of PowerShell you'd like. This is the Preview build of the _vs code extension_.

**Closed** 2020-03-27 19:00 UTC
Labels: Resolution-Duplicate
