### ISSUE TITLE
[Preview] Running F8 appears to be never ending

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3794] opened 2022-01-28 17:17 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When you run your code with F8 on highlighted code it appears like it's "doing" something, when it actually is already done and pressing enter is all it requires.

This shows this problem when running F8 during F5 debug and stopping on breakpoint
![image](https://user-images.githubusercontent.com/15063294/151591561-8d73f3d3-53e6-4609-bb0b-f8468f9a3795.png)

Adding "new line" (as in going to prompt) should solve the issue.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.5.0
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.1.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Highlight code
2. Run it with F8
3. Notice that it doesn't go to the prompt so it appears like it's running

**Comment by andschwa** [comment] 2022-01-28 17:43
Thanks @PrzemyslawKlys! This is (fortunately) a duplicate of https://github.com/PowerShell/vscode-powershell/issues/3685. So what's (wrongly) happening is that the prompt position isn't being updated, resulting in behavior that looks like this (also showed up in https://github.com/PowerShell/vscode-powershell/issues/3727#issuecomment-1018903103).

**Closed** 2022-01-28 17:45 UTC
Labels: Issue-Bug, Resolution-Duplicate
