### ISSUE TITLE
Issue running cmdltes from MicrosoftPowerBIMgmt Module

### ISSUE THREAD

**Issue by olyamusok** [PowerShell/vscode-powershell#2397] opened 2020-01-02 19:36 UTC
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
ms-vscode.powershell@2019.12.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.3383
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3383
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

I am experiencing a problem with running cmdlets from MicrosoftPowerBIMgmt module. Same script works as expected in ISE but fails in Visual Studio Code.
I am unable to run `Get-PowerBIActivityEvent` 
I believe the issue could be caused by version of the Newtonsoft.Json.dll that came with December version of the Powershell extension - it is 11.0.0 while the module requires 12.0.2 and higher
```
PS C:\Windows\system32> [Newtonsoft.Json.JsonConvert].Module

MDStreamVersion    : 131072
FullyQualifiedName : C:\Users\****\.vscode\extensions\ms-vscode.powershell-2019.12.0\modules\PowerShellEditorServices\bin\Desktop\Newtonsoft.Json.dll
ModuleVersionId    : 07e38931-19a9-45b2-9a35-e81930b1c8ad
MetadataToken      : 1
ScopeName          : Newtonsoft.Json.dll
Name               : Newtonsoft.Json.dll
Assembly           : Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes   : {}
ModuleHandle       : System.ModuleHandle`
```

#### Expected Behaviour

execution the same cmdlet in ISE returns results as expected with no errors.

#### Actual Behaviour

I get the following error:

```
Get-PowerBIActivityEvent : Attempted to access an element as a type incompatible with the array.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...BIActivityEvent:GetPowerBIActivityEvent) [Get-PowerBIActivityEvent], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.Commands.Admin.GetPowerBIActivityEvent

```

**Comment by rjmholt** [comment] 2020-01-02 22:51
@olyamusok this issue should be fixed in the latest `powershell-preview` extension. Could you uninstall the `powershell` extension, install `powershell-preview` and see if that resolves the issue?

**Comment by olyamusok** [comment] 2020-01-03 13:38
@rjmholt I uninstalled `powershell` extensions and installed `powershell-preview`. The error is gone and the script runs, but output is missing all _values_ for _key-value_ pairs.

I get an empty shell like this for each activity while the output I get from running same code in ISE is just fine:

[
  {
    "Id": [],
    "RecordType": [],
    "CreationTime": [],
    "Operation": [],
    "OrganizationId": [],
    "UserType": [],
    "UserKey": [],
    "Workload": [],
    "UserId": [],
    "ClientIP": [],
    "UserAgent": [],
    "Activity": [],
    "ItemName": [],
    "WorkSpaceName": [],
    "DatasetName": [],
    "WorkspaceId": [],
    "ObjectId": [],
    "DatasetId": [],
    "DataConnectivityMode": [],
    "IsSuccess": [],
    "RequestId": [],
    "ActivityId": [],
    "TableName": []
  },
  {
    "Id": [],
    "RecordType": [],
    "CreationTime": [],
    "Operation": [],
    "OrganizationId": [],
    "UserType": [],
    "UserKey": [],
    "Workload": [],
    "UserId": [],
    "ClientIP": [],
    "UserAgent": [],
    "Activity": [],
    "ItemName": [],
    "WorkSpaceName": [],
    "DatasetName": [],
    "ReportName": [],
    "WorkspaceId": [],
    "ObjectId": [],
    "DatasetId": [],
    "ReportId": [],
    "IsSuccess": [],
    "ReportType": [],
    "RequestId": [],
    "ActivityId": [],
    "DistributionMethod": []
  },
 
here is NewtonSoft module I see for `powershell-preview`

> PS C:\windows\system32> [Newtonsoft.Json.JsonConvert].Module

MDStreamVersion    : 131072
FullyQualifiedName : C:\Users\***\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\modules\PowerShellEditorServices\bin\Common\Newtonsoft.Json.dll
ModuleVersionId    : d32db49e-5e34-4072-9da3-1845c03ddc3a
MetadataToken      : 1
ScopeName          : Newtonsoft.Json.dll
Name               : Newtonsoft.Json.dll
Assembly           : Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes   : {}
ModuleHandle       : System.ModuleHandle

**Comment by rjmholt** [comment] 2020-01-03 21:56
Thanks for trying that out! I now have a similar repro (I'm not familiar with the MicrosoftPowerBIMgmt module and don't have any PowerBI workspaces, but have hit an error earlier on that I think has the same root cause).

The PowerShell extension has a hard dependency on Newtonsoft.Json (as does PSScriptAnalyzer). Since PowerShell 6+ also ships with Newtonsoft.Json, we version to that.

After taking on new dependencies when rearchitecting the PowerShell extension, we did some work to isolate those dependencies when possible. It seems that the .NET Framework side of that work didn't solve the problem. However, experimenting with different solutions suggests that the problem may not be solvable in .NET Framework.

We have, however, solved the problem in .NET Core. I tried this in PowerShell 6 and 7 and it seems to work normally in those.

**Comment by rjmholt** [comment] 2020-01-03 21:56
I'll continue playing with the .NET Framework solution to see if there's a possible solution, but I'm not optimistic.

**Comment by olyamusok** [comment] 2020-01-06 15:36
@rjmholt  thank you for looking into this in any case! I will keep this open for a bit longer in case something new will come up and will close in a month or so if not.

**Comment by rjmholt** [comment] 2020-03-10 00:14
@olyamusok can you try out this extension package for me and see if the issue persists?

[psvsix.zip](https://github.com/PowerShell/vscode-powershell/files/4309575/psvsix.zip)

It's a zip file, since GitHub won't allow uploading a VSIX directly. To install it, do this:

```powershell
# Download psvsix.zip to current directory

# Extract zip
Expand-Archive ./psvsix.zip ./psvsix

# Install to VSCode
code --install-extension ./psvsix/PowerShell-Insiders.vsix

# Open VSCode
# Ensure the PowerShell Preview is installed and the PowerShell extension is disabled
# Close and reopen VSCode
# Try your repro steps
```

**Comment by soulwiper** [comment] 2020-03-10 12:09
I don't have PowerShell-Insiders (I don't think).  Is that going to be a problem?  How do I tell if I have PowerShell-Insiders?

**Comment by rjmholt** [comment] 2020-03-10 14:13
That VSIX linked above will install “PowerShell Insiders” rather than “PowerShell”. It will appear as a separate VSCode extension. So after you install that VSIX you need to uninstall or disable the “PowerShell” extension and restart VSCode. Then “PowerShell Insiders” will start up

**Comment by TylerLeonhardt** [comment] 2020-03-10 16:33
This does not install PowerShell itself. We're only talking about the PowerShell extension and PowerShell Preview extension. You don't need to install anything else other than that VSIX

**Comment by rjmholt** [comment] 2020-03-10 16:43
> This does not install PowerShell itself.

Oh wow, rereading my comment I totally see the confusion. Yeah this installs the PowerShell **extension for VSCode**, not PowerShell the program. It will use the normal `powershell.exe`.

**Comment by soulwiper** [comment] 2020-03-10 17:13
Yeah ok,  thank you both.  I am hoping to try it a little later today.  I will let you know. 




Sent from my T-Mobile 4G LTE Device


Using Outlook for Android







On Tue, Mar 10, 2020 at 11:43 AM -0500, "Robert Holt" <notifications@github.com> wrote:













This does not install PowerShell itself.



Oh wow, rereading my comment I totally see the confusion. Yeah this installs the PowerShell extension for VSCode, not PowerShell the program. It will use the normal powershell.exe.

**Comment by soulwiper** [comment] 2020-03-11 03:05
Even with the preview (psvsix.zip) you requested me to try out I still run into the same problem as before.  I can not debug and language issue prompt poping up.

However I did not an error poping up for a second on the terminal before and with the preview.  I did not think of capturing it.  I have attached it as an jpeg image below.

![PowerShell preview extention error messages before blank terminal (with diagnostic)](https://user-images.githubusercontent.com/11999701/76378094-95b22100-631a-11ea-869e-4e935f93f1b4.jpg)

**Closed** 2020-03-11 20:20 UTC
Labels: Area-Engine, Issue-Bug, Needs: Attention :wave:, verify-fix

**Comment by olyamusok** [comment] 2020-03-12 13:26
@rjmholt apologies for delayed response, just saw the tag. Glad @soulwiper  else was able to test.

**Comment by soulwiper** [comment] 2020-03-12 17:16
@TylerLeonhardt and @rjmholt and @olyamusok is there a solution found to the dilemma of not been able to debug and the language issue when using PowerShell Extention 2020.3.0?

**Comment by rjmholt** [comment] 2020-03-12 17:24
@olyamusok I believe @soulwiper is experiencing a different issue, which it turns out isn't fixed by this. We're going to try a fix for your issue in the next preview release

**Comment by TylerLeonhardt** [comment] 2020-03-13 00:50
Can you all give the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension a try? We just did a release of it.

Don't forget to disable the regular PowerShell extension for VS Code when you enable the PowerShell Preview extension for VS Code

**Comment by sqlchick** [comment] 2020-06-14 22:45
Thank you, thank you, thank you @olyamusok for commenting about installation of PowerShell 7 -- I also was getting blank [ ] results in VSCode when running Get-PowerBIActivityEvent, while getting results returned just fine from the ISE. At this time, version 7.0.2 (https://github.com/PowerShell/PowerShell/releases) is the latest & whatever it installed resolved the issue. (And just for completeness on this thread...the Powershell preview extension in VSCode also had no effect for me on this particular issue that I was facing.)
