### ISSUE TITLE
The script file with Hg command does not work properly.

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/vscode-powershell#3279] opened 2021-04-06 10:06 UTC
## Issue Description

The script file with Hg command does not work properly.

A script file with the file name `hg.ps1` and the content `hg -v` exists, press Ctrl+F5 to run it.

#### Expected Behaviour

![image](https://user-images.githubusercontent.com/38101170/113694178-02f0db00-9702-11eb-9f86-43bad69aaeaa.png)

#### Actual Behaviour

It should finish executing immediately and return a message, but in fact it will be blocked and there is no way to continue running, only to end it manually.

![image](https://user-images.githubusercontent.com/38101170/113694278-1dc34f80-9702-11eb-976b-eda81606e428.png)

### Attached Logs

[log.zip](https://github.com/PowerShell/vscode-powershell/files/6263819/log.zip)

### VSCode extensions:
adamerose.better-outline@0.1.0
adamvoss.vscode-languagetool@3.8.0
adamvoss.vscode-languagetool-zh@3.8.0
alireza94.theme-gotham@0.4.0
almenon.arepl@2.0.2
andys8.jest-snippets@1.8.0
betterthantomorrow.calva@2.0.185
borkdude.clj-kondo@2021.3.310
casualjim.theme-desertex@0.0.6
cweijan.vscode-autohotkey-plus@2.6.2
DavidWang.ini-for-vscode@0.0.4
dbaeumer.vscode-eslint@2.1.16
emilast.LogFileHighlighter@2.11.0
Equinusocio.vsc-community-material-theme@1.4.2
Equinusocio.vsc-material-theme@33.2.0
equinusocio.vsc-material-theme-icons@1.2.2
eryouhao.brackets-light-pro@0.4.4
firsttris.vscode-jest-runner@0.4.31
formulahendry.code-runner@0.11.2
Gruntfuggly.auto-snippet@0.0.10
hbenl.vscode-test-explorer@2.19.6
helsmy.autohotkey-debug@0.6.12
Hyzeta.vscode-theme-github-light@7.14.2
IBM.output-colorizer@0.1.2
intellsmi.comment-translate@1.4.2
ionutvmi.reg@1.0.2
jeremyrajan.webpack@2.2.0
loilo.snazzy-light@1.1.7
lonefy.vscode-JS-CSS-HTML-formatter@0.2.3
lostfields.nodejs-repl@0.5.15
luokai.translate@2.1.0
luqimin.tiny-light@0.7.2
mdickin.markdown-shortcuts@0.12.0
mechatroner.rainbow-csv@1.8.1
MS-CEINTL.vscode-language-pack-zh-hans@1.54.2
ms-dotnettools.csharp@1.23.9
ms-python.python@2021.2.633441544
ms-toolsai.jupyter@2021.2.576440691
ms-vscode.cmake-tools@1.6.0
ms-vscode.cpptools@1.2.2
ms-vscode.powershell@2021.2.2
mushan.vscode-paste-image@1.0.4
octref.vetur@0.33.1
oderwat.indent-rainbow@7.5.0
onpaik.save-and-run-reg@0.1.3
rahmanyerli.fresh-light@1.1.0
redhat.java@0.76.0
royaction.color-manager@0.6.2
ryan-wdy.eyes-theme@1.1.8
selfrefactor.niketa-theme@9.22.0
SharzyL.cjk-word-handler@0.1.1
SirTori.indenticator@0.7.0
SolarLiner.linux-themes@1.0.1
telesoho.vscode-markdown-paste-image@0.12.3
thenikso.github-plus-theme@1.2.1
tht13.html-preview-vscode@0.2.5
tomconte.kickassembler@0.0.2
tranhl.find-then-jump@2.0.4
twxs.cmake@0.0.17
TylerLeonhardt.vscode-pester-test-adapter@0.0.23
uloco.theme-bluloco-light@3.3.7
VisualStudioExptTeam.vscodeintellicode@1.2.12
vscjava.vscode-java-debug@0.31.0
vscjava.vscode-java-dependency@0.18.1
vscjava.vscode-java-pack@0.13.0
vscjava.vscode-java-test@0.28.1
vscjava.vscode-maven@0.28.0
vscodevim.vim@1.19.3
WallabyJs.quokka-vscode@1.0.354
XadillaX.viml@1.0.1
yedhrab.yautohotkey@1.1.3
yzhang.markdown-all-in-one@3.4.0
ZacharyJia.quick-chinese-deletion@0.1.2
zero-plusplus.vscode-autohotkey-debug@1.6.9

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by Andy-AO** [comment] 2021-04-06 10:43
Additional:
1. it works fine in ISE
2. The problem also occurs when installing a new VSCode using a virtual machine

**Comment by SydneyhSmith** [comment] 2021-04-08 18:21
Thanks @Andy-AO could be related to #2559 , looks like the issue is being hit specifically with the debugger-- we may need to see if we can reproduce this to debug it further

**Comment by Andy-AO** [comment] 2021-04-08 22:39
look forward to your further news.

**Comment by andschwa** [comment] 2021-08-19 20:07
Sorry about that, the bot got a little eager. Please do test with v2021.8.1-preview that just went up on the marketplace and let me know what the result is!

**Comment by andschwa** [comment] 2022-04-12 22:26
@Andy-AO Hi there, we just released [v2022.4.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.4.0-preview)! Could you please try [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and verify this is fixed? It seemed to be in my testing, so marking as resolved, but please let me know if it's still occurs (or if new bugs show up)!

**Comment by andschwa** [comment] 2022-04-14 18:08
I'm going to assume this was fixed as the root cause was (finally) addressed. Please re-open if not the case!

**Closed** 2022-04-14 19:00 UTC
Labels: Issue-Bug, Area-Integrated Console, Resolution-Fixed
