### ISSUE TITLE
"Could not start language service" with vscode 1.54

### ISSUE THREAD

**Issue by vrdse** [PowerShell/vscode-powershell#3235] opened 2021-03-11 10:30 UTC
Issue Description
=====

I am experiencing a problem with starting PowerShell Integrated Console. After updating to vscode 1.54 and PowerShell Extension 2021.2.2 the Integrated Console did not start. After a few minutes I got "Could not start language service". Then I restarted the console a few times and it started again. Now, a few days later I just does not start at any time and I receive the "Could not start language service" immediately after starting vscode.

Attached Logs
=====

PowerShell Extension Log

´´´
10.3.2021 08:03:55 [NORMAL] - Visual Studio Code v1.54.1 64-bit
10.3.2021 08:03:55 [NORMAL] - PowerShell Extension v2021.2.2
10.3.2021 08:03:55 [NORMAL] - Operating System: Windows 64-bit
10.3.2021 08:03:55 [NORMAL] - Language server starting --
10.3.2021 08:03:55 [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
10.3.2021 08:03:55 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615359835-8e5c3394-2138-4c2d-a142-d3c7092713971615359820932\EditorServices.log' -SessionDetailsPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-29648-823800' -FeatureFlags @() 
10.3.2021 08:03:55 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615359835-8e5c3394-2138-4c2d-a142-d3c7092713971615359820932\EditorServices.log' -SessionDetailsPath 'c:\Users\usr\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-29648-823800' -FeatureFlags @() 
10.3.2021 08:03:55 [NORMAL] - pwsh.exe started.
10.3.2021 08:03:55 [NORMAL] - Waiting for session file
10.3.2021 08:04:00 [NORMAL] - Session file found
10.3.2021 08:04:00 [NORMAL] - Registering terminal close callback
10.3.2021 08:04:00 [NORMAL] - Registering terminal PID log callback
10.3.2021 08:04:00 [NORMAL] - pwsh.exe PID: 26328
10.3.2021 08:04:00 [NORMAL] - Language server started.
10.3.2021 08:04:00 [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_rg0e2uuu.o2l","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_nxtdi1py.rwa"}
10.3.2021 08:04:00 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_rg0e2uuu.o2l...
10.3.2021 08:04:00 [NORMAL] - Language service connected.
10.3.2021 08:04:00 [ERROR] - Could not start language service: 
10.3.2021 08:04:00 [ERROR] - Error: Connection to server got closed. Server will not be restarted.
´´´

`EditorServices.log`, `StartEditorServices.log`, `StartEditorServices-temp55C345AB.log` are all empty. 

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.54.1|
| PowerShell Extension Version | 2021.2.2 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.2|
|PSEdition|Core|
|GitCommitId|7.1.2|
|OS|Microsoft Windows 10.0.19042|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.7|
|azurecli|ms-vscode|0.5.0|
|azurepolicyextension|AzurePolicy|0.1.1|
|azurerm-vscode-tools|msazurermtools|0.14.1|
|gitlens|eamodio|11.3.0|
|kuskus-extensions-pack|rosshamish|1.0.1|
|kuskus-kusto-color-themes|rosshamish|0.1.0|
|kuskus-kusto-language-server|rosshamish|1.0.1|
|kuskus-kusto-syntax-highlighting|rosshamish|1.1.8|
|powershell|ms-vscode|2021.2.2|
|remote-wsl|ms-vscode-remote|0.54.0|
|terraform|hashicorp|2.7.0|
|vscode-aks-tools|ms-kubernetes-tools|0.0.8|
|vscode-azurefunctions|ms-azuretools|1.2.1|
|vscode-azureresourcegroups|ms-azuretools|0.3.0|
|vscode-azurestorage|ms-azuretools|0.12.0|
|vscode-azureterraform|ms-azuretools|0.3.2|
|vscode-azurevirtualmachines|ms-azuretools|0.3.0|
|vscode-docker|ms-azuretools|1.10.0|
|vscode-dotnet-runtime|ms-dotnettools|1.0.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.0|
|vscode-markdownlint|DavidAnson|0.39.0|
|vscode-yaml|redhat|0.16.0|

**Comment by alexhyy** [comment] 2021-03-11 10:59
I hit the same issue using VSCode 1.54.1 + PS extension 2021.2.2.
I try to downgrade PS extension to 2020.6.0, but it fails with error "Running the contributed command: 'PowerShell.ShowSessionMenu' failed."

**Comment by AspenForester** [comment] 2021-03-11 15:11
Seeing the same thing this morning.
vscode 1.54.1
PowerShell Extension v2021.2.2

**Comment by andschwa** [comment] 2021-03-11 18:17
Duplicate of #3227. New VS Code version 1.54.2 will be released today, resolving this.

**Closed** 2021-03-12 19:00 UTC
Labels: Needs: Triage :mag:, Resolution-Duplicate

**Comment by vrdse** [comment] 2021-03-15 07:30
I can confirm, it works again with vscode 1.54.2, thanks.
