### ISSUE TITLE
PowerShellEditorServices crashes when using Command + S to auto-format and save

### ISSUE THREAD

**Issue by hdansou** [PowerShell/vscode-powershell#1528] opened 2018-09-13 16:22 UTC
### System Details

- Operating system name and version:
- VS Code version: 1.27.1
- PowerShell extension version: 1.8.4.0
- Output from `$PSVersionTable`: 6.1.0-rc.1

```
PS /Users> code -v
1.27.1
5944e81f3c46a3938a82c701f96d7a59b074cfdc
x64
PS /Users> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      4      0


PS /Users> code --list-extensions --show-versions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
EditorConfig.EditorConfig@0.12.4
IBM.output-colorizer@0.1.2
RolandGreim.sharecode@0.4.1
abusaidm.html-snippets@0.2.1
akmittal.hugofy@0.1.0
AlanWalk.markdown-toc@1.5.6
alefragnani.Bookmarks@9.0.3
alefragnani.project-manager@8.0.0
atian25.copy-syntax@0.5.1
ban.spellright@2.5.32
bbenoist.vagrant@0.5.0
be5invis.toml@0.0.3
bernardodsanderson.theme-material-neutral@0.9.8
bierner.markdown-mermaid@1.0.0
blackmist.LinkCheckMD@0.1.5
bungcip.better-toml@0.3.2
chrisdias.vscode-opennewinstance@0.0.4
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
codezombiech.gitignore@0.5.0
CoenraadS.bracket-pair-colorizer@1.0.59
DavidAnson.vscode-markdownlint@0.20.0
dbaeumer.jshint@0.10.20
dbaeumer.vscode-eslint@1.6.0
donjayamanne.githistory@0.4.2
DotJoshJohnson.xml@2.3.2
eamodio.gitlens@8.5.6
eg2.tslint@1.0.39
eg2.vscode-npm-script@0.3.5
eppz.eppz-code@1.2.41
eriklynd.json-tools@1.0.2
esbenp.prettier-vscode@1.6.1
evilz.vscode-reveal@2.0.3
felipecaputo.git-project-manager@1.6.1
flowtype.flow-for-vscode@0.8.4
formulahendry.auto-close-tag@0.5.6
formulahendry.auto-rename-tag@0.0.15
formulahendry.code-runner@0.9.4
formulahendry.docker-explorer@0.1.6
GitHub.vscode-pull-request-github@0.1.4
GrapeCity.gc-excelviewer@2.1.26
hashhar.gitattributes@0.4.1
henriiik.docker-linter@0.5.0
hnw.vscode-auto-open-markdown-preview@0.0.4
HookyQR.beautify@1.4.3
humao.rest-client@0.19.1
jchannon.csharpextensions@1.3.0
jerriepelser.copy-markdown-as-html@1.1.0
jmMeessen.jenkins-declarative-support@0.1.0
joffreykern.markdown-toc@1.4.0
johnpapa.Angular2@6.1.5
joshwong.vscode-jmespath@0.0.5
keyring.Lua@0.0.9
mdickin.markdown-shortcuts@0.8.1
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@1.4.0
ms-python.python@2018.8.0
ms-vscode.Theme-TomorrowKit@0.1.4
ms-vscode.azure-account@0.4.3
ms-vscode.csharp@1.16.1
ms-vscode.Go@0.6.89
ms-vscode.jscs@0.1.9
ms-vscode.mono-debug@0.15.8
ms-vscode.PowerShell@1.8.4
ms-vscode.wordcount@0.1.0
ms-vsliveshare.vsliveshare@0.3.666
ms-vsts.team@1.136.0
msjsdiag.debugger-for-chrome@4.10.1
naumovs.color-highlight@2.3.0
PeterJausovec.vscode-docker@0.2.0
pflannery.vscode-versionlens@0.21.1
qub.qub-xml-vscode@1.2.8
rafaelmaiolla.remote-vscode@1.1.0
redhat.vscode-yaml@0.0.16
richie5um2.vscode-statusbar-json-path@1.2.0
robertohuertasm.vscode-icons@7.26.0
schneiderpat.aspnet-helper@0.6.4
seanmcbreen.MDTools@1.0.1
secanis.jenkinsfile-support@0.1.0
Shan.code-settings-sync@3.1.2
shardulm94.trailing-spaces@0.2.11
shd101wyy.markdown-preview-enhanced@0.3.5
spywhere.guides@0.9.2
steoates.autoimport@1.5.3
steve8708.Align@0.2.0
streetsidesoftware.code-spell-checker@1.6.10
tuxtina.json2yaml@0.2.0
vscoss.vscode-ansible@0.4.0
vstirbu.vscode-mermaid-preview@0.10.1
vyne.apostheme@0.4.2
waderyan.gitblame@2.4.4
wayou.vscode-todo-highlight@1.0.4
wesbos.theme-cobalt2@2.1.6
wholroyd.jinja@0.0.8
will-stone.plastic@2.1.0
wwm.better-align@1.1.6
yo1dog.cursor-align@1.0.4
yzhang.markdown-all-in-one@1.6.0
zhuangtongfa.Material-theme@2.16.5
ziyasal.vscode-open-in-github@1.3.5

PS /Users> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with Powershell Integrated console crashing when I save a file that is known to not have the proper formatting. 

How to reproduce:
- Create a PowerShell file in another text editor and set braces on the same line as the function name. Add two empty lines at the end of the file
- Set `"powershell.codeFormatting.openBraceOnSameLine": false,` in vscode user setting
- Set `    "editor.formatOnSave": true,    "files.trimTrailingWhitespace": true,` as well
- open the PowerShell file in vscode and use the `Command + S`

### Attached Logs

```
2018-09-13 10:45:29.992 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: In method 'OnListenTaskCompleted', line 391:
    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass6_0`2.<SetEventHandler>b__0(Message eventMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.DispatchMessage(Message messageToDispatch, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.ListenForMessages(CancellationToken cancellationToken)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc, ILogger logger)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
    

2018-09-13 10:45:29.992 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'ProtocolEndpoint_UnhandledException', line 435:
    PowerShell Editor Services is terminating due to an unhandled exception, see previous logs for details.

2018-09-13 10:45:30.010 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: In method 'PopRunspace', line 1969:
    Caller attempted to pop a runspace when no runspaces are on the stack.

2018-09-13 10:45:30.010 [ERROR] C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: In method 'PopRunspace', line 1969:
    Caller attempted to pop a runspace when no runspaces are on the stack.

```

**Comment by rjmholt** [comment] 2018-09-13 17:02
Closing as a duplicate of https://github.com/PowerShell/PowerShellEditorServices/issues/739

**Closed by rjmholt** 2018-09-13 17:02 UTC
