### ISSUE TITLE
Error: The terminal process terminated with exit code: {0}

### ISSUE THREAD

**Issue by Omzig** [PowerShell/vscode-powershell#2615] opened 2020-04-07 22:10 UTC
## System Details
- Operating system name and version
Windows 10 Enterprise 64-bit
- VS Code version
Version 1.43.2
Version 1.44.0-insider 
- PowerShell extension version
PSVersion =                     5.1.17763.1007                                                                                                                                                                 
PSEdition =                     Desktop                                                                                                                                                                        
PSCompatibleVersions =          {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                        
BuildVersion =                  10.0.17763.1007                                                                                                                                                                
CLRVersion =                    4.0.30319.42000                                                                                                                                                                
WSManStackVersion =             3.0                                                                                                                                                                            
PSRemotingProtocolVersion =     2.3                                                                                                                                                                            
SerializationVersion =          1.1.0.1      

## Issue Description
PowerShell will not load with the newest version.

## Expected Behaviour
I reverted back to PowerShell 2019.11.0 and this one works just fine.

## Troubleshooting Steps Taken
- Disabled all extensions. Tested again.
- Uninstalled PowerShell 2020.3.0 and reinstalled it. Could not reinstall it till I went to task manager and ended the PowerShell.exe from the Details Tab in task manager.
- Installed Insider version and then installed 2020.3.0 in it, same problem. The only extension I have ever loaded inside the insider version is PowerShell.

## Actual Behavior
- I get an error message:
The terminal process terminated with exit code: {0}
[Unable to upload image.]

- Log (Extension Host):
```
[2020-04-07 16:51:44.863] [exthost] [info] extension host started
[2020-04-07 16:51:44.935] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-04-07 16:51:44.936] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/debug-auto-launch/dist/extension
[2020-04-07 16:51:44.956] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-04-07 16:51:44.956] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/emmet/dist/extension
[2020-04-07 16:51:44.980] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
[2020-04-07 16:51:44.981] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/git/dist/main
[2020-04-07 16:51:45.039] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-04-07 16:51:45.039] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github-authentication/dist/extension.js
[2020-04-07 16:51:45.065] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-04-07 16:51:45.065] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/merge-conflict/dist/extension
[2020-04-07 16:51:45.081] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-04-07 16:51:45.081] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/search-result/dist/extension.js
[2020-04-07 16:51:45.089] [exthost] [info] ExtensionService#_doActivateExtension vscode.vscode-account {"startup":true,"extensionId":{"value":"vscode.vscode-account","_lower":"vscode.vscode-account"},"activationEvent":"*"}
[2020-04-07 16:51:45.089] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/vscode-account/dist/extension.js
[2020-04-07 16:51:45.116] [exthost] [info] eager extensions activated
[2020-04-07 16:51:46.176] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.powershell {"startup":false,"extensionId":{"value":"ms-vscode.powershell","_lower":"ms-vscode.powershell"},"activationEvent":"onView:PowerShellCommands"}
[2020-04-07 16:51:46.176] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/MyAccount/.vscode-insiders/extensions/ms-vscode.powershell-2020.3.0/out/src/main
```

- Log (Shared):
```
[2020-04-07 16:51:44.736] [sharedprocess] [info] main {"machineId":"17724cfb55c272d294eaa6e2732bb7866b3e98c5fffc4e3d8ce8af346a2d8e12","windowId":2}
[2020-04-07 16:52:24.801] [sharedprocess] [info] Starting to clean up unused language packs.
```

- Output (PowerShell Editor Service)
```
[Info  - 4:52:41 PM] PowerShell runtime version: 5.1.17763.1007, edition: Desktop
[Info  - 4:52:41 PM] highlight handler loaded
[Error - 4:52:42 PM] Could not resolve Script Analyzer settings path due to null or empty workspaceRootPath.
```

- Output (PowerShell Extension Logs)
```
4/7/2020 4:51:47 PM [NORMAL] - Visual Studio Code v1.44.0-insider 64-bit
4/7/2020 4:51:47 PM [NORMAL] - PowerShell Extension v2020.3.0
4/7/2020 4:51:47 PM [NORMAL] - Operating System: Windows 64-bit
4/7/2020 4:51:47 PM [NORMAL] - Language server starting --
4/7/2020 4:51:47 PM [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
4/7/2020 4:51:47 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\logs\1586296307-6a614b26-d20b-43fe-8bc4-4ed30cd773761586296302268\EditorServices.log' -SessionDetailsPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-23996-302478' -FeatureFlags @() 
4/7/2020 4:51:47 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\logs\1586296307-6a614b26-d20b-43fe-8bc4-4ed30cd773761586296302268\EditorServices.log' -SessionDetailsPath 'c:\Users\MyAccount\.vscode-insiders\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-23996-302478' -FeatureFlags @() 
4/7/2020 4:51:47 PM [NORMAL] - powershell.exe started.
4/7/2020 4:51:47 PM [NORMAL] - Waiting for session file
4/7/2020 4:52:37 PM [NORMAL] - Session file found
4/7/2020 4:52:37 PM [NORMAL] - Registering terminal close callback
4/7/2020 4:52:37 PM [NORMAL] - Registering terminal PID log callback
4/7/2020 4:52:37 PM [NORMAL] - Language server started.
4/7/2020 4:52:37 PM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_edqlrxwa.jmb","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_sjvdawdk.xpl"}
4/7/2020 4:52:37 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_edqlrxwa.jmb...
4/7/2020 4:52:37 PM [NORMAL] - Language service connected.
4/7/2020 4:52:42 PM [WARNING] - Invalid Version: null
```
# Workaround 
- Disable Auto Update
- Downgrade to PowerShell 2020.1.0 or less

**Comment by TylerLeonhardt** [comment] 2020-04-07 22:56
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-607990799

Can you follow the comment and fetch event logs/anti-virus logs?

**Comment by Omzig** [comment] 2020-04-07 23:04
This is not the same issue, I do not get a language service failure...

**Comment by Omzig** [comment] 2020-04-07 23:04
> This is a duplicate of [#2526 (comment)](https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-607990799)
> 
> Can you follow the comment and fetch event logs/anti-virus logs?

This is not the same issue, I do not get a language service failure...

**Comment by TylerLeonhardt** [comment] 2020-04-07 23:08
> [Error - 4:52:42 PM] Could not resolve Script Analyzer settings path due to null or empty workspaceRootPath.

I noticed this in your logs, if you open a folder in VS Code does that error go away and the extension loads properly?

**Comment by TylerLeonhardt** [comment] 2020-04-07 23:10
Can you also set the log level to diagnostic in your settings:
```
"powershell.developer.editorServicesLogLevel": "Diagnostic"
```
and provide payload logs:
https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs

**Comment by Omzig** [comment] 2020-04-08 15:07
> editorServicesLogLevel

Log is 669363 in length, sending to email: vscode-powershell@microsoft.com

**Comment by Omzig** [comment] 2020-04-08 15:14
> > [Error - 4:52:42 PM] Could not resolve Script Analyzer settings path due to null or empty workspaceRootPath.
> 
> I noticed this in your logs, if you open a folder in VS Code does that error go away and the extension loads properly?

No it never loads properly, I have to go into Task Manager and end task PowerShell.exe

**Comment by SydneyhSmith** [comment] 2020-04-14 21:20
@Omzig I noticed that you downgraded to version 2019.11 I was curious how you chose this one or if you had tried any others?

**Comment by TylerLeonhardt** [comment] 2020-04-14 21:22
@Omzig can you also describe what your workspace looks like that you're opening in VS Code?

**Comment by Omzig** [comment] 2020-04-23 15:30
> @Omzig can you also describe what your workspace looks like that you're opening in VS Code?

![image](https://user-images.githubusercontent.com/1987296/80117998-75969400-854d-11ea-8ab8-00d027709712.png)

**Comment by Omzig** [comment] 2020-04-23 17:56
> @Omzig I noticed that you downgraded to version 2019.11 I was curious how you chose this one or if you had tried any others?

It's the "PowerShell Integrated Console" that fails to load.

# 2020.4.0 Failed!
# 2020.3.0 Failed!
## 2020.1.0 Works!
## 2019.12 Works!
## 2019.11 Works!
## 2019.9 Works!

None of this happens when it fails, i just get the error {0}. This output is expected.
```
VERBOSE: 
#-- Console Encoding ---------------------------------------------------------
VERBOSE: System.Text.ASCIIEncoding
VERBOSE: 
#-- Updated PSModulePath to: -------------------------------------------------
VERBOSE: C:\Users\AccountName\Documents\WindowsPowerShell\Modules
VERBOSE: C:\Program Files (x86)\WindowsPowerShell\Modules
VERBOSE: C:\Program Files\WindowsPowerShell\Modules
VERBOSE: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\
VERBOSE: C:\Program Files (x86)\AutoIt3\AutoItX
VERBOSE: c:\Users\AccountName\.vscode-insiders\extensions\ms-vscode.powershell-2019.11.0\modules
VERBOSE: 
#-- Check required modules available -----------------------------------------
VERBOSE: Testing module availability PowerShellGet 
VERBOSE: Loading module from path 'C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: PowerShellGet  found
VERBOSE: 
#-- Start up PowerShellEditorServices ----------------------------------------
VERBOSE: Importing PowerShellEditorServices
VERBOSE: Loading module from path 'C:\Users\AccountName\.vscode-insiders\extensions\ms-vscode.powershell-2019.11.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'.
VERBOSE: Loading module from path 'C:\Users\AccountName\.vscode-insiders\extensions\ms-vscode.powershell-2019.11.0\modules\PowerShellEditorServices\PowerShellEditorServices.psm1'.
VERBOSE: Exporting function 'Start-EditorServicesHost'.
VERBOSE: Exporting function 'Compress-LogDir'.
VERBOSE: Exporting function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Compress-LogDir'.
VERBOSE: Importing function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Start-EditorServicesHost'.
PowerShell Integrated Console

VERBOSE: Invoking Start-EditorServicesHost
VERBOSE: Start-EditorServicesHost returned Microsoft.PowerShell.EditorServices.Host.EditorServicesHost
VERBOSE: Writing session file with contents:
VERBOSE: {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_g12qzp2j.swq","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_q1nwmphi.1yl"}
VERBOSE: Wrote out session file
VERBOSE: 
#-- Waiting for EditorServicesHost to complete execution ---------------------
PS C:\Users\AccountName>
```

**Comment by RobW3LGA** [comment] 2020-04-24 12:19
I have also experienced the same symptoms with 2020.3, and 2020.4 clearly does not resolve it. Excellent diagnostic work by Dr. Omzig.

**Comment by rjmholt** [comment] 2020-04-28 21:42
@Omzig (and @RobW3LGA) do you have [logs from the PowerShell extension](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs) rather than from VSCode or from the LSP transport? You should be able to find the relevant logs with this Command Palette command: `PowerShell: Open PowerShell Extension Logs Folder`.

**Comment by RobW3LGA** [comment] 2020-04-29 15:06
The following is from vscode-powershell.log after installing the extension and reloading:
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4552475/vscode-powershell.log)
 
If this is not what you're asking for, please let me know. Thank you, rjmholt

**Comment by rjmholt** [comment] 2020-04-29 17:10
@RobW3LGA can you set your log level to `Diagnostic` (instructions in the document I linked above) and report back with `vscode-powershell.log`, `EditorServices.log` and `StartEditorServices.log`

**Comment by RobW3LGA** [comment] 2020-04-29 18:29
The following logs reflect the actions of starting VSCode with no version of the PowerShell extension installed (with .vscode extension folders deleted, log level=diagnostic), then installing the 2020.4 extension and the extension attempting to start up (and subsequent failure):

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4553636/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4553638/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4553640/StartEditorServices.log)

**Comment by SydneyhSmith** [comment] 2020-04-30 21:19
Thanks for the diagnostic logging @RobW3LGA, unfortunately we still are not able to determine what is casing your crash-- It would be really helpful if you could also attach the payload logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by RobW3LGA** [comment] 2020-05-01 01:14
Appreciate the guidance, Sydney.
[payload.log](https://github.com/PowerShell/vscode-powershell/files/4562089/payload.log)

**Comment by SydneyhSmith** [comment] 2020-05-12 21:32
@RobW3LGA thanks for providing the logs we took a look at them and unfortunately the error is still not appearing...one thing to try is using Windows PowerShell x86 as this usually has a faster startup time (your issue could be caused by  too slow of a startup) to you this add to your setting file:
   ` "powershell.powerShellDefaultVersion": "Windows PowerShell (x86)"`

**Comment by MikeShepard** [comment] 2020-06-03 15:27
I'm having this issue as well

**Comment by Omzig** [comment] 2020-06-03 15:53
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4724516/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4724517/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4724518/StartEditorServices.log)

2020.4.0 with the latest version of vscode insiders still has problems.

**Comment by TylerLeonhardt** [comment] 2020-06-03 16:43
Can you both try this with the PowerShell Preview extension and see if it repros?

**Comment by Omzig** [comment] 2020-06-03 18:55
> Can you both try this with the PowerShell Preview extension and see if it repros?

[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4725567/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4725569/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4725570/EditorServices.log)

2020.6.0 (you have failed this user :P) 
It does the same thing as the other versions. Here are the logs.

**Comment by Omzig** [comment] 2020-06-16 14:31
> Can you both try this with the PowerShell Preview extension and see if it repros?

Do you need more logs?

**Comment by SydneyhSmith** [comment] 2020-06-18 21:23
@Omzig logs are probably not needed at this point although if you think of anything that may make your system unique that would be helpful in diagnosing this issue, thanks!

**Closed** 2021-08-19 19:01 UTC
Labels: Issue-Bug, Needs: Repro Info 🤔

**Comment by Omzig** [comment] 2021-11-17 14:17
Turns out what solved it for us, was an update to BeyondTrust - Privilege Management for Windows, somehow it was keeping the newer versions of PowerShell from running.

**Comment by andschwa** [comment] 2021-11-17 17:30
Woah, thanks for the update @Omzig! Glad it's working.
