### ISSUE TITLE
Go To Definition/Find All References with scope modifier

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#393] opened 2016-12-17 02:52 UTC
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:
- VS Code version: 1.8.0
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

### Issue Description

This is in the same boat as issue #379 I logged. If I use a scope modifier (like $Script:) in front of a variable Go To Definition cannot find the definition. Similarly Find All References will only find all references that use the modifier and not the initial declaration at the script level. This one could be tricky to implement because variables set in a function with the same name as a script level variable are created at the Local scope.

**Comment by tylerl0706** [comment] 2018-01-17 02:38
Closing this as a dupe of https://github.com/PowerShell/PowerShellEditorServices/issues/16 but we still need to make things scope aware.

**Closed by tylerl0706** 2018-01-17 02:38 UTC
Labels: Issue-Enhancement
