### ISSUE TITLE
Remoting from integrated powershell terminal loops trying to load local profle

### ISSUE THREAD

**Issue by hedzerjan** [PowerShell/vscode-powershell#2942] opened 2020-09-10 07:19 UTC
### System Details

System Details Output
```
### VSCode version: 1.48.2 a0479759d6e9ea56afa657e454193f72aef85bd0 x64

### VSCode extensions:
donjayamanne.githistory@0.6.9
DotJoshJohnson.xml@2.5.1
mechatroner.rainbow-csv@1.7.1
ms-dotnettools.csharp@1.23.1
ms-mssql.mssql@1.9.0
ms-vscode.powershell@2020.6.0


### PSES version: 2.2.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

When I use the integrated terminal to connect to a remote machine, the powershell session keeps looping trying to find the profle (that I use on the local machine) on the remote machine where it does not exist. The issue has been reported on SO as well (but not by me): [link](https://stackoverflow.com/questions/62470187/vs-code-powershell-remote-session-looking-for-local-profile) .

#### Expected Behaviour

Normal session operaton, being able to execute commands.

#### Actual Behaviour

Endless loop which keeps throwing errors.

### Attached Logs
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5199818/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/5199819/vscode-powershell.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5199820/StartEditorServices.log)

**Comment by SydneyhSmith** [comment] 2020-09-10 21:10
Thanks @hedzerjan we are currently working on re-writing the threading model for the extension which will solve this issue...in the meantime it would be helpful to know what is being run in your profile...thanks!

**Comment by hedzerjan** [comment] 2020-09-14 08:50
> Thanks @hedzerjan we are currently working on re-writing the threading model for the extension which will solve this issue...in the meantime it would be helpful to know what is being run in your profile...thanks!

Ah, its good to hear that this will be solved, thank you. Even with a profile that just defines one variable the problem occurs.

**Comment by SydneyhSmith** [comment] 2020-09-15 21:07
Thanks, going to track this as a duplicate of https://github.com/PowerShell/PowerShellEditorServices/issues/1295

**Closed** 2020-09-16 22:00 UTC
Labels: Needs-Repro-Info, Resolution-Duplicate
