### ISSUE TITLE
A relative path in powershell.scriptAnalysis.settingsPath deactivates all PSSA rules in workspaces without such a file

### ISSUE THREAD

**Issue by mklement0** [PowerShell/vscode-powershell#2287] opened 2019-11-05 20:05 UTC
### System Details

System Details Output
```
### VSCode version: 1.39.2 6ab598523be7a800d7f3eb4d92d7ab9a66069390 x64

### VSCode extensions:
ms-vscode.powershell@2019.11.0

### PSES version: 1.13.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

A _relative_ path in setting `powershell.scriptAnalysis.settingsPath` is designed to work on a per-workspace basis, by pointing to a workspace-root-relative path.

#### Expected Behaviour

If a given workspace (or VSCode having been opened without a folder) happens to have _no_ settings file specified in the relative path, the default PSSA rules should apply.

#### Actual Behaviour

If the workspace-relative settings file doesn't exist, all PSSA rules are seemingly _deactivated_.

The behavior can easily be verified by referencing a non-existent file-name-only `*.psd1` file in `settings.json`, such as with:

```
"powershell.scriptAnalysis.settingsPath": "nosuch.psd1"
```

**Comment by rjmholt** [comment] 2019-11-12 22:38
Going to mark this as a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2190, since the implementation there will solve this issue.

**Closed** 2019-11-13 23:00 UTC
Labels: Resolution-Duplicate
