### ISSUE TITLE
Terminal - Random "@" appear during typing and pasting

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#2353] opened 2019-12-09 09:51 UTC
### System Details
* Windows 10 1909 (18363.476)
* VS Code v1.40.2
* PowerShell Preview 2019.11.0
* PSVersionTable
```powershell

Name                           Value                                                                                                              
----                           -----                                                                                                              
PSVersion                      5.1.18362.145                                                                                                      
PSEdition                      Desktop                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                            
BuildVersion                   10.0.18362.145                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                    
WSManStackVersion              3.0                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                
SerializationVersion           1.1.0.1                                                                                                            
```

System Details Output
```powershell
### VSCode version: 1.40.2 f359dd69833dd8800b54d458f6d37ab7c78df520 x64

### VSCode extensions:
bencoleman.armview@0.3.3
DavidAnson.vscode-markdownlint@0.32.0
dracula-theme.theme-dracula@2.19.0
Equinusocio.vsc-material-theme@30.0.0
GitHub.vscode-pull-request-github@0.13.0
mblode.pretty-formatter@0.1.6
ms-azure-devops.azure-pipelines@1.157.4
ms-azuretools.vscode-azurefunctions@0.20.1
ms-vscode.azure-account@0.8.7
ms-vscode.powershell@2019.11.0
ms-vscode.powershell-preview@2019.11.0
richie5um2.vscode-sort-json@1.18.0
Tyriar.shell-launcher@0.4.0
zhuangtongfa.material-theme@3.2.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When writing and running some stuff if a open .ps1 file, then going down to the terminal for either pasting or writing anything, a random "@" appear in front.

Reproduce:
* Open a new file
* Write "$Var = 'value'", then F8 to run that line of code
* Go down to terminal, either paste something or start to write.
* A random "@" appears.
* Happens with both saved files and new unsaved files.

![2019-12-09_10-37-05](https://user-images.githubusercontent.com/6450056/70425093-d62aa600-1a70-11ea-839f-1e43c2989289.gif)

#### Expected Behaviour

No random characters should appear.

#### Actual Behaviour

Random "@" appear. 100% reproducable.

**Comment by rjmholt** [comment] 2019-12-09 17:06
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2274.

(Understand `@` doesn't suggest nice issue duplicates)

The fix for this should be released this month.

**Comment by o-l-a-v** [comment] 2019-12-09 21:47
@rjmholt 
So ot could still be weeks until a fix is released?!

 Sorry for seeming ungrateful but. ISE is effectively deprecated since 2017. The stable build of this extension has less features than ISE. You recommends us to use the preview as it's more feature packed and "as good as stable". For preview/ beta software it would be normal you'd be able to release builds at a higher cadence, especially with a bug that ruins workflow as much as this bug does. Things like this forces us that do PowerShell for a living to keep using legacy Windows PowerShell 5.1 and ISE.

Yes, it's open source. But this ain't good enough for the worlds most profitable company IMHO.

**Closed** 2019-12-10 23:00 UTC
Labels: Resolution-Duplicate
