### ISSUE TITLE
PowerShell format document is replacing "main" with "main.cpl"

### ISSUE THREAD

**Issue by gmahender** [PowerShell/vscode-powershell#1861] opened 2019-04-09 21:51 UTC
### System Details

System Details Output
```
### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
dbankier.vscode-instant-markdown@1.4.3
DotJoshJohnson.xml@2.4.0
Microsoft.al@0.12.15355
ms-vscode.csharp@1.18.0
ms-vscode.powershell@1.12.0
shd101wyy.markdown-preview-enhanced@0.3.13
zhuangtongfa.Material-theme@2.21.0


### PSES version: 1.12.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

### Issue Description

I am experiencing a problem with PowerShell "format document" functionality, where i have below simple PS1 code whenever I use "format document" my method name "main" is replacing with "main.cpl" and causing issues.

```
function main{
    Write-Host "hello world"
}

main
```

With above code, when formatting last line "main" is replacing with "main.cpl"

#### Expected Behaviour

when formatting the document, function name shouldn't be corrected

#### Actual Behaviour

when formatting the document, function call "main" is replacing with "main.cpl"

after formating the document:

```
function main {
    Write-Host "hello world"
}

main.cpl
```

**Comment by rjmholt** [comment] 2019-04-09 22:23
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1849

**Closed by rjmholt** 2019-04-09 22:23 UTC
