### ISSUE TITLE
running the contributed command 'powershell.showsessionmenu' failed

### ISSUE THREAD

**Issue by GuruGarrett** [PowerShell/vscode-powershell#3186] opened 2021-02-15 22:26 UTC
Issue Type: <b>Bug</b>

This just started happening today as soon as I launch VS Code. I got rid of the PowerShell preview extension and went to the regular one, problem solved or so I thought. Now it is back. Killing the terminal makes no difference. I cleaned out my profile script, nothing I do seems to fix this issue.

Extension version: 2020.6.0
VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.88GB free)|
|Process Argv|--crash-reporter-id 73db9766-634c-40a4-89e7-ab73f4bc186c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by SydneyhSmith** [comment] 2021-02-16 21:35
Thanks @GuruGarrett going to mark this as a duplicate of #3187 since it has a bit more detailed information

**Closed** 2021-02-17 22:00 UTC
Labels: Resolution-Duplicate
