### ISSUE TITLE
Ctrl+Backspace Does Not Work

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/vscode-powershell#1259] opened 2018-04-06 12:35 UTC
It looks like Ctrl+Backspace shortcut to delete word is not working although it is specified in keyboard Shortcuts.
![image](https://user-images.githubusercontent.com/5260172/38421550-2e368eb6-39b0-11e8-85ed-ff10a1e26c47.png)

### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment] 2018-04-10 17:28
Thanks for this! I want to narrow this down to the PowerShell extension if we can.

If you disable the PowerShell extension in your extensions tab and reload VSCode, does `ctrl+Backspace` work?

If so, then we're probably overwriting the shortcut. If that doesn't fix the issue then the problem is either with another extension or with VSCode itself.

**Comment by tylerl0706** [comment] 2018-04-10 17:38
Actually this looks like it's about the PowerShell Integrated Console. This will be added with PSReadLine support. That work is being tracked here:
https://github.com/PowerShell/vscode-powershell/issues/535

closing this as a dupe.

**Closed by tylerl0706** 2018-04-10 17:38 UTC
Labels: Needs-Repro-Info
