### ISSUE TITLE
PSSession extremely slow

### ISSUE THREAD

**Issue by Niglb** [PowerShell/vscode-powershell#2154] opened 2019-08-26 15:59 UTC
Issue Type: <b>Bug</b>

Hi there,

When using the Powershell extension to remote manage another machine via enter-pssession, VSCode consumes a lot of CPU, and is extremely slow to respond. 

Extension version: 2019.5.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment] 2019-08-29 22:21
@Niglb thanks for providing these logs.. looking closer at your issue it seems to be the same root cause as #1648 the good news is that this will likely be fixed by some ongoing work we are going to improve the architecture of the extension, to improve performance around PowerShell pipeline thread usage

**Comment by Niglb** [comment] 2019-08-29 22:33
Ok thank you!

**Closed** 2019-08-31 00:00 UTC
Labels: Area-Engine, Issue-Performance, Resolution-Duplicate
