### ISSUE TITLE
VSCode-PowerShell - Allsigned GPO fails with "Could not start language service:"

### ISSUE THREAD

**Issue by MN-Joe** [PowerShell/vscode-powershell#3723] opened 2021-12-15 17:40 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

We are just now setting our environment to AllSigned - prior to this it has worked fine.  If I set it to RemoteSigned I can get it to work but not AllSigned.

I've done many searches on this and I find one article from 2018 that sounds the same but they just state they will fix in the next version and no discussion or other comments continued.

What am I missing!
Thanks
------------------------------------------

12/15/2021 11:21:58 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.10.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\logs\1639588918-03abed12-2b07-4b8a-8bf2-bc24ef0ca5931639588477125\EditorServices.log' -SessionDetailsPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\sessions\PSES-VSCode-4664-762895' -FeatureFlags @() 
12/15/2021 11:21:58 AM [NORMAL] - Language server starting --
12/15/2021 11:21:58 AM [NORMAL] - Waiting for session file
12/15/2021 11:21:58 AM [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
12/15/2021 11:21:58 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.10.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\logs\1639588918-03abed12-2b07-4b8a-8bf2-bc24ef0ca5931639588477125\EditorServices.log' -SessionDetailsPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\sessions\PSES-VSCode-4664-762895' -FeatureFlags @() 
12/15/2021 11:21:58 AM [NORMAL] - powershell.exe started.
12/15/2021 11:22:32 AM [NORMAL] - Session file found
12/15/2021 11:22:32 AM [NORMAL] - Registering terminal close callback
12/15/2021 11:22:32 AM [NORMAL] - Registering terminal PID log callback
12/15/2021 11:22:32 AM [NORMAL] - powershell.exe PID: 28624
12/15/2021 11:22:32 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_hkczklnk.kdt","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_go3bwwbg.0fo"}
12/15/2021 11:22:32 AM [NORMAL] - Language server started.
12/15/2021 11:22:32 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_hkczklnk.kdt...
12/15/2021 11:22:32 AM [NORMAL] - Language service connected.
12/15/2021 11:30:27 AM [ERROR] - Error: Connection to server got closed. Server will not be restarted.
12/15/2021 11:30:27 AM [ERROR] - Could not start language service: 
12/15/2021 11:30:29 AM [NORMAL] - powershell.exe terminated or terminal UI was closed

### PowerShell Version

```console
Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.19041.1320                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.19041.1320                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.1
fe719cd3e5825bf14e14182fddeb88ee8daf044f
x64

From PowerShell 7 which does run in VSCode as I do not have the AllSigned set there yet
```

### Extension Version

```console
ronmansoftware.powershellprotools@2021.12.0         Disabled
ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.11.1              Disabled

I've tried it with just PowerShell along as well
```

### Steps to Reproduce

set GPO to AllSigned and launch VSCode with PowerShell extension for Version 5.1

### Logs

12/15/2021 11:21:58 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.10.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\logs\1639588918-03abed12-2b07-4b8a-8bf2-bc24ef0ca5931639588477125\EditorServices.log' -SessionDetailsPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\sessions\PSES-VSCode-4664-762895' -FeatureFlags @() 
12/15/2021 11:21:58 AM [NORMAL] - Language server starting --
12/15/2021 11:21:58 AM [NORMAL] - Waiting for session file
12/15/2021 11:21:58 AM [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
12/15/2021 11:21:58 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.10.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\logs\1639588918-03abed12-2b07-4b8a-8bf2-bc24ef0ca5931639588477125\EditorServices.log' -SessionDetailsPath 'c:\Users\Me\.vscode\extensions\ms-vscode.powershell-2021.10.2\sessions\PSES-VSCode-4664-762895' -FeatureFlags @() 
12/15/2021 11:21:58 AM [NORMAL] - powershell.exe started.
12/15/2021 11:22:32 AM [NORMAL] - Session file found
12/15/2021 11:22:32 AM [NORMAL] - Registering terminal close callback
12/15/2021 11:22:32 AM [NORMAL] - Registering terminal PID log callback
12/15/2021 11:22:32 AM [NORMAL] - powershell.exe PID: 28624
12/15/2021 11:22:32 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_hkczklnk.kdt","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_go3bwwbg.0fo"}
12/15/2021 11:22:32 AM [NORMAL] - Language server started.
12/15/2021 11:22:32 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_hkczklnk.kdt...
12/15/2021 11:22:32 AM [NORMAL] - Language service connected.
12/15/2021 11:30:27 AM [ERROR] - Error: Connection to server got closed. Server will not be restarted.
12/15/2021 11:30:27 AM [ERROR] - Could not start language service: 
12/15/2021 11:30:29 AM [NORMAL] - powershell.exe terminated or terminal UI was closed

**Comment by MN-Joe** [comment] 2021-12-20 21:40
The certificate expired on Dec 2, 2021 so maybe this is my issue within my AllSigned environment.  I was able to load the modules individually and I was then able to run the St
![image](https://user-images.githubusercontent.com/71799135/146836243-0812c212-2208-493d-93c2-7dd4cde20149.png)
art-EditorServices.ps1 script and save the certificate but the certificate is expired.

**Comment by andschwa** [comment] 2021-12-21 00:54
If it's a certificate used to sign extension code, then it should be automatically updated by our release process. I am actually _currently_ issuing a new Preview release. So in a few hours when it's out, please see if v2021.12.0 repros this.

**Comment by MN-Joe** [comment] 2021-12-21 17:14
So with the updated certificate I can now get PowerShell 5.1 to load.  Now I just need to figure out how to change the noninteractive mode so I can regain normal functionality.

**Comment by SeeminglyScience** [comment] 2021-12-21 17:22
> Now I just need to figure out how to change the noninteractive mode so I can regain normal functionality.

Are you experiencing an issue around interactivity? If you just mean the `-NonInteractive` flag passed on the command line to `powershell.exe` you can ignore that as implementation detail.

**Comment by MN-Joe** [comment] 2021-12-21 17:24
When I run a script that requires a prompt it comes back with the following:

Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.

Didn’t use to do this and doesn’t when I run PowerShell 7.1 in VSCode.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by andschwa** [comment] 2021-12-21 17:41
@MN-Joe Sorry, can you explicitly confirm the same issue is not occurring with the Preview extension? If so, I'll cut another stable extension which will put it through the same process that signs with whatever current certificate is available to the build and release infrastructure.

**Comment by MN-Joe** [comment] 2021-12-21 19:55
The Preview release works with the 9/1/2022 certificate except it comes up in noninteractive mode and I'm not finding out to change that.
The main release I think would be great if we could get the certificate updated.  For PowerShell 7 we do not have that GPO set yet to AllSigned so those works without the certificate being upgraded.

**Comment by andschwa** [comment] 2021-12-22 21:55
@MN-Joe I'm going to mark this as a duplicate of #3733 since it seems the root cause was the same. Can confirm that's correct? Thanks!

**Closed** 2021-12-23 22:00 UTC
Labels: Issue-Bug, Area-Build & Release, Resolution-Duplicate
