### ISSUE TITLE
ExecutionPolicy Allsigned -> the language service could not be started

### ISSUE THREAD

**Issue by deejaybeam** [PowerShell/vscode-powershell#1277] opened 2018-04-19 08:31 UTC
### System Details

- Operating system name and version: Windows Server 2016, Windows 10, ...
- VS Code version: 1.22.2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.2125
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2125
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

Can not use the extension.
The Powershell execusion policy is set to 'AllSigned' as MachinePolicy via GPO.
All visible scripts and modules seems to be signed valid (MS-CS-Cert. is in trusted Publishers), but on startup a temporary, unsigned ps1 failed to execute e.g.: 'C:\Users\[USERNAME]\AppData\Local\Temp\10\wrwqpfqr.q4r.ps1'
'

Found via Microsoft-Windows-CAPI2/Operational
### Attached Logs

Log Name:      Microsoft-Windows-CAPI2/Operational
Source:        Microsoft-Windows-CAPI2
Date:          4/19/2018 10:01:24 AM
Event ID:      81
Task Category: Verify Trust
Level:         Error
Keywords:      Trust Verification
User:          DOMAIN\user
Computer:      HOST.domain.name
Description:
For more details for this event, please refer to the "Details" section
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-CAPI2" Guid="{5bbca4a8-b209-48dc-a8c7-b23d3e5216fb}" />
    <EventID>81</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>80</Task>
    <Opcode>2</Opcode>
    <Keywords>0x4000000000000040</Keywords>
    <TimeCreated SystemTime="2018-04-19T08:01:24.465982500Z" />
    <EventRecordID>920907</EventRecordID>
    <Correlation ActivityID="{68315216-D21B-0000-1605-4F681BD2D301}" />
    <Execution ProcessID="7456" ThreadID="7768" />
    <Channel>Microsoft-Windows-CAPI2/Operational</Channel>
    <Computer>HOST.domain.name</Computer>
    <Security UserID="S-1-5-21-2361215-4229491221-4040045740-12595" />
  </System>
  <UserData>
    <WinVerifyTrust>
      <ActionID>{00AAC56B-CD44-11D0-8CC2-00C04FC295EE}</ActionID>
      <UIChoice value="2">WTD_UI_NONE</UIChoice>
      <RevocationCheck value="0" />
      <StateAction value="0">WTD_STATEACTION_IGNORE</StateAction>
      <Flags value="80000100" WTD_SAFER_FLAG="true" CPD_USE_NT5_CHAIN_FLAG="true" />
      <FileInfo filePath="C:\Users\user\AppData\Local\Temp\10\wrwqpfqr.q4r.ps1" hasFileHandle="true" />
      <DigestInfo digestAlgorithm="" digest="" />
      <RegPolicySetting value="23E00" WTPF_IGNOREREVOKATION="true" WTPF_OFFLINEOK_IND="true" WTPF_OFFLINEOK_COM="true" WTPF_OFFLINEOKNBU_IND="true" WTPF_OFFLINEOKNBU_COM="true" WTPF_IGNOREREVOCATIONONTS="true" />
      <StepError stepID="3" stepName="TRUSTERROR_STEP_SIP">
        <Result value="57">The parameter is incorrect.</Result>
      </StepError>
      <StepError stepID="9" stepName="TRUSTERROR_STEP_MSG_SIGNERCOUNT">
        <Result value="57">The parameter is incorrect.</Result>
      </StepError>
      <StepError stepID="32" stepName="TRUSTERROR_STEP_FINAL_OBJPROV">
        <Result value="800B0003">The form specified for the subject is not one supported or known by the specified trust provider.</Result>
      </StepError>
      <StepError stepID="33" stepName="TRUSTERROR_STEP_FINAL_SIGPROV">
        <Result value="800B0100">No signature was present in the subject.</Result>
      </StepError>
      <StepError stepID="34" stepName="TRUSTERROR_STEP_FINAL_CERTPROV">
        <Result value="800B0100">No signature was present in the subject.</Result>
      </StepError>
      <EventAuxInfo ProcessName="powershell.exe" />
      <CorrelationAuxInfo TaskId="{E511DA99-C143-403B-BEAA-EB84705C07F5}" SeqNumber="2" />
      <Result value="800B0100">No signature was present in the subject.</Result>
    </WinVerifyTrust>
  </UserData>
</Event>

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment] 2018-04-19 17:30
This looks like a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1048

I'd recommend taking a look at that one.

**Closed** 2018-04-24 16:00 UTC
