### ISSUE TITLE
Stepping too fast in the debugger causes a hang on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#1183] opened 2018-02-01 16:05 UTC
This was opened as a result of closing https://github.com/PowerShell/vscode-powershell/issues/156#issuecomment-362028145

Stepping too fast in the debugger causes a hang on Windows.

**Repro steps**
1. on Windows open VSCode and debug a script that has a while loop or some loop.
2. Press and hold down F10 to step over.

The debugging session will hang and you will not be able to continue debugging. All of the debugging options will not work.

**Comment by Omniusz** [comment] 2018-02-15 15:17
Yeah, this pesters me too.

**Comment by brianrreed** [comment] 2018-11-16 17:30
I am seeing the same issue.

**Comment by hoetz** [comment] 2018-12-06 11:56
Same here:

https://github.com/PowerShell/vscode-powershell/issues/738#issuecomment-444847054

**Comment by yobyot** [comment] 2018-12-07 15:49
@TylerLeonhardt Thanks for asking. Yes...there's _something_ basic that causes the debugger to crash/quit/hang. I've seen it across platforms (Windows, macOS) and PowerShell releases (5.1 and core 6.x on macOS).

On Windows, I can cut and paste the script into the ISE and it'll debug perfectly. It's the one thing that has me worried about the death of PowerShell desktop: this debugger still is, ahem, buggy.

**Comment by ili101** [comment] 2019-01-01 21:18
Hi guys, can you please look at this bug? It's very annoying to have your console cash in the middle of a long debug.
![error](https://user-images.githubusercontent.com/6960531/50576484-305fc780-0e1b-11e9-9bdc-8b2d9f90c51d.gif)

**Comment by TylerLeonhardt** [comment] 2019-01-01 21:56
Thanks for the info! Can you also [attach the logs](https://github.com/powershell/vscode-powershell#reporting-problems) here so we can get a better idea of what's going on?

**Comment by ili101** [comment] 2019-01-01 22:18
Logs:
[EditorServices.log (Normal)](https://github.com/PowerShell/vscode-powershell/files/2719674/EditorServices.log)
[EditorServices.log (Verbose)](https://github.com/PowerShell/vscode-powershell/files/2719677/EditorServices.log)

**Comment by fourpastmidnight** [comment] 2019-01-18 17:12
In addition to the console crashing, I've also had the session seem to just become "detached". I.e. the debugger still thinks it's debugging, but you can't step into/over/out of anything, nor F8 to continue execution. Thankfully, hitting Stop does seem to work so that I can restart the debugging session.

**Comment by tlovland1** [comment] 2019-05-31 18:37
I get this issue constantly.  If I step faster than ~once per second, the powershell / debugging session crashes

**Comment by tlovland1** [comment] 2019-05-31 18:38
I've gotten the issue @fourpastmidnight  describes quite often as well.

**Comment by pwahlmueller** [comment] 2020-02-23 21:15
I still have this issue with the actual versions (code 1.42.2 and powershell 2020-01). Very annoying as the system may then be partially in an inconsistent state - I then have to clean things up before I can debug again.

**Comment by rjmholt** [comment] 2020-02-23 21:26
> powershell 2020-01

Give `powershell-preview` 2020.2.0 a try. A large number of debugging issues have been solved in that. Changes there are being released to stable alongside PowerShell 7 next month.

**Comment by SydneyhSmith** [comment] 2020-02-25 22:09
Sounds like this has been fixed in our latest preview release so I will close for now. Thanks!

**Closed by SydneyhSmith** 2020-02-25 22:09 UTC
Labels: Area-Debugging, Issue-Bug, OS-Windows

**Comment by yobyot** [comment] 2020-02-25 22:12
With all due respect we don’t know if this issue — a long-standing one that makes debugging scripts difficult — is actually fixed. 

Can we leave this open until we have some evidence?

**Comment by SydneyhSmith** [comment] 2020-02-25 22:22
We have closed it given that there is no current action item for us on this issue, and we use this to track our work items...if we have evidence that it is persistent we are always happy to re-open

**Comment by pwahlmueller** [comment] 2020-02-26 07:25
Have tried it with 2020-02 powershell-preview on one machine - could not reproduce the issue any longer.
