### ISSUE TITLE
Powershell:Run command sets @ symbol in integrated terminal after run

### ISSUE THREAD

**Issue by kdf2883** [PowerShell/vscode-powershell#2350] opened 2019-12-06 19:18 UTC
Issue Description
=====

When I run a file with F5 (Powershell:Run command) , I get  @ symbol in the terminal every time I use the terminal after it runs.
![vscode-1575659794236](https://user-images.githubusercontent.com/21251604/70349661-2b797400-1833-11ea-9496-97132e6b2b71.gif)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.40.2|
| PowerShell Extension Version | 2019.11.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell-preview|ms-vscode|2019.11.0|

**Comment by corbob** [comment] 2019-12-06 20:40
This is a duplicate of #2274 Naturally the GitHub search doesn't surface this when searching for `@` so it's difficult to know it's previously reported and is solved in the next revision ¯\\\_( ͡° ͜ʖ ͡°)\_/¯

**Comment by rjmholt** [comment] 2019-12-07 06:32
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2274

**Closed** 2019-12-08 07:00 UTC
Labels: Resolution-Duplicate
