### ISSUE TITLE
Basic refactoring features

### ISSUE THREAD

**Issue by silverqx** [PowerShell/vscode-powershell#4999] opened 2024-05-30 20:09 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I would like to see basic refactoring features like renaming local variables and if possible renaming global variables and function names using Language Server Protocol and integrated with refactor features provided by vscode.

Would be awesome to have at least these.

**Comment by JustinGrote** [comment] 2024-05-30 23:03
Dupe of https://github.com/PowerShell/vscode-powershell/issues/261

In short, this is very difficult because PowerShell is not a statically typed or scoped language. We hope to explore a limited scope of rename but it would need to be known it will be opt-in with shortcomings with a warning. See more detail on that issue.

**Closed by JustinGrote** 2024-05-30 23:03 UTC
Labels: Issue-Enhancement, Needs: Triage

**Comment by silverqx** [comment] 2024-05-30 23:28
I saw #261, at least renaming a local variable inside functions or inside the closest scope shouldn't be a problem, vscode API provides `registerRenameProvider` a little described [here](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#rename-symbols) (this page also contains other info about renaming, search: "rename") and in deep described [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename) and [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename). 

Have you tried these APIs, they are supposed exactly for this purpose. You can use these APIs since this extension uses LSP.

**Comment by silverqx** [comment] 2024-05-30 23:36
Practically, you don't have to do anything, everything is done inside LSP, it looks like all you need to do is consume and implement these APIs and interfaces to provide rename functionality for this extension. What means you don't have to code the renaming feature from the ground up.

**Comment by JustinGrote** [comment] 2024-05-30 23:53
"Practically, you don't have to do anything, everything is done inside LSP"

And who do you think writes the LSP? 😁 
https://github.com/PowerShell/PowerShellEditorServices

There is no rename functionality implemented in the LSP (PSES) as of yet. That's the primary first task that must occur before it can be wired up in the frontend extension. Issues for PSES are usually first tracked here as it's where most people first look, but the two are developed mostly in tandem (VSCode being the "primary" consumer of PSES, but there's other editors too (neovim, atom, etc.)

**Comment by silverqx** [comment] 2024-05-31 00:07
> What means you don't have to code the renaming feature from the ground up.

It looks like that is the exact opposite of what I wrote. 😎🙃 You will have to code everything yourself. I have found PowerShell/PowerShellEditorServices#2152, it looks like one year of work, what is the state of this hard work, will be merged soon or it's still in early stages?

**Comment by silverqx** [comment] 2024-05-31 00:13
Code quality looks good with a lot of tests.

**Comment by JustinGrote** [comment] 2024-05-31 00:46
As I recall there are several edge cases this doesn't handle, so we were going to need to surface an opt-in to warn users about the potential perils of using this feature. @andyleejordan can elaborate, but I recommend continued discussion happen on the PR or issue and not on this dupe.

**Comment by silverqx** [comment] 2024-05-31 00:53
Ok, I'm going to sleep because I'm in half suspend mode already, writing with one eye already closed, thx for replies, I will dream about renaming in pwsh 😅
