### ISSUE TITLE
Preview 2019.12.00 crashes at startup with "Invalid URI: The hostname could not be parsed."

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#2373] opened 2019-12-18 08:21 UTC
## Issue Description

PowerShell Extension just crashes at startup with following error:

* The terminal process terminated with exit code: 3762504530

Happens no matter what PowerShell version is configured as default, tried with both 6.2.3 and 7rc1.

<details><summary>Error message from terminal (with diagnostic logging enabled)</summary><p>

```powershell

DEBUG: Logging started
DEBUG: Beginning EndProcessing block
VERBOSE: Removing PSReadLine        
DEBUG: Creating host configuration
DEBUG: Determining REPL kind
DEBUG: REPL configured as PSReadLine
DEBUG: Configuring LSP transport
DEBUG: Configuring debug transport
DEBUG: Session file writer created
VERBOSE: Adding AssemblyResolve event handler for new AssemblyLoadContext dependency loading
VERBOSE: Loading EditorServices
DEBUG: Logging host information
VERBOSE: 
== Build Details ==
- Editor Services version: <development-build>
- Build origin:            VSTS
- Build time:              13.12.2019 01:18:26

VERBOSE: 
== Host Startup Configuration Details ==
 - Host name:                 Visual Studio Code Host
 - Host version:              2019.12.0
 - Host profile ID:           Microsoft.VSCode
 - PowerShell host type:      System.Management.Automation.Internal.Host.InternalHost

 - REPL setting:              PSReadLine
 - Session details path:      c:\Users\OlavRønnestadBirkela\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\sessions\PSES-VSCode-16556-573187
 - Bundled modules path:      c:\Users\OlavRønnestadBirkela\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\modules
 - Additional modules:        PowerShellEditorServices.VSCode
 - Feature flags:

 - Log path:                  c:\Users\OlavRønnestadBirkela\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\logs\1576657201-5b389b1d-fcff-486f-8429-b659b95083701576656134103\EditorServices.log
 - Minimum log level:         Diagnostic

 - Profile paths:
   + AllUsersAllHosts:       C:\Program Files\PowerShell\7-preview\profile.ps1
   + AllUsersCurrentHost:    C:\Program Files\PowerShell\7-preview\Microsoft.VSCode_profile.ps1
   + CurrentUserAllHosts:    C:\Users\OlavRønnestadBirkela\OneDrive - Ironstone\Documents\PowerShell\profile.ps1
   + CurrentUserCurrentHost: C:\Users\OlavRønnestadBirkela\OneDrive - Ironstone\Documents\PowerShell\Microsoft.VSCode_profile.ps1

DEBUG: Assembly resolve event fired for System.Text.Encoding.CodePages.resources, Version=4.1.3.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Assembly resolve event fired for System.Text.Encoding.CodePages.resources, Version=4.1.3.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.Commands.Diagnostics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.Commands.Utility, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.MarkdownRender, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.Commands.Management, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.WSMan.Management, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.WSMan.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35   
DEBUG: Assembly resolve event fired for Microsoft.PowerShell.Security.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
DEBUG: Assembly resolve event fired for Microsoft.PowerShell.Security.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
DEBUG: Assembly resolve event fired for Microsoft.WSMan.Management.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
DEBUG: Assembly resolve event fired for Microsoft.WSMan.Management.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
VERBOSE: 
== Console Details ==
 - Console input encoding: OEM United States
 - Console output encoding: OEM United States
 - PowerShell output encoding: Unicode (UTF-8)

DEBUG: Assembly resolve event fired for System.Management.Automation.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
DEBUG: Assembly resolve event fired for System.Management.Automation.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
VERBOSE: 
== PowerShell Details ==
- PowerShell version: 7.0.0-rc.1
- Language mode:      FullLanguage

VERBOSE:
== Environment Details ==
 - OS description: Microsoft Windows 10.0.18363
 - OS architecture: X64
 - Process bitness: 64

DEBUG: Checking that PSES is running in FullLanguage mode
VERBOSE: Updated PSModulePath to: 'C:\Users\OlavRønnestadBirkela\OneDrive - Ironstone\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7-preview\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Common Files\Skype for Business Online\Modules\;C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell;c:\Users\OlavRønnestadBirkela\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\modules'
DEBUG: Validating configuration
VERBOSE: Loading PowerShell Editor Services
DEBUG: Assembly resolve event fired for Microsoft.PowerShell.EditorServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
VERBOSE: Loading PSES DLL using new assembly load context
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.PowerShell.EditorServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
VERBOSE: Starting EditorServices
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.Async, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Extensions.Logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.Text.Encoding, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.IO, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.IO.FileSystem.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Options, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Creating startup info object
VERBOSE: Starting server, deregistering host logger and registering shutdown listener



__/\\\\\\\\\\\\\_______/\\\\\\\\\\\____/\\\\\\\\\\\________/\\\\\\\\\_
 _\/\\\/////////\\\___/\\\/////////\\\_\/////\\\///______/\\\////////__
  _\/\\\_______\/\\\__\//\\\______\///______\/\\\_______/\\\/___________
   _\/\\\\\\\\\\\\\/____\////\\\_____________\/\\\______/\\\_____________
    _\/\\\/////////_________\////\\\__________\/\\\_____\/\\\_____________
     _\/\\\_____________________\////\\\_______\/\\\_____\//\\\____________
      _\/\\\______________/\\\______\//\\\______\/\\\______\///\\\__________
       _\/\\\_____________\///\\\\\\\\\\\/____/\\\\\\\\\\\____\////\\\\\\\\\_
        _\///________________\///////////_____\///////////________\/////////__


                  =====> PowerShell Integrated Console <=====



An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. PS C:\Users\OlavRønnestadBirkela> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters.AbsoluteUriConverter.ReadJson(JsonReader reader, Type objectType, Uri existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Notification notification)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Notification notification)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()



```

</p></details>

<details><summary>Settings</summary><p>

```json

{
    "[powershell]": {
        "editor.defaultFormatter": "ms-vscode.powershell-preview"
    },
    "[yaml]": {
        "editor.autoIndent": "none",
        "editor.formatOnSave": false
    },
    "debug.console.fontFamily": "default",
    "debug.console.wordWrap": true,
    "editor.autoIndent": "full",
    "editor.fontFamily": "Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.fontWeight": "normal",
    "editor.formatOnSave": true,
    "editor.mouseWheelZoom": true,
    "editor.tabSize": 4,
    "editor.trimAutoWhitespace": true,
    "editor.wordWrap": "on",
    "explorer.confirmDragAndDrop": false,
    "extensions.autoUpdate": true,
    "files.defaultLanguage": "powershell",
    "files.encoding": "utf8",
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "git.enableSmartCommit": true,
    "powershell.bugReporting.project": "https://github.com/PowerShell/vscode-powershell",
    "powershell.codeFormatting.alignPropertyValuePairs": true,
    "powershell.codeFormatting.autoCorrectAliases": true,
    "powershell.codeFormatting.ignoreOneLineBlock": true,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
    "powershell.codeFormatting.newLineAfterOpenBrace": true,
    "powershell.codeFormatting.openBraceOnSameLine": true,
    "powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationForFirstPipeline",
    "powershell.codeFormatting.useCorrectCasing": true,
    "powershell.codeFormatting.whitespaceAfterSeparator": false,
    "powershell.codeFormatting.whitespaceAroundOperator": false,
    "powershell.codeFormatting.whitespaceAroundPipe": true,
    "powershell.codeFormatting.whitespaceBeforeOpenBrace": false,
    "powershell.codeFormatting.whitespaceBeforeOpenParen": false,
    "powershell.codeFormatting.whitespaceInsideBrace": false,
    "powershell.integratedConsole.focusConsoleOnExecute": false,
    "powershell.integratedConsole.showOnStartup": true,
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
            "versionName": "PowerShell Core 7 Preview (x64)"
        }
    ],
    "powershell.powerShellDefaultVersion": "PowerShell Core 7 Preview (x64)",
    "powershell.promptToUpdatePowerShell": true,
    "powershell.scriptAnalysis.enable": true,
    "powershell.startAutomatically": true,
    "powershell.useX86Host": false,
    "shellLauncher.shells.windows": [
        {
            "label": "CMD (x64)",
            "shell": "%SystemRoot%\\System32\\cmd.exe"
        },
        {
            "label": "CMD (x86)",
            "shell": "%SystemRoot%\\SysWOW64\\cmd.exe"
        },
        {
            "args": [
                "/NoLogo"
            ],
            "label": "PowerShell Core 6.x (x64)",
            "launcName": "PowerShell Core 6.x (x64)",
            "shell": "%ProgramW6432%\\PowerShell\\6\\pwsh.exe"
        },
        {
            "args": [
                "/nologo"
            ],
            "label": "PowerShell Core 7 Preview (x64)",
            "launcName": "PowerShell Core 7 Preview (x64)",
            "shell": "%ProgramW6432%\\PowerShell\\7-preview\\pwsh.exe"
        },
        {
            "args": [
                "/nologo"
            ],
            "label": "Windows PowerShell (x64)",
            "shell": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        },
        {
            "args": [
                "/nologo"
            ],
            "label": "Windows PowerShell (x86)",
            "shell": "%SystemRoot%\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    ],
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
    "workbench.editor.tabSizing": "shrink",
    "workbench.list.horizontalScrolling": false,
    "workbench.startupEditor": "newUntitledFile"
}

```

</p></details>

## Attached Logs

[1576657005-5b389b1d-fcff-486f-8429-b659b95083701576656134103.zip](https://github.com/PowerShell/vscode-powershell/files/3977351/1576657005-5b389b1d-fcff-486f-8429-b659b95083701576656134103.zip)

## Environment Information

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.41.0|
| PowerShell Extension Version | 2019.12.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0-rc.1|
|PSEdition|Core|
|GitCommitId|7.0.0-rc.1|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0-rc.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|armview|bencoleman|0.3.3|
|azure-account|ms-vscode|0.8.7|
|azure-pipelines|ms-azure-devops|1.157.4|
|material-theme|zhuangtongfa|3.2.1|
|powershell-preview|ms-vscode|2019.12.0|
|pretty-formatter|mblode|0.1.7|
|shell-launcher|Tyriar|0.4.0|
|theme-dracula|dracula-theme|2.19.0|
|vsc-material-theme|Equinusocio|30.0.0|
|vscode-azurefunctions|ms-azuretools|0.20.1|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-pull-request-github|GitHub|0.13.0|
|vscode-sort-json|richie5um2|1.18.0|

</details>

**Comment by o-l-a-v** [comment] 2019-12-18 08:28
The stable 2019.12.00 extension also crashes.

Diagnostic logs:

[1576657663-fa20ebda-3a8f-4dec-a30f-3b8c09c9f5661576657576950.zip](https://github.com/PowerShell/vscode-powershell/files/3977374/1576657663-fa20ebda-3a8f-4dec-a30f-3b8c09c9f5661576657576950.zip)

**Comment by o-l-a-v** [comment] 2019-12-18 08:35
Found the cause.. Thought "powershell.powerShellDefaultVersion" should match the "versionName" of one of the "powershell.powerShellAdditionalExePaths", But no.

Better error messages or smarter logic around handling the "powershell.powerShellDefaultVersion" setting would be highly appreciated.

Fixed:

* "powershell.powerShellDefaultVersion": "PowerShell 7-preview (x64)",

**Comment by o-l-a-v** [comment] 2019-12-18 08:38
Nope, that did not fixed it. If opening a Visual Studio Code windows with three PS1 files open, it always crashes. If opening a empty VSCode window, the extension loads successfully.

**Comment by o-l-a-v** [comment] 2019-12-18 08:51
Got it working now, with:

* "powershell.powerShellDefaultVersion": "PowerShell Core 7 Preview (x64)"

Not a pleasent experience wasting 50 minutes of my work day troubleshooting this bisarre issue. I hope default shell can be handled smoother in feature versions.

**Comment by o-l-a-v** [comment] 2019-12-18 08:55
Now it started crashing again. Didn't touch anything.

[1576659301-ab90fdf1-2019-43f1-8c7e-0fd773c463971576659162452.zip](https://github.com/PowerShell/vscode-powershell/files/3977460/1576659301-ab90fdf1-2019-43f1-8c7e-0fd773c463971576659162452.zip)

**Comment by o-l-a-v** [comment] 2019-12-18 09:10
Long paths for files in the editor seems to maybe affect the stability of the extension. Might be visible in the logs.

Tried with shorter path for a PS1 file, seems to not crash anymore. But like. Why doesn't even basic intellisense work at all?

![image](https://user-images.githubusercontent.com/6450056/71072380-ab320780-217e-11ea-85f8-a817d1a9c79f.png)

**Comment by TylerLeonhardt** [comment] 2019-12-19 23:01
This is a dupe of #2324 because your username contains a non-ASCII character. This is my top priority right now but please be aware that the holidays are approaching so progress will be delayed.

**Closed** 2019-12-21 00:00 UTC
Labels: Resolution-Duplicate
