### ISSUE TITLE
Syntax errors are not reported when powershell.scriptAnalysis.enable is set to false

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#388] opened 2016-12-16 15:34 UTC
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: macOS sierra
- VS Code version: 1.8
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: PSv6 alpha 13

### Issue Description

It seems that Code no longer can detect problems in my scripts. I can make a number of edits that would prevent the script from compiling and Code never detects them.

### Attached Logs

Logs sent to David.

**Comment by daviwil** [comment] 2016-12-17 00:03
Ok, there might be a big here, I don't see *any* markers being sent back to the editor for syntax errors in the file.  I suspect it's because you've got the `powershell.scriptAnalysis.enable: "false"` setting in your config file.  This shouldn't stop syntax errors from being reported.  There was a change in that area of the code recently, I think it might have broken syntax error reporting when Script Analyzer is off.

**Comment by kapilmb** [comment] 2016-12-17 09:29
It is caused by [this](https://github.com/PowerShell/PowerShellEditorServices/blob/develop/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs#L1088). We actually return the syntax markers from a downstream method which never gets called if analysis is disabled. I already have a fix in a branch on the PSES repo but I'll wait till a pending PR is merged.

**Closed** 2016-12-19 23:14 UTC
Labels: bug
