### ISSUE TITLE
[PowerShell] Foldable regions not working #region #endregion

### ISSUE THREAD

**Issue by AlexHimself** [PowerShell/vscode-powershell#1449] opened 2018-07-24 17:53 UTC
Issue Type: <b>Bug</b>

Foldable regions are not working for Powershell. Here are screenshots of Powershell ISE vs VS Code:

**PowerShell ISE:**
![image](https://user-images.githubusercontent.com/10466466/43156718-c1443f8a-8f2f-11e8-8e2c-42570b4ca891.png)

**VS Code:**
![image](https://user-images.githubusercontent.com/10466466/43156735-c6a0361e-8f2f-11e8-9c1f-784a8724d236.png)

Extension version: 1.8.1
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (7.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rkeithhill** [comment] 2018-07-24 18:01
Duplicate of #1428 which has been fixed.  Fix will show up in the next release due sometime later this week - I hope.

**Closed by rkeithhill** 2018-07-24 18:01 UTC
