### ISSUE TITLE
PowerShell unable to load Az.Resources module 

### ISSUE THREAD

**Issue by chip-felton-montage** [PowerShell/vscode-powershell#2334] opened 2019-11-27 22:00 UTC
### System Details
- macOS Catalina 10.15.1
- VSCode version 1.41.0-insider
- PowerShell extension version ms-vscode.powershell-preview 2019.11.0

System Details Output
```
### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Issue Description

I am trying to run a PowerShell script that uses the Az.Resources module to export info from Azure AD.  This script has worked in the past, and I believe the problems started after I upgraded to macOS Catalina.  

I've pasted in the script below and also the output.

Script:

```powershell
# this exports users from Azure AD into a csv file format specified by Tableau for importing users into Tableau Server
# created by chip@montage.co.nz
# last modified 2019-10-16

# retrieve the object id for the nelson Office Azure AD security group
Get-AzADGroup -DisplayName "Nelson Office"

# retrieve all users belonging to the NO security group
$users = Get-AzADGroupMember -GroupObjectId "0bbfc2a1-e862-49f9-9745-c3d82a62cd5b"

# create custom objects for each user with the properties required by Tableau Server for importing users
$userArray = @()
foreach ($user in $users) {
    $properties = @{'UserName' = $user.UserPrincipalName;
                    'Password' = 'password'
                    'DisplayName' = $user.DisplayName;
                    'LicenseLevel' = '';
                    'AdminitratorLevel' = '';
                    'PublishingCapability' = '';
                    'Email' = $user.UserPrincipalName}
    $userArray += New-Object –TypeName PSObject –Prop $properties
}

# output to csv
$userArray | Select-Object -Property UserName, Password, DisplayName, LicenseLevel, AdminitratorLevel, PublishingCapability, Email | 
    ConvertTo-Csv | Set-Content -Path ./azure-ad-users.csv 

# strip out text qualifiers from the csv and also the header row and re-save file
(Get-Content -Path ./azure-ad-users.csv).Replace('"','') | Select-Object -Skip 1 | Set-Content -Path ./azure-ad-users.csv

# display results
Get-Content -Path ./azure-ad-users.csv#### Expected Behaviour
```

Output:
```
PowerShell Integrated Console

PS /Users/chip/Dropbox/Code/Powershell> Unable to find type [Microsoft.PowerShell.PSConsoleReadLine].
At line:1 char:71
+ ... :RunClassConstructor([Microsoft.PowerShell.PSConsoleReadLine].TypeHan ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShell.PSConsoleReadLine:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
 
PS /Users/chip/Dropbox/Code/Powershell> /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1

Get-AzADGroup : The 'Get-AzADGroup' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:6 char:1
+ Get-AzADGroup -DisplayName "Nelson Office"
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroup:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Get-AzADGroupMember : The 'Get-AzADGroupMember' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:9 char:10
+ $users = Get-AzADGroupMember -GroupObjectId "0bbfc2a1-e862-49f9-9745- ...
+          ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroupMember:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
krupesh.desai@montage.co.nz,password,Krupesh Desai,,,,krupesh.desai@montage.co.nz
PS> ./export-azure-ad-users.ps1
Get-AzADGroup : The 'Get-AzADGroup' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:6 char:1
+ Get-AzADGroup -DisplayName "Nelson Office"
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroup:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Get-AzADGroupMember : The 'Get-AzADGroupMember' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:9 char:10
+ $users = Get-AzADGroupMember -GroupObjectId "0bbfc2a1-e862-49f9-9745- ...
+          ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroupMember:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
krupesh.desai@montage.co.nz,password,Krupesh Desai,,,,krupesh.desai@montage.co.nz
ersion: $($pseditor.EditorServicesVersion)"; "`n### PowerShell version:`n$($PSVersionTable | Out-String)"}ions:`n$(code-insiders --list-extensions --show-versions | Out-String)"; "`n### PSES v
code-insiders : The term 'code-insiders' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:27
+ & {"### VSCode version: $(code-insiders -v)"; "`n### VSCode extension ...
+                           ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (code-insiders:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException 

### VSCode version: 
code-insiders : The term 'code-insiders' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:76
+ ... ode-insiders -v)"; "`n### VSCode extensions:`n$(code-insiders --list- ...
+                                                     ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (code-insiders:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

``` 

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /Users/chip/Dropbox/Code/Powershell> Unable to find type [Microsoft.PowerShell.PSConsoleReadLine].
At line:1 char:71
+ ... :RunClassConstructor([Microsoft.PowerShell.PSConsoleReadLine].TypeHan ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShell.PSConsoleReadLine:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
 
PS /Users/chip/Dropbox/Code/Powershell> /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1

Get-AzADGroup : The 'Get-AzADGroup' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:6 char:1
+ Get-AzADGroup -DisplayName "Nelson Office"
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroup:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Get-AzADGroupMember : The 'Get-AzADGroupMember' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.
At /Users/chip/Dropbox/Code/Powershell/export-azure-ad-users.ps1:9 char:10
+ $users = Get-AzADGroupMember -GroupObjectId "0bbfc2a1-e862-49f9-9745- ...
+          ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzADGroupMember:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
### Attached Logs
I've attached the powershell and editor services logs:
[Archive.zip](https://github.com/PowerShell/vscode-powershell/files/3898931/Archive.zip)

**Comment by rjmholt** [comment] 2019-11-28 01:08
Looks like something odd happened with some of the output script formatting there. But in any event, this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2292. I have a prototype of a fix in that issue, so please try it out and let me know in that issue if it solves the problem or if you have any other issues with it.

**Comment by chip-felton-montage** [comment] 2019-11-28 22:08
Hi Robert,

Your fix worked for me.  Many thanks!  Any idea when this will make its way into the main release? I’ll hold off on any updates until then.

Cheers,

Chip Felton

Principal Consultant

M: +64 21 241 5404
www.montage.co.nz<http://www.montage.co.nz/>
Get a free trial of Tableau and experience the power of visual data analysis.<http://www.tableausoftware.com/partner-trial?id=19538>

The information contained in this e-mail message is intended only for the use of the person or entity to whom it is addressed and contains information that is CONFIDENTIAL and may be exempt from disclosure under applicable laws. If you read this message and are not the addressee you are notified that use, dissemination, distribution, or reproduction of this message is prohibited. If you have received this message in error, please notify us immediately and delete the original message. You should scan this message and any attached files for viruses. Any views or opinions expressed in this email (unless otherwise stated) may not represent those of Montage Professional Services Ltd (trading as Montage). Montage Professional Services Ltd accepts no liability for any loss caused either directly or indirectly by a virus arising from the use of this message or any attached file.

On 28/11/2019, at 2:08 PM, Robert Holt <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like something odd happened with some of the output script formatting there. But in any event, this is a duplicate of #2292<https://github.com/PowerShell/vscode-powershell/issues/2292>. I have a prototype of a fix in that issue, so please try it out and let me know in that issue if it solves the problem or if you have any other issues with it.

**Comment by chip-felton-montage** [comment] 2019-11-28 22:30
I am seeing one issue with your fix though. When the Powershell integrated console starts up in Visual Studio, I get the error below:


=== PowerShell Integrated Console ===
PS /Users/chip/Dropbox/Code/Powershell>

An error occurred while reading input:

System.TypeInitializationException: The type initializer for 'UnixConsoleEcho.InputEcho' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.InteropServices.OSPlatform.get_Windows()
   at UnixConsoleEcho.InputEcho..cctor()
   --- End of inner exception stack trace ---
   at UnixConsoleEcho.InputEcho.Disable()
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.UnixConsoleOperations.ReadKeyAsync(Boolean intercept, CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Console\UnixConsoleOperations.cs:line 94
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.ConsoleReadLine.ReadKeyAsync(CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Console\ConsoleReadLine.cs:line 132
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.ConsoleReadLine.InvokeLegacyReadLineAsync(Boolean isCommandLine, CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Console\ConsoleReadLine.cs:line 180
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.LegacyReadLineContext.InvokeReadLineAsync(Boolean isCommandLine, CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Session\LegacyReadLineContext.cs:line 27
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.InvokeReadLineAsync(Boolean isCommandLine, CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 1117
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.ConsoleReadLine.ReadLineAsync(Boolean isCommandLine, CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Console\ConsoleReadLine.cs:line 137
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHostUserInterface.StartReplLoopAsync(CancellationToken cancellationToken) in C:\Users\Robert Holt\Documents\Dev\Microsoft\PowerShellEditorServices\src\PowerShellEditorServices\Services\PowerShellContext\Session\Host\EditorServicesPSHostUserInterface.cs:line 829

PS /Users/chip/Dropbox/Code/Powershell>


On 28/11/2019, at 2:08 PM, Robert Holt <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like something odd happened with some of the output script formatting there. But in any event, this is a duplicate of #2292<https://github.com/PowerShell/vscode-powershell/issues/2292>. I have a prototype of a fix in that issue, so please try it out and let me know in that issue if it solves the problem or if you have any other issues with it.

**Comment by rjmholt** [comment] 2019-11-29 22:22
Good information -- thanks for letting me know. You're on macOS, yes?

**Comment by rjmholt** [comment] 2019-11-29 22:28
> Any idea when this will make its way into the main release? 

It'll likely be in the next preview

**Comment by chip-felton-montage** [comment] 2019-11-30 03:32
Yes, MaOS Catalina 10.15.1


On 30/11/2019, at 11:22 AM, Robert Holt <notifications@github.com<mailto:notifications@github.com>> wrote:


Good information -- thanks for letting me know. You're on macOS, yes?

**Closed** 2019-12-01 04:00 UTC
Labels: Needs: Attention :wave:, Resolution-Duplicate
