### ISSUE TITLE
Debugging hangs when stepping through a while loop

### ISSUE THREAD

**Issue by vsccarl** [PowerShell/vscode-powershell#156] opened 2016-04-22 19:26 UTC
Code Version: 1.0.1-alpha
OS: Windows 10

Repro Steps:
1. Add the below code
2. Add breakpoints on line 4 and line 22
3. Add "str" to watch (not '$str')
4. Start debugging
5. Continue to hit the breakpoint on line 4
6. Step-over in the while loop, then slowly step-over through the while loop

Actual:
Debugging hangs and will not allow you to continue or step-over. When pushing stop and error pops up saying Canceled. Sometimes an error shows "Debug adapter process has terminated unexpectedly."

``` powershell
function Write-Item($itemCount) {
    $i = 1

    while ($i -le $itemCount) {
        $str = "Output $i"
        Write-Output $str

        # In the gutter on the left, right click and select "Add Conditional Breakpoint"
        # on the next line. Use the condition: $i -eq 25
        $i = $i + 1

        # Slow down execution a bit so user can test the "Pause debugger" feature.
        Start-Sleep -Milliseconds 100
    }
}

# Do-Work will be underlined in green if you haven't disable script analysis.
# Hover over the function name below to see the PSScriptAnalyzer warning that "Do-Work"
# doesn't use an approved verb.
function Do-Work($workCount) {
    Write-Output "Doing work..."
    Write-Item $workcount
    Write-Host "Done!"
}

Do-Work 50


```

**Comment by rkeithhill** [comment] 2016-04-23 20:47
Thanks for the repro.  It seems that the key is the watched expression that fails to evaluate.  Changing to `str` to `$str` works fine because `$str` evaluates without an error.  It seems there is something about us evaluating an invalid expression that is wedging the debugger.

**Comment by rkeithhill** [comment] 2016-04-23 20:50
And it really has nothing to do with the watch window.  It is merely executing script that generates errors.  Remove the watch and put `str` on `line 12`.  Same thing happens after a while of stepping. The debugger wedges.  :-( 

I guess that is one way to teach folks not to write code that generates errors.  :-)

**Comment by daviwil** [comment] 2016-04-25 13:44
Gonna mark this as an issue to investigate for 0.6.0

**Comment by rkeithhill** [comment] 2016-04-29 03:28
If I step really, really fast after a while a while the debug host crashes with:
```
    FATAL UNHANDLED EXCEPTION:
    
    System.InvalidOperationException: The collection has been marked as complete with regards to additions.
       at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Collections.Concurrent.BlockingCollection`1.Add(T item)
       at Microsoft.PowerShell.EditorServices.Utility.ThreadSynchronizationContext.Post(SendOrPostCallback callback, Object state) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\ThreadSynchronizationContext.cs:line 42
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.SendEvent[TParams](EventType`1 eventType, TParams eventParams) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 175
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<DebugService_DebuggerStopped>d__30.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs:line 538
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()

4/28/2016 9:23:53 PM [ERROR] - Method "CurrentDomain_UnhandledException" at line 178 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\Program.cs

    FATAL UNHANDLED EXCEPTION:
    
    System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.DebugAdapter.StackFrame.Create(StackFrameDetails stackFrame, Int32 id) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\DebugAdapter\StackFrame.cs:line 37
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleStackTraceRequest>d__25.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs:line 400
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 279
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 226
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContext.cs:line 48
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContextThread.cs:line 65
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 79
       at Microsoft.PowerShell.EditorServices.Host.Program.Main(String[] args) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\Program.cs:line 168
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.DebugAdapter.StackFrame.Create(StackFrameDetails stackFrame, Int32 id) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\DebugAdapter\StackFrame.cs:line 37
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleStackTraceRequest>d__25.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs:line 400
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 279
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 226
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContext.cs:line 48
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContextThread.cs:line 65
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.Protocol.DebugAdapter.StackFrame.Create(StackFrameDetails stackFrame, Int32 id) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\DebugAdapter\StackFrame.cs:line 37
       at Microsoft.PowerShell.EditorServices.Protocol.Server.DebugAdapter.<HandleStackTraceRequest>d__25.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs:line 400
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__32.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 279
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<ListenForMessages>d__31.MoveNext() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs:line 226
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContext.cs:line 48
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContextThread.<>c__DisplayClass4_0.<Run>b__0() in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Utility\AsyncContextThread.cs:line 65
       at System.Threading.Tasks.Task.Execute()<---
    <---
```
Is there any form of `pacing` between the client and host to prevent client requests from getting too backed up?

**Comment by daviwil** [comment] 2016-05-11 00:29
Hmm...  I haven't been able to reproduce this issue in the latest state of everything, even with the repro hints that Keith added..  I'm going to move this to 0.7.0 to give a little more time for investigation.

**Comment by rkeithhill** [comment] 2016-05-15 18:32
Still repros for me.  I pretty much press F10 after it hits the breakpoint and it sometimes wedges.  See the attached debug log.

[DebugAdapter.txt](https://github.com/PowerShell/vscode-powershell/files/265182/DebugAdapter.txt)

This part of the log looks suspect:
```
5/15/2016 12:22:18 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 804,
      "command": "next",
      "arguments": {
        "threadId": 1
      }
    }

5/15/2016 12:22:18 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "804",
      "command": "next",
      "success": true,
      "body": null
    }

5/15/2016 12:22:18 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "804",
      "command": "next",
      "success": true,
      "body": null
    }
```
Notice the two writes with seq number `804`.  Could be a glitch with logging.  If not, could that mess up vscode?

**Comment by tylerl0706** [comment] 2018-01-30 23:37
I'm having trouble reproing this. It _might_ be fixed. Can anyone repro the issue?

**Comment by rkeithhill** [comment] 2018-01-31 18:37
When I say press F10 above, what I really mean is press **and hold** F10.

**Comment by tylerl0706** [comment] 2018-02-01 01:09
Worked on macOS but I did experience a hang on my Windows VM.

**Comment by rkeithhill** [comment] 2018-02-01 01:58
Good ol' monkey testing FTW. BTW I believe we should close this issue.  I've tried the repro instructions and the original issue no longer repros.  Then we should open a new issue along the lines of "Stepping too fast in the debugger causes a hang on Windows".

**Comment by tylerl0706** [comment] 2018-02-01 16:02
I agree.

**Closed by tylerl0706** 2018-02-01 16:02 UTC
Labels: Area-Debugging, Issue-Bug, OS-Windows
