### ISSUE TITLE
Selection highlight colors within breakpoint (PowerShell ISE Theme)

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#1194] opened 2018-02-09 11:34 UTC
### System Details

- Operating system name and version:
- VS Code version: 1.20.0
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ code -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Temp\Test> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0


PS C:\Temp\Test> code --list-extensions --show-versions
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ code --list-extensions --show-versions
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

### Issue Description

I've noticed that when I try selecting a some code within a line at which the debugger has stopped at breakpoint, the selection doesn't show up which is somewhat confusing (i.e. I have word something selected on line 2):
![image](https://user-images.githubusercontent.com/18121861/36025799-115b3b3c-0d9d-11e8-947f-41a66f3e243f.png)

Here's how it looks in PowerShell ISE:
![image](https://user-images.githubusercontent.com/18121861/36025835-33bfec68-0d9d-11e8-9865-5e86e12e6271.png)

Is it possible to make the selection highlighting look different within a breakpoint line?
### Attached Logs

Please let me know if logs are actually needed.

**Comment by mattmcnabb** [comment] 2018-02-09 14:38
Logs probably aren't needed. I'll take a look and see if there's another way to highlight this. At first glance I think the problem is that the debugger highlight is the same color as the cursor highlight.

**Comment by mattmcnabb** [comment] 2018-02-10 15:03
Ok, I now think this may be a bug in the light theme defaults in VSCode itself. I was able to repro your issue with any light theme, but not with included dark themes:

### Light
![image](https://user-images.githubusercontent.com/6998507/36063322-7c622808-0e49-11e8-8144-6df756af8aa2.png)

### Dark
![image](https://user-images.githubusercontent.com/6998507/36063326-900bd156-0e49-11e8-97d6-fbf38a8c28a1.png)

I'll see if someone on the VSCode team can take a look at this.

**Comment by Tyriar** [comment] 2018-02-10 17:17
@mattmcnabb yeah it looks like a color clash with the light theme(s), you should create an issue at https://github.com/Microsoft/vscode

**Comment by tylerl0706** [comment] 2018-02-15 01:00
I'm going to close this as external for now since this is really outside of the extension's control. Go ahead and use @mattmcnabb's to track the issue.

Thanks all!

**Closed by tylerl0706** 2018-02-15 01:00 UTC
