### ISSUE TITLE
Login-AzureRmAccount doesn't prompt for login credentials

### ISSUE THREAD

**Issue by legobytes** [PowerShell/vscode-powershell#239] opened 2016-08-17 13:29 UTC
Seems to be a recurrence of #155 .

If I put a break on the line following the Login-AzureRmAccount, it will prompt for credentials.

VS Code: 1.4.0
PowerShell Extenstion: 0.6.2
OS: Windows 10 Version 1607 (OS Build 14393.10)
PowerShell: 5.1.14393.0

**Comment by legobytes** [comment] 2016-08-22 12:24
Appears to be resolved in 0.7.0

**Comment by daviwil** [comment] 2016-08-22 20:03
Interesting!  Not sure I did anything to fix it :)  Since it's working now I'll close this issue.  Please let me know if you see it again and I'll reopen to investigate.  Thanks!

**Closed by daviwil** 2016-08-22 20:03 UTC

**Comment by stas-sultanov** [comment] 2018-02-05 11:45
The problem reproduces from Terminal window
prompt window does not appear

VS Code:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

vscode-powershell 1.5.1

**Comment by tylerl0706** [comment] 2018-02-06 05:58
@stas-sultanov can you check to see if the prompt opened up behind VSCode?

We've been seeing that a lot and opened an issue here on VSCode:
https://github.com/Microsoft/vscode/issues/42356
