### ISSUE TITLE
Wrong reference highlighting and count in DSC module

### ISSUE THREAD

**Issue by wasker** [PowerShell/vscode-powershell#2641] opened 2020-04-17 20:43 UTC
Issue Description
=====

I'm working on DSC module and some references are not highlighted and counted correctly.

![powershell-names](https://user-images.githubusercontent.com/1999365/79612351-6036eb00-80b1-11ea-9b5c-38a83e76d666.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about capturing and sending logs.

**This link ^^^ is broken.**

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.44.2|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.14.5|
|markdown-toc|AlanWalk|1.5.6|
|powershell|ms-vscode|2020.4.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|rewrap|stkb|1.9.1|
|spellchecker|swyphcosmo|1.2.13|
|vscode-base64|adamhartford|0.1.0|
|vscode-guid|heaths|1.4.19|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|

**Comment by SydneyhSmith** [comment] 2020-04-21 21:11
@wasker thanks for opening this issue, sorry that the README link is broken we'll have to fix that...
It would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by wasker** [comment] 2020-04-22 23:12
Here you go:

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4519383/logs.zip)

**Comment by SydneyhSmith** [comment] 2020-04-28 21:37
Thanks @wasker looks like the stack trace is here: 
```
2020-04-22 16:08:28.295 -07:00 [ERR] Execution of the following command(s) completed with errors:

    Microsoft.PowerShell.Core\Get-Command DisableDisallowedProtocols -ErrorAction Ignore


2020-04-22 16:08:28.297 -07:00 [FTL] Failed to handle notification textDocument/hover
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.CommandHelpers.<GetCommandInfoAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Services.Symbols.SymbolDetails.<CreateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Services.SymbolsService.<FindSymbolDetailsAtLocationAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Handlers.HoverHandler.<Handle>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__9.MoveNext()
2020-04-22 16:08:28.298 -07:00 [DBG] Finished: Routing Request (22) textDocument/hover in 49ms
2020-04-22 16:08:28.641 -07:00 [DBG] Finding descriptor for textDocument/hover
```

**Comment by TylerLeonhardt** [comment] 2020-04-28 23:55
I'm thinking the stack trace is not related... we're just not calculating the column correctly...

@wasker can you share what these functions are wrapped in? They seem to be indented a bit.

**Comment by TylerLeonhardt** [comment] 2020-04-29 00:04
I have a fix for that stack trace here: https://github.com/PowerShell/PowerShellEditorServices/pull/1276

**Comment by wasker** [comment] 2020-04-30 02:26
Followed up offline with the file.

**Comment by TylerLeonhardt** [comment] 2020-04-30 21:49
The highlighting is a dupe of https://github.com/PowerShell/vscode-powershell/issues/305 (which is fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/1279)

**Comment by wasker** [comment] 2020-04-30 23:06
What about the case of "DisableRC4" (highlighted in yellow) - it has 0 references, even though there clearly is a reference to this function.

**Comment by TylerLeonhardt** [comment] 2020-05-01 22:36
That I'm not sure yet... very bizarre because it looks to be just like the others... the only difference is that it has a number in it? But that shouldn't matter.

**Comment by andschwa** [comment] 2023-02-07 22:30
Hey @wasker I know this is an old issue, but can you verify that this is fixed in the latest preview? We just redid all the symbols logic and I think this should be fixed.

**Comment by andschwa** [comment] 2023-02-23 19:29
Haven't heard back, assuming this is fixed!

**Closed by andschwa** 2023-02-23 19:29 UTC
Labels: Issue-Bug, Needs: Fix Verification 🤞, Area-Symbols & References
