### ISSUE TITLE
Request: Add IntelliSense support for pipeline script syntax

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#4433] opened 2023-02-26 11:21 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Currently, the keyword `Process` is not supported at script root. This keyword, however, is required for scripts processing the pipeline:

[StackOverflow: How can I get all pipeline elements at a time?](https://stackoverflow.com/questions/75526029/how-can-i-get-all-pipeline-elements-at-a-time#answer-75526329)

Currently, whenever you hit `Process` and [Enter], an arbitrary Cmdlet is being inserted in the VS Code editor.

### Proposed Design

Add IntelliSense support for keywords `Begin`, `Process` and `End` at root level.

Plus: Capitalize `param` code snippet content as `Param` (with capital `P`).

![Process](https://user-images.githubusercontent.com/9283914/221407477-b014f04c-9803-44ac-96f0-08515dd7690d.png)

**Comment by SeeminglyScience** [comment] 2023-02-27 18:11
Duplicate of PowerShell/PowerShell#10221

**Comment by SeeminglyScience** [comment] 2023-02-27 18:11
Thanks for the report! We're tracking this in the issue above

**Comment by SeeminglyScience** [comment] 2023-02-27 18:17
> Plus: Capitalize param code snippet content as Param (with capital P).

Keywords are intended to be all lowercase, partially to differentiate easier between commands, but mostly due to the languages PowerShell is modeled after. They aren't case sensitive so feel free to use the style you prefer but when intellisense is added for those it will likely also be all lowercase

**Comment by MartinGC94** [comment] 2023-02-27 21:41
Maybe an alternative fix for this could be to automatically dismiss the IntelliSense menu when the input is parsed as a keyword? The main complaint here is that the user accidentally adds an unintended command/snippet when they want a keyword, not that typing in a keyword is difficult or inconvenient.  
I've personally looked into implementing keyword completion in PowerShell but felt like it was too much work for too little benefit so it would take someone very passionate about it to implement it.

**Comment by SeeminglyScience** [comment] 2023-02-28 18:50
> Maybe an alternative fix for this could be to automatically dismiss the IntelliSense menu when the input is parsed as a keyword?

Tbh I'm not sure we have a mechanism to do that, though I don't disagree with you

**Closed** 2023-03-01 19:01 UTC
Labels: Issue-Enhancement, Resolution-Duplicate
