### ISSUE TITLE
Displayed Reference Count Doubled When In Folder

### ISSUE THREAD

**Issue by Kmek** [PowerShell/vscode-powershell#2875] opened 2020-08-06 20:35 UTC
### System Details

System Details Output
```
### VSCode version: 1.47.3 91899dcef7b8110878ea59626991a18c8a6a1b3e x64

### VSCode extensions:
CoenraadS.bracket-pair-colorizer-2@0.2.0
eamodio.gitlens@10.2.2
ms-vscode.powershell@2020.6.0
shd101wyy.markdown-preview-enhanced@0.5.12
streetsidesoftware.code-spell-checker@1.9.0


### PSES version: 2.2.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the displayed reference count for functions. It seems that when a file is in a subfolder, the displayed reference count is doubled. I have included numerous screenshots of my findings.

#### Expected Behaviour

This is my gutted code from the file `YmlForm.ps1`. This is the only file present in this project & open in VS Code, so the issue is narrowed down to only this file. This file is in a subfolder called `YmlForm`.
```
$AnotherScriptBlock = {
    $DockerComposeFile = DetectAndRemoveNewLines $DockerComposeFile
    InitialCommentsHighlight
}

Function DetectAndRemoveNewLines {
    # Code Removed
}

Function InitialCommentsHighlight {
    # Code Removed
}

$AnotherScriptBlock2 = {
    InitialCommentsHighlight
}

$AnotherScriptBlock3 = {
    $DockerComposeFile = DetectAndRemoveNewLines $DockerComposeFile
}
```

The reference counts for both the `DetectAndRemoveNewLines` and the `InitialCommentsHighlight` functions should be 2.

#### Actual Behaviour

Instead, the reference counts for both the `DetectAndRemoveNewLines` and the `InitialCommentsHighlight` functions are 4.

![Powershell-ext-inside-folder](https://user-images.githubusercontent.com/32857933/89578051-95ea1600-d7ff-11ea-984b-83cf2cac892f.PNG)

The dropdown only shows two references, which is correct, but the displayed reference count is incorrect.

![Powershell-ext-inside-folder-displays-2](https://user-images.githubusercontent.com/32857933/89578154-bb771f80-d7ff-11ea-866d-ba2c9a36b049.PNG)

More interestingly, when I add another function call of `InitialCommentsHighlight`, the reference count for that function jumps to 6, indicating that the reference count is being doubled somehow.

![Powershell-ext-inside-folder-displays-3](https://user-images.githubusercontent.com/32857933/89578527-41936600-d800-11ea-8561-511a3f986aff.PNG)

I noticed that when the `YmlForm.ps1` file was not in the subfolder `YmlForm`, the reference counts were displayed properly.

![Powershell-ext-outside-folder](https://user-images.githubusercontent.com/32857933/89578637-74d5f500-d800-11ea-968f-2222e05d65cf.PNG)

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment] 2020-08-06 21:02
I wonder if this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2810

**Comment by SydneyhSmith** [comment] 2020-08-06 21:22
Thanks @Kmek could you please also attach payload logs to this issue #2810 --instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs)

**Closed** 2020-08-07 22:00 UTC
Labels: Resolution-Duplicate
