### ISSUE TITLE
External Program Execution

### ISSUE THREAD

**Issue by g-pearl** [PowerShell/vscode-powershell#2764] opened 2020-06-12 16:07 UTC
### System Details

System Details Output
```

- Operating system name and version Windows 10 Enterprise 1909 Build 19363.836

### VSCode version: 1.45.1 5763d909d5f12fe19f215cbfdd29a91c0fa9208a x64

### VSCode extensions:
ironmansoftware.powershellprotools@5.11.0
ms-vscode.powershell@2020.6.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with running an external program
$times = (&"D:\exiftool-11.99\exiftool.exe" $filepath -csv -q | ConvertFrom-Csv).duration

#### Expected Behaviour

-- Description of what *should* be happening --
This should provide me the duration of all the video files in the specific path.  This works without any issue in the ISE on the same machine

#### Actual Behaviour

-- Description of what actually happens --
When this line is run it never proceeds.  The program does not run and results are not provided.
I have tried breaking in down to smaller steps and that runs inconsistently.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment] 2020-06-12 16:28
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2559

**Closed** 2020-06-13 19:00 UTC
Labels: Resolution-Duplicate
