### ISSUE TITLE
ctrl-c not working in terminal

### ISSUE THREAD

**Issue by Chiliyago** [PowerShell/vscode-powershell#227] opened 2016-07-14 22:43 UTC
In version 1.3.1 I noticed that ctrl-c does work which prevents exiting the current command.  In my case I configured terminal to open PowerShell.

Example:
```
PS: >mkdir
cmdlet mkdir at command pipeline position 1
Supply values for the following parameters:
Path[0]:  <<ctrl-c should exit but it does not work>>
```

**Comment by daviwil** [comment] 2016-07-14 22:45
Where is this, in the integrated terminal?  If so, you'll need to file a bug at the https://github.com/Microsoft/vscode repository because they own the UI for that terminal experience.

**Comment by daviwil** [comment] 2016-07-21 15:14
Looks like you filed this issue over at the VS Code repo, thanks for doing that!  I'll close this issue now since the problem is being tracked here:

https://github.com/Microsoft/vscode/issues/9347

**Closed by daviwil** 2016-07-21 15:14 UTC
