### ISSUE TITLE
Fails to detect the installed version of powershell Ubuntu Snap

### ISSUE THREAD

**Issue by antonydeepak** [PowerShell/vscode-powershell#2454] opened 2020-02-03 00:30 UTC
I have Powershell core installed in Ubuntu through Snap. This vscode extension fails to detect the installed version. Running `ShowSessionMenu`(or other powershell commands) fails with
`Running the contributed command: 'PowerShell.ShowSessionMenu' failed.`

I have updated the `powerShellAdditionalExePaths` but doesn't seem to help
```
 "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "/snap/bin/powershell",
            "versionName": "PowerShell 6.2.4(Snap)",
        },
    ],
    "powershell.powerShellDefaultVersion": "PowerShell 6.2.4(Snap)",
```

I turned on `Diagnostic` logging but surprisingly there are no logs in `/home/antonydeepak/.vscode/extensions/ms-vscode.powershell-2020.1.0/logs/`

#### System
`uname -a` -> `Linux <name> 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`$PsVersionTable`

```
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Linux 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment] 2020-02-03 18:34
It sounds like the whole extension is failing to start if you're unable to run `ShowSessionMenu`.

I just tried running this on my Ubuntu 18.04.4 LTS VM but wasn't able to reproduce it myself:

![snap](https://user-images.githubusercontent.com/7009879/73678420-30a94280-466d-11ea-96ea-d82a812274af.JPG)

That VM's details:

```
> uname -a
Linux ubuntuUI 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> $PSHome
/snap/powershell/88/opt/powershell
```

In some other cases of startup issues like this, it's come down to a particular machine configuration issue (for example, one user had overridden BSD `stat` with GNU `stat` on macOS).

I do notice your `uname` output indicates 18.04.1 but also indicates a v 5.3 kernel, so maybe there's some customisation in your install that we need to work around? Could you give us some details on how to set up an installation like the one you're running?

**Comment by antonydeepak** [comment] 2020-02-06 07:26
So, I found that `Powershell: Restart Current Session` worked. So making it permanent with `powershell.startAutomatically` kinda solved the problem.

Thank you for the timely help.

**Comment by TylerLeonhardt** [comment] 2020-02-06 15:15
The PowerShell extension starts automatically when you open a PowerShell file in the editor.

Does this not happen for you?

**Comment by antonydeepak** [comment] 2020-02-06 19:05
Looks like it does not. One another thing I noticed is that it happens in my Windows as well. So, it might be something about the way I configure my powershell core.

**Comment by SydneyhSmith** [comment] 2020-02-06 22:34
@antonydeepak thanks, could please share the entirety of your user and workspace settings if possible?

**Comment by antonydeepak** [comment] 2020-02-11 06:09
[user_settings.txt](https://github.com/PowerShell/vscode-powershell/files/4184280/code_user_settings.txt) - paths have been fuzzed.
Since I open random powershell files which are not part of any workspace, I am not sure if any workspace settings would help.

**Comment by SydneyhSmith** [comment] 2020-02-11 22:14
@antonydeepak we published an update to our [Preview Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?

**Comment by antonydeepak** [comment] 2020-02-12 05:06
@SydneyhSmith I guess the problem here is that `powershell.startAutomatically` option should be enabled for powershell extension to activate on opening a powershell file. Guess this option was not enabled by default in my installation  when I originally reported the issue; now that I have it turned on, the extension works all the time. Guess that explains right?

**Comment by SydneyhSmith** [comment] 2020-02-13 18:49
@antonydeepak glad to hear you were able to resolve your issue, thanks for reporting back. I am not sure what the underlying cause is for this, since the default value is supposed to be true, but given that you are the only one reporting this and you are resolved, I will close this issue for now.

**Closed by SydneyhSmith** 2020-02-13 18:49 UTC
Labels: Needs-Repro-Info, Needs: Attention :wave:
