### ISSUE TITLE
Syntax highlighter crasehes after typing subexpression within Write-Host cmd

### ISSUE THREAD

**Issue by 1RedOne** [PowerShell/vscode-powershell#1229] opened 2018-03-15 18:00 UTC
## Issue Description ##

Syntax highlighter reports everything as error when typing a $SubExpression.  

## Attached Logs ##

*sent via email* 
Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.14393 |
| VSCode | 1.20.1|
| PowerShell Extension Version | 1.6.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.14393.2068|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14393.2068|
|BuildVersion|10.0.14393.2068|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer|CoenraadS|1.0.20|
|git-indicators|lamartire|2.1.1|
|gitlens|eamodio|8.1.1|
|hopscotch|idleberg|0.2.2|
|nord-visual-studio-code|arcticicestudio|0.6.0|
|PowerShell|ms-vscode|1.6.0|
|theme-glacier|Kal|0.0.1|;

</details>

**Comment by 1RedOne** [comment] 2018-03-15 18:01
I mean, I know that I should avoid Write-host, but I didn't think it would crash VSCode Syntax Highlighter.

**Comment by rkeithhill** [comment] 2018-03-20 04:15
What exactly do you mean by crashing?  Does the language server actually crash?  If so, can you please provide the log files for that session (see https://github.com/PowerShell/vscode-powershell#reporting-problems for instructions on attaching a zip of the log files).  Or do you see that syntax colorization is messed up after this command?

**Comment by rjmholt** [comment] 2018-03-21 06:03
If you have an error trace for a crash like this, that would very helpful

**Comment by tylerl0706** [comment] 2018-03-25 14:27
I think I understand what @1RedOne is saying and I think it's a dupe of https://github.com/PowerShell/vscode-powershell/issues/1232. 

My guess is `syntax highlighter` is PSSA results (aka squiggles 👍 ).

**Comment by tylerl0706** [comment] 2018-03-27 00:28
Hmm I don't think I got the email. You sent it to: `vscode-powershell@microsoft.com`?

**Comment by tylerl0706** [comment] 2018-03-27 00:29
Alternatively you can upload the zip here so more eyes can debug 😄 lots of awesome non-Microsoft maintainers 😄

**Comment by tylerl0706** [comment] 2018-07-31 21:41
I don't think I ever got your email... :(

The squiggles are due to PSScriptAnalyzer and if you're receiving those when you shouldn't be, it's better to open an issue here: https://github.com/PowerShell/PSScriptAnalyzer

If it's related to general slowness of the extension not updating squiggles that's tracked with https://github.com/PowerShell/vscode-powershell/issues/1232

And if syntax highlighting is breaking for some reason, you'll want to open an issue on:
https://github.com/powershell/editorsyntax

I'm going to close this as both a mix of a dupe of 1232 and an external issue. If you see otherwise, let me know and I'm more than happy to reopen :)

**Closed by tylerl0706** 2018-07-31 21:41 UTC
Labels: Area-IntelliSense, Issue-Bug, Needs-Repro-Info
