### ISSUE TITLE
Add-AzureRmAccount hangs PowerShell Editor Services

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#178] opened 2016-05-14 12:05 UTC
Using version 0.6.0 of the PowerShell extension, `Add-AzureRmAccount` appears, but it hangs VS Code. I can't run any other commands with F8.

![image](https://cloud.githubusercontent.com/assets/466713/15268382/b3e04a0e-1999-11e6-9d4d-7d696a43a8a8.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment] 2016-05-14 17:39
Hmm, I can't repro this.  I was able to add an account using that cmdlet and then use F8 to run something else afterward:

```
PS C:\Program Files (x86)\Microsoft VS Code
Add-AzureRmAccount



Environment           : AzureCloud
Account               : david@daviwil.com
TenantId              : 1d5441f7-e6fa-40cb-a67f-ad29489c6f8e
SubscriptionId        : 932d132b-a8ba-490d-b10e-5a4bc5d404f4
CurrentStorageAccount : 




PS C:\Program Files (x86)\Microsoft VS Code
function Stop-LanguageServer($languageServer) {

}


PS C:\Program Files (x86)\Microsoft VS Code
Write-Output "INITIALIZED"

INITIALIZED

PS C:\Program Files (x86)\Microsoft VS Code
```

I'm also able to get IntelliSense etc after running it.  Have you tried this in a fresh VS Code session?  There may be some specific set of steps needed to make it happen.

**Comment by vikram-pendli** [comment] 2017-06-05 00:08
Hi,
I am also running into similar issue. Below is the version information for Visual Studio Code that I am using.

```
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

```
PowerShell extension version is `1.2.1`

VSCode is unable to display the Microsoft login prompt when we execute the CmdLet
`Add-AzureRmAccount`
This happens in all the following cases
1. Run the script (Ctrl + F5)
2. Debug thescript (F5)
3. Run the CmdLet from the integrated terminal shell.

Here is the prompt window when I run the command from regular  PowerShell console or ISE
![image](https://cloud.githubusercontent.com/assets/11705169/26766509/6ddb1536-4961-11e7-82f8-310f0f2af204.png)

Please let me know if I can provide any other information to help out.

**Comment by jwikman** [comment] 2018-01-17 13:31
I experience the same issue.

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.6
stuck-overflow|dge|0.2.1
vscode-PSStackoverflow|Dou|0.0.2
code-runner|for|0.8.7
codeshell|Kip|0.2.2
mssql|ms-|1.3.0
PowerShell|ms-|1.5.1
team|ms-|1.122.0
---
Reproduces without extensions: Yes

Steps to Reproduce:

1. Install latest AzureRM version from PowerShell ISE in elevated mod
```
Install-Module AzureRM -AllowClobber
```
2. Open VS Code with PowerShell as the terminal. 
3. Run the command in any way of 
- Run the script (Ctrl + F5)
- Debug thescript (F5)
- Run the CmdLet from the integrated terminal shell.
```
Add-AzureRmAccount
```
4. Now it just hangs...


The expected behavior is that a login prompt window should be opened (seen in the post above by @vikram-pendli )

@daviwil please just let me know if you need any more info. 

I was first just so happy when I switched to VS Code for developing my Azure PowerShell Script, but now i can't test them inside VS Code :(

**Comment by jwikman** [comment] 2018-01-17 13:57
Gaaah, I just found out what the issue is!

The login prompt window is opened behind all other open windows. And since it does not show up in task bar, you only see it if you minimize all other windows or if you use Alt+Tab...

So, this does is likely not a VS Code issue (or is it?), but an Azure PowerShell module issue. 

I found answer here (after searching closed issues as well): https://github.com/Microsoft/vscode/issues/28470

**Comment by tylerl0706** [comment] 2018-02-02 17:58
@jwikman yep. This is either a vscode or electron issue. I opened it on vscode since they closed the last one:

https://github.com/Microsoft/vscode/issues/42356

I'm going to close this issue since Add-AzureRmAccount isn't hanging. Let's watch the bug I created for the dialog showing behind vscode.

**Closed by tylerl0706** 2018-02-02 17:58 UTC
Labels: Needs-Repro-Info
