### ISSUE TITLE
Debug seems to hang when calling a python script within my PowerShell scripts

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#163] opened 2016-04-28 20:05 UTC
Hi,

I'm not sure if the is your bug or VSCode, so have posted to both.

I have a relatively simple PS script, but when I run a debug in VSCode, VSCode, seems to hang when invoking the Python script. However, if I set a break point (say on line 19 below), and press "pause", I see the output from the Python script in the Debug console and the breakpoint has been hit,

```
$ErrorActionPreference="SilentlyContinue"
Stop-Transcript | out-null
$ErrorActionPreference = "Continue"

$SnapsToTest = Get-ChildItem C:\Snaps\ -Directory
$ErrorFile = "C:\Tools\Scripts\Errors.txt"
$SnapDir = "C:\Logs"
$LogDir = "\var\log\"
$LogFile = "support.log"
$env:PYTHONIOENCODING="UTF-8"

Start-Transcript -path $ErrorFile
Push-Location
Set-Location -Path $SnapDir

$SnapsToTest | ForEach-Object {
        Write-Host $_.Name
        python C:\Tools\Scripts\script1.py $_.Name
        $LogToTest = $_.Name+$LogDir+$LogFile
        python C:\Tools\Scripts\script2.py $LogToTest
    }

Pop-Location
Stop-Transcript
```

**Comment by swinster** [comment] 2016-04-28 20:08
https://github.com/Microsoft/vscode/issues/5960

**Comment by rkeithhill** [comment] 2016-04-28 20:31
I suspect this has nothing to do with Python but is a duplicate of this issue https://github.com/PowerShell/vscode-powershell/issues/149   Can you verify this by commenting out the calls to python and try running the script (without breakpoints) and see if it still hangs?

**Comment by daviwil** [comment] 2016-04-28 20:49
I agree, this is due to the issue we currently have.  You should go ahead and close your issue on the VS Code repo, we'll have this fixed soon.  Thanks!

**Comment by daviwil** [comment] 2016-05-13 01:59
I tried to repro this issue and it seems that something weird is indeed going on when running Python in the debugger.  I'll have to look into this in more depth soon.

**Comment by tylerl0706** [comment] 2018-01-31 00:02
I can't seem to repro this anymore. Can anyone else give it a try?

**Comment by tylerl0706** [comment] 2018-07-31 21:29
Closing due to inactivity.

**Closed by tylerl0706** 2018-07-31 21:29 UTC
Labels: Area-Debugging, Issue-Bug, Needs-Repro-Info
