### ISSUE TITLE
VS Code freeze while "starting powershell"

### ISSUE THREAD

**Issue by pilgi3** [PowerShell/vscode-powershell#2568] opened 2020-03-18 07:46 UTC
We have written the n
Issue Type: <b>Bug</b>

We war using the software Privilege Management for Windows (Avecto).
Since version 2020.3.0 Visual Code freeze while starting the Integrated Console.

Start Visual Code and change the type of the file to powershell.
I see in the right bottom corner "starting powershell".
After a few seconds the dialog appears if i want "reload, still waiting, or close" .
So i open a new window and disable the extension
Then i install the older version 2020.1.0 with right click on the extension and choose "install another version" - no issue or freezing.

Extension version: 2020.1.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (14.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
eeded data into your clipboard because it was too large to send. Please paste.

**Comment by EdCallahan** [comment] 2020-03-19 15:10
Me as well. After the 2020.3.0 update Code froze when Starting Powershell. This only occurred on my workstation with Avecto installed, not on the ones I have without Avecto. I was able to downgrade to 2020.1.0 and keep working.

This morning my sysadmin made Avecto policy changes that made 2020.3.0 work for me. I wasn't able to get much for details from him, but he "created a rule that will run that file [code.exe] elevated and all child processes".

**Comment by rjmholt** [comment] 2020-03-19 21:13
Looks like this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2377.

@EdCallahan I believe you're seeing a different, more general startup hang caused by AV. Our current thinking on this is that we should try and document known software that causes startup issues here

**Comment by TylerLeonhardt** [comment] 2020-03-19 21:14
Does the following VS Code setting help at all?

```
"powershell.integratedConsole.useLegacyReadLine": true
```

**Comment by pilgi3** [comment] 2020-03-19 22:11
> Does the following VS Code setting help at all?
> 
> ```
> "powershell.integratedConsole.useLegacyReadLine": true
> ```

I have tried, but unfurtunately not.

**Comment by mmascolino** [comment] 2020-03-20 15:17
@TylerLeonhardt if it helps with #2526, this computer also has BeyondTrust on it.

**Comment by pilgi3** [comment] 2020-03-23 07:26
> Me as well. After the 2020.3.0 update Code froze when Starting Powershell. I was able to downgrade to 2020.1.0 and keep working.
> 
> This morning my sysadmin made Avecto policy changes that made 2020.3.0 work for me. I wasn't able to get much for details from him, but he "created a rule that will run that file [code.exe] elevated and all child processes".

We have tried, but without success - still the same behaviour.

**Closed** 2020-03-24 19:00 UTC
Labels: Resolution-Duplicate
