### ISSUE TITLE
Exception When Line is Too Long in PowerShell Integrated Console

### ISSUE THREAD

**Issue by changbowen** [PowerShell/vscode-powershell#2126] opened 2019-08-07 04:27 UTC
### System Details

Using code in portable mode.

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

The extension version is 2019.5.0.

### Issue Description

Exception when the line is too long in PowerShell Integrated Console. E.g. keep typing "a" until it reaches the right window border.
Seems the exception only occurs after start and stop debugging a script with a Read-Host at least once. For example after running the below with F5:
```
Read-Host 'test1'
Write-Host 'test2'
```
Then keep typing "a" into the Integrated Console. An exception will be thrown when the line reaches the right window border.
#### Expected Behaviour

Come on...

#### Actual Behaviour

The below exception is thrown.
```
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 17.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()
```

**Comment by corbob** [comment] 2019-08-07 13:23
I think this is a duplicate of #702. Reading through that, it sounds like this might be alleviated by the preview extension, but there's also mention that PSRL also has this issue, so it might not be quite fixed there.

**Comment by changbowen** [comment] 2019-08-08 09:13
Looks like the preview version does fix the problem. Hope it gets released soon.
Thanks!

**Comment by rjmholt** [comment] 2019-08-08 21:40
> there's also mention that PSRL also has this issue

PSRL is also making progress here. Despite all the work trickiness of managing it, this is why we went with taking PSRL into PSES; deduplication of work.

**Closed** 2019-08-10 09:00 UTC
Labels: Needs: Attention :wave:, Resolution-Duplicate
