### ISSUE TITLE
Many standard 'Visual Studio Code' features not working when developing PowerShell 'class'es

### ISSUE THREAD

**Issue by Pantharian** [PowerShell/vscode-powershell#1094] opened 2017-11-08 13:38 UTC
### System Details

- Operating system name and version: Windows 7 Pro Version 6.1 (Build 7601 Service Pack 1)
- VS Code version: 1.17.2
- PowerShell extension version: 1.5.0
- Output from `$PSVersionTable`:
```
Name                           Value
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.36392
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      0      0

code --list-extensions --show-versions
ms-vscode.PowerShell@1.5.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.36392
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Many of the standard features in 'Visual Studio Code' do not work with files containing PowerShell classes. e.g. syntax highlighting, Peek Definition, Rename (F2)  etc. IntelliSense and PSScriptAnalyzer **are** working.

An example of Peek Definition not working when the method is part of a class:
![peek-definition-not-working](https://user-images.githubusercontent.com/26254144/32551634-14e01028-c489-11e7-8bf6-b0c99c8c8e62.PNG)

An example of the same code working when converted to functions:
![peek-definition-working](https://user-images.githubusercontent.com/26254144/32551770-8514a08e-c489-11e7-9dab-8cf986d3b8ba.PNG)

Not sure if this is a bug (i.e. the extension should already support classes) or an enhancement (it doesn't currently but could in a later version)!

**Comment by andrewducker** [comment] 2018-08-28 14:52
Same here.  I try to "go to definition" for a class and it doesn't find anything, and it also doesn't find constructors.

**Comment by tylerl0706** [comment] 2018-08-28 15:20
Ah this is a dupe of https://github.com/PowerShell/vscode-powershell/issues/3

The problem here is that it's difficult to support classes AND PowerShell v3. @powercode has been working on adding this but I'm not quite sure on his status. Once we move to V2 of the extension which comes with PSReadLine, we will be able to support this with a smaller barrier.

**Closed by tylerl0706** 2018-08-28 15:20 UTC
