### ISSUE TITLE
Folding on #region tag in powershell broken

### ISSUE THREAD

**Issue by travis-sobeck** [PowerShell/vscode-powershell#1447] opened 2018-07-23 16:14 UTC
The latest update broke Folding on #region tag in powershell files.
VS code version 1.25.0 and 1.25.1

**Comment by rkeithhill** [comment] 2018-07-23 16:21
Duplicate of #1428 which has been fixed.  Fix will show up in the next release due sometime later this week - I hope.

**Closed by rkeithhill** 2018-07-23 16:21 UTC

**Comment by travis-sobeck** [comment] 2018-07-23 16:29
Sorry, I missed that when I searched.

**Comment by rkeithhill** [comment] 2018-07-23 16:30
No problem.  :-)

**Comment by rjmholt** [comment] 2018-07-27 18:42
@travis-sobeck The release went out this morning with a fix for this in it

**Comment by travis-sobeck** [comment] 2018-08-01 03:25
Thanks, so far its working great!
