### ISSUE TITLE
no Variable IntelliSense

### ISSUE THREAD

**Issue by TechGuyTJ** [PowerShell/vscode-powershell#186] opened 2016-05-17 17:13 UTC
When typing $ the only intellisense that comes up is 
![image101](https://cloud.githubusercontent.com/assets/6272541/15331787/f389b322-1c30-11e6-8333-db1812e379ba.png)

I then moved it outside of the function and received the same results
![image011](https://cloud.githubusercontent.com/assets/6272541/15331802/0a8d5344-1c31-11e6-9710-43b18350c51d.png)

I can get it to work but typing . and then typing $ in front of the .
![image001](https://cloud.githubusercontent.com/assets/6272541/15331836/2acf715a-1c31-11e6-8a84-1da0a1acf398.png)

**Comment by daviwil** [comment] 2016-05-17 17:19
Thanks for the report TJ.  First of all, are you using the latest versions of VS Code (1.1.1) and the PowerShell extension (0.6.1)?

You can gather logs by following these instructions:

Open up your VS Code User Settings (File -> Preferences -> User Settings) and insert this line into the file that appears in the pane on the right side:

`"powershell.developer.editorServicesLogLevel": "Verbose"`

Now restart VS Code and open a PowerShell file and try getting IntelliSense for a variable, then navigate to this path on your hard drive:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.6.1\bin`

There should be a file there called EditorServices.log. Could you drag and drop it into your reply to this issue?

**Comment by TechGuyTJ** [comment] 2016-05-17 20:11
[EditorServices.log.zip](https://github.com/PowerShell/vscode-powershell/files/269061/EditorServices.log.zip)

**Comment by daviwil** [comment] 2016-05-17 21:17
Hmmm, hard to tell what the issue is judging from the logs alone.  Can you try creating a blank .ps1 file and try it there?  I'm wondering if there's something about the specific file you're editing that could be causing this.

**Comment by TechGuyTJ** [comment] 2016-05-19 13:53
Tried with a new file. Hope this helps
[EditorServices.log.zip](https://github.com/PowerShell/vscode-powershell/files/272684/EditorServices.log.zip)

**Comment by rkeithhill** [comment] 2016-05-19 15:10
Windows refuses to open that and it kicked off a defender "send files to Microsoft" notification. Hmm...

**Comment by TechGuyTJ** [comment] 2016-05-19 17:09
My issue seems to be resolved. I realized I was running version 1.0.0 of VS Code. Updated to 1.1.1 and the intelliSence on variables work. Sorry for not checking my VS Code version.

**Comment by daviwil** [comment] 2016-05-19 17:24
Ahhhh that makes sense actually.  They fixed an IntelliSense bug for us in 1.1.  Glad to hear it's been resolved!

**Comment by tonidy** [comment] 2016-08-06 05:22
Hi @daviwil ,

I experienced this issue with the following environment:
* VS Code 1.4.0
* VS Code PS 0.6.1

![image](https://cloud.githubusercontent.com/assets/823034/17454860/0dc1752a-5bd0-11e6-9c59-ca2336150b86.png)


With VS Code 1.3.1 the intelliSence work well. Here my log https://gist.github.com/tonidy/ed0e9a056a24ebf2a9fc02372ce2a6fe

**Comment by rkeithhill** [comment] 2016-08-06 05:32
Weird.  It looks like the extension's language service receives a shutdown message about 34 seconds after starting.  Presumably you had the test.ps1 file open for longer than that.

**Comment by tonidy** [comment] 2016-08-06 05:40
@rkeithhill 
> Presumably you had the test.ps1 file open for longer than that.

I don't understand correctly about this. I have uninstalled then install vscode-powershell again. But it still error.

**Comment by rkeithhill** [comment] 2016-08-06 19:20
Dang, it appears that auto-completion is broken pretty badly in VSCode 1.4.0.

**Comment by omerbenamram** [comment] 2016-08-07 09:55
Experiencing the same since 1.4.0. Auto completion completely broken.

**Comment by daviwil** [comment] 2016-08-08 15:03
I'll look into this today, might be able to fix it and kick out an update.

**Comment by daviwil** [comment] 2016-08-08 15:05
I'm going to close this bug again because the original issue was resolved.  I've opened the following bug to track the issue with VS Code 1.4.0, let's continue the discussion there:  https://github.com/PowerShell/vscode-powershell/issues/231

**Closed by daviwil** 2016-08-08 15:05 UTC
Labels: bug
