### ISSUE TITLE
Classes: Go to definition

### ISSUE THREAD

**Issue by J-kit** [PowerShell/vscode-powershell#1956] opened 2019-05-10 09:49 UTC
**Summary of the new feature**
"Go to definition" works with simple scripts but not in classes. The editor just shows an info overlay saying "No definition found for [Method]"

It would be awesome if classes would be supported :)

**Comment by TylerLeonhardt** [comment] 2019-05-10 14:33
This is a dupe of https://github.com/PowerShell/vscode-powershell/issues/3

This was difficult before because the 1.x version of the extension supported back to v3 but the 2.0 version of the PowerShell extension will support 5.1+ making this change much easier.

We can finally bring this feature in we just need time to do it.

**Closed by TylerLeonhardt** 2019-05-10 14:33 UTC
