### ISSUE TITLE
Code formatting breaks the code by moving brace to a comment

### ISSUE THREAD

**Issue by Rogacz** [PowerShell/vscode-powershell#1272] opened 2018-04-16 09:19 UTC
### System Details

- Operating system name and version: Windows 10 1703
- VS Code version: 1.22.2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.966
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.966
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with code formatting.
I used default powershell.codeFormatting settings and have set:
```
"editor.formatOnPaste": true,
"editor.formatOnType": true,
```

If I paste a code with opening brace on second line it doesn't check if previous line finished with a comment and moves brace, breaking the code.

![c](https://user-images.githubusercontent.com/474255/38800435-8b649f2e-4167-11e8-861b-83c65adc68d5.gif)

**Comment by wsmelton** [comment] 2018-04-16 12:49
This would be expected to me and not the main reason but one of the reasons why I don't use online comments.

**Comment by Rogacz** [comment] 2018-04-16 14:21
@wsmelton I agree and I don't use inline comments. 
But I thought intention of code formatting feature is that I can grab poorly formatted code from internet or co-worker ;) and be able to read it.

**Comment by PrzemyslawKlys** [comment] 2018-04-16 15:39
what if you change the formatting to different code formatting preset? https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/81

Seems like Allman could work here?

**Comment by tylerl0706** [comment] 2018-04-17 21:55
This has been fixed in https://github.com/PowerShell/PSScriptAnalyzer/pull/929 . In the next PSScriptAnalyzer version, this will be fixed and the next vscode-extension release after that will contain that fix.

**Comment by tylerl0706** [comment] 2018-04-17 21:59
I'm going to close this for now as external/dupe of https://github.com/PowerShell/PSScriptAnalyzer/issues/826. 

If you want to get the CI build of PSSA so that this doesn't happen, go here:
https://ci.appveyor.com/project/PowerShell/psscriptanalyzer/branch/development/job/eeh97eis3ycxn9s9/artifacts

And put the unzipped folder in your `$env:PSModulePath`

No guarantee that the CI build will be 100% stable 😄

**Closed by tylerl0706** 2018-04-17 21:59 UTC
