### ISSUE TITLE
Can not use mouse anymore in Integrated console

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/vscode-powershell#953] opened 2017-07-13 00:05 UTC
### System Details

- Operating system name and version: Windows 10 (1703)
- VS Code version: 1.14
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`: 

Name                           Value                                                                                                                                        
----                           -----                                                                                                                                        
PSVersion                      5.1.15063.483                                                                                                                                
PSEdition                      Desktop                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                      
BuildVersion                   10.0.15063.483                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                              
WSManStackVersion              3.0                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                      

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

After VS Code was updated to 1.14 I can not select text using mouse from powershell integrated console. Standard powershell console works fine.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by PowerSchill** [comment] 2017-07-13 00:47
So for example you can’t select text and then use `Ctrl-C` to copy the text?

**Comment by artisticcheese** [comment] 2017-07-13 00:49
Correct. Positioning mouse anywhere inside console and click left button does not start selection process at all, it behaves like I did not click any button.

**Comment by PowerSchill** [comment] 2017-07-13 01:06
I was able to duplicate the issue under certain circumstances:

 **Steps to reproduce the bug**

1. Open Visual Studio Code. 
2. Select the version in the bottom right of the status bar.
3. Select *Restart Current Session*

At this point I am unable to select any text as you have described. 

* Restarting VSCode does **not** fix the issue. 
* Restarting the session does **not** fix the issue. 
* Killing  both the integrated terminal **and** the regular powershelgl  terminal using the trashcan icon and then restarting VSCode **does** fix the issue. 

Attaching log files in case it helps debugging the issue. This was done on a test system with no other extensions installed. 

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1143752/logs.zip)

**Comment by Tyriar** [comment] 2017-07-13 04:46
@daviwil selection is now completely disabled if the shell indicates it's in mouse mode. I saw this reported in VS Code and could not reproduce so it seems to only happen for some setups with the powershell extension.

**Comment by rkeithhill** [comment] 2017-07-13 04:56
It is very easy to repro if you're using the PowerShell Integrated Console instead of the terminal:
![image](https://user-images.githubusercontent.com/5177512/28150967-1e210c64-6755-11e7-938c-550ff17a4d49.png)
Open VSCode and run the `PowerShell: Open Examples Folder` command, then open the `DebugTest.ps1` file.  The PSIC will get initialized within a few seconds of opening the first ps1 file.

**Comment by rfresow** [comment] 2017-08-04 09:03
Experiencing the same problem. Any progress or workaround?

**Comment by daviwil** [comment] 2017-08-14 23:22
Looks like this is fixed now in VS Code 1.15.0, can @rfresow or @rkeithhill confirm whether they see it resolved too?

**Comment by artisticcheese** [comment] 2017-08-14 23:24
No, it's not fixed. I'm on 1.15.0

**Comment by daviwil** [comment] 2017-08-14 23:27
Interesting...  I'm able to repro it based on something @PowerSchill said earlier.  It appears that if a powershell.exe terminal gets launched **before** the PowerShell Integrated Console appears, mouse selection will not work in the Integrated Console.  However, if no powershell.exe terminal is opened before the PSIC gets launched, mouse selection works fine.

This definitely seems like an issue in VS Code but I'm not exactly sure what would cause it.

**Comment by rfresow** [comment] 2017-08-15 06:26
I'm now using 1.15.0 64b and it's like @daviwil says. I also notice that it takes a long time before PowerShell Integrated is ready.

**Comment by rfresow** [comment] 2017-08-15 12:40
After I enlarged the console with the up arrow in:

![image](https://user-images.githubusercontent.com/4982940/29316144-01519068-81c7-11e7-9f49-3f0e1f6d18d6.png)

The mouse selection seems to work again. Even after reducing the size back.

**Comment by artisticcheese** [comment] 2017-08-15 12:52
Confirming that enlarging windows is in fact fixing the issue.

**Comment by Tyriar** [comment] 2017-08-17 15:51
@daviwil could you try running PSIC against the xterm.js demo (on the v3 branch ideally) and see if it repros there? https://github.com/sourcelair/xterm.js/tree/v3#demo

You can set the executable here: https://github.com/sourcelair/xterm.js/blob/f3d375a7a8c4a078f9892b5983d700896eb13174/demo/app.js#L27

**Comment by daviwil** [comment] 2017-08-22 13:47
Tried setting it up to run in the demo page but I can't seem to get past this error:

![image](https://user-images.githubusercontent.com/79405/29568513-685b8bcc-8705-11e7-9149-8f03c5293f2d.png)

I think xterm.js is working fine on its own though, the problem only occurs in VS Code if "normal" terminal is opened before another that is opened with createTerminal.  If no prior terminal exists in VS Code before the PS Integrated Console appears, the mouse works fine.

**Comment by Tyriar** [comment] 2017-08-22 18:15
@daviwil weird.

Ok then, in VS Code when you can reproduce the problem could you open devtools, add a breakpoint to [this line](https://github.com/sourcelair/xterm.js/blob/cc7c310eee72b8b43d1b5372d4482b4ca54d5b91/src/xterm.js#L1021) and see whether `mouseEvents` is `true`?

**Comment by daviwil** [comment] 2017-08-22 18:49
Just tried repoing it in 1.15.1, any time I hit a breakpoint on that line (regardless of whether the issue reproes or not), self.mouseEvents is always undefined:

![image](https://user-images.githubusercontent.com/79405/29581395-f847e00a-872d-11e7-8afd-5d013bd8ac0e.png)

Also in VS Code Insiders (which seems to have a different build of xterm.js judging from the code), I see the same thing, _this.mouseEvents is undefined no matter if mouse events are working or not.

Anything else I can check?

Probably worth mentioning that I can't seem to repro this issue in VS Code running on Linux.

**Comment by Tyriar** [comment] 2017-08-30 18:19
Hm... Seeing if the event makes it to the SelectionManager would probably be the next step

https://github.com/sourcelair/xterm.js/blob/575c10114be5002b45d4d7842a6f8741ba87f5e3/src/SelectionManager.ts#L318
https://github.com/sourcelair/xterm.js/blob/575c10114be5002b45d4d7842a6f8741ba87f5e3/src/SelectionManager.ts#L453

This is the part of the code that actually does the selection.

**Closed** 2018-03-21 01:39 UTC
Labels: Area-Integrated Console, Issue-Bug

**Comment by Tyriar** [comment] 2018-03-22 17:32
@artisticcheese was this fixed?

**Comment by artisticcheese** [comment] 2018-03-22 17:38
Yes, works for me.
