### ISSUE TITLE
intellisense and scriptanalyzer are not working

### ISSUE THREAD

**Issue by SSvilen** [PowerShell/vscode-powershell#860] opened 2017-06-12 13:41 UTC
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.13.0
- PowerShell extension version:1.3.1
- Output from `$PSVersionTable`:

PSVersion                 5.1.15063.296
PSEdition                 Desktop
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0...}
BuildVersion              10.0.15063.296
CLRVersion                4.0.30319.42000
WSManStackVersion         3.0
PSRemotingProtocolVersion 2.3
SerializationVersion      1.1.0.1

```

code -v
1.13.0
376c52b955428d205459bea6619fc161fc8faacf

$pseditor.EditorServicesVersion

Major  Minor  Build   Revision
-----     -----       -----    --------
1           3             1              0
code --list-extensions --show-versions

emmanuelbeziat.vscode-great-icons@2.1.7
JohnyGeorges.jetjet-theme@0.17.0
ms-vscode.PowerShell@1.3.1

$PSVersionTable

PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with Intellisense and psscriptanalyzer and the code problems analysis as a whole. The problems seems to appear after using Ctrl+ Space for calling intellisense. After using that Keyboard shortcut none of the above mentioned tools work anymore. For instance: resolving the issues in the code, pointed out in the problems pane, they do not disappear; intellisense no longer works - it just sits on "loading" when ctrl+space is pressed and when I type nothing pops up.

### Attached Logs

I see the following error in the debugging pane:
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at HelpCompletionFeature.onEvent (C:\Users\user\.vscode\extensions\ms-vscode.powershell-1.3.1\out\features\HelpCompletion.js:33:100)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:14715)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:53565)
    at t.$acceptDirtyStateChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:343547)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:312304)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:176531)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:177208)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I`ll send the powershell extension logs via email as per the instructions.

**Comment by daviwil** [comment] 2017-06-12 13:50
Thanks @SSvilen!  Based on your logs this looks like a duplicate of #857 which will be fixed for an update that we're shipping today.  I'll close this as a duplicate of that issue.

**Closed by daviwil** 2017-06-12 13:50 UTC
