### ISSUE TITLE
psedit non PowerShell files are not actually saved.

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#1215] opened 2018-02-26 20:33 UTC
### System Details

```
code -v
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
x64

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0

code --list-extensions --show-versions
2gua.rainbow-brackets@0.0.6
ban.spellright@2.1.20
DavidAnson.vscode-markdownlint@0.13.0
dbaeumer.jshint@0.10.16
donjayamanne.githistory@0.4.0
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@8.0.2
emilast.LogFileHighlighter@2.1.1
Equinusocio.vsc-material-theme@1.4.2
haaaad.ansible@0.2.7
humao.rest-client@0.17.0
icsharpcode.ilspy-vscode@0.3.0
jpogran.puppet-vscode@0.9.0
mauve.terraform@0.0.20
mindginative.terraform-snippets@2.0.1
ms-mssql.mssql@1.3.0
ms-python.python@2018.1.0
ms-vscode.azure-account@0.3.1
ms-vscode.azurecli@0.4.0
ms-vscode.csharp@1.14.0
ms-vscode.jscs@0.1.9
ms-vscode.PowerShell@1.6.0
msazurermtools.azurerm-vscode-tools@0.4.0
Pendrica.chef@0.6.4
PeterJausovec.vscode-docker@0.0.24
PKief.material-icon-theme@3.2.3
Shan.code-settings-sync@2.8.7
wayou.vscode-todo-highlight@0.5.11

$PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.16299.248                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.16299.248                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1
```

### Issue Description

Enter a PSSession and open a PowerShell file (ps1) and edit is with vs code. Save it and works as expected. 

Now do the same for a different file type (e.g. .rb) adjust and save it. The modification is not saved. VS Code gives you the impression it is handled. But it isn't.

See gif for both cases:

![2018-02-26_21-30-21](https://user-images.githubusercontent.com/10071039/36693753-8ffa5c5a-1b3c-11e8-9892-f78f959caea3.gif)

**Comment by tylerl0706** [comment] 2018-02-28 00:53
Looks like a bug to me. Thanks for the report!

**Comment by p-rogalski** [comment] 2024-11-05 07:40
Duplicate of #2166

**Closed** 2024-11-12 21:05 UTC
Labels: Issue-Bug, Needs: Fix Verification, Area-psEditor, Resolution-Duplicate
