### ISSUE TITLE
Preview extension adding "@" in command line

### ISSUE THREAD

**Issue by AvrumFocus** [PowerShell/vscode-powershell#2326] opened 2019-11-25 16:12 UTC
## Extension Details
|Info|details|
|-|-|
Name|PowerShell Preview
Id|ms-vscode.powershell-preview
Description|(Preview) Develop PowerShell scripts in Visual Studio Code!
Version|2019.11.0
Publisher|Microsoft
VS Marketplace Link|https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview
VS Code version|Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version|Windows_NT x64 10.0.17763

### $PSVersionTable
Name | Value
|-|-|
PSVersion |5.1.17763.771
PSEdition|Desktop
PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0...}
BuildVersion|10.0.17763.771
CLRVersion|4.0.30319.42000
WSManStackVersion|3.0
PSRemotingProtocolVersion|2.3
SerializationVersion|1.1.0.1

### Issue Description
When running a command from the editor using F8 afterwards when I type "$" in the command line I get a "@"

### Screen-shot
![8kn6EKsZAc](https://user-images.githubusercontent.com/42219106/69550856-c176ea00-0f69-11ea-9e5b-b6969a2797a2.gif)

**Comment by AvrumFocus** [comment] 2019-11-26 00:02
Update, seems the issue happens when typing anything into the console after running a command from the editor using F8.

**Comment by rjmholt** [comment] 2019-11-26 00:53
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2274.

**Closed** 2019-11-27 01:00 UTC
Labels: Resolution-Duplicate
