### ISSUE TITLE
Powershell extension terminal keeps crashing

### ISSUE THREAD

**Issue by SeanCoB** [PowerShell/vscode-powershell#1709] opened 2019-01-20 16:42 UTC
- VSCode Version: 1.30.2
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Edit Powershell code. While typing, the terminal will crash and prompt to be restarted.

Does this issue occur when all extensions are disabled?: No

I turned on verbose logging and captured the attached log. It looks to be getting angry at my incorrect syntax that occurs as I'm typing...

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2776822/EditorServices.log)

**Comment by rkeithhill** [comment] 2019-01-20 19:47
Duplicate of #1675.  This has been fixed and should appear in the next release 1.10.3.  If you would like to verify the fix, you can install the "insiders" version of the extension that has the fix.  The Windows version can be downloaded from https://ci.appveyor.com/project/PowerShell/vscode-powershell/build/artifacts  Then use the Extension view's "..." menu to select "Install from VSIX...".  Or you can wait until we release 1.10.3  But if you do try the VSIX, would appreciate confirmation on whether it fixes this issue for you.

**Closed by rkeithhill** 2019-01-20 19:47 UTC

**Comment by SeanCoB** [comment] 2019-01-21 22:18
I've been using the new version for about a day without issue. Thanks!
