### ISSUE TITLE
Comment-Help shortcut seems broken

### ISSUE THREAD

**Issue by corbob** [PowerShell/vscode-powershell#1490] opened 2018-08-19 18:57 UTC
### System Details

- Operating system name and version: Windows 10 1803
- VS Code version: 1.25.1 & 1.27.0 Insiders
- PowerShell extension version: 1.8.3
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PS C:\repos\LeanPub> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
PS C:\repos\LeanPub> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      3      0


PS C:\repos\LeanPub> code --list-extensions --show-versions
CoenraadS.bracket-pair-colorizer@1.0.59
eamodio.gitlens@8.5.5
eg2.tslint@1.0.35
Equinusocio.vsc-material-theme@2.3.0
kisstkondoros.vscode-codemetrics@1.17.1
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.8.3
wesbos.theme-cobalt2@2.1.6
PS C:\repos\LeanPub> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


(using vscode insider:
Version: 1.27.0-insider
Commit: fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099
Date: 2018-08-17T05:18:51.696Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
)
```

### Issue Description

When typing `##` at the start of a function, it appears to insert the entire function less variables:

![image](https://user-images.githubusercontent.com/30301021/44312027-c7653f00-a3a6-11e8-99ef-c1a8f8fbc323.png)

### Attached Logs

[Start-EditorServices-EditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/2300591/Start-EditorServices-EditorServices.zip)

**Comment by tylerl0706** [comment] 2018-08-19 19:16
Dupe of https://github.com/PowerShell/vscode-powershell/issues/1488

Fix is in master, just need to do a release 👍

**Closed by tylerl0706** 2018-08-19 19:16 UTC
