### ISSUE TITLE
v2020.6.0 (preview) - 

### ISSUE THREAD

**Issue by bwhitehead0** [PowerShell/vscode-powershell#2962] opened 2020-09-17 20:43 UTC
### System Details

System Details Output
```
### VSCode version: 1.49.0 e790b931385d72cf5669fcefc51cdf65990efa5d x64

### VSCode extensions:
hashicorp.terraform@2.2.3
ms-python.python@2020.8.109390
ms-vscode.powershell@2020.6.0
rebornix.ruby@0.27.0
wingrunr21.vscode-ruby@0.27.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Format Document feature removes ": " (colon space) when beside a variable in a double quoted string. This occurs if the colon is escaped with the ` character, or, if the variable is wrapped in subexpression operator $().

#### Expected Behaviour

-- Description of what *should* be happening --

Nothing - escaping the character is valid, as is using a subexpression.

#### Actual Behaviour

-- Description of what actually happens --
Assuming the following two lines in code:
```write-host "There is an issue doing the thing on $server`: $($_.exception.message)"```
or
`write-host "There is an issue doing the thing on $($server): $($_.exception.message)"`

Format document removes the `: ` characters, leaving:
`write-host "There is an issue doing the thing on $server$($_.exception.message)"`
or
`write-host "There is an issue doing the thing on $($server)$($_.exception.message)"`

### Attached Logs

I'm not aware of any logging for this.

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment] 2020-09-17 21:20
Thanks @bwhitehead0 looks like a duplicate of the issues we are seeing with formatting being tracked in PSScriptAnalyzer https://github.com/PowerShell/PSScriptAnalyzer/issues/1580

**Closed** 2020-09-18 22:00 UTC
Labels: Resolution-Duplicate
